### ISSUE TITLE
Fashion accessory idle animation resets to default when entering gpose while Anamnesis is open

### ISSUE THREAD

**Issue by Louberries** [imchillin/Anamnesis#1001]
**Describe the bug**
6.1 introduced the /changepose command for fashion accessory idle animations, allowing for you to hold your umbrellas in different poses, as well as changing the way your character stand with the wings equipped. The poses by default will carry over into gpose, however, if the tool is open when you go into gpose, there seems to be a bug where the chosen idle will be ignored, and your character will be using the default idle instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Equip any fashion accessory, it happens to both wings and umbrellas;
2. Use /changepose to pick a different idle animation;
3. Enter GPOSE with Anamnesis open;
4. The idle animation will be reset to the default one.

**Expected behaviour**
The chosen idle should carry over to gpose when the tool is open, the same way the game does normally.

**Log file**
[2022-04-19-04-01-31.txt](https://github.com/imchillin/Anamnesis/files/8510736/2022-04-19-04-01-31.txt)

**Comment by Yuki-Walsh** [comment]
Likely a symptom of the NPC face hack. we should investigate what effect that has on these items.

**Comment by Yuki-Codes** [comment]
the NPC face hack has been entirely removed from the current version of Anamnesis, so this should be fixed.
