### ISSUE TITLE
Unable to update Anamnesis

### ISSUE THREAD

**Issue by Achloryn** [imchillin/Anamnesis#1007]
[2022-04-19-20-24-37.txt](https://github.com/imchillin/Anamnesis/files/8517450/2022-04-19-20-24-37.txt)

I tried to update Anamnesis today for the first time since the patch came out, and when I tried I got an error, saying it was unable to update. The above is the log from when the update failed. Now when I launch, it doesn't even try to update, just causes a critical error and says that it cannot recover from the critical error, and must close.  The log for the critical error on launch is below.

[2022-04-19-20-25-43.txt](https://github.com/imchillin/Anamnesis/files/8517460/2022-04-19-20-25-43.txt)

**Comment by Yuki-Walsh** [comment]
You may want to grab the latest release from https://github.com/imchillin/Anamnesis/releases.
Looks like Anamnesis couldn't reach github to download the update.

**Comment by Achloryn** [comment]
That does appear to work, thanks.
