### ISSUE TITLE
Anamnesis forcing PC to Blue Screen upon running application.

### ISSUE THREAD

**Issue by xAri-Kitsune** [imchillin/Anamnesis#1011]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

Since the latest update on Anamnesis, I've ran the program at least 3 times since release and in twice of my encounters, just upon clicking the EXE. File, it causes my Gaming Laptop to forcefully go into a blue screen of death. This issue hasn't happened before with the previous Anamnesis versions, however this is the first time that it has happened to me twice in a row from just running the application. (Even upon restarting). This happens while I am in-game and for some reason chooses to crash my laptop when I run the program. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Click on 'Anamnesis.exe'
2. See blue screen error

**Expected behaviour**

Well usually when I run the Anamnesis file, it executes perfectly with no errors, however for some reason ever since its latest patch with the new features, it has forced my Gaming Laptop to go into blue screen twice now. (Only happens the moment I click onto the exe file with a brief pause before blue screen appears causing my laptop to shut down.)

**Log file**
Unable to provide as once I click onto Anamnesis it just forces my laptop to go into blue screen and turn off completely.

**Comment by Ani-ki** [comment]
Can you please advise which version you are running?

**Comment by xAri-Kitsune** [comment]
My Laptop is running on Windows 10

The Anamnesis Version is 
v2022-04-18-beta

**Comment by Ani-ki** [comment]
Can you please run through Hosts and tell us what version of the .NET Desktop Runtime you're running? There are detailed instructions on the Troubleshooting page of the wiki.

**Comment by xAri-Kitsune** [comment]
After following through with the troubleshooting page, it mentions I am using version "5.0.7"

**Comment by xAri-Kitsune** [comment]
I've downloaded "5.0.13", so I will now try to run on this see if this works. Will let you know for any issues that arise in the future.

**Comment by xAri-Kitsune** [comment]
Today I ran the application after updating my .NET to the one recommended "5.0.14". And this time upon running the program it just caused my laptop to freeze completely before shutting it off. (No bluescreen, just a direct shutdown / crash).

**Comment by Ani-ki** [comment]
Okay, something is both preventing Ana from launching, and causing your PC to lose its gotdang mind. 

This is going to need further investigation by way of Event Viewer logs.

**Comment by thiccelf83** [comment]
lmao
