### ISSUE TITLE
Nothing is working at all.

### ISSUE THREAD

**Issue by Aszurie** [imchillin/Anamnesis#1012]
**Describe the bug**
Ever since the latest update of Anamnesis, I have been totally unable to use it. Any time I change anything, it'll reset back to what it was before the change. If I change clothes, it'll go back to what I'm currently wearing, if I try to load a pose, it won't do it, neither will allow me to move the bones individually. Same happens when changing character features, time, anything. Here's some examples: 
https://gyazo.com/234779d720bd3d39d89b4c8ec5342b3f
https://gyazo.com/a60390dd7dda1ee7f04a8bc237d65262

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app.
2. Change anything you'd like to modify.
3. Nothing at all happens.

**Expected behaviour**
I'd expect it to work as it used to in the previous versions before the 6.1 patch.

**Log file**
[2022-04-21-00-24-18.txt](https://github.com/imchillin/Anamnesis/files/8527046/2022-04-21-00-24-18.txt)

**Comment by Yuki-Walsh** [comment]
well that's certainly unique. Nothing in the log file looks wrong, and the UI appears to be working as normal.
It appears that Anamnesis is somehow being prevented from writing changes to ffxiv memory, but is reading memory just fine.

Maybe some odd anti-virus behavior?
Are you running multiple ffxiv instances?
Are you using XLauncher, Dalamud plugins, or other tools that connect to ffxiv?

**Comment by Aszurie** [comment]
It actually was an odd anti-virus issue. I've been using 360 Security for years now and it has never been an issue, so it being the problem actually never crossed my mind. Anyways, thank you for your patience and the help! I appreciate it.
