### ISSUE TITLE
Support for scrolling actor list with mouse wheel

### ISSUE THREAD

**Issue by yuyuisyuyu** [imchillin/Anamnesis#1014]
**Is your feature request related to a problem? Please describe.**
Unable to scroll the pinned actors list with mouse wheel while hovering over either the actor list or the scrollbar when the actor list is long enough to add the scrollbar.

**Describe the solution you'd like**
The mouse wheel would scroll the actor list left and right when the mouse is hovered over the list itself or the scrollbar area for the list when the actor list is long enough to add the scrollbar.

**Comment by Ani-ki** [comment]
We can absolutely look into this!

**Comment by Yuki-Walsh** [comment]
this has been fixed for the next release.
We've also added a dropdown when the list of actors exceeds 4:
![Untitled](https://user-images.githubusercontent.com/379714/165061250-640f9a28-4519-4ad6-8758-87a45db74ec3.jpg)
