### ISSUE TITLE
Convert Anamnesis char files to FFXIV dat files

### ISSUE THREAD

**Issue by Slightlyxz** [imchillin/Anamnesis#1015]
I think this has been requested before. Around two weeks ago it was also talked about on XIVLauncher discord, goat replied with this:
https://gist.github.com/goaaats/b87468f5c12d7a6e5a900c7b2af64b53
and said you guys could reach out to him to implement it.

Essentially give people the option to save char files directly as usable .dat files for ffxiv instead of needing to re-create it.

**Comment by Ani-ki** [comment]
[**We have already outlined our feelings on making DAT files with Anamnesis.**](https://github.com/imchillin/Anamnesis/wiki/Before-Making-a-Suggestion#exporting-character-data-as-dat-for-use-in-game)
