### ISSUE TITLE
Elbows not bending correctly (or adjusting correctly when forearm joint is selected.)

### ISSUE THREAD

**Issue by Vanquinn** [imchillin/Anamnesis#1016]
**Describe the bug**
When turning, rotating and adjusting the forearm joint, the elbow squishes in instead of moving properly and smoothly like it did pre-update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Anamnesis.
2. Click on  Edit, then Forearm (Left OR right)
3. Adjust forearm up and down using X axis, notice that it squishes in. Z axis also dramatically distorts the elbow when bent.

**Expected behaviour**
The elbow joint should bend cleanly with the forearm like it did pre-update. The elbow is scrunching in rather than bending cleanly. These issues did not exist prior, I spend 4+ hours on intricate poses, and never had difficulties with elbows like this before.
Below I attached a simple demonstration with very little editing. Mostly just X adjusted to raise the forearm slightly, no forearm turning or anything else., luckily I had a photo from a while back that I could use as a reference.

When loading older poses, the elbows do not adjust as they should either.

6.1 Update:
![6 1 Anamnesis Update](https://user-images.githubusercontent.com/104237696/164838440-2e414a13-dc97-4986-994e-b730fa3d8575.PNG)

Pre 6.1 Update
![Pre 6 1 Anamnesis Update (same character, same elbow )](https://user-images.githubusercontent.com/104237696/164838467-38a54863-e71b-4f22-a11f-f826fd3c1df6.PNG)

**Log file**
None, this can be easily reproduced.

**Comment by Yuki-Walsh** [comment]
Unfortunately, the way the model deforms when posing is not a feature of Anamnesis, that's controlled by how the gear is rigged to the skeleton, and we cannot affect it.

I also can't confirm that this did not occur before the 6.1 update, afaik this has always been how elbows work.
