### ISSUE TITLE
Anamnesis crashing when opening

### ISSUE THREAD

**Issue by levizimo** [imchillin/Anamnesis#1018]
Just installed Anamnesis, after closing and reopening I receive this error
[2022-04-23-22-51-30.txt](https://github.com/imchillin/Anamnesis/files/8548677/2022-04-23-22-51-30.txt)

Any help is greatly welcomed

**Comment by Yuki-Walsh** [comment]
Looks like your anamnesis is out of date (2022-03-24) try grabbing the latest version from https://github.com/imchillin/Anamnesis/releases
