### ISSUE TITLE
Game Crash when switching Actor Type

### ISSUE THREAD

**Issue by sorkerad** [imchillin/Anamnesis#1019]
**Describe the bug**
I want to change event npcs into player type characters so that they are able to be frozen inside gpose. Every time i've tried to change them into a player type character my game crashes, without fail- it has happened literally every time I've tried. This bug only happens when trying to change an event npc into any other type of npc.

**To Reproduce**
Steps to reproduce the behaviour:
1. (location was adder barracks)
2. In Anamnesis, pin the chosen event npc.
4. Select ' Actor type' field and change npc to "player" OR "battle npc".
5. Game freezes momentarily and crashes after selecting either option.

**Expected behaviour**
I expect the NPC to change into and behave as a player type character.

**Log file**
[2022-04-23-17-08-01.txt](https://github.com/imchillin/Anamnesis/files/8548735/2022-04-23-17-08-01.txt)

**Comment by Yuki-Walsh** [comment]
Changing event NPC's to players is not supported. We'll be removing the dropdown, or otherwise preventing this change in the next version.

Housing NPCs are safe to change, and are changed automatically to Player when loading a character or npc appearance.
