### ISSUE TITLE
Gizmo showing partly

### ISSUE THREAD

**Issue by Blakeqz** [imchillin/Anamnesis#1021]
The Gizmo is invisible. If I hover the mouse over, one line will be partly highlighted but the others won't. I can still more the model around normally. 

![25-04-2022(13-22-38)_Anamnesis_IlGY4oTQVp](https://user-images.githubusercontent.com/104363663/165088163-5e40f961-3529-4d5d-99b0-8e0e3319bd17.png)

I tried clearing cache and re-downloading Anamnesis already.

**Comment by Ani-ki** [comment]
**[FAQ.](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)**
