### ISSUE TITLE
Gizmo showing partly 

### ISSUE THREAD

**Issue by Blakeqz** [imchillin/Anamnesis#1022]
**Describe the bug**
The Gizmo cannot be seen fully as if there're something hiding it

**To Reproduce**
Steps to reproduce the behaviour: 
Opening Anamnesis normally

**Expected behaviour**
Not seeing the Gizmo or only a part of it

**Log file**
[2022-04-25-20-18-11.txt](https://github.com/imchillin/Anamnesis/files/8557393/2022-04-25-20-18-11.txt)

**Comment by AsgardXIV** [comment]
Do you have 12th gen intel graphics?
Depending on the exact driver version you sometimes get visual corruption instead of a crash.

See #888

**Comment by Blakeqz** [comment]
Yes I do! 
I did what #888 suggested and it worked.
Thank you so much.
