### ISSUE TITLE
Middle-click on dye slot to remove dye

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#1024]
**Is your feature request related to a problem? Please describe.**
Being able to middle-click to clear a gear slot is very useful, but if you just want to un-dye an item, at the moment you have to click to bring up the entire dye list, wait for it to load, and then pick the "None" option. If you're removing several dyes this gets real old real quick.

**Describe the solution you'd like**
Middle-click the dye slot on an item to clear the dye and set it back to regular colours without affecting the rest of the item.

**Comment by Yuki-Walsh** [comment]
This has been added for the next release.
