### ISSUE TITLE
Forced Translucency and Forced on top, disabling translucency causes tabs to become greyed out.

### ISSUE THREAD

**Issue by LexiKatta** [imchillin/Anamnesis#1026]
**Describe the bug**
Forced Window Translucency upon launch
Unchecking "Window translucency" Causes anamnesis to reload and all character tabs to become un-interactable.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on Window Translucency
3. See error

**Expected behaviour**
This only started with today's update, before this the window was set to opaque by default as well as not always on top, Now opens translucent and forced on top.

![image](https://user-images.githubusercontent.com/100780784/165422149-44397a27-fd60-4b8c-b727-7d8a086c9a6d.png)
![image](https://user-images.githubusercontent.com/100780784/165422181-188ecc41-c50b-447d-8f9c-bada7a8c4a69.png)

**Comment by LexiKatta** [comment]
don't mind me I'm just incredibly dumb...

**Comment by Ani-ki** [comment]
Just out of interest, what was your issue and fix?
