### ISSUE TITLE
Certain Settings Resetting on Open

### ISSUE THREAD

**Issue by 6DK6DK** [imchillin/Anamnesis#1027]
After the most recent update, some settings (but not all) are resetting every time I open the application. The ones I have tested: Always On Top, Window Translucency, and Gallery Mode are resetting; Mini Mode, Override System Theme, and Color are saving properly.

**To Reproduce:**
1. Turn gallery mode to 'none'
2. Close and reopen the application
3. The gallery has turned back on 😲

**Expected behaviour**
Settings should stay how they are set.

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release.
