### ISSUE TITLE
After the 6.11 update, Anamnesis doesn't save unique NPC appearances on myself when I go into Gpose

### ISSUE THREAD

**Issue by thatguywithawatch** [imchillin/Anamnesis#1029]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
In future, please complete the template fully.

The NPC face hack has been removed as it was causing more issues than it was solving. As such, NPC appearances can now only be loaded onto a Carbuncle or Chocobo, until such a time as we are able to work around changes made by SE.
