### ISSUE TITLE
Animation Speed Slider Fast on Both Directions

### ISSUE THREAD

**Issue by JSharpie** [imchillin/Anamnesis#1032]
**Describe the bug**
When you slide the `Base` animation Speed when it's `0` it will be slower to a standstill. And when you keep going to `-1` it will be default speed and when it does to `-5` it will be really fast 
**Anamnesis Version**
2022-04-26

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the `Animation` Tab
2. Keep your Character in motion (it can be idle)
3. Slide the `Base` Animation Slider to the Left `Slowly`
4. Notice when it gets to `0.1`. It's very slow
5. `Slowly` Start sliding the bar till it hits `-1`
6. Notice animation back to default speed
7. Keep moving it to the left
8. Notice the animation gets progressively faster

**Expected behaviour**
When sliding all the way to the left would progressively slow it down. 
Or 
Only have the speed to the left to 0.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[2022-04-28-12-08-02.txt](https://github.com/imchillin/Anamnesis/files/8585763/2022-04-28-12-08-02.txt)

**Comment by AsgardXIV** [comment]
When you use a minus speed, the animation is playing backward (and you can effectively scrub backwards and forwards), so this is the expected behavior. If you want to stop the animation, use 0 as the speed.

**Comment by JSharpie** [comment]
Ahh I see. Ok I was doing the idle animation test and saw this behavior so it looked the same.
