### ISSUE TITLE
Opening and closing settings makes tabs inaccessible

### ISSUE THREAD

**Issue by rarsneezes** [imchillin/Anamnesis#1033]
**Describe the bug**
After opening and closing settings, all tabs (appearance, posing, etc) are grayed out and cannot be accessed or interacted with.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open settings.
2. Close settings.
3. Tabs no longer accessible.

**Expected behaviour**
Tabs should be accessible after closing settings.

**Log file**
[2022-04-28-22-33-17.txt](https://github.com/imchillin/Anamnesis/files/8588362/2022-04-28-22-33-17.txt)

**Comment by Yuki-Walsh** [comment]
this is fixed for the next release.
