### ISSUE TITLE
Monoa Mask float above actor's head when using "Young Au Ra" model option

### ISSUE THREAD

**Issue by Aye-lander** [imchillin/Anamnesis#1034]
**Describe the bug**
This is probably just a me thing but whenever I try to place the Monoa Mask on "Young" Au ra actors, it just ends up floating above their head. The headpiece doesn't float on Young Hyurs and Young Elezens so it's just an Au ra thing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Customize Tab'
2. Turn actor into a "Young Au Ra" version
3. Wear Monoa Mask

**Expected behaviour**
Considering how Hyurs and Elezens on their Young option shows the Monoa Mask on their face, and not just floating on their head, I thought Au ras would be the same too, but when I tried putting a headpiece on them, it just ends up floating.

**Comment by Yuki-Codes** [comment]
This is unfortunately a game engine limitation. Au Ra children models are strange and only a few pieces of gear work correctly with them.
