### ISSUE TITLE
Windows 11 protection

### ISSUE THREAD

**Issue by blacklion5000** [imchillin/Anamnesis#1035]
hello I downloaded the new version of the program but Windows 11 is not letting me start it I get a protection. I don't know if it is incompatible or I have to deactivate the protection.

![photo_2022-04-29_22-43-43](https://user-images.githubusercontent.com/103529883/166073066-9ef44e84-5416-4f88-a316-e2828939391f.jpg)

**Comment by Tequilaselai** [comment]
Has click en donde dice Mas Informacion subrayada. alli te da el opcion de correr lo.
