### ISSUE TITLE
Mount override doesn't work with "Penumbra Redraw" enabled

### ISSUE THREAD

**Issue by Lanselotto** [imchillin/Anamnesis#1036]
**Describe the bug**
When i override my actual mount with the sub actor menu and Redraw Penumbra enabled, camera position change weirdly but mount doesn'tchange at all untill i force redraw e.g. by opening Gpose or disable/enable penumbra.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable "Penumbra Redraw" correctly.
2. Mount a Mount.
3. Override the mount with the Sub Actor menu in Anamnesis.
4. See error.

**Expected behaviour**
Mount should change correctly but it doesn't.

**Comment by AsgardXIV** [comment]
This is a known issue and unfortunately we can't fix it without changes on the Penumbra side.

**Comment by AsgardXIV** [comment]
This will be fixed with #1060.

**Comment by Yuki-Codes** [comment]
This is fixed for the next release.
