### ISSUE TITLE
Return of model number?

### ISSUE THREAD

**Issue by AevitaImperia** [imchillin/Anamnesis#1041]
No longer can i use model number, now only NPC search, which reduce a lot of model selection.

Let the model number choosing in the actor tab be available again along with NPC search.

**Comment by Yuki-Walsh** [comment]
the model number does not provide enough data to perform an npc search, Equipment and Customize must also be used.
Please try disabling the 'named' filter in the npc selector to see every single monster and npc in the entire game.
