### ISSUE TITLE
Crystal Exarch model cannot remove hood

### ISSUE THREAD

**Issue by Zifeara** [imchillin/Anamnesis#1045]
**Describe the bug**
There are only two of the Exarch in the Anem list now as far as I can tell and neither of them can remove his hood anymore. This used to be accomplished by removing the hat from your character model, exposing the Exarch's face. Now even when a carbuncle is turned into the Exarch, toggling his hat on and off still breaks the model. The Crystal Exarch model goes from the hood up shadowy appearance to face still shadowed and with holes in the model where the bottom of the hood should be.

**To Reproduce**
Turn ncp into the Exarch
Toggle hat in equipment list
Exarch model will distort instead of becoming the model seen in game with his hood down

**Expected behaviour**
When removing the hat from the Exarch model, it should reveal his face as if he'd lowed his hood.

**Log file**
No log

**Comment by Yuki-Walsh** [comment]
Hi, some of the exarch models do not support removing the hood, but some do, the exarch appears multiple times in the NPC selector: 
![image](https://user-images.githubusercontent.com/379714/166409618-71f3c8e4-00f6-4cd0-a387-f95fa4954e8c.png)

I'm not sure why only 2 entries would appear for you?

**Comment by Zifeara** [comment]
Huh. I suppose I was just being a dummy then? Because I could have sworn I looked for the Exarch under his name and used to not find him. Well then for the record, there are two Exarch models under 'G'raha Tia' that do not support hood removal. So sorry for the trouble!
