### ISSUE TITLE
Program causing game to black screen when making model nude and entering gpose

### ISSUE THREAD

**Issue by Momichichan** [imchillin/Anamnesis#1048]
I keep trying to nsfw gpose. I make my fairy/curbuncal into another model, make them and myself nude and enter gpose and the screen turns black with a load circle in bottom right corner. This only happens if they are naked and when i try to enter gpose (Tested out with clothes and not turning the fairy into actor and those load fine). I've tried uninstalling and reinstalling Anamnesis, uninstalling/reinstalling mods, turning mods on and off, turning dalamud on and off and nothing is working. I've narrowed it down to a problem with Anamnesis itself but do not know how to fix this.

**Comment by Ani-ki** [comment]
**[FAQ](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)**
