### ISSUE TITLE
Program causing game to black screen

### ISSUE THREAD

**Issue by Momichichan** [imchillin/Anamnesis#1049]
**Describe the bug**
This is the 2nd time I have encountered this issue. I'll change Eros or a minion into another character, remove all gear from 2nd character and my own, enter gpose and the screen will go black with a small loading circle in the bottom right corner. This only happens when the gear is removed from both characters or just my own using Anamnesis. I have uninstalled and reinstalled Anamnsis, I have done the same with textools mods turning them on and off and the same problem. Everything is updated including DotNET and my pc, even restarted my pc and nothing fixed it.
 
**To Reproduce**
1. Open Anamnesis
2. Summon Fairy/Minion
3. In Anamnesis load saved appearance
4. Remove gear from both characters in Anamnesis
5. Enter gpose
6. See error - Black screen with loading circle bottom right corner

**Expected behaviour**
When you enter gpose the screen will go black and a small loading circle will appear in the bottom right corner of the screen

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[Evidene.zip](https://github.com/imchillin/Anamnesis/files/8617598/Evidene.zip)

**Comment by Ani-ki** [comment]
This is usually caused by 
1. Invalid values in the main and/or off-hand slot(s);
2. You're using a weapon skill and have no weapon in your hand; or
3. You applied a partial animation to your full body.

When in doubt, regardless of whatever gear you're equipping, ensure all of your actors are using the Emperor's New Fist item, as these are simply invisible gloves. This will effectively resolve both 1 and 2.

**Comment by Ani-ki** [comment]
@Momichichan please advise if updating your main/offhand slots or resetting animations resolved your issue.

**Comment by Momichichan** [comment]
Main/Off hand didnt have weapons. Placing weapons in fixed issue thank you.
