### ISSUE TITLE
No pose options for Wings fashion accessories

### ISSUE THREAD

**Issue by Bookieson** [imchillin/Anamnesis#1050]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.
Wing fashion accessories do not have any movement abilities. Resizing seems to be the only available option.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load one of the wing fashion accessories onto character in-game
2. Add fashion accessory as another actor ("ornament" type) in Anem
3. Load /gpose in-game
4. Open modelling tab in Anem and open the fashion accessory's actor like normal
5. Boning shows up in the 3D View, but there is no way to actually move the wings (open/close/etc); only available manipulator is "Scale" (cannot rotate, change position even with "Freeze Positions" on, or adjust movement). Nothing shows up in the GUI or Matrix views.

**Expected behaviour**
Should be able to manipulate the wings since they are rigged in-game.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
In this instance, I'd like you to upload a screenshot of the Pose3D window when you have the wings selected, so I can see exactly what you're seeing, please.

**Comment by Bookieson** [comment]
After some time away, I took another look at the "j_hane_x_x" options under the 3D tab. Turns out I am smooth brain and just didn't realize this was how to manipulate them. Apologies~! Visual/Movement options in either the GUI or Matrix views would be MASSIVELY helpful for accessories like this, but that would be a feature suggestion rather than a bug. Thanks for the quick reply anyways! ^^;

**Comment by Ani-ki** [comment]
We can look into something in the near future; I'll pop this in as a feature request soon.
