### ISSUE TITLE
Settings Collum list extending to fit local gallery path

### ISSUE THREAD

**Issue by EstoyMejor** [imchillin/Anamnesis#1052]
**Describe the bug**
When setting the Gallery to local and inputting a decently long path, the left most collum tries to fit the entire path into view. Extending itself and shoving the right most collum of screen. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on Gallery - Mode
3. Select "Local" and input path to your screenshot folder. 

**Expected behaviour**
The Path being shown as far as possible, but the collum should stay the same length as before. 

**Log and Pic**
https://cdn.discordapp.com/attachments/748603390275223623/971747193402851328/unknown.png
[2022-05-05-14-15-19.txt](https://github.com/imchillin/Anamnesis/files/8631339/2022-05-05-14-15-19.txt)

**Comment by Yuki-Codes** [comment]
Fixed in aa682e97d0dc344af240d1f2f3a238ae76ed144f for the next release.
