### ISSUE TITLE
Timeline feature

### ISSUE THREAD

**Issue by JSharpie** [imchillin/Anamnesis#1057]
### Is your feature request related to a problem? Please describe.
_This is extremely long term request that's not expected happen anytime soon and will be in a deep backlog.
A few features needs to be implemented/fixed prior to this but I want to add this in as a 'Feature Request' for the record_

Now that animation is a thing. A more robust Machinimas seem to now be possible.

**Current challenge** 

Camera tracking
> Rotating seems to be the only thing that is easily controlled with speed. (Using a controller stick or if you have very good arm kinesthetics with a mouse).
Everything else like Zoom, tilt, height (3rd person camera angle),  etc is pretty linear or stepped using shortcuts.

Character model positioning
>I'm going to guess that currently we have to freeze animation to reposition characters is due to how the game-engine works. 
If so, haven't currently found a way to have Anamnesis be able to lock the position of the character while it's in motion. So this needs to be figured out first.

### Describe the solution you'd like
Have a timeline view that needs to be activated like "Create Scene" (Maybe create another window for it)
Have layers for Camera and each character that's pinned
Have a insert Keyframe for each layer (May have to use time in 0.01, 0.05, 0.1, or 0.5 second intervals due to game isn't always constant in framerate)
>Adding Camera keyframe is the current of the camera (Position, Angle, Rotation, Pan, Zoom, FoV)
Between keyframes will motion the camera 

>Adding Character keyframe can change character rotation, position, scale. (Not per bone, just overall)
Sub-timeline per character for animation execution on that keyframe. with an option of speed control.

![image](https://user-images.githubusercontent.com/53364876/167209505-0393960f-754a-4713-b829-894cbdd1e92c.png)

**What this can accomplish**
- Allow panning shot (like character walking)
- Drone shots to atmospheric feel
- Moody shot like changes in FoV in real time while action is happening
- ...and more

**Expectation for user**
- Not to make a long Scene or an entire Act
- Quick scene that's meant for a single cut with few action and camera movement.

**Comment by AsgardXIV** [comment]
> I'm going to guess that currently we have to freeze animation to reposition characters is due to how the game-engine works.
If so, haven't currently found a way to have Anamnesis be able to lock the position of the character while it's in motion. So this needs to be figured out first.

This actually already works. you can do this by using "Freeze Positions" on the Action tab. These allows them to keep animating but change their world position.

Beyond the complexity of the rest of it, there are specific challenges doing this from Ana that would need to be resolved. It's definitely something on my mind and something I want to do, but when and if I'll get to it, I can't say at the moment.

**Comment by Yuki-Codes** [comment]
Anamnesis is a screenshot tool. Not a machinema tool.
