### ISSUE TITLE
Character age appearance gets reverted once inside Gpose

### ISSUE THREAD

**Issue by Arisukv** [imchillin/Anamnesis#1058]
**Describe the bug**
The character age appearance will always revert back to "Normal" age once inside of Gpose, no matter the option for both "Old" and "Young".

**To Reproduce**
Steps to reproduce the behaviour:
1. Change character age appearance to "Young"
2. Character changes into "Young" appearance
3. Go into Gpose
4. Character reverts back to "Normal" appearance
5. Exit Gpose and characters goes back into "Young" appearance

**Expected behaviour**
Character appearance should stay as "Young" when going into gpose.

![unknown00](https://user-images.githubusercontent.com/105088007/167230197-2c3abde3-72a8-4b47-9201-ccc49e766fe6.png)

**Comment by Yuki-Codes** [comment]
We've added a warning about this in the next version.
NPC options (faces, ages, etc) will only work on NPC's when entering gpose currently.
