### ISSUE TITLE
ACT overlay not working and im not to good with code to figure out why

### ISSUE THREAD

**Issue by Joe8598** [imchillin/Anamnesis#1061]
Any help is appreciated on this I've been following the act troubleshooting site but can't seem to get past the second or third trouble shooting line I've updated my computer checked for updates on ACT and nothing is letting me get further in the terms of making it work

**Comment by EstoyMejor** [comment]
You might want to go to the ACT developers then. This is for anamnesis. An entirely unrelated program :)

**Comment by Ani-ki** [comment]
Thr FFXIV plugin server for ACT is [**HERE**](https://discord.gg/9tHJ7s2P3r).
