### ISSUE TITLE
Workaround for "NPC Face not GPose compatible" using also CMTools

### ISSUE THREAD

**Issue by rblanker** [imchillin/Anamnesis#1062]
Have no idea if this workaround is already known, if it is, I apologise. But it also a method for other people that want to use NPC faces for now. This is not the workaround for using the carbuncle instead. This workaround works on the main actor (you).

If you, for example, load Lyse on your own character, you will get a warning "NPC Face not GPose compatible". If you enter gpose, indeed the face is reverted to a vanilla face. However you can workaround this by also using CMTools.

Currently using latest versions of both tools, CM v2.0.15.4 and v2022-05-01.

How to reproduce the workaround:

1. Load NPC of with a face that is not GPose compatible (Lyse, Minfilia, Thancred etc)
2. Open CMTools, open the second tab 'Actor Properties'
3. You will need a secondary actor, such as a Summoners Carbuncle or a house NPC, example will be with the carbuncle
4. Select the carbuncle in CMTools, and enable the checkbox 'Entity Type', it should have the value '2', don't change anything else
5. In game, go into GPose (do /gpose)
6. Your character will now remain the NPC and will not revert back to vanilla
7. Turn off the checkbox in CMTools, so when you go out of GPose, everything will work fine (you can do this right after entering GPose)

What CMTools appears to do is put your character to entity type 2 when entering GPose, even when you only selected the carbuncle. But setting your character on type 2 before entering GPose will not work, because FFXIV will refuse to enter GPose (you are not a player actor). You might have mentioned this as the 'face hack' in issue #1029 

This is a feature request, not a bug report. It would be perfect if there was a switch that would do the same as what CMTools does by accident if you want to use a NPC face. The question is, if the Carbuncle is needed for this switch, it might only be needed for the trick to set your character to type 2 as soon as you enter GPose. I am sure the entity type isn't changed once in GPose, and will revert back to 1 when going out of GPose (if you turned it off in CMTools)

**Comment by Yuki-Codes** [comment]
Unfortunately the solution CMTool uses isn't working well in Anamnesis. The NPC face hack timing is very tight, and so far we've been unable to replicate it safely.
