### ISSUE TITLE
Anamnesis doesn't seem to open right?

### ISSUE THREAD

**Issue by Khonra** [imchillin/Anamnesis#1064]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.
The pose mod appears in a separate tab on it's own no matter what and I have to be Alt+Tabbed out of game to use it, it's annoying to continually swap tabs with the screen distortion from game to nongame. I'm not sure if this is normal or if it's supposed to be an overlay. If it's supposed to be an overlay is there any way I can fix it?
**To Reproduce**
Steps to reproduce the behaviour: I just open the mod.

**Expected behaviour**
I expected it to open like an overlay in the game so I could use it when I Gpose, but instead I have to alt tab out to use it.
**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
Anamnesis is an **external program**, noted by it being launched via an executable (`.exe`), not an overlay or mod. However, you can use the Always On Top and Mini Mode features to keep the window above the game window, assuming you are running the game in Borderless Windowed mode.

**Comment by Khonra** [comment]
I did the always on top and it wasn't working, the borderless window would explain that. I full screen. Thanks.
