### ISSUE TITLE
Keypresses in Anamnesis are passed through to XIV

### ISSUE THREAD

**Issue by JKAnderson** [imchillin/Anamnesis#1069]
**Describe the bug**
Any keypress in the Anamnesis window is registered by XIV (unless inside a textbox). This causes, for instance, the camera to move when trying to navigate item selectors with the arrow keys.
Occurs as of release 2022-05-04 and commit b2432cf regardless of whether hotkeys are enabled.

**Expected behaviour**
To not do that, or to be an option if it was intentional.

**Comment by Yuki-Codes** [comment]
Added an option to disable this behavior in the next release.
