### ISSUE TITLE
Version error shows up again when closing and reopening game

### ISSUE THREAD

**Issue by Vievin** [imchillin/Anamnesis#1077]
**Describe the bug**
When closing and reopening FF without closing Anamnesis, the "version not validated" error message pops up when I open the game again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FFXIV and Anamnesis
2. Close FFXIV without closing Anamnesis
3. Reopen FFXIV

**Expected behaviour**
The version error doesn't show up again.

Log:
[2022-05-24-21-25-26.txt](https://github.com/imchillin/Anamnesis/files/8765707/2022-05-24-21-25-26.txt)

**Comment by Yuki-Codes** [comment]
This is intended behavior, as its possible to launch different versions of ffxiv concurrently.
