### ISSUE TITLE
v2022-05-30 not recognizing installed 6.0.5 .NET Runtime

### ISSUE THREAD

**Issue by Chiyo2022** [imchillin/Anamnesis#1086]
**Describe the bug**
I have 6.0.5 of the .NET Desktop runtime installed on Windows 11, which Anamnesis is not recognizing. I cannot launch the application, as it is prompting me to install 6.0.4. 6.0.5 is a security patch.

**To Reproduce**
1. Install only [6.0.5](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer) of the .NET Desktop Runtime. Do not have 6.0.4 on the machine.
2. Download Anamnesis and attempt to run.
3. Prompt to install 6.0.4 is shown and Anamnesis will not launch.

**Expected behaviour**
Anamnesis recognizes the installation, does not prompt to install, and launches.

Install:
![Install](https://user-images.githubusercontent.com/106546823/171028564-5a1c7f4a-1fc3-4d32-a94a-78e652d4f4da.png)

Prompt I'm receiving:
![Prompt](https://user-images.githubusercontent.com/106546823/171028567-946a271f-5155-4ef0-84b1-997dfa9f5513.png)

**Comment by Yuki-Codes** [comment]
This has been fixed.
