### ISSUE TITLE
Missing Frameworks Error

### ISSUE THREAD

**Issue by Yulu7766** [imchillin/Anamnesis#1091]
![Command Prompt 6_1_2022 2_28_20 AM (2)](https://user-images.githubusercontent.com/103951241/171236628-648a356e-3616-4e68-a723-21fa149f1c2e.png)

I manually installed the new updated version and keep getting the "Missing Frameworks" error message and sent to download the .NET. I followed the Wiki manual and it seems my Windows(10) is hosting the newest version. Should I delete everything and do a fresh reinstall?

**Comment by Nonie6593** [comment]
I am having the same issue - I have uninstalled and reinstalled numerous times and I am still getting this error.

**Comment by AsgardXIV** [comment]
You need the desktop framework: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.5-windows-x64-installer

**Comment by Nonie6593** [comment]
I have it and it still wont work.

**Comment by AsgardXIV** [comment]
Please post the output of `dotnet --list-runtimes` from your command line.

**Comment by Yulu7766** [comment]
6.0.5 doesn't work. I went to the download/releases page and clicked the .NET and installed 6.0.4 and it worked.

**Comment by AsgardXIV** [comment]
> 

That's fixed in the most recent release (31st), but I guess you had the release from before (30th) installed.

**Comment by Aoi-Skywavegraphics** [comment]
I have the exact same error, no matter the direct link you put to install the deskop framework, it doesn't want to see it's installed, even with uninstalling it and installing it again... 
And I did use the last version of Anamnesis you speak of...

**Comment by Ani-ki** [comment]
> I have the exact same error, no matter the direct link you put to install the deskop framework, it doesn't want to see it's installed, even with uninstalling it and installing it again... And I did use the last version of Anamnesis you speak of...

Without a log file, we can't see what's going wrong. Please follow the directions outlined in troubleshooting to do so.

**Comment by Aoi-Skywavegraphics** [comment]
> > I have the exact same error, no matter the direct link you put to install the deskop framework, it doesn't want to see it's installed, even with uninstalling it and installing it again... And I did use the last version of Anamnesis you speak of...
> 
> Without a log file, we can't see what's going wrong. Please follow the directions outlined in troubleshooting to do so.

...I'm sorry if it's a dumb question but... I can't find the directions you're talking about. May I have a link or something to be able to give you these logs please ?

**Comment by Aoi-Skywavegraphics** [comment]
> > I have the exact same error, no matter the direct link you put to install the deskop framework, it doesn't want to see it's installed, even with uninstalling it and installing it again... And I did use the last version of Anamnesis you speak of...
> 
> Without a log file, we can't see what's going wrong. Please follow the directions outlined in troubleshooting to do so.

![image](https://user-images.githubusercontent.com/107625829/174082283-a6d276ad-92f3-4f1c-b4bb-813e63aacab8.png)


....I sadly can't find the Anamnesis folder to access the logs...

**Comment by RageShoTT** [comment]
You were never able to open anamnesis once correct? that might explain why it never create the folder or any logs, you did install the last .net desktop and you use the last version of anamnesis correct?
And it still gives you the "missing framework would you like to download it" popup?

**Comment by HavenLrenca** [comment]
Just made a GitHub account just to reply to the issue. Make sure you are downloading ".NET Desktop Runtime (Current Build)" instead of ".NET Runtime" because it's missing whatever Desktop Runtime contains. I had the same issue when it redirected me to the Microsoft .NET website and only the .NET Runtime download was available. My Anamnesis started working after installing the Desktop Runtime.

Here is the official MS list of .NET builds, including the Desktop Runtime that you'll need to run Anamnesis: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

![image_2022-06-23_125617339](https://user-images.githubusercontent.com/108086729/175353666-d0a10db4-8e57-4e85-a9fd-7996a2e45166.png)

**Comment by RakuRacoon7** [comment]
> Just made a GitHub account just to reply to the issue and also don't know if you've already done this.
> 
> Make sure you are downloading ".NET Desktop Runtime (Current Build)" instead of ".NET Runtime" because it's missing whatever Desktop Runtime contains and it'll most likely update everything that's already installed. I had the same issue when it redirected me to the Microsoft .NET website and only the .NET Runtime download was available. My Anamnesis started working after installing the Desktop Runtime.
> 
> Here is the official MS list of .NET builds, including the Desktop Runtime that you'll need to run Anamnesis: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> 
> ![image_2022-06-23_125617339](https://user-images.githubusercontent.com/108086729/175353666-d0a10db4-8e57-4e85-a9fd-7996a2e45166.png)

Just made an account to say thank you, now it works

**Comment by RakuRacoon7** [comment]
> Just made a GitHub account just to reply to the issue and also don't know if you've already done this.
> 
> Make sure you are downloading ".NET Desktop Runtime (Current Build)" instead of ".NET Runtime" because it's missing whatever Desktop Runtime contains and it'll most likely update everything that's already installed. I had the same issue when it redirected me to the Microsoft .NET website and only the .NET Runtime download was available. My Anamnesis started working after installing the Desktop Runtime.
> 
> Here is the official MS list of .NET builds, including the Desktop Runtime that you'll need to run Anamnesis: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> 
> ![image_2022-06-23_125617339](https://user-images.githubusercontent.com/108086729/175353666-d0a10db4-8e57-4e85-a9fd-7996a2e45166.png)

I just made an account to say thank you, now it works
