### ISSUE TITLE
Weird error and items will not dye on NPC's

### ISSUE THREAD

**Issue by fetchgames** [imchillin/Anamnesis#1093]
![image](https://user-images.githubusercontent.com/106719731/171543725-527685ef-512d-4e3e-818d-2d015623ce54.png)
I keep getting this weird error I don't know what is causing it but it pops up when I go to click on a pinned actor when first booting up anamnesis. I also put some clothes on thancred and it will not dye for some reason, help please!!!

**Comment by RageShoTT** [comment]
Greetings, may i know which clothes are you using?

That error usually comes out when the index is corrupted either by textool or penumbra, you use either one of them by any chance?

**Comment by RageShoTT** [comment]
as a reference see issue #986
