### ISSUE TITLE
Anamnesis won't open properly

### ISSUE THREAD

**Issue by Sanntinell** [imchillin/Anamnesis#1097]
I have an issue where my Anamnesis just won't work at all. It's stuck in this little blank, white window(screenshot). When you hover your mouse over it, that's all that is visible. After clicking on it, nothing happens. The issue started appearing yesterday. I thought it was just a bug that was going to probably get fixed soon. Last thing I remember when Anamnesis was still working was the program asking me to update. After clicking "update", the follow-up window that would appear was and update error telling me it couldn't find "something" and the program would turn into this unresponsive white thing on my app bar as shown on screenshot.

I tried:
installing "windowsdesktop-runtime-6.0.4-win-x64"
installing "windowsdesktop-runtime-6.0.5-win-x64"
installing "windowsdesktop-runtime-5.0.16-win-x64"

nothing worked.

![screen11](https://user-images.githubusercontent.com/106750298/171633594-87d64b64-f547-48fe-a34b-e5e80f7038f2.jpg)

**Comment by Sanntinell** [comment]
Update on the steps I have taken so far: 

- I made sure that "windowsdesktop-runtime-6.0.5-win-x64" is reinstalled
- I deleted and re-downloaded Anamnesis from the latest builds
- made sure that Anamnesis is excluded from Windows Security (default Windows protection)

Unfortunately, the issue persists...

**Comment by RageShoTT** [comment]
Please try to open Anamnesis and keep pressing shift, that will reset the software settings, if that doesn't work you can rename anamnesis folder in documents which will prompt to a settings reset
