### ISSUE TITLE
Program gives an error when trying to open.

### ISSUE THREAD

**Issue by LyraRhea** [imchillin/Anamnesis#1098]
Program gives an error when trying to open
[2022-06-02-19-57-03.txt](https://github.com/imchillin/Anamnesis/files/8826439/2022-06-02-19-57-03.txt)

**Comment by RageShoTT** [comment]
Software now uses net 6.0 and not 5.0

Please intall .net 6.0+ runtime https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer
