### ISSUE TITLE
Port CM2 Features - Actor Data

### ISSUE THREAD

**Issue by Yuuki-Walsh** [imchillin/Anamnesis#11]
~~-Overall Scale~~
~~Bust Scale (X/Y/Z)~~
~~Ear . Tail Scale~~
~~Data Path~~
~~Idle Animation~~
~~Force Animation~~
~~Transparency~~
~~Animation Speed~~
- [ ] Lock Facial Animation
- [x] Model Type

**Comment by MissAniThrope** [comment]
Crossed out features have been given their own tickets.
