### ISSUE TITLE
Anamnesis has stopped loading

### ISSUE THREAD

**Issue by TizioCiao** [imchillin/Anamnesis#1102]
**Describe the bug**
I logged out to install a couple of mods to try them out, but after logging in and opening anamnesis, the program stopped loading and "turned" himself just in a white window that doesn't load or work (just like in the pic). A friend suggested that maybe was one of the mods to have touched something and made anamnesis like that, but after deleting it multiple times, did a start over to delete said mods, restarting the pc and similar things, the problem is still there. I installed the 6.0.5 software multiple times as well, but that still gave me the same problem without a resolution.

**Log file**
![2022-06-03 (6)](https://user-images.githubusercontent.com/106829175/171904310-d0c9df2b-a529-45af-9460-bb3771e486d1.png)

**Comment by Yuki-Codes** [comment]
Try holding shift while launching Anamnesis to reset its settings.

**Comment by TizioCiao** [comment]
It worked, thanks a lot
