### ISSUE TITLE
Critical Error, Anamnesis crashes at launch

### ISSUE THREAD

**Issue by TigerNef** [imchillin/Anamnesis#1105]
I was using it normally early today and now it gives me this critical error and it force quits immediately. I have restarted, re installed .NET and even uninstalled xivAlexander just to see if it had something to do with that and it still gives me this problem.

![image](https://user-images.githubusercontent.com/106937390/172078213-819052da-ebf3-4711-8bdf-43beaf20c80b.png)

For some reason can't copy the log, so I just have this.

**Comment by Yuki-Codes** [comment]
Try holding shift while launching to reset your settings.

**Comment by TigerNef** [comment]
Oh hey, it worked ^^ thank you
