### ISSUE TITLE
Actors in gpose not unfreezing

### ISSUE THREAD

**Issue by Simusar** [imchillin/Anamnesis#1106]
[2022-06-05-12-30-31.txt](https://github.com/imchillin/Anamnesis/files/8841647/2022-06-05-12-30-31.txt)

**Comment by Simusar** [comment]
I don't remember what I changed before entering gpose and the actors aren't returning to normal

**Comment by RageShoTT** [comment]
Please update both anamnesis and your .net version and see if this happens again

**Comment by Peebs-miqo** [comment]
No further replies so I'll assume this issue has been resolved.
