### ISSUE TITLE
Error when i try to make the last update

### ISSUE THREAD

**Issue by KiyonaEl** [imchillin/Anamnesis#1107]
**Describe the bug**
When I launch, Anamnesis, and i try to make the last update, a error massage pop (Screen)

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Anamesis
2. Click on 'Update"
3. See error

**Expected behaviour**

That the update be done

**Log file**
[2022-06-06-06-47-41.txt](https://github.com/imchillin/Anamnesis/files/8841948/2022-06-06-06-47-41.txt)
![Capture](https://user-images.githubusercontent.com/93752193/172097337-a78f7c49-189e-45db-906f-6ef3662cd04c.PNG)

**Comment by RageShoTT** [comment]
Know error, please install the last version manually [https://github.com/imchillin/Anamnesis/releases/tag/v2022-05-31](url)
This should fix the issue

**Comment by KiyonaEl** [comment]
thanks, it's work !
