### ISSUE TITLE
Anamnesis fails to launch (failed to initialize Lumina)

### ISSUE THREAD

**Issue by trakasis** [imchillin/Anamnesis#1108]
**Describe the bug**
Decided to use Anamnesis again today and I pressed the update button for it but now the program just hits a critical error and dies, giving the attached log file.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Amanesis
2. Launch program
3. Program dies

**Expected behaviour**
Program should launch

**Log file**

[2022-06-06-00-23-39.txt](https://github.com/imchillin/Anamnesis/files/8842071/2022-06-06-00-23-39.txt)

**Comment by RageShoTT** [comment]
Please install the .net 6.0 framework: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.4-windows-x64-installer
if it happens that anamnesis starts but stays invisible close it and reset your setting by opening it again and keep shift pressed until a prompet will say so

**Comment by Yuki-Codes** [comment]
You're also running a quite old version of Anamnesis (2022-03-24), you should grab the latest version from https://github.com/imchillin/Anamnesis/releases
