### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by KuroiYuki02** [imchillin/Anamnesis#1112]
When I open Anamnesis, sometimes it crashes. 

Other times I would go into GPOSE and then it will error that the Skeletons are having multiple errors.

It would then warp either my character's skeleton once I exit GPOSE or the skeletons of other nearby people. 

So I would
1. Enter GPOSE
2. Move around the body parts to pose or upload a pose. 
3. Exit Gpose 
4. Error would then occur

Other times even if I'm just editing the outfits, it would also crash and warp the skeletons. 

This has been happening since the latest update.

**Comment by RageShoTT** [comment]
May we have a screenshot of the error and the log?

**Comment by KuroiYuki02** [comment]
![image](https://user-images.githubusercontent.com/106978322/172595910-2eb0d16c-0a04-4c6f-9311-917ee3c8a4c9.png)
![image](https://user-images.githubusercontent.com/106978322/172621037-7b8096e0-62b3-48ca-98ae-0e01d337c9d4.png)
I also moved someone but it didnt put them back out of GPOSE. 

I didnt get to screenshot the skeleton errors but I'll take a photo once they return.

**Comment by RageShoTT** [comment]
do you use any modded client by any chance?
have you tried reset you settings by holding down shift after opening Anamnesis?
i would still need the log file if that happens again [https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#accessing-log-files-for-issue-reporting](url)

**Comment by KuroiYuki02** [comment]
[2022-06-06-22-01-08.txt](https://github.com/imchillin/Anamnesis/files/8886069/2022-06-06-22-01-08.txt)
[2022-06-06-22-23-11.txt](https://github.com/imchillin/Anamnesis/files/8886070/2022-06-06-22-23-11.txt)
[2022-06-06-22-26-48.txt](https://github.com/imchillin/Anamnesis/files/8886071/2022-06-06-22-26-48.txt)
I just use the Dalamud launcher and I haven't reset the settings after opening Anamnesis but here is the log file from when I had the skeletons crash

**Comment by KuroiYuki02** [comment]
![image](https://user-images.githubusercontent.com/106978322/173238961-92ee263a-da34-4e02-8ed5-9ef25d0c7928.png)
![image](https://user-images.githubusercontent.com/106978322/173238974-00b806ac-b89c-4bc5-a538-b5ca4cc0ee34.png)
![image](https://user-images.githubusercontent.com/106978322/173238984-d00572ef-4286-41a0-ba55-20685316b4a8.png)
![image](https://user-images.githubusercontent.com/106978322/173238991-4d66e873-5f10-4a80-8456-420b191336cf.png)

**Comment by KuroiYuki02** [comment]
This is what it looks like after the Skeleton glitch 
![image](https://user-images.githubusercontent.com/106978322/173239030-e70b846d-b446-44fd-8616-4de37402e196.png)

**Comment by KuroiYuki02** [comment]
[2022-06-12-22-51-02.txt](https://github.com/imchillin/Anamnesis/files/8886077/2022-06-12-22-51-02.txt)
Sorry for so many posts but this is the log for today's skeleton glitch

**Comment by KuroiYuki02** [comment]
> do you use any modded client by any chance? have you tried reset you settings by holding down shift after opening Anamnesis? i would still need the log file if that happens again
> 
> in this link you can find how to reset settings and how to get a log file https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#accessing-log-files-for-issue-reporting

Hi! I just want to ask if there's any update on this?

**Comment by Ani-ki** [comment]
Update to .NET Desktop Framework 6.0.6
