### ISSUE TITLE
More choices for window resize?

### ISSUE THREAD

**Issue by Elypha** [imchillin/Anamnesis#1115]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hello, I think it would be great if we have smaller increments for that function, if it is only a problem of the value of scale and doesn't require complex work.
I think for most users this will only be a one-off setup where everyone picks their favourite scale, so it doesn't really matter for the drop down list to be a little long.
For my case, I can't see the text clearly in 1x and I can't see my character in 1.25x. Shall we have, for example, 1 - 1.05 - 1.10 - 1.15 ...? or even a slide bar that covers 0.50~2.00 with increments of 0.01 for that?

**Comment by RageShoTT** [comment]
You can manually change the window dimension by dragging the bottom right corner(when the diagonal arrow appear) if you want it to be more dynamic.

And if i understood the question correctly of course.

**Comment by Elypha** [comment]
> You can manually change the window dimension by dragging the bottom right corner(when the diagonal arrow appear) if you want it to be more dynamic.
> 
> And if i understood the question correctly of course.

gosh you're right. don't know why I had the impression that the window couldn't be dragged around so that I didn't give it a try
