### ISSUE TITLE
Anamnesis not updated for 6.15

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#1118]
**Describe the bug**
Shit be broken.

**To Reproduce**
1. Open game
2. Run Ana
3. Cry when DX11 error pops up

**Expected behaviour**
Stop wrecking our shit, SE.

**Log file**
N/A

**Comment by thiccelf83** [comment]
updat for india pleas :0))

**Comment by thiccelf83** [comment]
bob

**Comment by Ani-ki** [comment]
Pardon

**Comment by Ani-ki** [comment]
Jumped the gun on this one, damn thing worked perfectly. Praise be to signatures.
