### ISSUE TITLE
Penumbra HTTP API issues

### ISSUE THREAD

**Issue by Nemo-Tiger** [imchillin/Anamnesis#1121]
**Describe the bug**
Reinstalled Anamnesis for the update but now whenever I try to load character data or change the appearance of pre-existing targeted characters I always get the enabling penumbra http api question. When I select OK, either nothing happens or the character model completely disappears until I force a loading screen between to get them back to normal. I have the "Use Penumbra Redraw" box selected but other than that I'm not sure on what to do. There's no conflicting mods and I don't have penumbra installed either but if it's as simple as needing to install it or if it's something really small I'm missing then that's what I'll do. I have attached screenshots of what I see because I'm not the best at explaining stuff but any assistance would be lovely, thank you in advance
![image](https://user-images.githubusercontent.com/107215972/172934732-afd999cd-5d36-43ee-b5bb-2aad6a68b606.png)
![image](https://user-images.githubusercontent.com/107215972/172934828-62e74a99-58d0-4eb5-9c05-0be560896996.png)

**Comment by RageShoTT** [comment]
you can uncheck the use penumbra redraw option there, it should let you do it
don't get fooled by the gray theme! :D

**Comment by Nemo-Tiger** [comment]
> you can uncheck the use penumbra redraw option there, it should let you do it don't get fooled by the gray theme! :D
> 
> Joke aside that shoud solve the issue when you change items in the equipment menu, if something else happens with that remove that should not i'll be here to try and solve it

It worked! I knew it'd be something tiny throwing me through a loop haha, thank you very much :D
