### ISSUE TITLE
Anamnesis not working

### ISSUE THREAD

**Issue by Khenbish** [imchillin/Anamnesis#1123]
So, I'm having this issue when i launch anamnesis

![Στιγμιότυπο οθόνης (24)](https://user-images.githubusercontent.com/107294989/173175164-e0ca0cae-7b28-4ab5-83a8-223c9444e6a5.png)

I noticed a few more users had it as well so i tried some of the solutions mentioned like:
* downloading latest builds (both anamnesis.exe & windowsdesktop-runtime-6.0.5-win-x64)
* holding shift while launching the program all the way until the screen above
* removing & renaming the anamnesis folder from documents

I even redownloaded the game itself but none of them worked

**Comment by RageShoTT** [comment]
When you hold down shift to reset the settings you have a prompt that says so? Or it just goes into that blank state?
Mind you shift has to keep pressed even during windows access control system (that annoying do you wanna run as admin popup)

**Comment by Khenbish** [comment]
No i don't get any pop up messages when holding shift

**Comment by RageShoTT** [comment]
OK that would explain why, settings folder for anamnesis should be in %appdata%\Anamnesis , try to manually rename that folder or rename the Settings.JSON

**Comment by Khenbish** [comment]
That fixed it, thanks
