### ISSUE TITLE
Critical Error when launching Anamnesis

### ISSUE THREAD

**Issue by LeoLeppakoski** [imchillin/Anamnesis#1128]
**Describe the bug**
After recognizing ff14 client, I get a notification about game version change. After pressing "OK" the loading circle with the Anamnesis logo comes up normally, but Anamnesis window will not show up. Right clicking Anamnesis in the taskbar and clicking on "Anamnesis" produces a Critical Error with a message "Multiple Anamnesis processes found. Please close all other instances." This happens even after fresh PC restart.

**To Reproduce**
Steps to reproduce the behaviour:
1. With FF14 open, launch Anamnesis
2. Click on 'OK' when Anamnesis informs about Anamnesis not being validated against this game version
3. Wait for Anamnesis loading circle to complete
4. When Anamnesis window doesn't show up, try to open the window from Windows taskbar with right click and selecting Anamnesis 
5. Critical Error is produced "The tool was unable to recover from this error, and must close. Multiple Anamnesis processes found. Please close all other instances."

**Expected behaviour**
After step 3 Anamnesis window should show on top of other programs.

**Comment by LeoLeppakoski** [comment]
At step 4. Anamnesis' preview window from Windows taskbar shows as solid white screen.

**Comment by RageShoTT** [comment]
Try to reset your settings by holding down shift right after opening Anamnesis or rename/delete %appadata%\Anamnesis if it does let you and shift doesn't work

**Comment by LeoLeppakoski** [comment]
I'm not sure I understood when to hold shift, but renaming and thus resetting appdata\Anamnesis worked.
