### ISSUE TITLE
disable changing number values with scrollwheel in developer tab

### ISSUE THREAD

**Issue by Peebs-miqo** [imchillin/Anamnesis#1133]
Using the scrollwheel in the developer tab causes Anamnesis to crash. Disabling input of number values using the scrollwheel in that tab should fix it so that you don't crash when trying to look at actor info.

**Log file**
[2022-06-17-19-44-36.txt](https://github.com/imchillin/Anamnesis/files/8926558/2022-06-17-19-44-36.txt)

**Comment by MegaScience** [comment]
Noted this in #1101.
