### ISSUE TITLE
Error when loading Anamnesis

### ISSUE THREAD

**Issue by UnderWolfe** [imchillin/Anamnesis#1142]
**Describe the bug**
Anamnesis appears as open but then doesn't appear on screen. The "thumbnail" on the taskbar appears full white and clicking on it doesn't show it. 

I don't know how to reproduce the bug. I simply click it open, starts to load, and doesn't appear on screen.

**Comment by RageShoTT** [comment]
i... don't know if you fixed it since you instantly close it but that's due to settings issue, please reset your settings by holding down shift after booting anamnesis or delete/rename the anamnesis folder in %appdata%
