### ISSUE TITLE
Issue with children

### ISSUE THREAD

**Issue by UnderWolfe** [imchillin/Anamnesis#1143]
When changing character to children or "young" version a bug happens where the head isn't shown. The rest of the body appears perfectly but the head appears like invisible, despite not being put as invisible at all

Steps to reproduce the behaviour:
1. Choose any actor
2. Go to the page where you can change race, gender and more
3. Click on normal, a tab opens. Click then on young
4. Bug happens

Supposedly the children should appear with heads. However, they don't.

**Comment by chirpcodes** [comment]
Children only face 1 face variant. Do you have face 1 selected?

**Comment by UnderWolfe** [comment]
I will check it!

**Comment by UnderWolfe** [comment]
Most likely I didn't had face 1 selected! I used a random npc and started changing it, only worked indeed with face 1! Thank you!

**Comment by RageShoTT** [comment]
*please don't take this issue title out of context*

also if the problem was solved please close the issue ^^
