### ISSUE TITLE
Character appearance changing without imput.

### ISSUE THREAD

**Issue by Avalon304** [imchillin/Anamnesis#1147]
**Describe the bug**
Facial features reset when entering the 'Character' tab for the first time after opening the program for the first time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Click on the the character you wish to change.
3. Go to the Character tab

4. Facial features reset. Only occurs the first time you enter after starting the program.

**Expected behaviour**
Nothing should occur without user input when entering the character tab at any point.

**Log file**
Log file attached. Character appearance was set properly, program was opened, character was selected, character tab was entered and program was closed as soon as the error occurred. Additionally a screenshot is attached, displaying the 'History' menu showing which things were affected without user input.
[2022-06-28-02-06-02.txt](https://github.com/imchillin/Anamnesis/files/8999429/2022-06-28-02-06-02.txt)

![Untitled](https://user-images.githubusercontent.com/8188470/176140797-92bb83d8-3785-4560-a6b4-cf08a402786b.png)

This just started occurring within the last hour (as of this message), for the past week the program hadnt been doing it, and Ive changed nothing about how Ive used the program.

**Comment by chirpcodes** [comment]
This was fixed by #1131 and should be in the next release.

**Comment by Avalon304** [comment]
I see, thanks!  I just found it strange that it had been working fine for like a week (since I updated to the current release) and then it just started within the last hour. Thanks again.

**Comment by RageShoTT** [comment]
Hey Avalon can you confirm if this issue was fixed for you? if so could you please mark the issue as completed?
