### ISSUE TITLE
Doesn't want to open anymore

### ISSUE THREAD

**Issue by VyzoG** [imchillin/Anamnesis#1148]
**Describe the bug**
The software doesn't want to launch anymore. I get the window telling about the patch release and that this version of ana could have problems, and when I click "OK", nothing happens. The software is still open and running on my task manager and hotbar, but I can't see any window opening.
I used it 2 days ago (June 28) and it was working fine.

I tried to uninstall and reinstall the latest version (2022-05-31) but same issue.

**Comment by RageShoTT** [comment]
Please reset your settings by holding down shift when you open Anamnesis, a popup should tell you that the settings were resetted.
In Alternative you can rename/delate the folder Anamnesis in %appdata%

I guess the software stays open but with a white preview by Windows
