### ISSUE TITLE
Critical Error after start Anamnesis

### ISSUE THREAD

**Issue by Ruoswolf** [imchillin/Anamnesis#1151]
**Describe the bug**
Starting Anamneis and get the Message: Critical Error  -6666666490462208

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'the Anamnesis.exe'
2. Start it
3. Click okay

What I done:
Check the newest version of Anamnesis
Check the newest doNet Version
Turn off the Anti Virus Software McAfee and Windowsfirewall
Install FFXIV new and check it without the Quick Launcher / Dalamud 

Logfile in Attachment
 I hope you can help me to fix the bug. Sorry for my bad englisch ;)

[2022-06-30-20-51-04.txt](https://github.com/imchillin/Anamnesis/files/9022669/2022-06-30-20-51-04.txt)

**Comment by Ruoswolf** [comment]
Oh sorry for my late answer! 
Thank you for answe
I install the new anamnesis version, After this I have the same error. But thank you for the tip, I try to reset the settings by holding shift while opening Anamnesis and that works. Thank you so much! I can open it now!

**Comment by RageShoTT** [comment]
@Ruoswolf please mark the issue as completed, thanks!
