### ISSUE TITLE
Failed to perform update

### ISSUE THREAD

**Issue by AnimeKC** [imchillin/Anamnesis#1152]
Anytime I started up Anamnesis, I have gotten the message, "Failed to perform update. The process cannot access the file 'C:\Users\...tmpF207.tmp' because it is being used by another process." This has been happening for almost a month and I cannot figure out what to do.

**Comment by EstoyMejor** [comment]
Did you try redownloading the newest update from GitHub manually already?

**Comment by AnimeKC** [comment]
I did do that immediately when the problem came up. After opening up Anamnesis again, the message before still came up.

**Comment by Ani-ki** [comment]
That can't be the case as there's no update after 20220531. Please try downloading it again and manually updating.

**Comment by AnimeKC** [comment]
That's the update I'm talking about. May 31st was the update I never got to install because the issue came up at that time. Since then, I have not been able to update Anamnesis at all. I already downloaded it and manually updated, but the problem is still coming up.

**Comment by Ani-ki** [comment]
Anamnesis is not a traditionally installed app (IE there is no installer for it); you run the exe directly, so to remove it from your pc, you just delete it.

 A new update was pushed today last night (AEST). Grab that version and extract it, and see if that one works.

**Comment by AnimeKC** [comment]
I did extract it and download it, but the problem keeps occurring. Is there anyway I can delete this so I can start fresh? I want to get the new updates, but this error is not allowing me to get any updates from May 31st and onwards.

**Comment by Ani-ki** [comment]
As stated in the comment above yours, **to remove it from your pc, you just delete it.** Locate `Anamnesis.exe`, delete it from your system, then **[ensure you have grabbed the latest version](https://github.com/imchillin/Anamnesis/releases/latest)** and extract that.

If it's saying you're still using the old 31/05 version, then you have not removed it.
