### ISSUE TITLE
Remove unreleased gear from the equipment selector

### ISSUE THREAD

**Issue by roy-van-dijk** [imchillin/Anamnesis#1155]
There is currently a bit of controversy going on in the ffxiv community over a billboard which is displaying a character with unreleased gear. I think it is fairly safe to assume Anamnesis was used to create the image and it would be a shame if this project got in trouble because of that.

As much as I like this feature I think it would be safer to remove it.

**Comment by Ani-ki** [comment]
Of note: This would need to be manually handled, which means someone will need to be proactive in masking them out. And that unfortunately wouldn't prevent people from merely entering the IDs in.

Ideally, SE could stop adding things preemptively, which would absolutely prevent this in future.

**Comment by RageShoTT** [comment]
i wouldn't go as far as implement such thing until square says something, it's very likely that they instead go and stop adding item all together (as they were against datamine even before this last billboard thing)

**Comment by Yuki-Codes** [comment]
We have no plans on doing this, as we don't have a way to filter out unreleased gear vs NPC gear.
