### ISSUE TITLE
.Net Runtime download link leads to the incorrect page according to the wiki.

### ISSUE THREAD

**Issue by Zilronman** [imchillin/Anamnesis#1156]
The link to download .Net 6.0.6 when attempting to run Anamnesis without it can be incorrect.

The Link leads to https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime?cid=getdotnetcore , which downloads the runtime. However, I needed to download the .NET desktop runtime [which includes the linked runtime] for Anamnesis to work on my system [Windows 10, no abnormal modifications in place]. This is consistent with the Basic Setup page on the wiki. The link in the program itself leads to a page inconsistent with how the wiki is written.

**To Reproduce**
1. Do not have .Net Framework 6.0.6 set up and attempt to run Anamnesis
2. Click the link to install .Net
3. You are now at the page that has the incorrect download.

**Expected behaviour**
I expected the link the program gave me to allow me to download the proper runtime without opening the wiki or exploring Microsoft's website.

**Log file**
The first Log File is from before I downloaded the Runtime at the link to install .Net. No log files were generated afterwards until I solved my problem. The second log file was generated after I downloaded the Desktop Runtime and tested Anamnesis. It ran properly.
[2022-07-05-21-12-59.txt](https://github.com/imchillin/Anamnesis/files/9055488/2022-07-05-21-12-59.txt)
[2022-07-06-07-59-49.txt](https://github.com/imchillin/Anamnesis/files/9055491/2022-07-06-07-59-49.txt)

**Comment by RageShoTT** [comment]
The popup requiring you to download net 6.0 is microsoft stuff so not a lot we can do btw
