### ISSUE TITLE
Option to exclude expression when loading pose

### ISSUE THREAD

**Issue by ivalith** [imchillin/Anamnesis#1157]
**Is your feature request related to a problem? Please describe.**
The problem I have is that as a femroe player my face is almost always distorted when trying out a shared pose if it was designed using most other races and so trying out poses is always a process of importing the pose itself and then having to go another step of importing an individual expression in order to actually evaluate it because the distorted faces are so distracting. 

**Describe the solution you'd like**
What I'd like is to have something like a checkbox or a toggle switch that lets me ignore the expression when importing a pose file so my character's face remains however it was prior to importing the pose. I imagine this might be a niche issue but it would be incredibly helpful and I'd really appreciate it being considered as a feature to add.

**Comment by CapnKett** [comment]
That already exists.

Import [v] > Load body pose

**Comment by ivalith** [comment]
> 

Thank you I just completely missed this, appreciate the help.
