### ISSUE TITLE
Anamnesis fails to recognize NET Runtime after installation

### ISSUE THREAD

**Issue by Jenneke42** [imchillin/Anamnesis#1163]
**Describe the bug**
Upon downloading Anamnesis (v.2022-07-05) and running .exe as administrator, it requires Microsfot .NET runtime updated to 6.0.6 and opens browser window. After downloading x64 version for Windows 10 [Link used](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.6-windows-x64-installer) and re-running Anamnesis, Anamnesis displays error message: "To run this application, you must install missing frameworks for .NET." Clicking 'Yes' to install redirects you to the above URL and re-downloads the exact same file as before.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have Microsoft .NET not updated to v6.0.6
2. Download Anamnesis v2022-07-05 and run executable
3. Download and install Microsoft .NET x64 for Windows 10, v6.0.6 from URL opened by Anamnesis
4. Restart Anamnesis
5. Click 'Yes' to install missing frameworks.

**Expected behaviour**
Anamnesis should start after updating Microsoft .NET to v6.0.6.

**Log file**
Unable to provide log file, as Anamnesis fails to start.

**Comment by Ani-ki** [comment]
The link provided is done so by Microsoft, not Anamnesis. It links to the incorrect Runtime- per the installation instructions, the **Desktop** Runtime is required. Please ensure you have that installed.
