### ISSUE TITLE
Au Ra F expression not loading

### ISSUE THREAD

**Issue by SweetiieFox** [imchillin/Anamnesis#1166]
**Describe the bug**
When loading the expressions added to the standard library, the ones (and only them) for Au Ra F don't work at all. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go in gpose
2. Go to 'Pose - Pose your character'
3. Freeze your character
4. Click on 'Import'
5. Go to the 'Built In Poses' folder
6. Click on the 'Expressions' folder
7. Click on the 'Au Ra F' folder
8. Click on any of the expressions, all will reproduce this behavior

**Expected behaviour**
Nothing is happening, the character expression doesn't change. 

Here's a video for an example, and also an example that expression for other races and genders work: https://streamable.com/ensjn8

**Comment by RageShoTT** [comment]
Yup can confirm it seems like Aura F expression aren't working, it does work on my Viera tho so i think it's on the pose file itself

**Comment by RageShoTT** [comment]
As per discussion in the discord with Ari Elezen F also has this issue

**Comment by Peebs-miqo** [comment]
This has been fixed in the latest release.
