### ISSUE TITLE
Scaling not working as intended with the newest update

### ISSUE THREAD

**Issue by KaiMods** [imchillin/Anamnesis#1167]
When trying to scale up using either mouse wheel or manual input, number rubber bands back to 1, regardless of if in or out of Gpose

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Ana
2. Go to the posing Menu
3. Interact with scaling
4. Rubberbanding back to '1'

**Expected behaviour**
Scaling to stick to chosen value.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[scaling.zip](https://github.com/imchillin/Anamnesis/files/9106281/scaling.zip)

**Comment by RageShoTT** [comment]
To add on that (in reference to what we did in community support)
Scaling option enabled
Net updated
Both scroll wheel and manually input result in the same behaviour

**Comment by RageShoTT** [comment]
Again as in community support discuss Moth did specified how disabling customize + did solve their issue, if you didn't do so try disabling that and the other plugin I keep forgetting the name to see if that changes something

**Comment by Yuki-Codes** [comment]
since this is a customize+ bug, we'll track it over there.
