### ISSUE TITLE
Error on attempting to import new .chara file

### ISSUE THREAD

**Issue by blairg23** [imchillin/Anamnesis#1170]
**Describe the bug**
Trying to import a chara file onto a selected character to begin gposing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Import'
2. Click on 'character.chara' (whatever chara file you're trying to import)
3. Click "okay"
4. Error screenshot (can't copy / paste for some reason):
![image](https://user-images.githubusercontent.com/6225764/179300555-e64fcff6-dc41-4c51-bac7-ff7ac2020ff3.png)

**Expected behaviour**
Chara data should import onto selected character.

**Comment by RageShoTT** [comment]
do you use Penumbra? if so do you have the HTTP Api enable in the advance settings there?

**Comment by blairg23** [comment]
I do use Penumbra. I haven't had this issue before with Penumbra, but how do I check that setting? I don't seem to be able to locate it.

**Comment by RageShoTT** [comment]
![Cattura](https://user-images.githubusercontent.com/22059860/179301181-475debb5-7517-4e2a-89aa-bdb5f3a1be31.PNG)

There

**Comment by blairg23** [comment]
Omg thanks so much! I didn't see it cos I didn't have the "Advanced Settings" checkbox checked.
