### ISSUE TITLE
Anamnesis just disappears once focus is lost

### ISSUE THREAD

**Issue by Ryushanna** [imchillin/Anamnesis#1172]
**Describe the bug**
You read the title. Anamnesis launches, updates and even work correctly but once i click back on the game or anywhere else i can't get Anamnesis to show again. Process is still running but won't show again.
Forcing "fullscreen" from the task manager will just display Anamnesis icon on the center of the screen, it will animate correctly when clicked on but won't show Anamnesis window.
For it to show again i have to shut it down from task manager and launch again, until i lose focus again and have to shut down and relaunch...

I don't think it's something we can reproduce and i doubt log files will help, but here's the last one generated today.
I thought about removing everything from Ana and install it again, but i'm not even sure it's going to do anything.

**Log file**
[2022-07-17-08-13-57.txt](https://github.com/imchillin/Anamnesis/files/9127128/2022-07-17-08-13-57.txt)

**Comment by RageShoTT** [comment]
Do you have Mini mode active in the settings? if not please try using another language (EN) just in case that changes something

**Comment by Ryushanna** [comment]
Thank you. Mini mode was the culprit.
Even with language set to english there is still the same problem with Mini mode.
The problem with Mini mode remains and need to be solved but since it just works without it i will set this case as "solved".
Thank you again !

**Comment by RageShoTT** [comment]
in mini mode the only way to show anamnesis is by clicking the anmanesis overlay in FFXIV (top left)

**Comment by Ryushanna** [comment]
Yeah i know, but it's not working anymore on my end. Nothing at the top left.
Thank you again and thank you for your work on Ana, that's really a great tool ^^
