### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by KhojinKurusu** [imchillin/Anamnesis#1173]
Just downloaded Anamnesis, and it asked me to download Windows windows .NET 6.0.0, when I clicked the link for "Next" it took me to 6.0.7, I downloaded 6.0.7 and it is now saying I need to download 6.0.0, but I can't download 6.0.0 because I have the newer version dowloaded, I'm not sure how to fix this or what to do. Is there any way I can fix this, or do I need to restart the entire installation process?

**Comment by EstoyMejor** [comment]
Make sure you downloaded the _**Desktop Runtime**_.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer

**Comment by KhojinKurusu** [comment]
...I was dumb and didn't do that. please just ignore I ever said anything so I may retain some sense of dignity.

**Comment by EstoyMejor** [comment]
Dont worry, it happens more often then youd expect ;)
