### ISSUE TITLE
Characters affected after closing anamnesis and forced loading screen

### ISSUE THREAD

**Issue by glasseschibi** [imchillin/Anamnesis#1174]
**Describe the bug**
Anamnesis crashed during gpose, forced it closed, restarted Anamnesis, came up with error and asked if i need to restart game however it then loaded home page. Once closed gpose and anamnesis (cant remember if saw pop up asking about losing pose), player was still frozen in posing mode even when moving, forced loading screen by teleporting to new area and player, other players and other objects in game glitched/was severely stretched out, had to close game to fix
**To Reproduce**
So far unable to reproduce, unsure what caused crash

**Expected behaviour**
Once Anamnesis closes, expected player to not be stuck in posing mode whislt moving and players and in game items not to be glitched despite forced loading screen

**Log file**
First log is from the crashed Anamnesis, second log is from the anamnesis that caused glitch despite forced loading screen

[2022-07-20-23-52-26.txt](https://github.com/imchillin/Anamnesis/files/9155195/2022-07-20-23-52-26.txt)
[2022-07-21-00-22-52.txt](https://github.com/imchillin/Anamnesis/files/9155196/2022-07-21-00-22-52.txt)

**Comment by Yuki-Codes** [comment]
Unfortunately, if Anamnesis crashes during posing, you must restart FFXIV to reset everything in memory.
