### ISSUE TITLE
"You must install or update .NET to run this application."

### ISSUE THREAD

**Issue by kuroganashi** [imchillin/Anamnesis#1175]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4380256/180125694-d784cf42-e0a7-4ad4-811b-a74cfe1384af.png)
![image](https://user-images.githubusercontent.com/4380256/180125714-90bfe303-09dc-4f0c-a0b4-eecc55b93973.png)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
Please doublecheck what you have installed. 

Your image clearly states you have the regular Runtime installed. The error clearly states you need the **Desktop Runtime**. They are not the same thing.

**Comment by EstoyMejor** [comment]
Get your wares from here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer

This is the one you need :)

**Comment by kuroganashi** [comment]
> Get your wares from here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer
> 
> This is the one you need :)

Thank you it worked !
