### ISSUE TITLE
Multiple Anamnesis processes found. Please close all other instances.

### ISSUE THREAD

**Issue by onelastkiss1230** [imchillin/Anamnesis#1176]
There are **no instances of Anamnesis already running** and I've **restarted the computer** several times. P.S, I also close the game and any other third party tool before relaunching the game and try again. My game is Chinese client.
_Reset your settings by holding down shift right after opening Anamnesis or rename/delete %appadata%\Anamnesis if it does let you and shift doesn't work._ This has been tried but still didn't work.

To Reproduce
Steps to reproduce the behaviour:
1.Start Anamnesis（ I've launched Final Fantasy XIV and logged into a character ）
2.Warning
3.An error occurred on the client
[2022-07-22-10-10-34.txt](https://github.com/imchillin/Anamnesis/files/9163955/2022-07-22-10-10-34.txt)
[2022-07-22-10-13-46.txt](https://github.com/imchillin/Anamnesis/files/9163956/2022-07-22-10-13-46.txt)

**Comment by onelastkiss1230** [comment]
![image](https://user-images.githubusercontent.com/109775394/180349933-899f970f-b876-4a47-9954-b4a98e96934a.png)

**Comment by RyanHans-La** [comment]
I have the same question too, and I can end this on task manager,because it shows access denied
![SharedScreenshot](https://user-images.githubusercontent.com/59070902/180410414-bb7bffaf-fafe-4b96-bfa2-c3b198bc5ad9.jpg)
.

**Comment by RyanHans-La** [comment]
我刚刚想重启进入安全模式删除来着，结果上图详细信息里的Anamnesis.exe阴差阳错的因为电脑关机的时候给强制关闭了，之前我有删除Anamnesis.exe和其所在的文件夹，你可以先删掉试一试不保证有用，但是我现在确实可以正常使用了。

**Comment by Ani-ki** [comment]
The development team only speaks English.

**Comment by RyanHans-La** [comment]
我刚刚想重启进入安全模式删除来着，结果上图详细信息里的Anamnesis.exe阴差阳错的因为电脑关机的时候给强制关闭了，之前我有删除Anamnesis.exe和其所在的文件夹，你可以先删掉试一试不保证有用，但是我现在确实可以正常使用了。

**Comment by RyanHans-La** [comment]
I tried to tell onelastkiss1230 that I solved tihs problem by restarting the computer and becasue onelastkiss1230 is in  Chinese client so I write it by Chinese.

**Comment by RageShoTT** [comment]
on the subject, please keep in mind that Anamnesis might (or to be more honest can't) work on Chinese clients

**Comment by RageShoTT** [comment]
also that's a very old version of Anamnesis that you are using

**Comment by onelastkiss1230** [comment]
Wow it's quiet useful!!!! I I did solve the problem by deleting and installing the software. Thanks for everyone!! The problem was solved magically.

**Comment by onelastkiss1230** [comment]
I have no choice but to use this version because Chinese clients is still at version 6.05. Thanks again.
