### ISSUE TITLE
.net issues

### ISSUE THREAD

**Issue by KingKusho** [imchillin/Anamnesis#1180]
**Describe the bug**
When updating to .net 6.0 (v6.0.7) Anemnesis seems to refuse to acknowledge its installed. every single time i run it, it asks me to update it or shut the program down. I've gone through my programs and deleted all instances of .net (had a 5.0 in there) then re downloaded it fresh and it still tells me to install the same .net i have installed

**To Reproduce**
Im not sure how to tell others how to reproduce it. clean install of .net v6.0.7 and watch anemnesis say nope?

**Expected behavior**
For the program to open up and allow me to pose my character

**Log file**
I cannot open Anemnesis to even provide a log file. it only provides me the options to download .net or close program

**Comment by RageShoTT** [comment]
Please be sure you are installing the Desktop Runtime of .net as Microsoft can't make a decent download page (btw that, pop up error aswell, is all outside of anamnesis)

here you have the direct download

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer

**Comment by LongTimeNoSiege** [comment]
I'm having this same issue. Anamnesis refuses to open and says .net is not installed, when .net is installed.

**Comment by Ani-ki** [comment]
Are you using the link provided in the Anamnesis zip? The link that Anamnesis itself throws is actually Windows being a dick, and it's sending you to the wrong runtime. We provide a direct link to the desktop runtime.

**Comment by Peebs-miqo** [comment]
No further replies so I'll assume that this issue is fixed.
