### ISSUE TITLE
Constantly getting a Penumbra HTTP API Error on attempt to change appearance

### ISSUE THREAD

**Issue by Fourtunehunter1** [imchillin/Anamnesis#1182]
**Describe the bug**
Any time I try to change the appearance of anyone in game, whether in gpose or outside of it, I always get a: Error Refreshing Actor... Penumbra HTTP API error...
Even clicking the Reset for resetting the appearance will cause the error to pop up

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Char tab
2. Click on Import NPC
3. Find NPC you want to change them to
4. Click on NPC
5. See error

**Expected behaviour**
Expected that the NPC I'm attempting to change will change into the selected NPC

**Log file**
[2022-07-27-18-19-55.txt](https://github.com/imchillin/Anamnesis/files/9204015/2022-07-27-18-19-55.txt)

**Comment by chirpcodes** [comment]
Disable "Use Penumbra Redraw" under the Penumbra section in your settings.

**Comment by Fourtunehunter1** [comment]
Yes, that seems to have fixed it, thank you!

**Comment by Bloody-Muse** [comment]
I have been getting the same thing, and followed the turning redraw off, and now I can't even select items.

Maybe it has something to do with not being able to uninstall previous versions of Anamnesis that were doing the same thing...

**Comment by EstoyMejor** [comment]
You can't 'uninstall' Anamnesis since you don't 'install' it in the first place. Try holding shift while starting Anamnesis, that should reset the settings and see if it works then.
