### ISSUE TITLE
It doesn't even open. 

### ISSUE THREAD

**Issue by PancakeOakhurst** [imchillin/Anamnesis#1183]
It doesn't even open and tried everything the troubleshooting guide said. It prepares to launch then silently closes but the fixes listed didn't help. 

[2022-07-31-01-01-09.txt](https://github.com/imchillin/Anamnesis/files/9229342/2022-07-31-01-01-09.txt)

**Comment by RageShoTT** [comment]
you are on a very old version of Anamnesis, please download the last release from the download page and .NET 6.x desktop runtime

https://github.com/imchillin/Anamnesis/releases/latest

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

**Comment by PancakeOakhurst** [comment]
Well here is the other thing. Every time I try to update it, it says it updates then it still has the same thing in the log. I'm still kinda lost lol

**Comment by PancakeOakhurst** [comment]
I fixed it. I just had to deep dive into my files and delete all old/existing files. I dunno why I had a bunch of older versions still but its fixed.
