### ISSUE TITLE
Entering gpose afters using anamnesis starts endless loading screen/black screen

### ISSUE THREAD

**Issue by Paprikahoernchen** [imchillin/Anamnesis#1185]
Sometimes (not always!) when I use anamnesis to create an outfit, change the race of my toon or smth like this and try to enter gpose ffxiv enters a black screen and won't stop loading. And then I have to force close the program. No idea what causes this in detail or what to do. 

I also use penumbra and dalamud plugins. (bdth, chat bubbles, peeping tom)

**Comment by Yuki-Codes** [comment]
This is usually cased by not having a valid mainhand / offhand combo equipped for the animation you last did, as GPose attempts to loop the last animation.

Make sure you have a valid weapon or prop, and try sitting and standing up to reset your animations before entering GPose.

**Comment by Paprikahoernchen** [comment]
Oh for real? O:

Guess the coffee cup was evil then >.> 

Good to know, thank you so much <3
