### ISSUE TITLE
Adding full animation path to Animation Status

### ISSUE THREAD

**Issue by ggonok** [imchillin/Anamnesis#1186]
**Is your feature request related to a problem? Please describe.**
Currently, the animation status only shows the last few sub-folders of any given animation, and can't feasibly be used to find animations with it.

**Describe the solution you'd like**
Having an option to get it to show the full path to an animation would be of great help in locating an animation's path in the game files, and would also help avoid trying to load animations with the wrong data path, as it would show right away what skeleton an animation is for.

**Comment by AsgardXIV** [comment]
The path that is show in Anamnesis is the ActionTimeline path, which is what the game uses to determine which animations to play.

There's a bunch of logic game side which takes place to determine which animation plays for a given timeline (for example, a timeline can play multiple individual animations).

So unfortunately this isn't trivial to do. Tools like VFXEditor and XAT are better placed for this kind of logic.
