### ISSUE TITLE
Updating anamnesis causes program to display critical error and closes before running

### ISSUE THREAD

**Issue by misstsundere** [imchillin/Anamnesis#1187]
**Describe the bug**
Everytime I load the program, it gives me an error code saying my files may not be up to date after updating. Resetting the program (shift key) allows it to update it again but the same code keeps popping up.

**To Reproduce**
Steps to reproduce the behaviour:
1. run anamnesis
2. update to current version
3. bug procs

**Expected behaviour**
anamnesis runs

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

[2022-08-08-17-50-31.txt](https://github.com/imchillin/Anamnesis/files/9285451/2022-08-08-17-50-31.txt)

**Comment by RageShoTT** [comment]
Please manually update the tool by downloading the lastest realese from https://github.com/imchillin/Anamnesis/releases/latest

This will also require you to download .net6 desktop runtime, here's the download link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.7-windows-x64-installer
