### ISSUE TITLE
Mini mode toggle ended up off screen somehow, making it impossible to use mini mode

### ISSUE THREAD

**Issue by PremaMarina** [imchillin/Anamnesis#1188]
![anatoggle](https://user-images.githubusercontent.com/75226914/183628420-49f69b1e-aa4f-4906-a8d5-637e907c9e63.png)

Mini mode toggle ended up off screen somehow so I can't use mini mode anymore, cause it's impossible to press it.
Is there any way to reset its position?

Anamnesis is not a proper install on my system, to uninstall it and reinstall it, so even when I download a newer version, the mini mode toggle stays off screen.

**Comment by Yuki-Codes** [comment]
Hold Shift while starting Anamnesis to reset your settings, that should bring the window back to its default position.

We're aware of the mini mode issue, we have a fix coming as part of a larger update soon.
