### ISSUE TITLE
Camera position not working

### ISSUE THREAD

**Issue by FiraliaDev** [imchillin/Anamnesis#1195]
**Describe the bug**
Upon attempting to move the camera in gpose, it glitches back to its initial position. 
Both myself and a friend have experienced the bug, and it's only happened in the past couple days. It's ongoing, and restarting both the game and Anamnesis (XIVLauncher _and_ vanilla launcher versions) does not fix it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter gpose
2. Go to the home tab
3. Adjust camera position sliders (xyz)
4. After a few seconds, the camera will snap back to the initial position.

**Expected behaviour**
Camera should stay in the place indicated by the position slider in Anamnesis.

**Log file**
[2022-08-19-11-49-22.txt](https://github.com/imchillin/Anamnesis/files/9378746/2022-08-19-11-49-22.txt)

**Comment by SoyaX** [comment]
Disable motion in the in game gpose window.
