### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by blacklion5000** [imchillin/Anamnesis#1199]
describe the bug
when the error appears it is like the last time like the previous patch I made sure I had downloaded the most current version but it continues to give an error
![photo_2022-08-23_13-47-46](https://user-images.githubusercontent.com/103529883/186162133-66ab17d6-8d10-49e1-b4e1-037e230a6dad.jpg)

**Comment by Ani-ki** [comment]
Anamnesis has not been updated for the latest game patch. Please be patient.
