### ISSUE TITLE
Critical error - Failed to initialize Lumina (Are your game files up to date?) - After 6.2 patch

### ISSUE THREAD

**Issue by Spliph** [imchillin/Anamnesis#1202]
**Describe the bug**
Critical error when attempting to open Anamnesis.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open game and log on with character
2. Open Anamnesis once character has loaded into world
3. See error

Game files should be up to date since patch 6.2 was downloaded successfully and I was able to log into the game without issue.

![image](https://user-images.githubusercontent.com/111918203/186257751-05fd605c-d70b-4325-9980-f8ad6eaf6917.png)

**Comment by EstoyMejor** [comment]
The tool is not currently able to run with 6.2. Wait for an update, it should release soon(-ish).

**Comment by Spliph** [comment]
@EstoyMejor Thank you! ♥
