### ISSUE TITLE
Changing character height no longer adjusts nameplates and camera position

### ISSUE THREAD

**Issue by velemi** [imchillin/Anamnesis#1203]
**Describe the bug**
After updating to version 2022-08-24, adjusting a character's height through the 'Model' section no longer adjusts the character's nameplate or camera position. In previous versions, the camera and nameplate would automatically adjust to match the change in character height.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load an actor and go to the 'Character' tab.
2. In the 'Model' section, change the height value up or down. The nameplate position will not change.

**Expected behaviour**
The nameplate position (and camera position, if the actor is the player's character) should be updated automatically to match the height value set in the character tab, as was the case in previous versions of Anamnesis.

**Comment by AsgardXIV** [comment]
Fixed in #1204
