### ISSUE TITLE
"You must install or update .NET to run this application" 

### ISSUE THREAD

**Issue by Dausu** [imchillin/Anamnesis#1208]
**Describe the bug**
Good evening to you. So me and a FC member have encountered a persistent error when attempting to run Anamnesis after the game update & we are constantly hit with this:
![image_2022-08-25_215407413](https://user-images.githubusercontent.com/112142353/186806467-9c5f8cd9-9c7d-4d05-8b4e-38ba2a832970.png)  Every. Single. Time. I have followed the solution prompts on this website as well as updating my game files in addition to reinstalling Anamnesis. I have updated my .NET to the newest version that was requested, yet I am still unable to run this program for whatever reason. My mate is running into the exact same issue & we are unable to wrap our heads around it. 

Running in Administrator did not help at all, either. We would greatly appreciate the help if anyone here could assist. Thank you.

**Comment by Ani-ki** [comment]
That's a Windows issue, unfortunately. There's no way to force that dialogue to send you to the correct download. If you look in the Anamnesis folded there should be a web link that will take you directly to the Desktop Runtime.

**Comment by Dausu** [comment]
OMG that worked!!! Thank you so much!!! Gonna tell my mate about it!

**Comment by Dausu** [comment]
> That's a Windows issue, unfortunately. There's no way to force that dialogue to send you to the correct download. If you look in the Anamnesis folder there should be a web link that will take you directly to the Desktop Runtime.


OMG that worked!!! Thank you so much!!! Gonna tell my mate about it!
