### ISSUE TITLE
Initialize Lumina?

### ISSUE THREAD

**Issue by Callmenannerpuss** [imchillin/Anamnesis#1210]
when launching it gives a critical error that the tool failed to initialize Lumina. it asks if my game files are up to date but i have updated the game and ana. please help, this has never happened before

![Screenshot 2022-08-26 214348](https://user-images.githubusercontent.com/112223391/187009393-65bf0b83-c69f-4b47-b6b4-b6272b8b7b48.png)

**Comment by Rosabeth** [comment]
Also having this same problem

**Comment by Ani-ki** [comment]
You're on a super old version. Grab the latest version from the Releases page, and then grab the 6.0.6 DESKTOP runtime. Install both, and you'll be golden.

**Comment by Callmenannerpuss** [comment]
Thank you! i had everything downloaded, i just didnt replace the old files with the new ones. Thank you so much!

**Comment by TXKBOY** [comment]
https://github.com/imchillin/Anamnesis/releases/download/v2022-08-29/Anamnesis.zip，I downloaded the latest version, so why did this problem happen? It doesn't work even if I installed NET Desktop Runtime6.0.6.

**Comment by EstoyMejor** [comment]
> https://github.com/imchillin/Anamnesis/releases/download/v2022-08-29/Anamnesis.zip，I downloaded the latest version, so why did this problem happen? It doesn't work even if I installed NET Desktop Runtime6.0.6.



Get this one: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer
