### ISSUE TITLE
multiple anamnesis running?

### ISSUE THREAD

**Issue by caramelbubbles** [imchillin/Anamnesis#1212]
Was trying to gpose in Anamnesis Anyder (Explorer Mode) instance and received a critical error window in Anamnesis saying "Multiple Anamnesis processes found. Please close all other instances." I closed out my Anamnesis window through Taskmaster and then attempted to open it again in instance with the same result. I left the instance and still received the same window. I'm on v2022-08-24!

The log was as follows: 

**[Exception]** Multiple Anamnesis processes found. Please close all other instances.
at Anamnesis.App.CheckForProcesses()
at Anamnesis.App.Start

**Comment by TXKBOY** [comment]
me too
