### ISSUE TITLE
Model Height

### ISSUE THREAD

**Issue by NeoFooty** [imchillin/Anamnesis#1214]
When changing the Model -> Height, the value is reset back to 1 upon getting on a mount. Also no longer changes your camera/name height to your character on applying.

Earlier versions any changes persisted when mounting and your camera automatically adjusted to your height change.

**Comment by AsgardXIV** [comment]
This was fixed in #1204 and is in the latest Ana release.

**Comment by NeoFooty** [comment]
Can confirm launching now prompted update and issue has been fixed, thanks!
