### ISSUE TITLE
Continued height issue

### ISSUE THREAD

**Issue by MyUserNameWasNotAvailable** [imchillin/Anamnesis#1215]
I updated to the latest version of ana, the previous one had that height issue but it's even worse now, even with scaling set to 1 on both characters, the height difference is way off.

**Comment by AsgardXIV** [comment]
They wouldn't both be 1 though in most cases.
The model height is the real rendered height/scale of the model, scaled based on the height in customize. 

So for example, a Min Male Miqo'te at 159cm (1 on the slider) would have a model of 0.911.

In general, you should use the customize height slider, then scale the model if you want to go outside the range available in customize.

Unless I am missing something, I believe that's how it's meant to work and worked before 6.2.

**Comment by MyUserNameWasNotAvailable** [comment]
Ah okay I see, I tried to just reloading the models and the height difference was still way bigger, and I usually don't play around with the height sliders, I use default for both

**Comment by MyUserNameWasNotAvailable** [comment]
Wait nvm I'm not smart, seems like the models I re-saved from the previous bug are causing me this issue! It's sorted!

**Comment by AsgardXIV** [comment]
The model height issue that was introduced by Patch 6.2 in Anamnesis 2022-08-24 is now resolved in Anamnesis 2022-08-29.

Appearances created prior to the 2022-08-24 version or on/after the 2022-08-29  version will continue to work correctly as before.

Appearances saved with the 2022-08-24 version will set the height incorrectly when being loaded.
To work around this, the user should adjust the height in the customize section of Anamnesis (for example if the height is 5, set it to 6 and then back to 5). This will correctly set the model height to what it should be, and the appearance can be saved again.
