### ISSUE TITLE
Unable to run.

### ISSUE THREAD

**Issue by TXKBOY** [imchillin/Anamnesis#1217]
![001](https://user-images.githubusercontent.com/56968863/187854031-abda26c3-1339-4258-ab5d-5f5eb2f829f3.jpg)
It's a strange problem. That's how I downloaded the latest file. The Windows Desktop-Runtime-6.0.6-Win-x64 that I installed is also the latest version. The problem is strange.

**Comment by Peebs-miqo** [comment]
Please upload a log so we can verify the version of the tool and .NET runtime. Screenshots of error messages are not helpful.

**Comment by ImJustKelly** [comment]
I have also received this same error after updating the tool.  Game and .NET are up to date.  Have never encountered this error before.  (I hope I have added my log correctly.)

[2022-09-01-13-22-12.txt](https://github.com/imchillin/Anamnesis/files/9472165/2022-09-01-13-22-12.txt)

**Comment by EstoyMejor** [comment]
> I have also received this same error after updating the tool. Game and .NET are up to date. Have never encountered this error before. (I hope I have added my log correctly.)
> 
> [2022-09-01-13-22-12.txt](https://github.com/imchillin/Anamnesis/files/9472165/2022-09-01-13-22-12.txt)

you have a very old version, download the newest version form this github.

**Comment by ImJustKelly** [comment]
Clean install of both Anam and .NET and it works again.  Thank you.
