### ISSUE TITLE
Windows 10 error

### ISSUE THREAD

**Issue by TamaoRengar** [imchillin/Anamnesis#1218]
I keep getting an error saying that anamnesis needs windows 10 or newer to run when I run my pc on windows 10.

**Comment by EstoyMejor** [comment]
Does your PC run windows 10 Educational?

**Comment by TamaoRengar** [comment]
It's currently running windows 10 home. I will try updating it to windows 11 and see if it works like that.

**Comment by EstoyMejor** [comment]
I wouldnt recommend installing W11 unless you know you want it. 
Try getting some W10 updates first maybe and see if that fixes it.

**Comment by TamaoRengar** [comment]
My windows 10 seems to be up to date apparently. Not sure if going back to another version of windows 10 would help in that case (though I'm not even sure how I would do that)

**Comment by harkmagic** [comment]
Same issue. first time install. Windows 10 up to date. Followed all install directions. It crashes and tells me that it is because I don't have Windows 10.

**Comment by Yuki-Codes** [comment]
Make sure you are not running Anamnesis in compatibility mode: 
![image](https://user-images.githubusercontent.com/379714/188560453-3a6b743e-f410-4a89-aec2-b6da14e67945.png)
