### ISSUE TITLE
NET Framework 6.0 Issue

### ISSUE THREAD

**Issue by Eris98** [imchillin/Anamnesis#1219]
I redownloaded a fresh version of Anamnesis for 6.2 since I hadn't updated in a while and when I start up the program I keep getting walled by a dialogue box requiring me to download the Microsoft NET Framework 6.0. I've downloaded and installed it for both x64 and x86 for the odd chance that it helps, but nothing is working to make the program open. If it changes anything, the current version on the MS website is 6.0.8 or something so Anamnesis may not be written to look for that version? Please advise (I'm using Windows 10).

**Comment by EstoyMejor** [comment]
Get this version: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

The popup comes from windows, not Anamnesis. Windows is dumb and links to the wrong one.

**Comment by Eris98** [comment]
Yup, that did it, thanks!
