### ISSUE TITLE
Help with Anamnesis plz.

### ISSUE THREAD

**Issue by AceofDisasters** [imchillin/Anamnesis#1224]
I keep getting an error every time I try and load Anamnesis for Final Fantasy XIV. The game and Anamnesis are both up to date so I don't know what's wrong. I closed and opened the game like 5 times, shut of my computer and even uninstalled Anamnesis. I'd rather not uninstall FFXIV if I can help it. 
![unknown](https://user-images.githubusercontent.com/112817984/188322298-3e372496-f2ac-4cb8-a135-a24cb01c6c89.png)

**Comment by EstoyMejor** [comment]
Your version is Ancient. Please update.

**Comment by KajesLorian** [comment]
I'm getting the exact same error after using the update prompt and restarting
![image](https://user-images.githubusercontent.com/16963626/188322822-b2df7a1b-7542-4a4a-90d1-e07e606bb065.png)

**Comment by EstoyMejor** [comment]
Your version is also not up to date. Please grab the newest version from the Github releases channel [Here](https://github.com/imchillin/Anamnesis/releases/tag/v2022-09-04).
