### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by woowind** [imchillin/Anamnesis#1225]
Keeps crashing say it cant find the directx 11 file, but im useing directx11.  i didnt have an issue with it until game update and update on the program. was running fine. It dont make any sense. Im useing directx 11. i tried many different things. cant fix it.

**Comment by EstoyMejor** [comment]
Please upload a log. And next time follow the bug report form.

**Comment by woowind** [comment]
you say upload a log. what log and where is it? i screenshot the errors it giving. where the bug report form? im new here. 
    On Sunday, September 4, 2022 at 05:32:38 PM CDT, Estoy Mejor ***@***.***> wrote:  
 
 


Please upload a log. And next time follow the bug report form.

**Comment by woowind** [comment]
figured out it cm tool causeing the game to crash with directx 11 errors. im not sure as to why. i have always ran both same time no problem. but i loaded cm tool in alone, it crashed it. anamnesis, loads in alone fine and dont crash    On Sunday, September 4, 2022 at 05:59:20 PM CDT, Charlene King ***@***.***> wrote:  
 
  you say upload a log. what log and where is it? i screenshot the errors it giving. where the bug report form? im new here. 
    On Sunday, September 4, 2022 at 05:32:38 PM CDT, Estoy Mejor ***@***.***> wrote:  
 
 


Please upload a log. And next time follow the bug report form.
