### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by ffxivgamergirl** [imchillin/Anamnesis#1227]
it will not allow me to use anamnesis and im not sure why. keeps saying critical error and my game is update to the latest patch and all. but its been like this for a few weeks. any idea what to do to fix it

**Comment by EstoyMejor** [comment]
Download the newest version from the releases tab.

**Comment by ffxivgamergirl** [comment]
i did

**Comment by Ani-ki** [comment]
Please provide a log file.

**Comment by ffxivgamergirl** [comment]
log file?

**Comment by EstoyMejor** [comment]
https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#accessing-log-files-for-issue-reporting

**Comment by ffxivgamergirl** [comment]
fixed it. thank u

**Comment by EstoyMejor** [comment]
Would you grace us with an expanation on how for future references?
