### ISSUE TITLE
Critical error with new version launch

### ISSUE THREAD

**Issue by JesuFernandez** [imchillin/Anamnesis#1228]
**Describe the bug**
After updating the app to the latest version, a critical error aiming at a certain value's length does not allow any further execution.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis as administrator
2. Execute the current update

**Repeatability**
- Tested under normal ciscumstances. Error kept executing.
- Downloaded previous version and executed, same error.
- Uninstalled current runtime version, re-tried with 6.0.8 and 6.0.9, no changes.

**Log file**
![ana_error](https://user-images.githubusercontent.com/30236497/190228886-a1691d89-b49d-409b-af93-07c9f90e5f38.png)

**Comment by Peebs-miqo** [comment]
No further comments so I'll assume this is resolved.
