### ISSUE TITLE
Anamnesis wont open 

### ISSUE THREAD

**Issue by sercatthew02** [imchillin/Anamnesis#1230]
**Describe the bug**
anamnesis will not open, fails to start up and doesn't even show up in my roaming folder at all, icon is on desktop and .NET was downloaded, uninstalled and reinstalled it worked before then suddenly didn't, CMTools worked just fine until this new patch. 

only thing that pops up that might be of use that i could've used would've been the AppCrash files that keep being generated, only problem is no matter what permissions I give myself,  I tried to attach one here and no luck. 

**To Reproduce**
Steps to reproduce the behaviour:
1. download Anamnesis
2. Run as administrator 
3. fails to open

**Repeatability**
Every time 

**Expected behaviour**
Program to open

**Log file**
I can't even get a log file, its as if it hasn't fully downloaded onto my computer, CMTools folder is still there.

**Comment by EstoyMejor** [comment]
Without any kind of log, nothing, it's kinda hard to troubleshoot.

Try holding shift while starting Anamnesis.

**Comment by Yuki-Codes** [comment]
Make sure you've installed the correct version of dotnet. there is an installer in the download zip, and a link directly to the correct download. If that doesn't solve it, have a look in the Windows Event Viewer, under Windows Logs -> Application, and see if there are any errors in there relating to Anamnesis.

**Comment by sercatthew02** [comment]
so it actually was the dot net! the one that is in the folder for some reason wasn't working, i upgraded to a different version still within the 6.0 something and anamnesis ended up working!
