### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by TXKBOY** [imchillin/Anamnesis#1231]
my friend ，have the latest Anamnesis, the latest. NET, but it still can't run.
[2022-09-16-16-35-50.txt](https://github.com/imchillin/Anamnesis/files/9582195/2022-09-16-16-35-50.txt)
log
![001](https://user-images.githubusercontent.com/56968863/190595097-db97930d-dc48-4d50-8d5a-c1d6a5dd6497.jpg)

**Comment by EstoyMejor** [comment]
Anamnesis does not officially support the Chinese version of the game. Try an older version, maybe that works.

**Comment by TXKBOY** [comment]
> Anamnesis官方不支持游戏中文版。试试旧版本，也许有用。

Anamnesis9.4 can run, but it crashed today. I just want to try the latest version and then it crashed. It's a sad story.

**Comment by EstoyMejor** [comment]
Yeah, the newest version won't run because the Chinese version of the game is behind the global one. So you need an older version in order for it to work.
