### ISSUE TITLE
Minion reverts back to it's un-modded state when I start /gpose with Anamnesis active

### ISSUE THREAD

**Issue by T3L3V1510N** [imchillin/Anamnesis#1232]
When I start /gpose with Anamnesis active modded minions revert back to their original model. As a work around I'm able to start /gpose before running Anamnesis.

**Comment by EstoyMejor** [comment]
Yep. Dont use minions, they dont work.

**Comment by T3L3V1510N** [comment]
But they have worked in the past, or am I going crazy?

**Comment by Peebs-miqo** [comment]
Minions modded with Penumbra either need to be put in your *default* collection or a *named* character collection. Not the *Your Character* collection
