### ISSUE TITLE
Actor in Motion

### ISSUE THREAD

**Issue by Konekomods** [imchillin/Anamnesis#1233]
When posing with a Fairy, no matter what fairy is labeled in motion. Have relogged, made sure the program is up to date, have made sure fairy is for sure frozen, and have tried other zones. I am continued to get the message Actor motion must be disabled in Group pose...... 
[2022-09-18-03-49-08.txt](https://github.com/imchillin/Anamnesis/files/9593718/2022-09-18-03-49-08.txt)

**Comment by Ani-ki** [comment]
You may want to update to the correct version of the **[.NET Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer)**.

**Comment by Peebs-miqo** [comment]
No further comments so I'll assume this is resolved.
