### ISSUE TITLE
Anamnesis fails to install

### ISSUE THREAD

**Issue by GinnySsk** [imchillin/Anamnesis#1234]
**Describe the bug**
I try to install Anamnesis.  An error message appears saying: "To run this application, you must install missing frameworks for .NET."
I checked: my Windows 10 does installed .NET Framework 4.8
I restarted my computer. The problem is not solved. 
Then I installed the lastest Ver. .NET Framework 4.8.1. and restarted my computer. Still the problem is not solved. I got the same error message.
Then I try to install CMTools. CMTools is successfully opened. (To open CMTools also requires NET framework installed)
So I guess：Bug is: NET Framework is installed but somehow  Anamnesis can not recognize it.
So sad I don't know how to solve it.

**To Reproduce**
Steps to reproduce the behaviour:
download Anamnesis
Run as administrator
See error message appears: "To run this application, you must install missing frameworks for .NET."

**Repeatability**
How often does the bug occur:
Every time

**Expected behaviour**
I hope to install Anamnesis.

**Log file**
I checked there is no log file. In the Roaming folder there is no  Anamnesis folder.
I guess it is because I could not install Anamnesis.

**Comment by EstoyMejor** [comment]
Version 4 of .NET is ancient.

Get this one https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

**Comment by GinnySsk** [comment]
> Version 4 of .NET is ancient.
> 
> Get this one https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer
Thanks for your help.
I installed .NET 6.0.9 before the error message appears.  The error message is not “ you must install .NET.” ，but " you must install missing frameworks for .NET "
I have both .NET 6.0.9 and  .NET Framework 4.8 installed before I try to open Anamnesis.
I guess the issue is with frameworks, not .NET.

**Comment by EstoyMejor** [comment]
Please install the linked version.

**Comment by GinnySsk** [comment]
> Please install the linked version.

Thank you for your kind help. Followed you instruction and the problem is solved!!!!! Soooooo happy!!!
