### ISSUE TITLE
Anamnesis crashes often when using the search for Poses etc

### ISSUE THREAD

**Issue by Enduni** [imchillin/Anamnesis#1239]
Hey,

I'm rather frequently experiencing crashes of Anamnesis when using the search for Poses, though not exclusively when running the search in my poses folder. Also happened when searching the pre packaged poses and expressions though, so it is likely not my poses that are corrupted. 

It appears to be an issue for not many people though, so I'm not sure you can easily reproduce it. It's just entering a search command and then hovering repeatedly. Seems to be a tooltip issue. Here's two example logs with a clean restart of the game.

[2022-10-11-18-10-06.txt](https://github.com/imchillin/Anamnesis/files/9758366/2022-10-11-18-10-06.txt)
[2022-10-11-19-09-12.txt](https://github.com/imchillin/Anamnesis/files/9758367/2022-10-11-19-09-12.txt)

**Comment by AsgardXIV** [comment]
This is a known issue with the version of DotNet you are using.
Grab the latest version: https://download.visualstudio.microsoft.com/download/pr/a6e878eb-d1da-40cb-8b6a-7f5b9390f09c/e4431ce2aa28b6c9956db672209be500/windowsdesktop-runtime-6.0.10-win-x64.exe

**Comment by Enduni** [comment]
Thanks, I'll update it!
