### ISSUE TITLE
Requesting feature that allows loading next pose in current folder

### ISSUE THREAD

**Issue by ivalith** [imchillin/Anamnesis#1241]
**Is your feature request related to a problem? Please describe.**
My problem is that when I'm browsing through a folder with lots of pose files through the use of "Import" to try and find one I'd like, the process of clicking import and sifting through each pose often takes awhile and requires going through the folder one pose at a time.

**Describe the solution you'd like**
What I'd like to request is a feature like a button or arrows that can be used instead of the import button that will go to the previous or next (alphabetical) pose in the folder I last loaded a pose from and load the previous/next pose file instead of having to click import and find it by browsing through the folder. Presumably it would follow the alphabetical or newest-to-oldest sorting that I last chose when browsing through the folder. Thank you.

**Comment by Yuki-Codes** [comment]
This is something we are addressing with the [Anamnesis-Studio](https://github.com/XIV-Tools/Anamnesis-Studio) update with a new pose / file selector, (please look forward to it!) but it's unlikely to be implemented in the current Anamnesis version.
