### ISSUE TITLE
Anamnesis failing to detect .poses

### ISSUE THREAD

**Issue by MaveyyWaveyy** [imchillin/Anamnesis#1243]
**The Problem**
I re-downloaded Anamnesis since concept matrix kept crashing my game, but Anamnesis can't detect the pose files. I've downloaded a couple of them and made sure they were the right files, but the software isn't detecting them as downloaded. This means I can't load the preset pose I downloaded to take pictures with. Not only this, but the Anamnesis also fails to detect my figure despite being in group pose. I've not had this problem before, so I'm unsure what the issue is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Anamnesis.exe and and click on import
2. Click on any folder saved with your poses and find the pose you want
3. After that, it won't detect the files.

**Repeatability**
How often does the bug occur:
This bug has occurred 100% of the time in my attempts to fix the problem.

**Expected behaviour**
I expected Anamnesis to work, as I have never had these problems in the past. 

**Log file**
[2022-10-28-02-41-30.txt](https://github.com/imchillin/Anamnesis/files/9886485/2022-10-28-02-41-30.txt)

**Comment by EstoyMejor** [comment]
Are you sure you are in the pose tab when you try to load the poses?
