### ISSUE TITLE
Carbuncles are broken

### ISSUE THREAD

**Issue by yshtola22** [imchillin/Anamnesis#1245]
**Describe the bug**
Carbuncles cannot be used to load .chara files and do poses, apparently.

**To Reproduce**
Steps to reproduce the behaviour:
Pin a carbuncle
Load a character file on it
Go into Gpose and try to pose it.
Nothing happens.

**Repeatability**
How often does the bug occur:
Every time, the poses work on other characters, but will not work on a carbuncle at all.

**Expected behaviour**
Well, unless something serious has changed, posing? I've used this any number times before with no problem, but suddenly it won't work.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Peebs-miqo** [comment]
Can you please upload a log file?

**Comment by yshtola22** [comment]
Not sure if I still have it. I ended up having to shut down Anam and restart it, and the problem resolved. But it popped up again slightly, requiring me to pin/unpin the Carbuncle a couple times. And it had the weird duplicating error where there were two Carbuncles interposed over one another, requiring one to be hidden or removed.
