### ISSUE TITLE
Actor gets a weird animation when putting on Invisible Hat

### ISSUE THREAD

**Issue by Blue1608** [imchillin/Anamnesis#1247]
![2022-11-09_22-19-46-562_ Neneko  x  EC  Gameplay Vivid](https://user-images.githubusercontent.com/102282172/200854361-ea2333c2-bf08-41a2-be05-1b277f4da859.png)

**Describe the bug**
When using the 'Invisible Hat' option available on Anamnesis, the Actor will have a weird animation that looks like flashing blocks. Tested it on both player character and NPCs and all of them appear to have the same issue (Attached image shows the bug happening when the Invisible Hat is equipped.) This bug does not appear when using the Invisible option on the body, only the head. It goes away when the Invisible Hat is removed or toggled off.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Character'
2. Click on 'Head'
3. Select 'Invisible' on the Search option
4. See error (Make sure Hat is visible)

**Repeatability**
How often does the bug occur:
This is the first time I've seen it. I reinstalled Anamnesis to the latest version when the bug first appeared, but it persisted even after reinstalling. I am unsure if other users are having this problem.

**Expected behaviour**
I was expecting the head to become invisible in the game. This is an option that I have tried in the past and had no issue with, it was only today (09/11/2022) where I first encountered this bug.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Peebs-miqo** [comment]
Just to check, are you running mods? If so, try disabling all mods (both TexTools and Penumbra) and trying again. Let me know how it goes

**Comment by Blue1608** [comment]
Hello I just tried again without mods and it worked just fine!

**Comment by Peebs-miqo** [comment]
That means it's some mod that you've installed has done this, rather than Anamnesis. Once you've narrowed down which one it is you may want to contact the mod author.
