### ISSUE TITLE
Special makeup not visible in gpose

### ISSUE THREAD

**Issue by akopsykokwak** [imchillin/Anamnesis#1248]
**Describe the bug**
If a special makeup is chosen (one which is not in the list : for exemple number 59) on our own character, the makeup disappears once go into /gpose. It only works ingpose if a carbuncle has the makeup.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Character'
2. Select a makeup for your own character that is not in the list : for example number 59
3. Go to /gpose

**Repeatability**
How often does the bug occur:
This is the first time I've seen this. It worked fine before. I reinstalled Anamnesis to the latest version when the bug first appeared, but it persisted even after reinstalling.

**Expected behaviour**
The makeup should appear on our character in gpose as well.

**Comment by Peebs-miqo** [comment]
This is due to the removal of the NPC face hack. Only valid player customisations will appear in Player Characters when going into GPose. 
Please use a Carbuncle or Chocobo.
