### ISSUE TITLE
Stop starting animation when inputting custom animation speed

### ISSUE THREAD

**Issue by Dajova** [imchillin/Anamnesis#1249]
**Is your feature request related to a problem? Please describe.**
As it is right now, a animation starts running the moment it has >0 speed, even if it's selected as "paused". I'm guessing this is currently "intended", as it seems like they are linked, not separated.

**Describe the solution you'd like**
I would like it to not start a animation when putting in a custom speed, so i can properly sync up multiple animations.

**Comment by EstoyMejor** [comment]
Until a Dev responds: https://youtu.be/SoKAURXU-9o
