### ISSUE TITLE
Clothing Mods Stop reflecting in Pose mode

### ISSUE THREAD

**Issue by AimmePuff** [imchillin/Anamnesis#1250]
Hi I have loaded appearance data onto a carbuncle, however the clothing mods will only reflect while in gameplay mode - the minute I go into gpose it sets the carbuncles clothes into the vanilla outfit (without mods reflected). 

**Expected behaviour**
I thought that since the game reflected the mods that it would continue to do so in gpose as well

**Comment by EstoyMejor** [comment]
That's an issue with your penumbra collections.
