### ISSUE TITLE
An error occur

### ISSUE THREAD

**Issue by 9i845gf** [imchillin/Anamnesis#1252]
![image](https://user-images.githubusercontent.com/119586876/205024628-b0ce938c-0716-425f-bfc1-cbdd9d575ac6.png)
the error was shown when I open Anamnesis after running the XIV game process, and Im using Anamnesis on China server for modding, maybe this is the reason why problem occur? someone know what's wrong with it?
(I post the link of screenshot with the error message, if it not display here, please writedown an e-mail address and I will sent you for checking)

**Comment by 9i845gf** [comment]
![image](https://user-images.githubusercontent.com/119586876/205027593-d33d1298-eeac-4f36-8d26-7f049ce09dd7.png)
and Im already ensure that the game process is running in DX11 mode

**Comment by EstoyMejor** [comment]
Chinas game version is older. You have to use an older Anamnesis version as well, which one I don't know. Go through the history and find the one that is patched for your game version.

**Comment by 9i845gf** [comment]
> 

but I wonder make sure whether Anamnesis was useful for China server? because now the game version is v6.18, maybe not too elder I thought >w<

**Comment by 9i845gf** [comment]
oh~, I have checked the tag of update patch 6.18 download and try to running, its really worked, thk Estoy for reminding~

**Comment by 9i845gf** [comment]
> 

this meaning if I wanna locked the whole appearance, I must using another tool which name Glamourer to achieve, because Anamnesis cannot lock these when refreshing? (sorry for my bad english expression >w< @EstoyMejor

**Comment by 9i845gf** [comment]
can I get a reply?

**Comment by Ani-ki** [comment]
That has already been covered in the wiki. [Why won't the changes I make to my character stick when I move zones?](https://github.com/imchillin/Anamnesis/wiki/FAQ#why-wont-the-changes-i-make-to-my-character-stick-when-i-move-zones).

So yes, you must use Glamourer. Anamnesis will not be adding this feature.
