### ISSUE TITLE
Switching to Rinascita Gear makes target Permanently Invisible

### ISSUE THREAD

**Issue by ikarugagouki** [imchillin/Anamnesis#1257]
I made a bunch of group poses through Anamnesis the past two days. Everything is fine up until a friend makes a request. I switch to Rinascita's Healing Torso and it made my character invisible. Removing or swapping gear out changes nothing. I had to use Penumbra to redraw my actor, but upon switching gear or loading sets it sets my actor to invisible again. Alpha is at 1, so it's not that.

It seems tied ONLY to the Rinascita gear. I can't test it myself because Anamnesis is screwed for me.

Reinstalling Anamnesis changes nothing for me, it's now invisible for the time being, and my hands are tied.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
Is the gear modded?

**Comment by ikarugagouki** [comment]
No. It is completely vanilla, but I've managed to find a temporary workaround now.

**Comment by StoiaCode** [comment]
Would you be so kind to explain to us _what_ workaround? In case this comes up in the future?
