### ISSUE TITLE
NPCS are not importing correctly, they are missing their unique face and hair models. 

### ISSUE THREAD

**Issue by 8bllgrl** [imchillin/Anamnesis#1258]
NPCS that load with a lack of features include:
-Aymeric
-Estinien
-Urianger
-Lyse
-Y'shtola
and possibly other NPCS. 

1.Import NPC
This happens every time on the latest version of Anamnesis.

The NPCS should load in with their unique features and should work both inside of GPose and outside of Gpose.

**Comment by StoiaCode** [comment]
Not a bug, NPC faces on PCs are only supported outside GPose with the checkmarked ticked in the settings. Inside GPose only with Penumbra redraw and some trickery. 
Use Carbuncles or Chocobos, or any other NPCs around at the time for NPCs instead.

**Comment by 8bllgrl** [comment]
I don't understand. This feature existed before, where you could turn yourself into an NPC. Are you saying there's an option to enable this now?

This is me using Anamnesis to turn myself into Aymeric with an older version of Anamnesis installed. This worked inside of GPose as well. 
![image](https://user-images.githubusercontent.com/102974548/207882331-3f8acb86-0c8e-42bd-9bce-9763d4658c93.png)

**Comment by 8bllgrl** [comment]
Adding onto this. Sorry to comment twice in a row. 

![image](https://user-images.githubusercontent.com/102974548/207882807-4099c089-d8cf-45b1-8e67-dd3dcf4810ec.png)


This is what happens when I use the latest version of anamnesis. This is still myself, by the way. Both images I've uploaded were my WOL, not a carbunkle.

**Comment by StoiaCode** [comment]
It used to yes. There was a feature called 'NPC Face Hack' but it was unsustainable, caused many bugs and consistent care from the Devs so it was decided to remove it. 

Right now you cannot enter Gpose as NPC. You can use Penumbra (with API enabled) to turn yourself into a NPC while already inside Gpose tho. 

Otherwise, Carbuncle and Choco.

**Comment by 8bllgrl** [comment]
Ah okay. Makes sense. What is Penumbra, may I have a link?
