### ISSUE TITLE
Carbuncle & Minion Crash

### ISSUE THREAD

**Issue by Yulu7766** [imchillin/Anamnesis#1259]
Hello, 
Crashes occur when I have both a carbuncle & minion out. I think I'm updated on the latest one. Not sure.
I keep getting this error message:
![FINAL FANTASY XIV 12_19_2022 5_09_43 PM](https://user-images.githubusercontent.com/103951241/208378942-8580e3a3-8e5e-4fd0-a8a8-d1c008b2bbd1.png)

**Comment by StoiaCode** [comment]
Please follow the bug report template.

**Comment by Yulu7766** [comment]
Sorry.
![2022-12-19-20-28-59 - Notepad 12_19_2022 8_32_39 PM](https://user-images.githubusercontent.com/103951241/208416934-5bae3e6b-6807-4279-80c0-b49bda9b05d1.png)

**Comment by Ani-ki** [comment]
You need to upload the entire text file.

**Comment by Yulu7766** [comment]
Ah, sorry! Did that work? 
[2022-12-19-20-28-59.txt](https://github.com/imchillin/Anamnesis/files/10258903/2022-12-19-20-28-59.txt)

**Comment by StoiaCode** [comment]
As a first troubleshooting step please move your anamnesis.exe to somewhere around C:/.
Maybe C:/Anamnesis/ or something but _not_ a OneDrive folder on your desktop. :D

**Comment by Yulu7766** [comment]
Oh no >< 
Ok. Thank you.

**Comment by Yulu7766** [comment]
I tried it again with other minions and it doesn't crash this time! Only with just one mod. So, I think it was the Anamnesis folder placement plus just one corrupted mod. Thank you for the feedback!
