### ISSUE TITLE
Taskbar button does not follow window itself.

### ISSUE THREAD

**Issue by Dajova** [imchillin/Anamnesis#1260]
**Describe the bug**
Taskbar button only displays on main monitor, even if the window is on the secondary monitor.

**To Reproduce**
Start the program.
Taskbar button refuses to use any other taskbar other than the main one.

**Repeatability**
Always.

**Expected behaviour**
The button is supposed to follow the window to whatever display it's on. I'm on a 3-monitor setup and it just refuses to use any other display. The window itself is movable just fine.

**Log file**
None.

**Comment by Yuki-Codes** [comment]
Hmm, this sounds like a bug with the windows taskbar rather than with Anamnesis itself.
What version of windows are you on?

**Comment by Dajova** [comment]
Anamnesis is the only program i have on my computer where this happens on. And i have alot of programs, including one that helps me with multi-monitor setups. And even with said program, the button doesn't go over to the other monitor (and yes, i have tested without that program as well and still the button doesnt move from the primary screen).


Anyway, i'm on this OS build:

Edition	Windows 11 Pro
Version	21H2
OS build	22000.1335
Experience	Windows Feature Experience Pack 1000.22000.1335.0


Don't know what else to tell you. It doesnt make the program unusable, but it does make it annoying, since I have to click on it at least once to even show it after it's launched (even with always-on-top enabled).

**Comment by StoiaCode** [comment]
Took me a bit to rember that there is a setting in Windows to only show the taskbar icon on whatever screen the application is on. 

Will activate that in a bit and try myself.

**Comment by Yuki-Codes** [comment]
might be related to running the app as admin? I'm not sure why windows would randomly not track window position correctly.

**Comment by Dajova** [comment]
hey sry, took a week break from the pc, so thats why i havent replied yet.

> might be related to running the app as admin? I'm not sure why windows would randomly not track window position correctly.

I didn't see a option to change that behaviour (neither in windows or options itself), so i have no way of testing that theory. Either way, even ACT acts properly moving it between monitors and that one also starts up as admin. It's still only Anamnesis not behaving correctly.
