### ISSUE TITLE
better IVCS support

### ISSUE THREAD

**Issue by Schwegg** [imchillin/Anamnesis#1265]
eg. having a toggle option within the settings to change the GUI view to include IVCS bones for easier posing.

**Comment by Ani-ki** [comment]
Please format your request correctly.

**Comment by Schwegg** [comment]
Hi! sorry about that.

**Problem:**
I use IVCS and found that digging through the large list of bones to find the specific one I'm looking for is rather annoying after the Nth time doing it. There are guides which list each bone and what each bone correlates to online, but having it separate from Anamnesis can be frustrating at times when jumping between different bones from IVCS.

**Solution:**
Adding IVCS support, eg. having a toggleable option within the settings to enable a IVCS version of the skeleton GUI would be a massive help and would make editing poses much easier along with a version for the list UI as well.

**Comment by Ani-ki** [comment]
Peebs has made additions to the Matrix view, and should be pushing the change soon, so it'll be in the next build. We can work on 3D and GUI view in the near future.

**Comment by Yuki-Codes** [comment]
you can try her version for now: https://github.com/Peebs-miqo/Anamnesis-IVCS
