### ISSUE TITLE
Cannot read character position/find best suitable skeleton for cn server

### ISSUE THREAD

**Issue by 1622429779** [imchillin/Anamnesis#1266]
**Describe the bug**
I tried opening the 9.04 version of anmnesis tool, which is validated for the 6.2 patch of ffxiv, corresponding with the newest patch of the cn server. It worked for a day, but the next day when I tried clicking on the character information to load info and change the pose in the posing mode, the tool froze and shut down. I have tried different versions of the anmesis tool and its all the same. The camera position and changing time and weather functions are still working though. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the cn version of ffxiv
2. Click on 'charactor name' icon after loading anmnesis tool

**Repeatability**
How often does the bug occur:
Bug occurred every time since yesterday

**Expected behaviour**
It would shut down by itself or freeze.

**Log file**
[2022-12-27-01-39-24.txt](https://github.com/imchillin/Anamnesis/files/10306437/2022-12-27-01-39-24.txt)

**Comment by Yuki-Codes** [comment]
I'm afraid the CN client is not supported by Anamnesis, so support here will be limited.

Your log file has a lot of 'UCEERR_RENDERTHREADFAILURE' as fatal errors though, might be graphics card related, rather than skeleton?

**Comment by AsgardXIV** [comment]
Yeh, that's the 12th gen intel crash. See https://github.com/imchillin/Anamnesis/issues/888 for more info.

**Comment by 1622429779** [comment]
Thank you so much. I'll take a look at #888 to see if this will solve the problem or not! :) This is indeed a new computer I bought, so the chances the problem is it is high.
