### ISSUE TITLE
Certain NPCs are no longer loading 

### ISSUE THREAD

**Issue by Necroneko13** [imchillin/Anamnesis#1267]
When trying to import certain NPCs, it no longer loads their data. Specifically, ones that have unique features like Venat, Ryne, Emet Selch, Hades, Hermes and Hythlodaeus. I could have sworn it worked a few weeks ago but not it's loading up completely different characters for them. Gaia strangely enough isn't affected despite having unique features.

**Comment by StoiaCode** [comment]
Intended.
NPC Face hack got removed, so no more NPC features on PCs. 
Use Carbuncles or Chocobos for that.
