### ISSUE TITLE
Chicken Head

### ISSUE THREAD

**Issue by EoinKing** [imchillin/Anamnesis#1269]
**Describe the bug**
Turning NPC or PC heads invisible under the armor settings makes you have a chicken head instead or your body shows set on fire. This is happening to several of my friends on their own pcs and accounts... but not everyone. My anmanesis IS up to date.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the helmet selection slot Head, 
2. Click on choose turn your head invisible
3. your head doesnt dissapear, instead it turns into the chicken head costume piece
do the same with the body and instead you look as if you are on fire

**Repeatability**
How often does the bug occur:
Bug occured so far every time today 1/9/23

**Expected behaviour**
well i expected the head adn torso to be invisible as the choice suggests.
![image](https://user-images.githubusercontent.com/122312209/211393370-ff6e6f3e-fbe1-43b1-ba17-aca4e9eea59d.png)

**Comment by StoiaCode** [comment]
Cant confirm on my end, are you on CN/KR servers by chance?

**Comment by EoinKing** [comment]
i am in us na servers, on primal i cant see if teh issue persists atm i
cant long in for rn

**Comment by StoiaCode** [comment]
Once you can confirm again, can you post a log file?

**Comment by EoinKing** [comment]
it seems to have fixed itself? I didnt do anything XD it just worked the
next day. but if i thappens again ill try to save a log to share!

**Comment by Yuki-Codes** [comment]
what the
