### ISSUE TITLE
Proposed solution to use Penumbra / Glamourer does not solve NPC in gpose problem. 

### ISSUE THREAD

**Issue by 8bllgrl** [imchillin/Anamnesis#1277]
Proposed solution to use Penumbra / Glamourer does not solve NPC in gpose problem. 
https://github.com/imchillin/Anamnesis/issues/1258

Refer to the link above, in this closed issue.

Using penumbra / glamourer still produces the same result. 

![image](https://user-images.githubusercontent.com/102974548/213373199-d664e321-4d46-49a3-b189-803b43328b1d.png)

I like to GPose with canon characters and now I can no longer do this since previous versions of Anamnesis no longer work. Going on the help discord for the server proved with no new results, the image is the result. Please either re-implement NPCs in gpose, or actually find a solution to my problem thanks!

**Comment by 8bllgrl** [comment]
Solution to use carbunkle works. However, I want to use multiple characters, 2-3 or more. Can't summon more than 1 carbunkle, and friends are not always available to assist.

**Comment by StoiaCode** [comment]
https://github.com/AsgardXIV/Brio
Nowadays you can just use this.

Additionally, Im not sure what Glamourer has to do with it, it was never part of the workaround. 
You only need Penumbra and Ana with the API turned on in both. I will be so free as to copy paste a tutorial the lovely quail did on the discord: 

Penumbra HTTP API Redraw for NPC Faces 
(this is working off the assumption that you've saved the appearance you want to apply already)

1) Open Anamnesis and navigate to the Settings cog
2) Tick the "Use Penumbra Redraw" box in the middle section of the screen
3) Open Penumbra and click the Settings tab
4) Click on "Advanced" and tick the "Enable HTTP API" box
5) Pin your player character in Anamnesis and pin your carbuncle if you're using it
6) Apply the appearance you want to your carbuncle, but leave your player character alone
7) Go into Gpose
8) Import the NPC face appearance you want onto your player character before you do anything else - the Penumbra HTTP API function will automatically refresh your characters and your NPC face appearance should work! 
Note 1: Do not use the manual "Redraw" buttons in Penumbra or type /penumbra redraw, as this will reset your appearance and you will lose your NPC face. You can press Import again however, and re-import your character appearance and it will then work
Note 2: you can also change equipment while in Gpose using the same method!

**Comment by 8bllgrl** [comment]
Okay, this worked, thank you so much!
I was told by someone inside of the Penumbra discord to use Glamourer, that is why i brought it up. seems like I don't need to use it at all like you said.

The last issue now is that now carbuncle & "brio" characters do not allow importing poses. Specifically, facial expressions. Is this a bug or am I missing something?

**Comment by 8bllgrl** [comment]
If this question is irrelevant to this issue, I can open a new one and close this one.

**Comment by 8bllgrl** [comment]
I have made the decision to close this issue to start a new one with a more fitting topic name, since the title of this issue has been resolved.
