### ISSUE TITLE
Video Attached❕Bug that causes actors while using the Brio plugin to not respond, with temporary fix using Carbuncle. 

### ISSUE THREAD

**Issue by 8bllgrl** [imchillin/Anamnesis#1283]
This problem/bug occurs when using [Brio](https://github.com/AsgardXIV/Brio)  through [Penumbra](https://github.com/xivdev/Penumbra).
"Brio" actors do not respond to expression changes as NPC models until a carbuncle with the same NPC model has also made the expression. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Get out your Carbuncle.
2. Change the Carbuncle to an NPC Model outside of GPose.
3. Make sure NPC Face hack and Penumbra Redraw are enabled in settings, 
4. Spawn a "Brio Actor" from your player model/WOL.
5. While In GPose, turn the additional "Brio Actor" into an NPC model.
6. This is where the issue resides -- Inside of the POSE tab in Anamnesis, the import option (even without specification using the dropdown menu,) does not apply any expression to the "Brio Actor" disguised with the NPC Model appearance.
7. The strange bug fix, as this may be related to why the issue is occuring --> If Carbuncle is in the scene, change its expression using POSE tab, import expression. This will work on the NPC model if the NPC allows for facial expressions. 
8. Now that Carbuncle has put on a facial expression, when you go back to the "Brio Actor" which is also an NPC Model (previously not responding to imported expression poses) repeating the steps to import the expression will now work for whatever reason.

Here is a video showing this more clearly:

https://user-images.githubusercontent.com/102974548/213803009-3de8c5ee-ad70-477d-a572-44bfb8468dd1.mp4

Note:
- "Brio" actors respond to expressions being changed when the Brio actor is not an NPC model.
- I'm fairly certain "Brio" actors with NPC model appearances do not respond to expressions being changed when the player's expression is changed in place of the Carbuncle. 

**Repeatability**
How often does the bug occur:
The Brio Actor with NPC Model never responds to facial expression imports, every single time.
The workaround for making a carbuncle with the same NPC model import the expression, and then importing the expression onto the Brio Actor afterwards works every single time.

**Expected behaviour**
We should not have to use a Carbuncle in order to make our clones spawned with [Brio](https://github.com/AsgardXIV/Brio) to make expressions. It's a fine workaround for now, but I have not tried this with multiple Brio actors at once. We should not have to use this workaround to this issue in the first place. Actors spawned in with the Brio plugin & penumbra should be able to respond to pose imports, without the use of a Carbuncle.

**Comment by AsgardXIV** [comment]
I think this is the issue I fixed in #1276 so it should be resolved in the next version.
Try unpinning and repinning the actor after you change the appearance, and see if that resolves it. If so, it's the above issue and will be fixed soon.

**Comment by 8bllgrl** [comment]
Okay! 🙂 Thank you @AsgardXIV . I'll keep this open for the time being just in case.

**Comment by 8bllgrl** [comment]
@AsgardXIV Yes. This was the issue. Unpinning & Re-Pinning solved the bug as well.
