### ISSUE TITLE
Anamnesis cannot read the game 

### ISSUE THREAD

**Issue by Megamustafa** [imchillin/Anamnesis#1284]
Hello, recently I've been getting into this issue whenever i start launching anamnesis, i tried restarting the game, my pc and the issue still appearing 
![image](https://user-images.githubusercontent.com/123237389/213860936-cb9e5fb9-67fb-4114-91dd-0ac53a02c806.png)
would be very appreciated if you can help me solve it :D

**Comment by Ani-ki** [comment]
Please see [**this explanation**](https://twitter.com/AsgardXIV/status/1616594940326457345?s=20).

**Comment by Megamustafa** [comment]
> Please see [**this explanation**](https://twitter.com/AsgardXIV/status/1616594940326457345?s=20).

I see now, thanks for your reply.

**Comment by Megamustafa** [comment]
I will be closing this issue now ty for your help :D
