### ISSUE TITLE
Young Models Not loading

### ISSUE THREAD

**Issue by angelsdelight** [imchillin/Anamnesis#1288]
The young models/child models do not seem to be loading. When i attempt to load one they come out as the adult model.
![Capture2](https://user-images.githubusercontent.com/74432753/215172322-3f24d30f-b6ca-459e-aba1-2c5b1faf2765.JPG)

**Comment by Ani-ki** [comment]
Please load them onto a different actor. For the time being they cannot be loaded onto your character. We suggest using a Carbuncle.
