### ISSUE TITLE
Strange Things Happens when you load/despawn Brio Npc's with Anam

### ISSUE THREAD

**Issue by NevendyND** [imchillin/Anamnesis#1291]
**Describe the bug**
I was gposing in a Map when i wanted to load a Npc in gpose on a Brio Npc.
before i did this i clicked on freeze and activated posing in anam.
I loaded the Npc on this Brio Npc and nothing changed so i wanted to despawn the Npc in Anam inside the Menu (rightclick on the name and despawn) didn't work, after i leaved the gpose i got teleported to water standing and was jumping there (i had a video from it but my pc didn't save it probably..)
I ported away to my Privat House and then this happend. (Picture)
(I sadly was not able to reproduce the same bug in the Picture but another one)

![jfstjf](https://user-images.githubusercontent.com/28860034/216766473-0448b733-6d5f-4262-ad59-345dbe2e05e6.png)

More Info's!
- I tried to reproduce the Bug but i only got stuck on the Point i was standing no porting over the Map.
- An NPC was loaded on me too and i used the Emote "/lookout".
- It doesn't occure when i don't freeze and enter posing in anam before loading the npc.
- Maybe i got ported because i moved the npc in this state with Anam (tried it but no).
- Anam crashes when you try to despawn a "not correctly changed npc" (click quit here then the bug should appear).

- You can port in this state where you can't move but you will teleport to the Point where you stood before!
The port doesn't work even after restarting the Game. (you stay on the point u were before).
- The Port worked the first time after i teleported on another Map before, but then i got this state in the Picture upove.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter Gpose with Anam, Ktisis and Brio activated.
2. Spawn an Brio Npc and change it in Anam to First Freeze and then Posing.
3. Try to load an NPC via Anam( if its not changing then it should trigger the bug)
4. If not changed try to despawn the Npc via Anam Menu(not Brio)
5. if not despawned = leave gpose and see what happens (if you log to character window your character is "mash")

**Repeatability**
3 times out of 3.

**Expected behaviour**

**Log file**

[2023-02-04-12-30-20.txt](https://github.com/imchillin/Anamnesis/files/10609249/2023-02-04-12-30-20.txt)
[2023-02-04-12-45-09.txt](https://github.com/imchillin/Anamnesis/files/10609250/2023-02-04-12-45-09.txt)
[2023-02-04-12-54-03.txt](https://github.com/imchillin/Anamnesis/files/10609251/2023-02-04-12-54-03.txt)
[2023-02-04-13-06-04.txt](https://github.com/imchillin/Anamnesis/files/10609254/2023-02-04-13-06-04.txt)
[2023-02-04-13-07-43.txt](https://github.com/imchillin/Anamnesis/files/10609255/2023-02-04-13-07-43.txt)
[2023-02-04-13-13-31.txt](https://github.com/imchillin/Anamnesis/files/10609256/2023-02-04-13-13-31.txt)
[2023-02-04-13-23-07.txt](https://github.com/imchillin/Anamnesis/files/10609257/2023-02-04-13-23-07.txt)

**Comment by Ani-ki** [comment]
Please upload a log file.

**Comment by NevendyND** [comment]
> Please upload a log file.

Log file got uploaded.

**Comment by Ani-ki** [comment]
Just one log as a text file, please. I can't extract zip files on my phone.

This is a head-scratcher because
1. Ana doesn't edit anything that would cause this in memory
2. You cannot use Ana to 'despawn'. The most you could do is equip them with the Invisible items or change their alpha to 0 so they're hidden, but they can't be *removed* from the game. That is plugin territory. Something is causing a conflict. 

Try reproducing this with JUST ANA running. Disable both Ktisis and Brio when you do this. If you can't reproduce it without those plugins, then it's a matter of figuring out which plugin is causing the conflict and addressing it with the appropriate dev.

**Comment by Ani-ki** [comment]
Really want to reiterate this, especially if this happens to anyone else. When I say 'disable' I mean go into the Plugin Directory and toggle both off, not just 'don't use them at the same time'.

**Comment by NevendyND** [comment]
First i uploaded all Files one by one.

An Update from Testing
I disabled both Plugins and disabled the Brio Connection in Anam.

> 2. You cannot use Ana to 'despawn'. The most you could do is equip them with the Invisible items or change their alpha to 0 so they're hidden, but they can't be _removed_ from the game. That is plugin territory. Something is causing a conflict.

![hdarjhdj](https://user-images.githubusercontent.com/28860034/216781664-16f299b4-d2bd-4f14-bbd8-a3889baf4d0b.PNG)
- When i use this despawn i can recreate the Bug again.
- Anam asks me if i really enabled the Brio connection in Anam and crashes.

**Comment by StoiaCode** [comment]
[2023-02-04-18-44-10.txt](https://github.com/imchillin/Anamnesis/files/10609296/2023-02-04-18-44-10.txt)
Followed steps 1 to 3 and my entire game crashed from it 🤔 Unsure, but something sure is up. Tho it does feel to me like its more  a Brio thing then an Ana thing. 
That in turn means its probably not going to be fixed for a bit, if ever. Brio dev is on a very well deserved Hiatus :)

**Comment by Ani-ki** [comment]
> Sorry for the Late Answer!
> First i uploaded all Files one by one.
> 
> An Update from Testing
> I disabled both Plugins and disabled the Brio Connection in Anam.
> 
> > 2. You cannot use Ana to 'despawn'. The most you could do is equip them with the Invisible items or change their alpha to 0 so they're hidden, but they can't be _removed_ from the game. That is plugin territory. Something is causing a conflict.
> 
> ![hdarjhdj](https://user-images.githubusercontent.com/28860034/216781664-16f299b4-d2bd-4f14-bbd8-a3889baf4d0b.PNG)
> - When i use this despawn i can recreate the Bug again.
> - Anam asks me if i really enabled the Brio connection in Anam and crashes. (So this Disable Button comes from Brio i guess..?)
> 

Well now, don't I look foolish. This is why I shouldn't be doing tech support at 3am kekw

My sincerest apologies; I'd actually forgotten Asgard added that menu item.

**Comment by NevendyND** [comment]
I found a Video what i made, after that i ported away to another spot on the map i got teleported back to this spot after the loadingscreen, (i stood there after i relogged too)
After that i ported to my House and stood under the Map on my clientside, but i think stood infront of my house serverside, because after i relogged there i stood infront of my House.

https://user-images.githubusercontent.com/28860034/218492412-f5520bc5-9be0-4a8d-beb2-118d6ad59e01.mp4
