### ISSUE TITLE
Compressed Folders Error

### ISSUE THREAD

**Issue by DanSong511** [imchillin/Anamnesis#1294]
When I go to load up Anamesis it says the following 
"Compressed (zipped) Folders Error
Windows cannot complete the extraction.
The destination file could not be created." 
I had been using Anamesis just two hours prior to sending this, and reloading it I was hit with this.

**Comment by StoiaCode** [comment]
It sounds like you never extracted the anamnesis.exe. Try to move the contents of the folder that contain Anamnesis somewhere else, best case somewhere like C:/Anamnesis
