### ISSUE TITLE
Ryne/Minfilia of the first cannot be imported

### ISSUE THREAD

**Issue by noctiilio** [imchillin/Anamnesis#1299]
**Describe the bug**
Whenever importing any version of Ryne, both as minfilia and as herself, it defaults to an adult midlander hyur female with short hair wearing her outfit, as if it was forcing anamnesis to boot the character creation feature when loading her unique model.
It displays the error message "Player Characters are not NPC-Face Compatible
Other characters with unique models like Gaia do not have this issue, it's only Ryne.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Select tab
3. Import NPC
4. Select Ryne or shadowbringers Minfilia

**Repeatability**
How often does the bug occur:
Every attempt

**Expected behaviour**

**Log file**
https://imgur.com/a/yxhD5To

**Comment by StoiaCode** [comment]
NPCs on your PC are not supported. As the error already says. Please use Carbuncle or Brio actors.
