### ISSUE TITLE
Brio/HTTP Api/redraw Won't work

### ISSUE THREAD

**Issue by MisaMiko** [imchillin/Anamnesis#1300]
**Brio integration** wont simply work, I activate the check box inside Anamnesis, I did also activate **HTTP API** From **Penumbra**.
I also unistall Anamnesis from Every folder but in the end nothing work i also repair FF XIV but it didn't help aswel, It worked time ago, But now it wont.

I also did recive an error **2728128110048** **When i actually try to change Any item**.
I allegate the log file.

[2023-03-15-04-11-16.txt](https://github.com/imchillin/Anamnesis/files/10975720/2023-03-15-04-11-16.txt)

**I Do also recive this error while i open Anamnesis**
![image](https://user-images.githubusercontent.com/127915781/225198790-91506ab4-b229-4633-aab9-911b83d2e36a.png)

Despite Everyerror, Anamnesis work normally as it should, But Can't use Brio.

**Comment by Yuki-Codes** [comment]
Hi, have you enabled the HTTP API in **brio**? Penumbra and Brio are two separate plugins that both have http API options for Anamnesis,

**Comment by MisaMiko** [comment]
> Hi, have you enabled the HTTP API in **brio**? Penumbra and Brio are two separate plugins that both have http API options for Anamnesis,

Hi, I didn't know it was an actual plugin but not long time ago i was able to use the option in Gpose.  
I did download Brio right now and seems it work Thank you a lot! 
But is actually suppose to redraw the position aswel? 

Beside it, do the **Signature error** i do get when i open Anamnesis is normal?

**Comment by Yuki-Codes** [comment]
Both Brio and Penumbra can redraw actors. But you don't need them both, and you can disable either in the Anamensis settings.

The signature error is a problem we are aware of, and a fix for that is coming in the next version. 👍

**Comment by MisaMiko** [comment]
> Both Brio and Penumbra can redraw actors. But you don't need them both, and you can disable either in the Anamnesis settings.
> 
> The signature error is a problem we are aware of, and a fix for that is coming in the next version. 👍

Thank you very much, My problem is solve then!

**Comment by songstress-aya** [comment]
I am having the same issue since brio updated. And no enabling it in brio did not work.
