### ISSUE TITLE
"Penumbra HTTP API Error" 

### ISSUE THREAD

**Issue by Telliexyz** [imchillin/Anamnesis#1305]
**Describe the bug**
Whenever I try to change the gear for my character, an error saying "Actor cannot be refreshed" followed by "Penumbra HTTP API Error". I do not have Penumbra installed and never have, and as far as I know you don't need it. It won't change the clothes at all unless I switch into GPose directly afterwards, but if I change anything, I have to switch out of GPose and back in.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'character'
2. Click on any gear slot
3. Change item in gear slot

**Repeatability**
How often does the bug occur:
Every time I try to change gear or appearance of character.

**Expected behaviour**
To not get an error message, and for the clothes to change without needing to open up GPose.

**Log file**
[2023-04-08-13-47-42.txt](https://github.com/imchillin/Anamnesis/files/11184383/2023-04-08-13-47-42.txt)

![Screenshot 2023-04-08 133711](https://user-images.githubusercontent.com/130251670/230745606-a85f431b-62c6-408e-b8f5-996bd00e97f0.png)

**Comment by StoiaCode** [comment]
Go into the settings and disable the Penumbra HTTPI API.

**Comment by Raulke** [comment]
I get this too, but enabling or disabling the setting in Penumbra doesn't fix it.  I also have another problem after the most recent update, but I don't know if I should discuss that there or somewhere else.
