### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Detlimu** [imchillin/Anamnesis#1307]
I’m a Chinese gamer，the version of the ffxiv is 6.28 now in China，I will try my best to describe this error
it can’t open probably a week
i uninstalled and downloaded a new Anamnesis for 6.28 patch（Release v2022-12-13），it also Critical Error
what should i do
![C_YVK}U1BPJOPI51(~SF_X3](https://user-images.githubusercontent.com/132254163/235423276-5f554be8-332b-49ce-b93e-f01049ba9c9c.png)

if this picture is error occured，please read this：
Critical Error

The tool was unable to recover from this error, and must close.
Multiple Anamnesis processes found.Please close all other instances. 
[Exception] Multiple Anamnesis processes found.Please close all other instances.
at Anamnesis.App.CheckForProcesse
at Anamnesis.App.Start

thanks for your help

**Comment by StoiaCode** [comment]
Check taskmanager for Anamnesis and close all instances. 
Then restart your PC.
