### ISSUE TITLE
Unmoveable joints and limbs

### ISSUE THREAD

**Issue by Kenorath** [imchillin/Anamnesis#1308]
So since a few days ago I started up anamnesis to do some gposing and when I activated posing on my character it seemed fine but when I clicked to move my arm/shoulder/hand/leg you name it, the XYZ to move that certain part of the body was greyed out and unineractable.

It happens every time I start anamnesis, I have tried re-installing countless times.

![2f9d652a4ee8e198c0d9dff315af0032](https://github.com/imchillin/Anamnesis/assets/133543694/2a82d11e-808a-4ff3-93b3-3d420c600da8)

**Comment by Ani-ki** [comment]
Anamnesis has not received any updates since the last patch drop, so nothing has changed in the tool itself.

Just to clarify, are you trying to *rotate* or *move* the bones? The standard posing method is rotation, and doesn't require the greyed-out sliders under 'Position'.

**Comment by Kenorath** [comment]
I can use the "rotation ball" to adjust limbs, bones etc, though I prefered using the sliders but they don't work for me anymore and I'm just wondering why, using the ball still works fine for some reason.

**Comment by StoiaCode** [comment]
The 'position' sliders only work once you check []P. And that's something you only do if you have a reason to.

The other sliders, the ones below the ball (gizmo) should still work just the same.

**Comment by Kenorath** [comment]
> The 'position' sliders only work once you check []P. And that's something you only do if you have a reason to.
> 
> The other sliders, the ones below the ball (gizmo) should still work just the same.

Could you tell me where I go to check "[]P"?

**Comment by Ani-ki** [comment]
> > The 'position' sliders only work once you check []P. And that's something you only do if you have a reason to.
> > 
> > The other sliders, the ones below the ball (gizmo) should still work just the same.
> 
> Could you tell me where I go to check "[]P"?

In the screenshot you provided, it'll be somewhere above where the ears are. There are three checkboxes, R, P, and S.

**Comment by Kenorath** [comment]
> 



> > > The 'position' sliders only work once you check []P. And that's something you only do if you have a reason to.
> > > The other sliders, the ones below the ball (gizmo) should still work just the same.
> > 
> > 
> > Could you tell me where I go to check "[]P"?
> 
> In the screenshot you provided, it'll be somewhere above where the ears are. There are three checkboxes, R, P, and S.

omggg, thank you!, it fixed it!
