### ISSUE TITLE
Animations with Penumbra/Anamnesis

### ISSUE THREAD

**Issue by EpheriaA** [imchillin/Anamnesis#1309]
**Describe the bug**
I have noticed this last week, and it just randomly started happening seemingly. When I go into Gpose with an animation on Penumbra, and I enable Freeze Positions. It will start lifting my character's Height or the Y Axis. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable an Animation in Penumbra, then use the Emote for it.
2. Go into Gpose, and then open Anamnesis.
3. With your character sheet, enable Freeze Positions
4. Watch your character suddenly gaining height/y axis.

**Repeatability**
How often does the bug occur:
Every single time I've tried to do the Animations and Freeze Position

**Expected behaviour**
I've used Animations and Freeze Position in Anamensis before, it has never gained height/y axis. I could adjust the characters as I needed without flaw.

**Log file**
There is no log file, no error code just random gain in height/y axis with animations.

**Comment by StoiaCode** [comment]
Disable XLHeels. 
Anamnesis hasnt received any updated lately so very unlikely its this.

**Comment by EpheriaA** [comment]
Appreciate it I will try that!

**Comment by EpheriaA** [comment]
Yup that was the entire issue, thank you!
