### ISSUE TITLE
Imported Character Appearances Have Jumbled Comments?

### ISSUE THREAD

**Issue by SomebodyAnxious** [imchillin/Anamnesis#1314]
Okay, I'm going to try my best to explain what I mean.

Whenever I attempt to import a character appearance (the appearance data used in Character Creation, NOT Anamnesis), I would find that the comments I leave on the files become gibberish/some sort of combination of every previous comment I wrote.

This happens whenever I overwrite the file with a new comment. It doesn't erase the old one and instead, like previously mentioned, will combine every old comment into one unreadable phrase.

It's been happening for as long as I can remember and I wanted to see if I'm the only one dealing with it.

**Comment by Ani-ki** [comment]
This sounds very strange, and I'm not really able to understand what's happening. Are you at all able to get a recording of it?

**Comment by SomebodyAnxious** [comment]
The middle file is the one with the gibberish bug I'm trying to explain. I've tried deleting the file in the program, then saving the appearance again in Character Creation, but the comment is unable to change.

![image](https://github.com/imchillin/Anamnesis/assets/101953244/63e2188c-d658-4672-934b-247fd88a1c97)

**Comment by Ani-ki** [comment]
Huh! Leave this one with me, I'll be able to go over it proper when I'm next at my PC.
