### ISSUE TITLE
Character data export/imprort Errors

### ISSUE THREAD

**Issue by Khenbish** [imchillin/Anamnesis#1315]
Ever since the new update earlier, i've been getting errors whenever i try to export or import new .chara files, even though the old ones still work and while .chara files are being saved, they do not work.

[2023-06-19-14-05-49.txt](https://github.com/imchillin/Anamnesis/files/11787487/2023-06-19-14-05-49.txt)

**Comment by StoiaCode** [comment]
Get the new-new version

**Comment by Khenbish** [comment]
I kept getting a "no updates found" message, so i redownloaded the whole thing. Everything seems to work ok now
