### ISSUE TITLE
Icon failing to load

### ISSUE THREAD

**Issue by Foxophonist** [imchillin/Anamnesis#1316]
Opening Anamnesis I get and error  stating  failed to load icon for shortcuts/AnamnesisBultin.png System.OverflowException: The image data generated an overflow during processing. Mini mode no longer works and Anamnesis is only closeable through through task manger
[2023-06-25-23-09-15.txt](https://github.com/imchillin/Anamnesis/files/11862772/2023-06-25-23-09-15.txt)

**Comment by Ani-ki** [comment]
This may be an issue with your Windows colour management settings. Chances are you've installed something that's messed around with them needlessly, so it should just be a matter of swapping them back.

This can be done by opening the Start menu, typing `color management` (or colour management depending on your language settings) and hitting Enter. From there, click on the Advanced tab, and set `Device profile` to `System default (sRGB IEC61966-2.1)`, then hit Close.

Sorry for the delay in the response here! It's been a little hectic. Let me know how this goes.

**Comment by Foxophonist** [comment]
This this fixed it thank you and don't sweat it its understandable.
