### ISSUE TITLE
windows Error

### ISSUE THREAD

**Issue by Lirimgrimsbane** [imchillin/Anamnesis#1317]
whenever I try to load anamnesis since the new patch it keeps coming up with an error saying "only Windows 10 or newer is supported" even though I have windows 11 pro"

i simply open anamnesis and the error comes up

this error occurs every time I try to open and load anamnesis

all i can do is show a snippet of the error that comes up:
![image](https://github.com/imchillin/Anamnesis/assets/138314487/2db19ac9-6998-4414-8151-98540e159383)
(i dont know if that worked, please let me know if it didnt)

**Comment by Ani-ki** [comment]
Hi there, can you right click on the exe and go into Properties, and check if Compatibility mode is on or off?

**Comment by Lirimgrimsbane** [comment]
Hi, compatibility mode is on but it only lets me have it for windows 8,
this wasn’t an issue before the patch

**Comment by Ani-ki** [comment]
Does it work when you turn Compatibility Mode off?

**Comment by Lirimgrimsbane** [comment]
no it doesnt, the same error keeps occurring
