### ISSUE TITLE
Gizmo Disappeared 

### ISSUE THREAD

**Issue by Dragonlicious** [imchillin/Anamnesis#1324]
When trying to use gpose with Anamnesis, I cannot see the usual gizmo for manipulating the bones. It just flat out vanished on me and I have tried multiple times to get it back. I have redownloaded Anamnesis after deleting everything involving it 5 separate times in the hope that it would return. I have ran the program as administrator and consulted with a friend who also uses Anamnesis. My friend does not have the gizmo missing but I do.
![image](https://github.com/imchillin/Anamnesis/assets/142318114/6522a998-8a1a-4857-ac82-b7223b9ef7f8)
I'm including a picture of what my interface with Anamnesis looks like. As you can see, the tool used for manipulating the bones is completely gone. 
I recently had changed computers and I was wondering if this is an issue because of that, since my new computer is on Windows 11. But Anamnesis does have Windows 11 support, according to the download page. 

Any help would be really welcomed and appreciated.

**Comment by StoiaCode** [comment]
If your gizmo/rotation ball thingy is gone try this: 

https://www.ghacks.net/2021/10/29/how-to-assign-graphics-performance-preferences-to-windows-11-programs/

https://www.top-password.com/blog/enable-high-performance-gpu-for-windows-10-apps-or-games/

**Comment by Dragonlicious** [comment]
> If your gizmo/rotation ball thingy is gone try this:
> 
> https://www.ghacks.net/2021/10/29/how-to-assign-graphics-performance-preferences-to-windows-11-programs/
> 
> https://www.top-password.com/blog/enable-high-performance-gpu-for-windows-10-apps-or-games/

IT WORKED!! thank you so much!
