### ISSUE TITLE
Anamnesis modified base game

### ISSUE THREAD

**Issue by Kaunoet** [imchillin/Anamnesis#1328]
My character was not reverting to his vanilla self when I was choosing "Reset". I logged on vanilla game without mods or Anamnesis open and his face was still modified in a mix between his original and the character I had been posing as. A friend logged in on vanilla launcher too and saw the character modified, so it's not just on my end. 

It is the first time this bug occurs, but it is worrying that it could modify my base game. 
![kau with seph face](https://github.com/imchillin/Anamnesis/assets/145921372/97df05bc-c130-4881-92df-0e30cffd75e6)

**Comment by StoiaCode** [comment]
The pic is useless since we cant tell what isnt supposed to be there.

if you used the Barber while having Ana open with the changed aspects, this might happen. In any other case, it cant.
