### ISSUE TITLE
Carbuncle Reverting back after importing

### ISSUE THREAD

**Issue by Mathia-Famfrit** [imchillin/Anamnesis#1329]
**Describe the bug**
Every time I import a character onto my Carbuncle, one of two things happen.
1. Character shows completely naked
2. Character is in the wrong clothing

After I import, if I change any item on the character they transform back into the carbuncle. Trying to re-import the character no longer works until I un summon the carbuncle and resummon. Then #1 and #2 happen again and eventually it transforms back into a carbuncle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Import' or 'Import NPC'
2. Click on 'Any saved character or NPC'
3. Import onto Carbuncle

**Repeatability**
How often does the bug occur:
100% of the time

**Expected behaviour**
Load any character selected onto the Carbuncle without it reverting back to the Carbuncle State

I would include a log file but I don't know where to get them.

I've tried reinstalling Anamnesis as well as removing all mods from XIV and this bug still occurs even then.

If I use any other type of NPC, everything is fine. It's just the carbuncle that doesn't work for some reason any more.

**Comment by StoiaCode** [comment]
Disable Glamourer when using Carbuncle in gpose.

**Comment by Mathia-Famfrit** [comment]
Holy crap, I didn't think it was Dalamud doing it. Okay then thanks! Lol. Works perfect now xD
