### ISSUE TITLE
Demi-human use malfunctioning

### ISSUE THREAD

**Issue by Kisa-Allmark** [imchillin/Anamnesis#1331]
**Describe the bug**
Just recently, likely involving the most recent update, I attempted starting a pose like normal using my Emerald Carbuncle as a demi-human. When I imported the .chara file the usual way, it simply reverted back to carbuncle shape immediately. I tried this with SCH Faerie and my Chocobo for the sake of posterity, and the result was the same, with the obvious outlier being the hovering, improperly sized Faerie. I did read the recent issues suggesting disabling Glamourer, and while the clothed body worked now, there was a distinct absence of hands/feet where the player character does not have this issue. I have mostly ruled out Bibo+ or Penumbra being the issue, so I open this report in hopes someone can advise a fix that I have yet to try.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pin demi-human actor
2. Go to character details tab
3. Click Import
4. Select .chara file

**Repeatability**
How often does the bug occur: 
Bug occured constantly in 8 attempts with Glamourer active and 5 with Glamourer disabled.

**Expected behaviour**
Essentially, the selfsame way this function worked before; to copy another character/model's appearance onto another non-player entity.

**Comment by StoiaCode** [comment]
You are using Glamourer. 

Glamourer and anamnesis are no longer compatible, use either one or use Brio actors instead of carbuncle.

**Comment by Kisa-Allmark** [comment]
Ahhh okay. I did not know they were strictly non-compatible anymore. As long as Brio still works in Anam I should have minimal issues :) I will attempt next time I'm online. Thank you!
