### ISSUE TITLE
使用不了

### ISSUE THREAD

**Issue by A1ixe** [imchillin/Anamnesis#1332]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Repeatability**
How often does the bug occur:
[2023-10-09-11-11-58.txt](https://github.com/imchillin/Anamnesis/files/12842471/2023-10-09-11-11-58.txt)

Bug occured .../... attempts

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by StoiaCode** [comment]
Your most likely on CN client. You need to use a specific older version of Anamnesis. Which one we don't know, try it out.
