### ISSUE TITLE
Ericthonios not appearing in NPC import list?

### ISSUE THREAD

**Issue by FeroLouis** [imchillin/Anamnesis#1333]
Ericthonios is not appearing in the list for npc imports anymore, was he removed or is it a glitch?

I try searching him up in the NPC import list he's just not there. he's my favorite character and I was just wondering why this is happening :<

**Comment by StoiaCode** [comment]
Ancient but: Not all NPCs are in the list, some need to be manually selected via ID. Found NPCs can be searched for on our Discord.
