### ISSUE TITLE
Bones aren't showing correctly

### ISSUE THREAD

**Issue by HummingBird95** [imchillin/Anamnesis#1336]
Whenever i open anamnesis up the bones doesn't recognize when i change race. I opened it up as an Au'Ra and got the tail bones as normal, but when i change to Viera or Miqo'te it doesn't give me the bones for ears anymore. It only recognises that i changed race if i restart the program. And sometimes it is even stuck on the previous appearance i loaded without changing me in the game.

The issue started yesterday and is still going on no matter what i do in both anamnesis and glamourer. It only gives me the correct bones after i restart anamnesis, but sometimes it won't work either.

[Logs.zip](https://github.com/imchillin/Anamnesis/files/13053746/Logs.zip)

**Comment by StoiaCode** [comment]
Glamourer and Anamnesis are not compatible. 
Disable glamourer when using Ana.

**Comment by HummingBird95** [comment]
Okay, thank you for the answer.
