### ISSUE TITLE
Can't replace carbuncle for a saved appearance file

### ISSUE THREAD

**Issue by zeus0z** [imchillin/Anamnesis#1337]
It's an issue in my GF's game. Whenever she tries to replace her carbuncle with an actor's saved file (like the file of my character as saved file). She can replace her own character normally, the issue is with the carbuncle only. She was doing this with no problems until a couple weeks ago.

Steps to reproduce the behaviour:
1.  She adds her carbuncle as an actor.
2. She procceeds to import a saved appearance for the carbuncle.
3. It works the first time, but when she tries to change the hair for example, or any other part of the body, or even change to a different appearance file, the software crashes.

How often does the bug occur:
Every time she tries to use Anamnesis to replace the model or change its characteristics like hair.

**Expected behaviour**
She wants to replace the carbuncle model with my character's model, that's saved on a file

**Log file**
Attached
[2023-10-21-20-16-19.txt](https://github.com/imchillin/Anamnesis/files/13062019/2023-10-21-20-16-19.txt)

**Comment by StoiaCode** [comment]
Disable glamourer

**Comment by zeus0z** [comment]
It solved the problem, thanks !
