### ISSUE TITLE
Unable to use Anamnesis! Failed to update item

### ISSUE THREAD

**Issue by AvisXxx** [imchillin/Anamnesis#1340]
**Describe the bug**

Hi there, I am a CN server user and normally it works great, but today I updated it because it warned me about that. After the update when I clicked on my character in Anamnesis, It stopped working and showed me that There had been an error
"Failed to update item:
Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet ClassJobCategory column hash mismatch! expected hash: 65bbdb12, actual hash: 7caef8ce!"

When I closed this pop-up window, the rest of the interface became grey and unable to interact with. 

I tried to uninstall and download it again, but it has been the same problem

**To Reproduce**
Steps to reproduce the behaviour:
1. opened Anamnesis
2. Click on my character

**Repeatability**
How often does the bug occur:
Every time even after the re-install

**Expected behaviour**
any way to fix this?

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[2023-10-29-23-36-17.txt](https://github.com/imchillin/Anamnesis/files/13199453/2023-10-29-23-36-17.txt)

**Comment by dynamicfire** [comment]
Since the current version in China is 6.4, using the latest version of Anamnesis may cause issues. You can opt for an older version of Anamnesis. It's available for download  [here](https://github.com/imchillin/Anamnesis/releases/tag/v2023-08-08).
