### ISSUE TITLE
It won't open, says I must have .NET Desktop Runtime to run this application, when it is already installed.

### ISSUE THREAD

**Issue by occupywalrus13** [imchillin/Anamnesis#1341]
**Describe the bug**
I ran a system restore to fix an issue I had with ReShade and now I got this error.

**To Reproduce**
1. After updating ReShade it looked horrible
2. I did a system restore to fix it
3. Now when I try to open Anamnesis I got the error
4. Full Error details: 

Architecture: x64
App host version: 6.0.20

Would you like to download it now?

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

5. It has a Yes or No button.
6. I clicked "Yes" 
7. It downloaded and installed
8. Got the same error

**Repeatability**
Always.  I can't open Anamnesis now

**Expected behaviour**
I hope to find a solution or any way to get back to it working

**Log file**

**Comment by StoiaCode** [comment]
that popup links you to the wrong version. Thank MS for that. 

Get the .NET DESKTOP runtime in version 7.0 while you are at that.

**Comment by occupywalrus13** [comment]
Thank you @StoiaCode  I somehow managed to fix it as soon as I posted this.....
