### ISSUE TITLE
Error Refreshing actor. Brio Http API error.

### ISSUE THREAD

**Issue by bunboygenius** [imchillin/Anamnesis#1345]
Whenever I try to change gear on an actor, I get this error message.

![Screenshot 2024-01-16 095413](https://github.com/imchillin/Anamnesis/assets/156819613/2309a9b8-d3ae-4c3e-af9f-b28cf18c1f95)

Here are my settings where Brio Integration is turned on. 

![Screenshot 2024-01-16 095523](https://github.com/imchillin/Anamnesis/assets/156819613/c031c800-4f30-473a-82f9-5441c0464c4f)
 
However, this error will persist regardless of whether or not Brio is installed, as I have tried completely removing it to see if that was the issue. Currently, Dalamud is down and the error still occurs as it did before. 

Log is below

[2024-01-16-09-44-47.txt](https://github.com/imchillin/Anamnesis/files/13951940/2024-01-16-09-44-47.txt)

**Comment by juhuanomeili** [comment]
Has the problem been solved?

**Comment by StoiaCode** [comment]
It was never an issue. Disable Brio Integration when Brio isnt available, if Brio is available make sure its enabled in Brio settings.
