### ISSUE TITLE
Rotation wheel issue 

### ISSUE THREAD

**Issue by Renorebun** [imchillin/Anamnesis#1348]
As I open anamesis and go to the posing tab, I freeze the character select a bone and the rotation wheel doesn't appear.
![image_2024-02-21_161027820](https://github.com/imchillin/Anamnesis/assets/160788821/51354f07-b381-44cd-abf6-c6fbecd1fc72)

**Comment by teutelquessir** [comment]
Same issue.

![image](https://github.com/imchillin/Anamnesis/assets/29414917/80ee4fa5-4b03-4fd0-b727-39f12e7fdc9d)

**Comment by StoiaCode** [comment]
If your gizmo/rotation ball thingy is gone try this: 

https://www.ghacks.net/2021/10/29/how-to-assign-graphics-performance-preferences-to-windows-11-programs/

https://www.top-password.com/blog/enable-high-performance-gpu-for-windows-10-apps-or-games/

**Comment by Renorebun** [comment]
It worked thanks so much!
