### ISSUE TITLE
Anamnesis causes a crash shortly after I begin posing.

### ISSUE THREAD

**Issue by Goatsarecute** [imchillin/Anamnesis#1353]
**Describe the bug**
A few days ago, Anamnesis started to cause a crash when I pose, I could get away with quick poses, but now it crashes the moment I touch any vector.

**To Reproduce**
Steps to reproduce the behaviour:
1. I Spawn models using Brio.
2. I prepare them for the pose using Glamourer.
3. I use Brio to add minions.
4. I activate posing on Anamnesis.
5. I try to rotate the models to match the intended pause.
6. This results in a crash.

**Repeatability**
How often does the bug occur:
It started tame a few days before this post, crashing once every few hours.
This morning, I failed to finish the pose requested by
 a friend repeatedly, every time I tried to start posing.

**Expected behaviour**
Ideally, the program would continue to function without crashing the game. I am not savvy enough to make an accurate expectation.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[2024-04-29-14-52-40.txt](https://github.com/imchillin/Anamnesis/files/15148408/2024-04-29-14-52-40.txt)

**Comment by StoiaCode** [comment]
Unlikely a Ana crash, more likely to be related to Brio. Old as well, so not sure this even happens still.
