### ISSUE TITLE
Having trouble with NPC posing, Content Warning, but please help.

### ISSUE THREAD

**Issue by Delovely15** [imchillin/Anamnesis#1354]
**Describe the bug**
So I've been trying to gpose with some NPCs (Male Roe) and have been having trouble getting the mods to apply to them. This didn't used to be the case, and I' rather uncertain how it came to be. I used to pose things just fine, but suddenly can't, without changing any options. It may be an update I missed? If so, can I reenable the ability to put mods on NPCs? It specifically gives trouble with more unique NPCs- like Gosetsu, for example.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Penumbra, enable any hrbody3 mod, then import NPC on a Carbuncle or self.
2. Attempt to change the NPCs clothes via Anamnesis, then Refresh/Redraw instanced characters.
3. See error

**Repeatability**
How often does the bug occur:
Bug occurred 20/20 attempts

**Expected behaviour**
What usually occurs is the body model works perfectly, so even NPCs will wear the appropriate clothes with no invisible torso, feet, hands, etc. Animations also do not affect the clothes in any way.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
First file is current problem, second is what normally happens. The second photo is from jan of this year, 1st is from May 1st. CW for 2nd photo: Fat/chubby. Please be warned, I know not everyone can handle that, and I apologize in advance, I can't find any other pictures to demonstrate. 
![ffxiv_dx11 2024-05-01 21-04-51](https://github.com/imchillin/Anamnesis/assets/168697738/95213d8b-31cc-4de1-9aea-be49c0c71f26)
![ffxiv_dx11 2024-01-20 22-31-33](https://github.com/imchillin/Anamnesis/assets/168697738/39fb317b-d728-4515-9c2d-6b007e7eb9d3)

**Comment by StoiaCode** [comment]
This isnt even about Ana, this is a mod bug on your end. Nothing ana can do to fix your mods.
