### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by MiserlyYee** [imchillin/Anamnesis#1356]
**Describe the bug**
Everytime I load up Anamnesis, I am experiencing a Critical Error called

GameDataService Error: Failed to initiate Lumina (Are your game files up to date)

Please be advised, I have already started over with Textools and did the backups. I have Anamnesis up to date and I launch FF14 through its own client.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Anamnesis while 14 is running
2. Click on Anamnesis
3. App says it is not up to date with current game, click ok.

**Repeatability**
How often does the bug occur:
Bug occurred 10/10 times.

**Expected behaviour**
To not suffer a critical error.

**Log file**

![image](https://github.com/imchillin/Anamnesis/assets/171471629/b2ac482d-b002-4823-939c-99ee73c6dadc)

![gameerror](https://github.com/imchillin/Anamnesis/assets/171471629/3d8aa29a-dff1-430d-a8fd-446f4a8a17fa)

**Comment by woowind** [comment]
As of right now Ana doesn't work with DawnTrail. They have been working on it.
