### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by syaellew** [imchillin/Anamnesis#1358]
![Screenshot (3962)](https://github.com/imchillin/Anamnesis/assets/174495117/7b0a6f61-d816-4980-a9dd-4ef29f74e652)

**Comment by Alisaie22** [comment]
well i have this to ,game is up to date and i CANT update anam so i hope it be fixed soon, if its updated in patch 7.0 please explain it to me on how to update it =3

**Comment by StoiaCode** [comment]
THE TOOL IS NOT UPDATED. 
And it won't be updated faster if you keep asking. The next person that asks gets yeeted to the moon.

**Comment by Alisaie22** [comment]
Bruh rude, i know its not updated i were just curious and if i just missed something on pc to know if i could fix it thats why i said -IF its updated- but ty for the -kind-  replay
