### ISSUE TITLE
Face bug, specifically eyes

### ISSUE THREAD

**Issue by JohnDoe166** [imchillin/Anamnesis#1365]
Ever since the DT compat update, whenever I load a pose, ones I have used for ages as well as brand new ones I checked are compatible with Dawntrail, the face of a character, specifically around the eyes, break/warp the face. If I load any expression through the default gpose menu included in game and use Ana as normal but just load the body pose, the face keeps the expression with no issues, however, if I use the load expression through anam and load the exact same expression, the face or rather eyes, break/warp. I have tested this on several races and Highlanders, Elezen, Miqto' Viera, and Hroths all have this issue yet middlanders and Rogs do not for whatever weird reason. If I load any pose on midlanders or rogs, the poses work as intended and their faces do not break at all, just the others mentioned. I have tried everything, I have position mode off and I have deleted and reinstalled Anamnesis several times thinking a clean install may fix the issue, but the issue persists.

**Comment by StoiaCode** [comment]
You need to use Full Transform when loading face expressions.
