### ISSUE TITLE
Unable to manipulate lips

### ISSUE THREAD

**Issue by Oni-Senpai** [imchillin/Anamnesis#1367]
When doing a gpose, I'm unable to manipulate the lips or jaw. I wasn't sure if it was a bug or just not added yet. 

you can reproduce it by just enabling pose mode and freezing everything FFXIV
Happens every time. The lips are grayed out and the jaw is unresponsive

I'm sorry if it's something I missed and turns out this was mentioned but I looked around a bit and couldn't see anything on manipulating lips and lower facial muscles.

**Comment by StoiaCode** [comment]
2D View is not updated, use Matrix view or 3D view until #1369
