### ISSUE TITLE
Hair "j_ex_h0120_ke_f" not responding to any settings change

### ISSUE THREAD

**Issue by geshp** [imchillin/Anamnesis#1371]
On a Miqo'te female, hair style 120, the front bangs haven't been responsive since the Dawntrail patch.  The bone is listed as "j_ex_h0120_ke_f" and won't respond to any requests to rotate, reposition or scale.  May have possibly been renamed since the patch?

**Comment by StoiaCode** [comment]
Not an Ana issue, that hair no longer is weighted to those bones and can no longer be posed.
