### ISSUE TITLE
eyes off center - not able to correct

### ISSUE THREAD

**Issue by IllieG2024** [imchillin/Anamnesis#1372]
When loading a DT compatible pose, the eyes are not in line and are rolled back and the upper cheeks are warping and unable to manually correct

**Repeatability**
How often does the bug occur: with each pre load pose

**Comment by StoiaCode** [comment]
You need to load Expressions with Full Transform

**Comment by IllieG2024** [comment]
I'm sorta basic haha. Where is that setting at please. Dmi don't see it any place

**Comment by StoiaCode** [comment]
There is a dropdown next to the import button. The process of using Expressions is currently very convoluted, id suggest you just use the in game included expression emotes before posing and go from there.
