### ISSUE TITLE
Not finding my Pose folder when in Anamnesis

### ISSUE THREAD

**Issue by Shpadoinkleday** [imchillin/Anamnesis#1377]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue. 

I have updated anamnesis and when I log in I'm unable to see my pose folder when trying to export/import,  When I do see the folder none of the .pose are visible but there visible outside of Anamnesis.  

**To Reproduce**
Steps to reproduce the behaviour:  

**Repeatability**
How often does the bug occur:
Bug occured .../... attempts

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

[2024-08-18-18-14-10.txt](https://github.com/user-attachments/files/16654150/2024-08-18-18-14-10.txt)

**Comment by StoiaCode** [comment]
Youre in the wrong tab. Make sure youre in the Posing tab.

**Comment by Shpadoinkleday** [comment]
I moved all of my poses into just the pose folder and I'm still not able to see the .pose files is there something else I'm doing incorrectly?

[2024-08-19-17-55-15.txt](https://github.com/user-attachments/files/16667439/2024-08-19-17-55-15.txt)

**Comment by CaptainSticky** [comment]
Just looking at your log file compared to mine... something that stands out to me immediately is this line here: (followed by the one after it)
`2024-08-19 17:55:15.427 -07:00 [INF] Check Working Directory: "C:\WINDOWS\system32" for executable: Anamnesis`

That's not where Anamnesis should be. :O And, the following line talks about it being in your downloads folder. I would not recommend putting it there. Try moving it somewhere else. In the past, some have recommended under C:\Anamnesis or under your Documents folder. 

Next, when you launch Anamnesis, make sure you click on the gear on the top left and set your 3 folders for Poses, Charas, and Cams. You can do this with the settings in the middle column under "Directories".
