### ISSUE TITLE
[Suggestion] Right click menu on item slots

### ISSUE THREAD

**Issue by alexpado** [imchillin/Anamnesis#1380]
Hi,
I love using Anamnesis to plan my glamour plates and take screenshot. When it comes to planning my glamour plates, it is always a bit frustrating to search for each item manually on lodestone to see where I can get it.

It would be cool to be able to right click and copy the item name from Anamnesis. Also having a menu to open the Lodestone search page would be cool.

Here what could be in the right click menu:
![image](https://github.com/user-attachments/assets/b3852e98-872f-49ab-88bb-58aab3c0c752)

- **Copy Item Name:** Just as the text suggest, put the item name in the clipboard.
- **Search Item on Lodestone:** Open a link `https://eu.finalfantasyxiv.com/lodestone/playguide/db/search/?q=<item>` where `<item>` is replaced by the url encoded item name.
- **Reset Slot:** Much like the global reset button we have right now, but for a specific slot.

Having at least the option to copy the item name would be enough, but more features are a welcomed addition.

As a sidenote, I don't know which ids you have for items, but if it is the same ids as lodestone, it would be even better to directly open it on lodestone without going through the search results.

**Comment by CaptainSticky** [comment]
I can look into this. I noticed that others avoid Lodestone links and instead opt for GamerEscape, Consolegames Wiki, and Garland tools. Would those work instead? (I personally prefer those over Lodestone.)

As for the reset to pinned button, It can be done. I'll try to find a way to do it cleanly. Right now the reset button loads a chara file object that's saved to the actor in memory when they're pinned. Totally accessible, just need a not-dirty way to reset a specific slot. I can try some things later.

**Comment by alexpado** [comment]
Even without opening a website directly, being able to copy the item name would already be a huge help. As for the reset menu, yes, I don't mean removing the item but reverting it back to its pinned state :)

**Comment by CaptainSticky** [comment]
Okay, understood! I'll get cooking on it this week. :>

**Comment by StoiaCode** [comment]
@CaptainSticky Yeah, check the already existing Partial loading options, in theory it should be simple enough to create a new one that loads individual items. But as it always is "in theory". 

Im partial towards lodestone or any other source, in practice once you got a system working it shouldnt even be too hard to add multiple.
