### ISSUE TITLE
Hrothgar player appearance settings cut off in window & face numbering inaccurate

### ISSUE THREAD

**Issue by thecolossalennui** [imchillin/Anamnesis#1391]
**Describe the bug**
Issue 1: Hrothgar player appearance settings include a selection for fur pattern (tiger stripes, leopard spots, etc.), which is cut off by the Anamnesis fixed window aspect ratio currently. On past Anamnesis versions, the -/+ buttons were sometimes just selectable at the bottom of the window, but in the most recent version, they are completely cut off.

Issue 2: Hrothgar player characters actually use faces 5/6/7/8 (sometimes given as 105/106/107/108 for Lost Hrothgar). This is true for both male and female Hrothgar. Hrothgar male faces 1/2/3/4 exist, but are used on NPCs only and lack some facial customization features. The problem is that the customization preview images only show up on faces 1/2/3/4, which is inconvenient. Female Hrothgar faces 1/2/3/4 do not exist, and will revert to displaying face 5. The generic 1.0 returner character tattoo is shown for all customization preview images on faces 5/6/7/8 for both male and female Hrothgar.

This also triggers the Anamnesis warning about attempting to assign an NPC-only face to a player character, which blocks the "extended customization" options, and is inconvenient to try to work around. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a male or female Hrothgar player character in Anamnesis.
2. Issues 1 and 2 above will be apparent in the customization section and extended customization section. I have attached a screenshot showing same.

**Repeatability**
How often does the bug occur:
Every time Anamnesis is used.

**Expected behaviour**
A clear and concise description of what you expected to happen:
Ideally, Hrothgar faces 5/6/7/8 would no longer trigger the NPC-only face warning, and the customization preview thumbnails that appear for faces 1/2/3/4 currently would be copied to 5/6/7/8. The Anamnesis window size would be increased to be able to display the Hrothgar fur pattern selection option, or some other aesthetically pleasing aspect ratio change or option rearrangement used to achieve the same result.

Thank you! I use Anamnesis often and it is very useful.
![Screenshot 2024-09-22 153148](https://github.com/user-attachments/assets/9fa85ee9-06d9-44bf-990b-b350a477b9f5)

**Comment by CaptainSticky** [comment]
Hello! 

For Issue#1, the fur pattern selector was moved. It's now next to the mouth selector. Since it uses the same byte as lip color, the selector for fur replaces that of lips specifically for Hrothgar.

For Issue#2, my understanding was that male Hrothgar use faces 1-4 and female use 5-8. But it looks like males use both 1-4 and 5-8, while females only use 5-8. I will take a look at cleaning this up as the next thing I work on. I think I'll have to make an actual Hrothgar character instead of using Runar to test with, haha!
