### ISSUE TITLE
Changing lips in Anamnesis actually changes the character lips for real

### ISSUE THREAD

**Issue by feastmother** [imchillin/Anamnesis#1398]
**Describe the bug**
When changing my characters lips in Anamnesis, then going to a barber and saving, the lips stay the same as the changed ones. Its been a while but I think I remember teleporting/ getting in/out of barber resets your character to what it actually is. I tested with a friend who does not use mods to confirm if he sees the change as well and he does.

**To Reproduce**
Steps to reproduce the behaviour:
1. Import your saved character in Anamnesis (I haven't tested if this was necessary)
2. Change your mouth number in Anamnesis
3. Go to the barber and click something to change so you can pay and exit (I would do lip color)
4. Close Anamnesis/Exit the game and when you log back in or teleport, you will notice your lips aren't your original number, but the one you changed to

**Repeatability**
How often does the bug occur:
I've changed it about 5 times and tested with a friend that doesnt use mods 3 of those times

**Expected behaviour**
The character reverts to what it originally is upon teleporting/getting out of barber/logging out/ or exiting the game

**Log file**
Sorry I'm not entirely sure what to put here

**Comment by StoiaCode** [comment]
As is expected. It has always been heavily warned against to NEVER open the Asthethician menu with Ana active because it becomes server readable.
