### ISSUE TITLE
Character rapidly blinks in and out of existence after changing appearance with "Enable NPC faces on PC"

### ISSUE THREAD

**Issue by kayennepepper** [imchillin/Anamnesis#1404]
When changing appearance with Anamnesis on player characters with "Enable NPC faces on PC" turned on, such as hairstyle or gear, the character will rapidly disappear and reappear in the game, and Anamnesis will show them cycling between Player and Battle NPC.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Turn on "Enable NPC faces on PC"
3. Go to a pinned player character
4. Go to Character - Change Appearance
5. Select another hairstyle or piece of gear
6. Observe error in game and in Anamnesis.

**Repeatability**
Bug occured 9/10 attempts

**Expected behaviour**
The character should not blink, and should remain marked as Player instead of Battle NPC.

**Comment by StoiaCode** [comment]
Known issue, fixed In #1402
