### ISSUE TITLE
NPCs missing from Add Character after 7.1

### ISSUE THREAD

**Issue by Bronya-Rand** [imchillin/Anamnesis#1405]
**Describe the bug**
Prior to 7.1 and the accompanied Anamnesis update, NPCs that are around the player's vicinity without a name and with a name (say a random Miqo'te in Solution Nine or Y'shtola) were able to be selected and changed with Anamnesis. After updating both the game, and the tool, only named NPCs and players are able to be selected (at times named NPCs may become uneditable due to "No GPose" when in GPose).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a region in the game with both no-name and named NPCs (preferably a low-population area like Old Sharlayan, Eulmore, etc.)
2. Stand close to said NPC.
3. Open Anamnesis and add a new character.

Even with `Others` and `Show Hidden/Unloaded` enabled, the NPCs will not appear in the selection menu which was able to be accessed prior. Only some icons appear that lead to no character data whatsoever.
![image](https://github.com/user-attachments/assets/e0d902c1-91f5-4482-b439-e04ec9259992)
> On occasions, a "Floor Mandrill" char may appear which loads 0 data now.

Even in dense areas like Idyllshire, NPCs like Rowena do not show up on the list in both GPose and non-GPose modes.
![Screenshot 2024-11-15 055128](https://github.com/user-attachments/assets/0dc7acf3-8f34-4fb4-a61b-c6f566978b08)

**Repeatability**
Persistent even with different map changes, walking back and forth the area to despawn and respawn characters, restart of XIV and Anamnesis itself.

**Expected behaviour**
A no-name NPC or named NPC appears with the yalm distance (no name NPCs being blank names with yalm distance). Clicking said  NPC should load the outfits the NPC is wearing, appearance data, etc.

**Log file**
[2024-11-15-05-43-16.txt](https://github.com/user-attachments/files/17770283/2024-11-15-05-43-16.txt)
The log file only appears to output a single error about the GPose camera but not on the loading of characters.

**Comment by Bronya-Rand** [comment]
In addition to the stuff above, manually selecting a NPC results in no data loading + the "Appearance can only be changed when not in GPose" message 
![image](https://github.com/user-attachments/assets/9cb74da4-ef8d-40b3-af79-b5011424c113)

**Comment by StoiaCode** [comment]
Known issue.

**Comment by CaptainSticky** [comment]
This should be fixed as of [2024-11-24](https://github.com/imchillin/Anamnesis/releases/tag/v2024-11-24). Are you still encountering this issue?
