### ISSUE TITLE
Undo unselects the node you are currently in

### ISSUE THREAD

**Issue by Artemyy** [imchillin/Anamnesis#1406]
**Describe the bug**
Unless it's always happened - is undo meant to unselect the node you are currently using (in posing panel)? If so it breaks flow by having to reselect the node you were currently on

**Repeatability**
How often does the bug occur: every time ctrl+Z is pressed 

**Expected behaviour**
For the node to still be selected when pressing undo.

**Comment by StoiaCode** [comment]
Known unintended change due to the Histroy rework. Will be looked into.
