### ISSUE TITLE
Carbuncle unable to retain Appearance Data 7.11

### ISSUE THREAD

**Issue by Panthanaea** [imchillin/Anamnesis#1413]
**Describe the bug**
Every time I try to use my carbuncle as an extra actor, I cannot change the outfit without the carbuncle reverting to a carbuncle.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pin Carbuncle
2. Import NPC
3. Change Outfit

**Repeatability**
How often does the bug occur:
Bug occured 10/10 attempts across 3/3 zones

**Expected behaviour**
Expected Carbuncle to retain appearance.

**Log file**
[2024-11-27-15-53-49.txt](https://github.com/user-attachments/files/17940999/2024-11-27-15-53-49.txt)

**Comment by StoiaCode** [comment]
Disable Glamourer
