### ISSUE TITLE
启动一直报错

### ISSUE THREAD

**Issue by yeqiu3982846** [imchillin/Anamnesis#1415]
![企业微信截图_17345758957877](https://github.com/user-attachments/assets/e381c1e5-64e0-457a-9220-06a2af35c9f1)

**Comment by yeqiu3982846** [comment]
国服7.0版本使用2024-9-25版本成功打开了

**Comment by CaptainSticky** [comment]
Title (as of now) says: `Startup keeps reporting errors`
Comment above says: `The national server 7.0 version was successfully opened using the 2024-9-25 version.`

The Chinese game patch version for FFXIV run slightly behind as compared to other regions. As you mentioned in your comment, you'll have to use a slightly older version of Anamnesis to run with your version of the game.

Version [2024-09-25](https://github.com/imchillin/Anamnesis/releases/tag/v2024-09-25) of Anamnesis is the last version which supported Patch 7.0 of FFXIV. I recommend using that until Patch 7.1 releases in China, at which point you can use [2024-11-24](https://github.com/imchillin/Anamnesis/releases/tag/v2024-11-24). Similarly for patch 7.11 and 7.15... although I am completely unaware of what the patch schedule for FFXIV is for that region. Releases for Anamnesis, which correspond with patch releases for FFXIV will have the patch version listed.
