### ISSUE TITLE
Prefer chargen numerical values over memory values

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#173]
These are all off by 1 errors (should start at 1, not 0)
- [x] eyes
- [x] Jaw
- [x] Eyebrows
- [x] Nose
- [x] Mouth

**Comment by Yuuki-Walsh** [comment]
can someone get a list of the values that are incorrect? which ones anamnesis shows as "0" that the chargen shows as "1" for example.

**Comment by sleepyquail** [comment]
Some differing values for male Midlander and Elezen wildwood - eyes seem to be the same on both of these, and ears are the same for Elezen. CC is Character Creator.

**Male Midlander Face 4**
CC: Jaw 2 -> Anam: Jaw 1
CC: Eye 5 -> Anam: Eye 5
CC: Brows 5 -> Anam: Brows 4
CC: Nose 5 -> Anam: Nose 4
CC: Mouth 4 -> Anam: Lips 3

**Elezen Wildwood Male Face 2**
CC: Jaw 4 -> Anam: Jaw 3
CC: Eye 5 -> Anam: Eye 5
CC: Brows 5 -> Anam: Brows 4
CC: Nose 5 -> Anam: Nose 4
CC: Mouth 4 -> Anam: Lips 3
CC: Ears 2 -> Anam: Ears 2
