### ISSUE TITLE
UpdateService crashing because of time

### ISSUE THREAD

**Issue by LD6** [imchillin/Anamnesis#199]
So, first time running Anamnesis.
I'm getting this error related to UpdateService

![image](https://user-images.githubusercontent.com/48480080/102002654-2ae4aa80-3cdd-11eb-9ea0-47fbe10469b7.png)

Any way to fix it?

**Comment by LD6** [comment]
"Fixed" by never using the UpdateService, works completely fine without it

Buuuuuuuuut that's not a solution lmao

**Comment by Yuuki-Walsh** [comment]
Fixed this by using a manual version string, since we were echoing out a value wich produced different version strings on different machines due to local time differences.
