### ISSUE TITLE
Main window not displaying while looping in TickMemoryViewModelThread()

### ISSUE THREAD

**Issue by Balbereith** [imchillin/Anamnesis#251]
![image](https://user-images.githubusercontent.com/14954623/112698564-34f47880-8e8a-11eb-8524-75929fe031cb.png)

Hello, after init.
The main windows isn't displayed when compiled. Their are some XAML issues apparently but no breaking exception.

![image](https://user-images.githubusercontent.com/14954623/112698640-60776300-8e8a-11eb-8eaf-6f7137e11655.png)

**Comment by Yuuki-Walsh** [comment]
sounds like its getting stuck somewhere in the service initialization?

Maybe stick a breakpoint in the App.caml.cs:85 Start() method and see if its getting through it?

**Comment by Balbereith** [comment]
Hello,
Seems to be parsing cultures. When activating the debugging outside the domain, le log stops with this : 

> System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
>    at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
>    at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
> System.Windows.Data Error: 23 : Cannot convert '<null>' from type '<null>' to type 'System.Windows.Media.ImageSource' for 'en-US' culture with default conversions; consider using Converter property of Binding. NotSupportedException:'System.NotSupportedException: ImageSourceConverter cannot convert from (null).
>    at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
>    at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
>    at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)'
> System.Windows.Data Error: 40 : BindingExpression path error: 'RootRotation' property not found on 'object' ''TransformViewModel' (HashCode=59928422)'. BindingExpression:Path=Value.RootRotation; DataItem='TransformEditor' (Name=''); target element is 'QuaternionEditor' (Name=''); target property is 'RootRotation' (type 'Nullable`1')
> 'Anamnesis.exe' (CoreCLR: clrhost) : Chargé 'D:\anamesisGit\Anamnesis\bin\/bin/Markdig.Signed.dll'. Chargement des symboles ignoré. Le module est optimisé et l'option du débogueur 'Uniquement mon code' est activée.

Also, the version file seems to be unstable from culture to another with the new line. I had to modify the two lines (duplicated) where it's parsed :  
![image](https://user-images.githubusercontent.com/14954623/112771061-1f1db980-902a-11eb-9297-9658c05c4abd.png)
![image](https://user-images.githubusercontent.com/14954623/112771067-2c3aa880-902a-11eb-94f9-f65090131487.png)
and sadly both chars /r or /n don't match and Environment.Newline (/r/n)

**Comment by Yuuki-Walsh** [comment]
Hmm, that image converter issue is weird. There shouldn't be any conversation happening that's culture dependant.

The version file I might just use a semicolon separator instead of new line to fix that.
