### ISSUE TITLE
Change Animation ID per move on load?

### ISSUE THREAD

**Issue by Kitsune86** [imchillin/Anamnesis#261]
I’m not sure if this should go into concept matrix or this successor project and the title may not exactly make a lot of sense so let me explain.

It’s possible (via cheat engine) to modify the move lookup table and replace while the game is running the animation ID that is played when a certain move is executed.

for example if I wanted to replace Machinst’s Reassemble animation value in the actions.csv table with the discontinued reload I can. The problem with using things like cheat engine is looking up the location of the animation id you want to replace at runtime every time you want to do this and if you accidentally change a wrong value by mistake it can make the client highly unstable.

It seems CM and it’s successor already have a full list of action ID and animation ID and the ability to overwrite the default gpose or idle animation is literally how it works.

so my proposal is a drop down menu per class / Job that lists every currently used skill name and their animations. Obviously this poses a problem for “two step” animations that are actually split into two discrete animations but for stuff like 

Machinist:
Ability:                      (Second drop down)
Reassemble              Reload 
Heated Shot 1 —-.>  unheated 1 
Heated Shot 2 ——-> Unheated 2

brd 
Ability 
Quick knock —-> Wide Volley

And these customized lists would just be loaded at runtime and replace the animation call IDs for the respective moves and nothing more

**Comment by Ani-ki** [comment]
New features aren't being added to CMTool, FYI.

**Comment by Kitsune86** [comment]
> New features aren't being added to CMTool, FYI.

Oh that’s cool. Well feel free to take this idea and run with it if it’s of interest. This is actually something I’ve been wanting to do myself but it feels like CM/Successor literally already do this. So why spend all the time investigating program ram etc when you’ve already done that. Don’t need to reinvent the wheel and that’s why I brought this idea to you

**Comment by Ani-ki** [comment]
To be perfectly honest we're hesitant to touch animations in Anamnesis given there's a potential plugin for XIV Launcher in development to handle it better using Dalamud. I feel you'd be best holding out for that instead.

(Or if you're a developer, perhaps consider forking the repo and diving into it yourself? We'd appreciate the help.)
