### ISSUE TITLE
Load valid weathers from LVB

### ISSUE THREAD

**Issue by lmcintyre** [imchillin/Anamnesis#280]
Congrats on the release, guys. I noticed weathers are not filtered based on valid weathers for the zone. Here is an example of an LvbFile FileResource you can load with Lumina that will get you the valid weathers for the current zone, given its lvb file:

```
public class LvbFile : FileResource
{
    public ushort[] weatherIds;
    
    public override void LoadFile()
    {
        weatherIds = new ushort[32];

        int pos = 0xC;
        if (Data[pos] != 'S' || Data[pos + 1] != 'C' || Data[pos + 2] != 'N' || Data[pos + 3] != '1')
            pos += 0x14;
        int sceneChunkStart = pos;
        pos += 0x10;
        int settingsStart = sceneChunkStart + 8 + BitConverter.ToInt32(Data, pos);
        pos = settingsStart + 0x40;
        int weatherTableStart = settingsStart + BitConverter.ToInt32(Data, pos);
        pos = weatherTableStart;
        for (int i = 0; i < 32; i++)
            weatherIds[i] = BitConverter.ToUInt16(Data, pos + i * 2);
    }
}
```

I know there are some valid uses for killing the lighting that weathers include by setting weather invalid. I think 0 is always invalid, so you can keep that as an option.

**Comment by Yuuki-Walsh** [comment]
you can filter the list of available weathers to only ones that normally appear in the current zone with this filter at the top of the weather selector: 
![image](https://user-images.githubusercontent.com/379714/115501768-23e72d80-a2b7-11eb-992d-def1b276db99.png)

There are also a couple of invalid weather ID's that will result in unique cut-scene or event weathers from loading.

We currently filter the weathers based on the Weather Rates excel sheet from Lumina: `GetExcelSheet<WeatherRate>()`
