### ISSUE TITLE
Window does not go transparent if Custom window border is disabled, instead it just darkens.

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#281]
![image](https://user-images.githubusercontent.com/82767067/115431065-3d9d5c00-a248-11eb-8c5c-fad4a089c522.png)

**Comment by Yuuki-Walsh** [comment]
Since windows doesn't let us make transparent windows borders, if the custom border option is disabled, transparency is now disabled too. The window will no longer go black, but it wont become transparent either.
