### ISSUE TITLE
Anamnesis won't launch, even after downloading the latest Windows .NET file 

### ISSUE THREAD

**Issue by bloomedsecret** [imchillin/Anamnesis#283]
[2021-04-20-11-01-05.txt](https://github.com/imchillin/Anamnesis/files/6345403/2021-04-20-11-01-05.txt)

I'm new to writing a post on GitHub, so if you need anymore information let me know o7

**Comment by solitonmedic** [comment]
Try restarting your PC, there's a good chance the Anamnesis process is still active. Ana worked for me right after I restarted.

**Comment by bloomedsecret** [comment]
I’ve already tried that, but unfortunately no results. I’ll try restarting again though :)

**Comment by CalCrazy** [comment]
I'm having the same issue. I installed .NET, but it still says I need it in order to run. https://gyazo.com/ef444187bd36135da51a92b305b01385

Picture of what it's saying anytime I run it. I am a first time user of the program so I don't know if I'm doing something wrong.

**Comment by bloomedsecret** [comment]
Hi everyone, I found a solution! Instead of opening Ana through the windows search bar, open the **file location** and click **open** instead. Hope this works for you all! <3

**Comment by Yuuki-Walsh** [comment]
This issue is also fixed by: https://github.com/imchillin/Anamnesis/issues/296

so in the next version it shouldn't matter where you launch Ana from.

**Comment by Yuuki-Walsh** [comment]
@CalCrazy if your still having issues, can you try the steps outlined in this post: https://github.com/imchillin/Anamnesis/issues/294#issuecomment-823734391 and see if you're having the same issues described there?
