### ISSUE TITLE
Improve error handling of malformed pose files

### ISSUE THREAD

**Issue by Faane** [imchillin/Anamnesis#284]
Hello,

I am having an issue where when I try to load a .pose file, it throws an error. They do not show in the file explorer inside Anamnesis, and when manually loaded they throw the error. Here is the log file attached as well.
[2021-04-20-20-29-48.txt](https://github.com/imchillin/Anamnesis/files/6345931/2021-04-20-20-29-48.txt)

**Comment by Yuuki-Walsh** [comment]
can you send through the pose file itself? something seems to be wrong with it. (here or directly to me on discord is also fine)
