### ISSUE TITLE
Error when opening Anamnesis (Unknown Reason)

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#285]
https://discord.com/channels/748454690118828163/833882377964355614/834134923907432508
Log file at linked location, problem submitted by user 羅真雪村#1644

**Comment by hallow-gram** [comment]
[2021-04-20-16-14-15.txt](https://github.com/imchillin/Anamnesis/files/6346530/2021-04-20-16-14-15.txt)
similar issue here, though with a few different errors

**Comment by Yuuki-Walsh** [comment]
First issue looks like the memory signature was wrong, perhaps the game needed to be restarted after memory was editied somewhere, or was possibly not the international client?

Second issue looks like the application did not launch with the correct working directory. This appears to happen when some launchers start applications incorrectly? it shouldn't happen if you launch Anamnesis by double-clicking its exe. (I'll be adding some more sanity checks to catch this issue with a better error message)
