### ISSUE TITLE
Opening Anamnesis while Anamnesis is still open leads to a permanently loading instance that doesn't acknowledge when other instances are closed.

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#287]
Step 1: Load Anamnesis.
Step 2: Forget you opened Anamnesis.
Step 3: Load Anamnesis.
Step 4: Get an error saying "Close other instances."
Step 5: Press "Quit"
Step 6: Close the other instance.

There's no step 7 except enjoy becoming Anamnesis-Man with the symbol on your chest (or opening task manager)
![image](https://user-images.githubusercontent.com/82767067/115454997-bca08d80-a264-11eb-8c89-80bd07853cf8.png)

**Comment by Featherbrew** [comment]
![image](https://user-images.githubusercontent.com/82767067/115455589-81eb2500-a265-11eb-895b-533be74868e5.png)

**Comment by Yuuki-Walsh** [comment]
fixed this in commit: <a href="https://github.com/imchillin/Anamnesis/commit/b130afe01a19f8094600bada618448153fe36876">quit button in error dialog must terminate process at any cost</a>
