### ISSUE TITLE
Updater deletes user files if the target path is incorrect

### ISSUE THREAD

**Issue by Asche00** [imchillin/Anamnesis#289]
Upon attempting to start the new version of Anamnesis for the first time I was given the open beta prompt. Upon clicking okay, the updater seemed to run in the background and started deleting all of my Documents Folder during the "Cleaning Up" phase.

I initially had some issues with getting it to run so I was running a version I had compiled from the repo(I didn't make any modifications to the code, just pulled the latest, built the exe and ran it from the bin) the path was the following: 

Documents\Visual Studio 2019\Projects\Anamnesis\bin

Just to clarify, I had ran an older version compiled from the repo as well, so that is likely what triggered the updater.

**Comment by Yuuki-Walsh** [comment]
I've removed the updater from the current release, so if you're on the private beta builds and it tries to update, it will fail (better then erasing documents!)

I'll add some sanity checks to the updater to make sure its running in the correct folder before it erases anything.
