### ISSUE TITLE
Scaling Mode Not Working for Custom Scaling

### ISSUE THREAD

**Issue by sleepyquail** [imchillin/Anamnesis#293]
I loaded in a custom scaling with the [s] button ticked, and then saved it as a .pose file. Unticking the [s] button then removes the custom scaling from my character. So I tried loading it in again, leaving [s] ticked and loading in another file and it still removes the custom scaling - I can't see any way to stop it from doing this.

**Comment by Yuuki-Walsh** [comment]
you can keep the current scaling while loading a new pose by disabling scale loading in advanced options when selecting the file: 
![image](https://user-images.githubusercontent.com/379714/115495670-863a3100-a2ab-11eb-9bf1-8747f2185794.png)

**Comment by sleepyquail** [comment]
> you can keep the current scaling while loading a new pose by disabling scale loading in advanced options when selecting the file:
> ![image](https://user-images.githubusercontent.com/379714/115495670-863a3100-a2ab-11eb-9bf1-8747f2185794.png)
> 
> By default, pose files loaded while scaling is enabled will load the scaling from the pose file (this behavior is the same for rotations and positions)

Thank you, that did work! It would be worth uploading that screenshot onto the wiki and specifying that there is a difference, as at the moment it only refers to the [s] box at the top.
