### ISSUE TITLE
EXE won't run (even though .NET is installed)

### ISSUE THREAD

**Issue by CalCrazy** [imchillin/Anamnesis#294]
https://gyazo.com/ef444187bd36135da51a92b305b01385

I downloaded the zip file located on the download page, and I unzipped it into the drive I have CMT and TT in, and it keeps saying the above message anytime I try to run the .exe program, even though .NET is installed. I even tried moving the "dotnet" folder from my C drive to the drive Anamenesis is on (which is my F drive) and that didn't help either. I even downloaded and placed the other two files located on the download page into the program folder just to be safe.

I've not used this program, nor installed anything using this github system. Did I do something wrong? Am I missing something? I've tried running it as an Admin also with no luck :(

**Comment by seirralanzce** [comment]
what version of .NET you've installed.

It requires .NET 5.0,
To be safe, never place the tool in same folder as other tool at all..

**Comment by CalCrazy** [comment]
It was the current one, I downloaded it from the microsoft site. But that was on the C drive which is my SSID and everything else is on my F drive. Is that the issue?

**Comment by Yuuki-Walsh** [comment]
can you try running the `dotnet --info` command (or download a batch file that runs that command <a href="https://cdn.discordapp.com/attachments/833882377964355614/834250755149922314/dotnetinfo.bat">here</a>) and show what versions of dotnet you have installed?

Additionally, if you check the windows logs (Event Viewer ->Windows Logs -> Application) there should be entries for Anamnesis failing to launch, can you share what those say?

We have been having trouble with the wrong version of .net being selected, causing the app to fail to launch which we are investigating.

**Comment by CalCrazy** [comment]
.NET runtimes installed:
  Microsoft.NETCore.App 5.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  
Description: A .NET application failed.
Application: Anamnesis.exe
Path: F:\Anamesis\Anamnesis.exe
Message: A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [F:\Anamesis\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.2

**Comment by CalCrazy** [comment]
The top is what the dotnet info showed, the bottom is what the window log showed.

**Comment by Yuuki-Walsh** [comment]
hmm, looks like you have the x86 version of .net installed, but your PC and Anamnesis need the x64 version, can you double check that you're downloading the<a href="https://download.visualstudio.microsoft.com/download/pr/c1ef0b3f-9663-4fc5-85eb-4a9cadacdb87/52b890f91e6bd4350d29d2482038df1c/windowsdesktop-runtime-5.0.5-win-x64.exe
">x64 version</a>

**Comment by CalCrazy** [comment]
It's late but I will do that tomorrow and update you!

**Comment by CalCrazy** [comment]
ok I installed the 64 and it seems to be running now, thank you very much!
