### ISSUE TITLE
Loading .pose files causes invalid bone values

### ISSUE THREAD

**Issue by Felidea** [imchillin/Anamnesis#298]
I just started my game and tried to pose in my FC-House-Room.

Than i tried to load in a .pose, but my character broke[ https://i.gyazo.com/c0f283cdd71fd410bb9a7e42f12588f0.png ]. 
I just had [R] checked. With [P] checked my character fully dissapeared. 
cma-Files working fine. 

I tried to pose a Midlander-Girl with no special bonescaling etc.

**Comment by Yuuki-Walsh** [comment]
This may be caused by the recent format changed for locales with comma decimal separators. Does this still happen with the most recent version and with poses saved in the most recent version?

**Comment by Felidea** [comment]
So far it seems to work now! Thank you very much!
