### ISSUE TITLE
Character "implodes" when loading .pose

### ISSUE THREAD

**Issue by Kiimmmiiii89** [imchillin/Anamnesis#299]
Here's a step by step;
Load game
Load Anamnesis after log in
Put wanted gear etc on
Open Gpose
Load saved .pose
https://www.xivmodarchive.com/modid/29591
Character "implodes" as seen on image.
When also selecting P, as well as R, character disappears completely
Character reappears when disable and enable again.
![2021-04-21_13-56-38-655_TheFashionista_-_Colourbringers_2 0_Gameplay](https://user-images.githubusercontent.com/82948449/115552265-68210080-a2ac-11eb-900e-269a1bdd881a.png)

**Comment by Yuuki-Walsh** [comment]
Going to push this discussion to #298 since I believe they are the same issue.
