### ISSUE TITLE
Disable bone transform editor when multiple bones are selected

### ISSUE THREAD

**Issue by arubibi** [imchillin/Anamnesis#300]
This was tested in mind that once children bones are selected, nothing should be moving when you are using orb/coords.
If this assumption is wrong, please disregard.
Selecting chain of "children bones" prompts to automatic selection of clothing or an "end".
Selecting upper body prompts to Pauldron [R] with a ability to move it around.
Selecting Lower body may prompt to a Tail [D] selection or toes on other races. 
Selecting neck, leads to hair with ability to move the latter.
and similar scenarios. 

![selection_v1](https://user-images.githubusercontent.com/82907756/115602368-89eba900-a2e7-11eb-9e08-86c87be0704b.png)
![selection_v2](https://user-images.githubusercontent.com/82907756/115602386-8ce69980-a2e7-11eb-9c25-a74318b5fff4.png)

**Comment by Yuuki-Walsh** [comment]
We should disable the bone editing panel when multiple bones are selected to avoid this confusion until we can edit multiple bones at once.
