### ISSUE TITLE
Issue: Unable to load .pose files, occaisonally unable to load .cmp files.

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#301]
Reported by *likes to hiss at children*#0666
https://discord.com/channels/748454690118828163/833882377964355614/834485818416037936
Watched via screenshare - They attempted to load a .cmp in gpose and nothing occurred. Featherbrew loaded the .cmp themselves, and it worked fine. Featherbrew loaded the .cmp and then saved it as a .pose, and sent the file to the user, which caused a visible error (attached logs).
They left gpose, reopened it, and .cmp files worked - but they still had errors using .pose files including ones downloaded from the pose showcase.
Version checked, latest version, no user error.
Using steam version + XIV Launcher

in less formality, the fact it can load ANOTHER PROGRAMS FILES but not ITS OWN is kinda fucking funny.
[2021-04-21-20-18-35 (1).txt](https://github.com/imchillin/Anamnesis/files/6353150/2021-04-21-20-18-35.1.txt)
The .cmp and .pose files are DM'd to Yuuki with this issue attached.

**Comment by Yuuki-Walsh** [comment]
This looks like issue #297.  Should be fixed with the next release.
