### ISSUE TITLE
camera position temporary save/load

### ISSUE THREAD

**Issue by CitySim** [imchillin/Anamnesis#305]
It would be cool if the temporary save/load for the camera from CMTool could be added. Very handy if you have your camera already setup, and then want to check/tweak something and can reload your camera setup.

![image](https://user-images.githubusercontent.com/109395/115673110-8cccb500-a34c-11eb-9e32-25ddb3e922a2.png)

**Comment by Yuuki-Walsh** [comment]
going to push this discussion to #92 to consolidate.
