### ISSUE TITLE
Load sometimes not displaying entire folder of appearances on first open after launching

### ISSUE THREAD

**Issue by yuyuisyuyu** [imchillin/Anamnesis#307]
At times I have noticed after hitting Load that not all appearances in the Local Files directory are being displayed. Closing the Load panel and reopening it seems to have resolved this issue any time it has appeared.

Having trouble replicating the issue on demand but I have noticed it when I have first booted Anamnesis. Thinking about how often it has occurred it is possible it has only happened when I am booting a new version of Anamnesis though I'm not sure how that would be the case.

**Comment by yuyuisyuyu** [comment]
Haven't cleared or altered any files between boots of the tool aside from sometimes downloading new versions and unpacking and deleting the previous release files.

I tried redownloading the new release again to see if that would somehow produce the issue, but as I expected it did not. I will keep trying to replicate the issue.

**Comment by Yuuki-Walsh** [comment]
Might need some logs to dig into this. there might be something going wrong with the file scanner the first time it opens.
