### ISSUE TITLE
Failed to open ".chara" file 

### ISSUE THREAD

**Issue by hiromell** [imchillin/Anamnesis#309]
When i'm saving appearances, my friend don't have problems with it, but when i'm trying to open his saved apperance, always get "FAILED TO OPEN FILE" error. 
[2021-04-23-12-08-37.txt](https://github.com/imchillin/Anamnesis/files/6362899/2021-04-23-12-08-37.txt)

**Comment by Yuuki-Walsh** [comment]
this appears to be the same issue as #297 and should be fixed in the next release along with it
