### ISSUE TITLE
If the camera moves too far from the original model, the model can't be targetted and manipulated.

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#310]
https://discord.com/channels/748454690118828163/832187278209318932/835136834081783808
Referenced here.

Only in an extreme distance however. Not sure if this is something that has a feature, workaround or is an inbuilt game problem.

**Comment by Yuuki-Walsh** [comment]
This is just the games culling system removing everything that gets too far away from the camera, or the point where your actor is meant to be.

There is nothing we can currently do about it.
