### ISSUE TITLE
Reset user settings function

### ISSUE THREAD

**Issue by gardeniadill** [imchillin/Anamnesis#311]
hi !!
i tried loading anamesis and when it asked me for the window size, i accidently picked a size that was too large. now the program won't give me access to settings, and is cropped to the point where i can't access the bottom left hand corner of the screen or anything on the right side of the program. is there a way to reset the window size? 

(i tried submitting a screenshot of it but i don't really know how to use github so i'm not sure if it worked :') please help LOL)
![Screenshot 2021-04-23 165845](https://user-images.githubusercontent.com/83099779/115940116-3eefa400-a455-11eb-92fa-4c411404ff18.png)

**Comment by Yuuki-Walsh** [comment]
You can reset your settings by deleting the file at `C:\Users\[your user]\AppData\Roaming\Anamnesis\Settings.json`.

We should provide a way to reset user settings easily for these cases.

**Comment by Yuuki-Walsh** [comment]
In future builds, holding shift when launching should clear the settings.
