### ISSUE TITLE
Visor when enabled editing pose 

### ISSUE THREAD

**Issue by Lanselotto** [imchillin/Anamnesis#314]
When I enable pose editing with visor enabled, the visor displays as off and if I disable Freeze Physics the visor continues to rotate around my face. Tested with "Shadowless Petasos of casting" and "Kokuko Men".

**Comment by Yuuki-Walsh** [comment]
Not sure if there's anything that we can do about this. whats the behavior with CMTool?

**Comment by Lanselotto** [comment]
I checked, the physics behavior in CMTool is pretty much the same. The only difference is that the visor does not appear if it has been removed when I activate the pose editing, or does not return to its initial position in case, like the mask, it is moved to the side.

**Comment by cervinee** [comment]
New to Anamnesis so forgive me if I missed that this was already answered - same thing is happening to me with the Shadowless Petasos of Healing. I've tried editing pose with visor both on and off, and regardless it turns on then clips into the middle of the face. Is it something on my end?

**Comment by Ani-ki** [comment]
> 
> 
> New to Anamnesis so forgive me if I missed that this was already answered - same thing is happening to me with the Shadowless Petasos of Healing. I've tried editing pose with visor both on and off, and regardless it turns on then clips into the middle of the face. Is it something on my end?

This should have been resolved in the latest update. Can you please advise if this is working correctly for you?

**Comment by Yuki-Walsh** [comment]
Going to close this as there isn't really anything we can do about it, and we've made improvements to visor handling that gets us close.
