### ISSUE TITLE
French translation pose view layout adjustments

### ISSUE THREAD

**Issue by Luna664** [imchillin/Anamnesis#315]
Hello, I would like to make a pull request to change the size of some elements that poses a problem for the French translation, I have detailed everything here: https://github.com/Luna664/Anamnesis/pull/7

**Comment by Ani-ki** [comment]
Is this taking into consideration the recent updates? The FR localisation was recently updated to address a lot of this.

**Comment by Luna664** [comment]
Yes, I downloaded the code 2 hours ago, I made screenshots of what I modified if you want to check ^^

Before: 

https://cdn.discordapp.com/attachments/835491954098831371/835492009821077522/IwBCYCKY18.png
https://cdn.discordapp.com/attachments/835491954098831371/835492048416145458/onLjO3bKa9.png
https://cdn.discordapp.com/attachments/835491954098831371/835492076928892948/LClxAdA38H.png

After:

https://cdn.discordapp.com/attachments/835491954098831371/835492027197030400/Anamnesis_FLaNtW5783.png
https://cdn.discordapp.com/attachments/835491954098831371/835492060756705310/Anamnesis_cj5Bu1b7MZ.png
https://cdn.discordapp.com/attachments/835491954098831371/835492087402070046/Anamnesis_Y7XaPV7HjE.png

**Comment by Yuuki-Walsh** [comment]
I don't want to make the window any wider than it currently is, but we can definitely adjust the width of the columns in the pose matrix and pose 3d.

I think the top-bar in pose gui needs a reshuffle anyway, so we can solve that one separately.

If you want to open a pull request from your branch to the main one I can merge your changes in and make adjustments.

**Comment by Luna664** [comment]
It's done, for the moment I sent only one file, I'll try to see if I can do something for the rest without changing the size of the window ^^

**Comment by Yuuki-Walsh** [comment]
I'll be going though some pages and adjusting layout this week, so I may solve those as I go. Particularly pose view is getting more buttons.

**Comment by Yuuki-Walsh** [comment]
Should be plenty of space up here now:
![image](https://user-images.githubusercontent.com/379714/116395258-3f2ddc00-a867-11eb-9d80-8d6c027d42ca.png)

Also adjusted pose matrix.
