### ISSUE TITLE
Gpose not loading when turning carbuncle into NPC

### ISSUE THREAD

**Issue by Mimorinnn** [imchillin/Anamnesis#318]

**Comment by Ani-ki** [comment]
Can you please provide more information?

**Comment by solitonmedic** [comment]
When you’re editing NPCs changed into player models, it’ll sometimes freeze Gpose if they got invalid main and offhand weapons, i.e no weapons equipped. To avoid this, equip the New Emperor’s Fists on their main hand.

**Comment by Mimorinnn** [comment]
thank you i'll try this! i know it does it on CMtools too but putting
everything to 0 fixed it so I thought it would be the same if I put no
weapon on the npc as well via Anamnesis. Thank you again!

Le dim. 25 avr. 2021 à 04:00, solitonmedic ***@***.***> a
écrit :
