### ISSUE TITLE
Lag/Slowdown of Entire Tool After ~45-60 Minutes

### ISSUE THREAD

**Issue by shichiloafs** [imchillin/Anamnesis#324]
Not sure if it's just a 'my computer is baby' problem, but I've noticed this happening in every posing session, usually at around 45m to an hour.  This is without loading any pose files, I know there was another post about that.

**Comment by Luna664** [comment]
Hello, is it only when you do poses or only with the open software?

**Comment by Ani-ki** [comment]
@shichiloafs Can you please advise if you are using CMP files when this is happening? If, so this has already been brought up in #272.

**Comment by Yuuki-Walsh** [comment]
Hi, we're investigating these issues over at #272 now, please chime in on there and help us track this down.
Since this seems related to posing and not specifically *.cmp files, we've changed that issue, and are still investigating.
