### ISSUE TITLE
Anamnesis' update error prompt does not close when pressing any key

### ISSUE THREAD

**Issue by Vauun** [imchillin/Anamnesis#325]
To replicate:
1. Extract Anamnesis to a folder not located on the C:\ drive
2. Attempt to update normally.
3. When Anamnesis fails to update, press 'any' key to close the CLI that appears.

![image](https://user-images.githubusercontent.com/9652169/116282732-1e776080-a759-11eb-8ca4-8ab40d90d3ce.png)

**Comment by seirralanzce** [comment]
i have this issue always. My Program Files are set to different Drive then C:\ as well. always having this issue everytime there is prompt new updates.
