### ISSUE TITLE
XYZ positioning resets when no bones selected

### ISSUE THREAD

**Issue by Toki-Snow** [imchillin/Anamnesis#326]
Hello! I am new to the tool so forgive me if this is an obvious issue and I am doing something wrong. When trying to adjust the XYZ position of an actor's entire body (no specific bones selected), the new position last for only a second then resets/snaps back to the default setting. Thank you for your help!

**Comment by Ani-ki** [comment]
Hi there, it sounds like you've not frozen your actors in GPose itself. Can't remember what the keyboard shortcut is off the top of my head, but it's L2/LT by default on controller.

**Comment by Mothism** [comment]
The shortcut on keyboard would be the 1 key (not the Numpad 1).

**Comment by Toki-Snow** [comment]
That was it!! Thank you so much guys, I really appreciate it!!
