### ISSUE TITLE
Maintain gear and appearance when changing areas.

### ISSUE THREAD

**Issue by Lanselotto** [imchillin/Anamnesis#328]
It would be helpful to be able to keep gears and appearance when I change areas.

**Comment by Ani-ki** [comment]
```Gear being carried across loading screens (teleporting etc.)- the developers have no plans for this feature as it doesn’t really fall within the scope of ‘screenshot tool’. Additionally doing anything that survives loading screens is dangerous since memory gets weird while loading. ```

This has been [**covered in our FAQ**](https://discord.com/channels/748454690118828163/748603390275223623/835776032303874088), which we ask people to read prior to making suggestions.
