### ISSUE TITLE
Failed to Initialize Memory Service

### ISSUE THREAD

**Issue by Dainichi22** [imchillin/Anamnesis#331]
Anamnesis opens and gives me the Failed to Initialize service : Memory service
closing the error opens the program but doesn't work in gpose, I didn't have this problem prior today, I have also restarted my PC and it didn't fix it

[2021-04-29-15-55-00.txt](https://github.com/imchillin/Anamnesis/files/6401278/2021-04-29-15-55-00.txt)

**Comment by Yuuki-Walsh** [comment]
We've seen this issue pop up a few times.
Are you on the international version of FFXIV?
Does it still happen after restarting FFXIV or rebooting your PC?

**Comment by Dainichi22** [comment]
After disabling Weatherman (a plugin that controls weather via XIV Launcher (https://github.com/Eternita-S/Weatherman)) the plugin might be interfering with the program

**Comment by Yuuki-Walsh** [comment]
ah, yes, Dalamud plugins that modify memory can conflict with anamnesis (and each-other).
