### ISSUE TITLE
Failed to Initialize Memory Service

### ISSUE THREAD

**Issue by XilloTV** [imchillin/Anamnesis#336]
[2021-05-01-01-13-27.txt](https://github.com/imchillin/Anamnesis/files/6408856/2021-05-01-01-13-27.txt)

I was in the middle of using anamnesis. I get this problem where the program will eventually crash for no reason while I'm in the middle of fiddling with poses. When I get the crash I can no longer open the program. I get the memory service error and I can no longer select the equipment and gpose tabs. I have to completely reinstall the program and reset my PC in order to get the two tabs back. I would like to know what is causing this error in the first place.

**Comment by Yuuki-Walsh** [comment]
If Anamnesis crashes, it can leave the ffxiv memory in a bad state, this bad state is whats causing the error the next time you launch Anamnesis. the only solution is to restart ffxiv to load correct memory.

if you can upload a log of anamnesis crashing, I can try and fix that.

**Comment by XilloTV** [comment]
--Ignore the comment from the github bot.. I posted it in the wrong thread for this.. but yeah.. I can try that if it happens again.

**Comment by Ani-ki** [comment]
Hi @XilloTV, can you please advise if this resolved your issue so we can close the ticket?

**Comment by XilloTV** [comment]
Restarting FF does let me open the program again, yes. But the crashes do not cease. I have already uploaded my log in the very first post.

**Comment by Yuuki-Walsh** [comment]
Sorry, that log is from when you opened Anamnesis the second time, I need the log from when you encounter the crash.
