### ISSUE TITLE
Set privilege failure: "The caller does not have all the privileges or groups referenced."

### ISSUE THREAD

**Issue by Kuriini** [imchillin/Anamnesis#342]
Hello, 

I can not launch the application. When I run it (even as an administrator) it opens directly with an error message.
As indicated I show you the log file :

[2021-05-04-20-11-27.txt](https://github.com/imchillin/Anamnesis/files/6423154/2021-05-04-20-11-27.txt)

Thank you in advance for your reply

**Comment by Yuuki-Walsh** [comment]
hmm, that looks like a privilege error, but I'm not sure why. It may be antivirus or windows settings interfering with anamnesis' ability to access ffxiv.

**Comment by Ani-ki** [comment]
@Kuriini just wanting to follow up on this; have you had a chance to read Yuuki's response above?
