### ISSUE TITLE
Gpose hangs on black screen 

### ISSUE THREAD

**Issue by Carceri256** [imchillin/Anamnesis#344]
Using Anamnesis to mess around with Housing NPC's, changing them to Players.

An issue occurred where anytime I tried to use GPose near the Materia Melder specifically it would just not get past the black load screen prior to entering into GPose and would sit in loading limbo. Other NPC's seemed to work fine. The log denotes an error of "failed to read gpose address". 

Unsure if the issue is the ceiling of the second floor of the house, the NPC-turned-Player, or errors caused by multiple stacked furniture pieces (including the NPC's).

[2021-05-05-23-57-58.txt](https://github.com/imchillin/Anamnesis/files/6431731/2021-05-05-23-57-58.txt)

**Comment by Ani-ki** [comment]
Hi there. Are you loading an appearance onto these NPCs after changing them into editable actors by any chance?

**Comment by Carceri256** [comment]
Yes, that has happened a couple times. 

I swapped the Mender NPC to a Player and loaded a previously created look with no issues. GPose worked fine.

The Materia Melder made GPose hang with or without having loaded an appearance, I tried both ways with the same result.

The odd thing is I've been doing the same thing for the past couple days with no issues til now.

**Comment by Yuuki-Walsh** [comment]
Hanging on gpose entry is usually caused by weapons, having 0,0,0 equipped is fine as long as your not doing a weapon animation. Otherwise any invalid numbers will cause gpose to die

Might be prudent to add a check for valid weapons after loading an appearance?

**Comment by Yuuki-Walsh** [comment]
Looks like a common cause for this is character saves having dye values left in them from changing weapons not correctly clearing the dye.

I've added some safety checks to loading character files with no weapons, as well as fixed the UI to remove dye when equipping none items directly.
