### ISSUE TITLE
Failed to bind skeleton to view

### ISSUE THREAD

**Issue by Retrouvaillesx** [imchillin/Anamnesis#346]
Anamnesis fails to bind player skeleton to view when gpose is started up
[2021-05-08-00-37-52.txt](https://github.com/imchillin/Anamnesis/files/6445220/2021-05-08-00-37-52.txt)

**Comment by Yuuki-Walsh** [comment]
looks like a bone was missing from the skeleton when it tried to load, not sure why. I'll add more logging to help track this down for the next version.
