### ISSUE TITLE
loading npc data prior to entering gpose causes black screen

### ISSUE THREAD

**Issue by goomyluca** [imchillin/Anamnesis#353]
apologies if this issue is known already, i can't glean from similar threads if i have the exact same issue as other users. problem is simple: i convert the actor to Player, apply npc appearance, then try loading into gpose itself. gpose never finishes loading, just a very long black screen. this does not happen with my own character's appearance; i tested back and forth a few times to check. 

if i've done something obviously wrong, sorry for the trouble! thanks so much for your hard work on this software, it is incredible!!

**Comment by Ani-ki** [comment]
Hi there! Which NPC appearance are you loading on?

**Comment by goomyluca** [comment]
> Hi there! Which NPC appearance are you loading on?

hello! it was haurchefant in particular--i chose a few different ones from the list just to be sure, and all of them had the same issue.

**Comment by Yuuki-Walsh** [comment]
Going to follow this up on #344

**Comment by Yuuki-Walsh** [comment]
So this is a different issue, Hershefant here has some odd weapon values:
![image](https://user-images.githubusercontent.com/379714/118106755-4a653800-b421-11eb-8b18-804675825262.png)
