### ISSUE TITLE
Invalid equipment Ids from Lumina (Naked NPC's)

### ISSUE THREAD

**Issue by goomyluca** [imchillin/Anamnesis#356]
hello; i've still had issues with loading npc data and then entering gpose--as i mentioned in a now-closed issue, the game remains on a black screen and gpose loads indefinitely. after some testing... it seems like only Haurchefant has this issue? which is bizarre, but i've now tried every existing model with his name (and the minion too just to be sure), and here are my findings:

- his hair has bright blonde highlights, strangely (every version)
- i've switched between Player, Battle NPC, and Event NPC; none seemed to work
- my best guess that due to [spoiler], the game gets confused because his model shouldn't exist; i tested several other characters like ardbert and yotsuyu, both were fine, so that can't be the problem i don't think?
- haurchefant is also in his smalls in all of his models while others have clothes in some versions of theirs, which while hilarious is kind of strange
- i also tested monsters/etc misc categories, and had no issues entering gpose

i'm sorry that i can't explain this in a more programmer-minded way; i am however passionate about the wonderful resource your guys have built, and want to help in any way i can! i'm happy to keep testing things until i break something and report the results like this. thank you for your patience and hard work!!!!

**Comment by Yuuki-Walsh** [comment]
Yea this might be a bug with Lumina or just some weird change to how equipment works in the npc database.

I've fixed invalid equipment from causing the black screen when entering gpose in the next update, but so far I don't know why the equipment is invalid in the first place.

**Comment by Yuuki-Walsh** [comment]
Note: CMTool does not seem to have this issue
