### ISSUE TITLE
Anamnesis .exe failing to launch

### ISSUE THREAD

**Issue by HumWasTaken** [imchillin/Anamnesis#360]
When opening Anamnesis, even in Administrator mode, the .exe fails to launch. A look at Task Manager shows the .exe starting for a few moments before closing immediately. 

I have confirmed that no anti-virus or windows defender (firewall) is interrupting with the process either, too, having disabled those to test, too. I have also restarted my PC and re-installed Anamnesis to test for any of these. This issue has been prevalent since trying to install from 3 updates prior and including the current build.

Thank you.

**Comment by Yuuki-Walsh** [comment]
Make sure you have the correct .Net 5.0.5 installed, if so, have a look in the windows event viewer -> Windows  Logs -> Application and see if there are errors there about it.

**Comment by HumWasTaken** [comment]
I did have the correct version installed and decided to reinstall it which solved the issue, thank you.
