### ISSUE TITLE
Pose Saving not displaying full folder hierarchy 

### ISSUE THREAD

**Issue by mogilymog** [imchillin/Anamnesis#363]
When loading a pose file, you're able to type in the search box to help narrow down what you're looking for - this is great and I love it dearly.  However, if you leave anything in that text box, and then you go to save a pose, any existing folders aren't displayed because I believe it's still trying to search for whatever you have in the search box in the load menu. As soon as you clear out that text and go to save again, the full folder structure is visible.  Image attached to better show folders not being displayed

Gods I hope I'm doing this right and/or this hasn't already been brought up or if this is working as intended then oops.
![3JYDDmG](https://user-images.githubusercontent.com/76633834/119212279-241c4980-ba6c-11eb-85f4-803e46781c0a.png)

**Comment by Ani-ki** [comment]
I could have sworn we'd looked into that and resolved it, but you're right, and I was able to replicate.

**Comment by Yuuki-Walsh** [comment]
duplicates #350 
Fixed for next build.
