### ISSUE TITLE
Can't open Anamnesis: Possible Permission Error

### ISSUE THREAD

**Issue by Ganolink** [imchillin/Anamnesis#372]
![Capture](https://user-images.githubusercontent.com/84793627/119527606-7bf9cf80-bd4e-11eb-9f91-f9242e58ec65.PNG)
I got this error after the update. I've downloaded the new release on 2 drives and got the same error when opening them on both.

**Comment by HikariYamiTwin** [comment]
Did you try making an exception of this version on your AntiVir?

**Comment by Ganolink** [comment]
Ah, sorry I just got it working and I should've troubleshooted more. It wasn't my antivirus, though I did recheck and it was in my exceptions list. I downloaded an old version of Anamnesis and opened that then exited out of FFXIV and Anamnesis. Then I restarded FFXIV which somehow let me open up the latest Anamnesis.
