### ISSUE TITLE
Failed to bind skeleton to view

### ISSUE THREAD

**Issue by eijifloren** [imchillin/Anamnesis#379]
See that there are other closed instances of this but couldn't see a fix. I loaded a character file onto a squadron member and got this error for both the squadron member and my character. Have restarted the game and Anemnesis but am still getting the error even when only my character is in the gpose. Program no longer working. Attaching the log from when the error first occurred.
[2021-05-28-00-06-59.txt](https://github.com/imchillin/Anamnesis/files/6558174/2021-05-28-00-06-59.txt)

**Comment by Yuuki-Walsh** [comment]
looks like you somehow generated a custom skeleton for the plyer model: ` Loaded skeleton file: Data/Skeletons/Generated_0_Normal.json` Deleting this should restore normal operation.

**Comment by eijifloren** [comment]
I ended up completely removing Anamnesis. The game still crashes whenever I try to load into the character I was on when it happened. I deleted my character data, and it still crashes when I try to log in on her. Not sure what the issue is, but I can't help but think it's associated with this problem?

**Comment by Ani-ki** [comment]
The game crashes when you load a character, but you no longer have Anamnesis? This sounds like it could be an issue with a mod. Try Starting Over in Textools. If you're not using Anamnesis, then it cannot be an issue with Anamnesis.

**Comment by Ani-ki** [comment]
Have not heard back from this user in a fortnight, so can only assume this is no longer an issue.
