### ISSUE TITLE
Localization Service Error, forced application close

### ISSUE THREAD

**Issue by snailsmails** [imchillin/Anamnesis#380]
I recently downloaded the program and ran into this on opening it for the first time. 

[2021-05-30-14-36-46.txt](https://github.com/imchillin/Anamnesis/files/6566746/2021-05-30-14-36-46.txt)

**Comment by Ani-ki** [comment]
Hi there. Did you extract everything in the archive? The tool cannot be run with just the `.exe` file; it **requires** the folders in the archive.

**Comment by snailsmails** [comment]
Looks like that was the issue! Thanks so much.
