### ISSUE TITLE
Unsupported Game Version

### ISSUE THREAD

**Issue by KitsuneTales90** [imchillin/Anamnesis#382]
Every time I go to open up Anamnesis I get the error 'unsupported game version' I have grabbed the files directly from the release pages, deleted old ones etc...and continue to get this error.

I do use Norton Anti-virus but I have gone through in the exclude, dont block etc...any and all files so I am at a lose at this point

[2021-06-02-17-40-18.txt](https://github.com/imchillin/Anamnesis/files/6587786/2021-06-02-17-40-18.txt)
![image](https://user-images.githubusercontent.com/85261232/120561533-53b34600-c3ca-11eb-80cf-4e3e5119bff0.png)

**Comment by Ani-ki** [comment]
Hi there! We recently made an [announcement about this on the XIV Tools server](https://discord.com/channels/748454690118828163/748603610207748106/849613384445984788). I've copypasted it here in case you're not in the server.

> Despite the emergency maintenance earlier today, there were no changes of note to the game that would cause Anamnesis to function incorrectly. 
> That said, there was a game version update, and you'll receive a notice when you launch Anamnesis telling you about this. **Rest assured that you'll be able to hit the OK button and continue using the tool as normal**; we didn't want to inundate you with releases this week, so we'll update the game version check on our end with the next weekly build (on Sunday). We apologise for the inconvenience this may cause in the meantime, and thank you for your patience!

I highly recommend joining the XIV Tools server to keep up to date with the tool.

I'm closing this as this is a documented phenomenon with a functioning workaround.
