### ISSUE TITLE
Amanesis fails to launch while game is running

### ISSUE THREAD

**Issue by Voyan** [imchillin/Anamnesis#386]
[2021-06-05-23-44-17.txt](https://github.com/imchillin/Anamnesis/files/6603643/2021-06-05-23-44-17.txt)

**Comment by Ani-ki** [comment]
Can you confirm that you've extracted the entirety of the archive? The tool will **not** run unless all files and folders in the archive are present.

**Comment by Voyan** [comment]
How would I confirm that? A clean install, or is there something I can check?

**Comment by Ani-ki** [comment]
Delete the existing folder, then do a fresh install, and ensure you extract EVERYTHING from the archive.

**Comment by Ani-ki** [comment]
Can you please confirm whether or not a fresh install fixed your issue?

**Comment by Voyan** [comment]
So I did a fresh install, and I'm pretty sure I extracted everything? It worked Once, and then when I tried again this morning it did this
[2021-06-06-10-32-07.txt](https://github.com/imchillin/Anamnesis/files/6604419/2021-06-06-10-32-07.txt)

**Comment by Ani-ki** [comment]
Sorry, when you say 'this morning', what time zone? Us developers are Australian, so your morning might mean something else to us.

Please upload a screenshot of your folder, so I can see if anything is missing.

Additionally, have you updated to today's release?

**Comment by Voyan** [comment]
Ah, sorry! I meant literally 15 minutes ago, as I'd gone to sleep after it seemed to work. This is a screencap of the inside of the folder I downloaded before I slept, which isn't the newest update
![Screenshot_3](https://user-images.githubusercontent.com/85426365/120930558-6b811780-c6b3-11eb-879a-6e3d78fd87fa.png)

**Comment by Ani-ki** [comment]
The folders are definitely there. This could be related to an issue we were having in previous builds, but check if the latest update resolves it on your end (though just as a heads-up, we've acknowledged an issue in the current build wherein the launcher doesn't play nice with filepaths that have spaces in them, so when you extract the new version, please keep this in mind!)

**Comment by Voyan** [comment]
I think this has worked? I seem to have been missing a .net when the new installer hit me up. Thanks for the help!
