### ISSUE TITLE
Launcher Error if space in the path

### ISSUE THREAD

**Issue by Lanselotto** [imchillin/Anamnesis#389]
If there is a name with a space in the path of Anamnesis, the launcher crash
![image](https://user-images.githubusercontent.com/39704475/120926587-cb8cb380-c6dd-11eb-826a-942b9fc60a58.png)
"impossible find the file"

**Comment by Ani-ki** [comment]
Thanks for opening the ticket. It's a known issue (we found it after we'd gone to bed), and will be rectified in the next build.
