### ISSUE TITLE
Several NPC appearances load in nude

### ISSUE THREAD

**Issue by ThaddeusCleaver** [imchillin/Anamnesis#390]
A large chunk of the NPC appearances loadable via Anamnesis over Players or otherwise currently do not properly load any of their equipment or unique clothing. Exceptions largely seem to be incidental ARR NPCs with very basic equipment. Role/Job quest NPCs, Scions, Adventurer's Guild heads and many other story NPCs are affected. Another odd exception: elidibus-possessed ardbert is nude, but _does_ still get Bravura equipped to his main hand. Certain appearances can be 'fixed' if they were saved as character files in older versions, but not all. Further, they do not even load with NPC smallclothes. 

Methods tried in attempts to fix so far: un and re-installing. Deleting appdata folder. Closing and re-opening the game. Closing and re-opening Anamnesis.

**Comment by Yuuki-Walsh** [comment]
Probably introduced this with the #356 fix.
