### ISSUE TITLE
'invalid target' when attempting to teleport even after tool is closed

### ISSUE THREAD

**Issue by hhhhh00** [imchillin/Anamnesis#391]

**Comment by Ani-ki** [comment]
Hi, can you please provide more information? This is not enough to work with. The *minimum* we require is:
- the exact steps you took to trigger the issue
- how many times you encountered the issue
- the log files for the session that you experienced the issue in

**Comment by Yuuki-Walsh** [comment]
Sounds like another "getting stuck as Battle NPC" bug.
