### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by EliLightX** [imchillin/Anamnesis#392]
I always get an error when I update saying Anamnesis is not in a location blahblahblah. Then it deletes the shortcut.

**Comment by Yuuki-Walsh** [comment]
Hi, can you try downloading the update manually: https://github.com/imchillin/Anamnesis/releases/latest And see if that works?

**Comment by thechocorooms** [comment]
Hello, just here to report the same issue, I have always had to manually download updates because of this error. I have attached a screenshot of the error I get every time, if it helps any.
![UpdateExtractor_0iXS9xNsaW](https://user-images.githubusercontent.com/85652485/121765535-190b8500-cb11-11eb-8738-b25dafb13269.png)

**Comment by Ani-ki** [comment]
You might be on an older version from before we scrapped the launcher, @thechocorooms

Please do a fresh install by grabbing the [latest version from Releases](https://github.com/imchillin/Anamnesis/releases/latest).

**Comment by thechocorooms** [comment]
I have the latest release now.

The mentioned error occurs every time there is an update.

**Comment by Ani-ki** [comment]
The latest version will not ask you for an update, because it's the latest version, so there's nothing for it to update.

Can you please confirm which version you are using?

**Comment by Ani-ki** [comment]
@thechocorooms can you please confirm if updating to the latest version with the launcher removed solved this issue for you?

**Comment by thechocorooms** [comment]
Sorry for the delay! @Ani-ki Tonight's update no longer errored on me and it updated just fine.

**Comment by Ani-ki** [comment]
Glad to hear it! Sounds like it was just teething pains with the now-defunct launcher (goodnight sweet prince). Updating to the latest version removes all of that and goes back to how it was previously. I'll close this for now, but if there are any other issues, please don't hesitate to open a new one!
