### ISSUE TITLE
Code execution cannot proceed because .dll

### ISSUE THREAD

**Issue by ParadiseHK** [imchillin/Anamnesis#395]
I downloaded the latest version to fresh try and open anamnesis and the command prompt opened with no code and got these errors, unsure what to do and don't know if it's a program error or a computer error, downloaded latest versions of C++ visual and still coming up with error.
![msvcp140d dll](https://user-images.githubusercontent.com/85492170/121009119-2229e880-c7d7-11eb-9941-ad47403cdb6c.png)
![ucrtbased dll](https://user-images.githubusercontent.com/85492170/121009130-25bd6f80-c7d7-11eb-8d61-3386e12a8d5d.png)
![vcruntime140d dll](https://user-images.githubusercontent.com/85492170/121009139-2950f680-c7d7-11eb-8c52-c91c5631d23b.png)

**Comment by ParadiseHK** [comment]
I'll add node that the program was working fine before now even with it wanting an update to the program

**Comment by kotmon** [comment]
I had the same issues so I downloaded the .dll files on the internet, but now I have an error, code is 0xc000007b. I already tried to reinstall.

**Comment by ParadiseHK** [comment]
im gonna see about downloading those files then and see how the app works

**Comment by TheCampingOwl** [comment]
The problem is only with the launcher, if you launch the .exe directly from the Bin folder, it works fine. Not sure why it happens considering they are all installed, at least for me. But the tool is still usable.

**Comment by ParadiseHK** [comment]
Okay downloading those specific files did fix the launcher fortunately, so i guess i'll close this issue now, for anyone that see's this and has this issue before they fix it go to a .dll website and download the 32x and 64x versions of the files that show up as missing and follow the instructions on the website!
