### ISSUE TITLE
Multiple errors on trying to run the tool after it tried to update automatically 

### ISSUE THREAD

**Issue by Ferretdragon** [imchillin/Anamnesis#396]
![errors](https://user-images.githubusercontent.com/85493129/121009316-ecabdd80-c78b-11eb-9c28-14eda5013373.png)

**Comment by UVFrost** [comment]
Same issues. Reinstalling did not fix the issue, and the same errors are given.

**Comment by TheCampingOwl** [comment]
The problem is only with the launcher, if you launch the .exe directly from the Bin folder, it works fine. Not sure why it happens considering they are all installed, at least for me. But the tool is still usable.

**Comment by Atori-ffxiv** [comment]
> The problem is only with the launcher, if you launch the .exe directly from the Bin folder, it works fine. Not sure why it happens considering they are all installed, at least for me. But the tool is still usable.

I had the same problem using the launcher. I did what was mentioned above, went into the bin folder, and used the .exe directly, and it seems to be working for me as well.

**Comment by Yuuki-Walsh** [comment]
We've decided to just remove the launcher to avoid these problems, latest release should launch straight into Anamnesis instead.
