### ISSUE TITLE
View or edit Character height as a measurement

### ISSUE THREAD

**Issue by g-o-o-f** [imchillin/Anamnesis#397]
Not entirely sure where to start off with this but...

Sometimes situations occur where people want to take a screenshot, or some, of their character who, regardless of race or gender, happens to be either taller or shorter than what the default height slider for their specific race/gender allowed for and it feels sort of "meh" knowing your character's actual height won't be visualised.

This situation can to some degree be remedied by using the "Height" slider found in Anamnesis' "Character → Model" tab. 
Alas, it isn't exactly accurate and it can be a pain to get a character's specific height right by just eyeballing so I thought: 
_"Why not suggest the addition of a 'Character → Custom Height' section underneath or within the 'Character → Model' section—or wherever else the devs would like to put it—where a person can specify the actual height of their character in either cm, inches or feet+inches and their character scales up/down accordingly?"_

I imagine the interface would possibly be something along the lines of:
- **Measurement** - Dropdown with the option to select: _Centimetres_ | _Inches_ | _Feet+Inches_
- **Height** - An empty field where you write the character's height based on the chosen measurement.
  - Unsure if Feet+Inches should have one field for Feet and a second for Inches to prevent going over 12 inches per foot.
    - 5'12" is the same as 6' and 6'0" and 5'13" is just a weird way to say 6'1", maybe good for trolling people on Tinder?
  - Uses the selected actor's current "Character → Appearance → Race/Gender" as reference for the equation. 
  Probably obvious...
- Uh, I guess press enter and it will adjust your "Characer → Model → Height" according to internal math (more on that below).
- Would be extremely useful if a person could click a button to bring up information about either the current race or just a huge table with all the min/average/max (0%/50%/100%) height values of every race and gender to use as a reference sheet. 
I'd offer to do this but I have no idea how I'd accomplish it for Anamnesis specifically. Let me know if there's something I can do.
- Should perhaps include a note at the bottom or somewhere saying:
  - _Note that these values are **race and gender** specific. 
  This means you cannot use the same model height value for a feminine Miqo'te and a feminine Hyur Midlander and then expect them to be the same height.
  Only exceptions are male and female lalafells who have the same height values as each other._

Though I'm sure the actual devs know best how to fit it in should it come to it.

I'm aware this is no simple addition with little work required, so that's why I decided to take it upon myself to do a big chunk of the work in hopes of helping to reduce the workload for the Anamnesis devs, by gathering all the necessary character model data and formatting the required math calculations.

I've never made a spreadsheet before so pardon me if it looks like unintelligible garbage. 
[Spreadsheet with many number and much math and stuff](https://docs.google.com/spreadsheets/d/13RgGI6Hv6rpzpvUxjuo3jFuVYVxibzbQQVYJI8MdS_s/edit#gid=0)
Either way it should contain everything that is required for calculating precise character model scales regardless of race/gender/height slider/desired height/unit of measurement.
I'm no maths expert, I just love numbers, so I might've missed something. But I've tested it out a lot in-game with other players and NPCs and everything's perfect from what I've gathered.
I wish I knew coding, would help me make sure it's all compatible, but yea I'm happy to answer any questions.

1. I will update it with male Viera and female Hrothgar information once I know their model height and scale values. 
2. Personally I'll still use it should it turn out to be too much trouble—or too useless—to add as a feature to Anamnesis, in which case, no worries at all. 
3. I appreciate all the effort that has been and continues to be put into this project. Thamnk u 👍

**Comment by Yuuki-Walsh** [comment]
We used to display the character height as a value, but with the addition of racial scaling mods in TexTools we removed it. We may need to check how the racial scaling mods affect height to be sure (do they just affect overall scale, a bone scale, or something we cant see?)

Otherwise this looks sound.
