### ISSUE TITLE
Invalid actor model pointer

### ISSUE THREAD

**Issue by LyriaG** [imchillin/Anamnesis#399]
Edited by @Yuuki-Walsh:

We have added a better UI for this state to prevent confusion:
![No Model Error](https://cdn.discordapp.com/attachments/833882377964355614/855636771358244884/now_the_bones_are_just_gone_completely.png)

> I start the program as administrator and disable!! my complete av programm and firewall:
> 
> ![08-06-_2021_11-21-14](https://user-images.githubusercontent.com/85554143/121163806-6062ee80-c84f-11eb-88c3-6ed09214fe8a.png)
> ![08-06-_2021_11-22-14](https://user-images.githubusercontent.com/85554143/121163830-65c03900-c84f-11eb-89cd-ab308abe3c73.png)
> ![08-06-_2021_11-22-58](https://user-images.githubusercontent.com/85554143/121163845-6a84ed00-c84f-11eb-8c15-df1f60e19a58.png)
> Loading a pose:
> ![08-06-_2021_11-25-03](https://user-images.githubusercontent.com/85554143/121164093-9ef8a900-c84f-11eb-8190-b2fdb2ad5b68.png)
> ![08-06-_2021_11-25-22](https://user-images.githubusercontent.com/85554143/121164141-a9b33e00-c84f-11eb-8bf6-f2d55dd53a9d.png)
> ![08-06-_2021_11-25-34](https://user-images.githubusercontent.com/85554143/121164165-afa91f00-c84f-11eb-98f9-2b3a962d48a3.png)
> 
> 
> 
> I can only hit the titel in the pose column. change race and equipment is working. nothing else

**Comment by Ani-ki** [comment]
Can you please upload your latest log file?

**Comment by LyriaG** [comment]
where can i find them ?

**Comment by LyriaG** [comment]
got it^^

[2021-06-08-11-18-39.txt](https://github.com/imchillin/Anamnesis/files/6615478/2021-06-08-11-18-39.txt)

**Comment by LyriaG** [comment]
this time i made a complete clean install. also clean registration and all files on my pc. nothing changes

**Comment by Yuuki-Walsh** [comment]
Looks like its failing to find your character model (`Exception: Actor has no model`). This is an issue we only saw previosly on Windows 7 computers due to differnet memory layouts.

What operating system are you using?

**Comment by LyriaG** [comment]
i use Win 10. And yes, i did the rightclick and select allow on the package ;)

[Sysinfo.txt](https://github.com/imchillin/Anamnesis/files/6617741/Sysinfo.txt)
Maybe this may helps. A complete System Information

**Comment by Yuuki-Walsh** [comment]
hmm no clues there, everything looks fine. No idea why the model pointer is invalid for you. We'll need to keep investigating.

**Comment by ennoevlys** [comment]
Hi, having a similar issue! It occurred while moving characters pretty far from their original locations and then trying to toggle back after moving the camera to be able to see the models better. I even tried using an Xbox controller (since the D-pad can be used to toggle through visible characters) and it doesn't detect anything.

**Comment by ennoevlys** [comment]
[2021-06-28-23-44-35.txt](https://github.com/imchillin/Anamnesis/files/6731635/2021-06-28-23-44-35.txt)
Here's my log; it wouldn't upload in my last comment. Running Windows 10 as well.

**Comment by Ani-ki** [comment]
@ennoevlys 
> 
> [2021-06-28-23-44-35.txt](https://github.com/imchillin/Anamnesis/files/6731635/2021-06-28-23-44-35.txt)
> Here's my log; it wouldn't upload in my last comment. Running Windows 10 as well.

> `2021-06-28 23:44:35.253 -07:00 [INF] Framework: .NET 5.0.2`

You appear to be running the incorrect version of .NET. Please update to 5.0.7 using the links provided in the Wiki, or on the main repo page.

**Comment by ennoevlys** [comment]
I updated it, but it seems to still be doing it.
[2021-06-29-01-05-34.txt](https://github.com/imchillin/Anamnesis/files/6732382/2021-06-29-01-05-34.txt)

**Comment by LyriaG** [comment]
IDK whats going on, but after a clean new installation of Windows Anamnesis works fine ... :O
