### ISSUE TITLE
Startup issue 

### ISSUE THREAD

**Issue by Violetgenesis** [imchillin/Anamnesis#402]
Been having this issue since I updated. 
Critical Error: Localization service error- could not find part of the path 'C:\users\allyb\desktop\languages'

have tried reinstalling but still gives me the same error

**Comment by Ani-ki** [comment]
Just to check, when you reinstall, have you ensured that *everything* is extracted?

**Comment by Violetgenesis** [comment]
ahhhh im dumb tyyy ^^
