### ISSUE TITLE
Remember Equipment Scroll Bar Position

### ISSUE THREAD

**Issue by TheH1ddenSushi** [imchillin/Anamnesis#403]
Inconvenient when browsing equipment options and choosing to dye them, and then deciding to search for another piece instead and having to find where you left off.

![AmnesisScroll2](https://user-images.githubusercontent.com/85421437/121764546-96c39680-caf9-11eb-8047-a1db908b86bb.png)

**Comment by Ani-ki** [comment]
Thanks for ticketing this. We'll be taking it on board shortly.
