### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by keikun393** [imchillin/Anamnesis#405]
I just downloaded Anamnesis and had .NET on my system before now. I run the program as admin told it to yes run and it keeps saying i must install .NET. Would you like the download it now? Even tho i have the lastest version. Even tried uninstalling it and trying the older version of 5.0.0 like it kept saying and still same thing.

**Comment by Ani-ki** [comment]
We've just added a bit in the wiki about this: [https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#the-tool-asks-you-to-install-net-despite-net-50x-being-installed](Troubleshooting/The tool asks you to install .NET despite .NET 5.0.x being installed). Can you please check which version it says you have?

**Comment by keikun393** [comment]
i have version 5.0.7 its not blocked in my firewall nor virus scanner, and i did try launching it while 14 was running with the same thing

**Comment by Ani-ki** [comment]
Just to confirm, when you follow the instructions I linked you to, it says this:

```Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964```

Is that correct?

**Comment by keikun393** [comment]
yes that is correct

**Comment by Ani-ki** [comment]
And can you please confirm which version you installed, x86 or x64?

**Comment by keikun393** [comment]
x86

**Comment by Ani-ki** [comment]
Righto, can I get you to install the x64 version, please?

**Comment by keikun393** [comment]
"To run this application, you must install .NET.

The framework 'Mircrosoft.WindowsDesktop.App', Version '5.0.0' was not found.

Would you like to download it now?"

This pops up now with the x64 installed

**Comment by Ani-ki** [comment]
Just to make absolutely sure that this isn't an issue on our end, can you run that cmd step again to ensure it was installed properly? There's been issues with 5.0.x versions of .NET not installing correctly, which is unfortunately out of our hands. Make sure you uninstall that x86 version as well.

**Comment by keikun393** [comment]
it shows that it is install correctly and the other is uninstalled i will try a computer restart and see if that works

**Comment by keikun393** [comment]
it appears i didn't install the "right" .net... i was installing the "Run console apps" not the "Run desktop apps" one now that I have it installed it "magically" started working! sorry for all the trouble on this and thanks ♥

**Comment by Ani-ki** [comment]
No worries! Microsoft is really bad about this; we used to have a direct link to the exact version of .NET we used, then Microsoft changed how their website displays things, so it became invalid. We're toying with the idea of packaging .NET with the tool itself as part of a fully self-contained exe file, but eeeeh we don't know how comfortable people will be with downloading a ~60MB exe file.
