### ISSUE TITLE
LocalizationService Error

### ISSUE THREAD

**Issue by Aurelstar** [imchillin/Anamnesis#408]
Installed Anamnesis, reset PC after installing Windows Runtime, extracted Anamnesis to where I wanted it. When trying to run it, it keeps giving me this LocalizationService Error, saying Directory not found, etc.

[Error Issue](https://gyazo.com/dd6cf834ec7ae9301d224308ffb46f35)

**Comment by Ani-ki** [comment]
Have you ensured that EVERYTHING from the archive was extrracted?

**Comment by Ani-ki** [comment]
@Aurelstar as this is considered user error, please reinstall the tool, and ensure you follow the **[installation instructions](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#installation)** in full.
