### ISSUE TITLE
failed to start application

### ISSUE THREAD

**Issue by Starlettefire** [imchillin/Anamnesis#411]
Everytime i tried opening Anamnesis i got this error message so i deleted anamnesis and downloaded the latest version. Days prior to having thing problem when i would open Anamnesis the update window would pop up every single time and i updated it several times but it still kept popping up. Please help i dont know what else to do!`

[2021-06-16-19-58-08.txt](https://github.com/imchillin/Anamnesis/files/6666441/2021-06-16-19-58-08.txt)

**Comment by Ani-ki** [comment]
Please update to the latest version of NET Desktop Runtime v5.0.7 x64.

**Comment by Russetplay** [comment]
Having the same issue with the same symptoms of the program wanting to update every time I opened it. After making sure that the latest version of NET Desktop Runtime v5.0.7 x64 was running, I tried again and Anamnesis still refuses to open. The log says that it could not fine a specified file.

**Comment by Ani-ki** [comment]
Can you please upload your log here? You can just drag it into the textbox.

**Comment by Russetplay** [comment]
[2021-06-16-22-54-41.txt](https://github.com/imchillin/Anamnesis/files/6667257/2021-06-16-22-54-41.txt)

**Comment by Ani-ki** [comment]
@Russetplay you've not extracted the archive per the **[installation instructions](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#installation)**:
![image](https://user-images.githubusercontent.com/56663405/122329386-acf7a980-cf74-11eb-9301-259cfbf78a64.png)

Additionally, you do not appear to have 5.0.7 installed
![image](https://user-images.githubusercontent.com/56663405/122329427-bf71e300-cf74-11eb-9377-e6223c67ed29.png)

**Comment by Russetplay** [comment]
I fixed both those issues and it is now giving me an error that says only Windows 10 is supported. And I am on Windows 10

![7823e60dc26d294db02a2d05680d2f42](https://user-images.githubusercontent.com/86035746/122330819-716bc980-cef9-11eb-85e7-7f28d09e9f67.png)

**Comment by Ani-ki** [comment]
Can we have the newest log file, please? Screenshots of error messages do not suffice reporting issues.

**Comment by Russetplay** [comment]
[2021-06-17-00-46-39.txt](https://github.com/imchillin/Anamnesis/files/6667679/2021-06-17-00-46-39.txt)
 My apologies, here is the log

**Comment by Ani-ki** [comment]
Are you running it in compatibility mode by any chance? Your first log does very clearly say you're running Windows 10, but the second one is suggesting it's now Windows 8.

![image](https://user-images.githubusercontent.com/56663405/122338960-c7854f00-cf83-11eb-97b8-098560358114.png)

**Comment by Russetplay** [comment]
I don't know how compatibility mode turned on, but turning it off worked! Thank you so much for your time <3

**Comment by Ani-ki** [comment]
No worries! Glad we got to the bottom of it!

**Comment by Ani-ki** [comment]
@Starlettefire can you please confirm if updating to the correct version of .NET fixed your issue?

**Comment by Ani-ki** [comment]
Closing because it's been three days and we've not heard from OP. The solution is in the comments here, if they decide to check up on this.
