### ISSUE TITLE
Failed to Start Application

### ISSUE THREAD

**Issue by SaberRadioProducts** [imchillin/Anamnesis#413]
Hello, Im getting a critical error when trying to boot my Anamnesis up. I was wondering why the issue was happening. I dont have compadability mode on and I tried uninstalling and reinstalling the program. But it doesnt seem to work.
[2021-06-17-19-13-56.txt](https://github.com/imchillin/Anamnesis/files/6674191/2021-06-17-19-13-56.txt)

**Comment by Ani-ki** [comment]
Hi there. Can you please ensure you've installed the correct version of .NET? According to your log file, you're running 5.0.6 when the tool requires 5.0.7.

**Comment by SaberRadioProducts** [comment]
That worked, Thank you so much

**Comment by Ani-ki** [comment]
All good!
