### ISSUE TITLE
Anamnesis says FFXIV isn't running, but it does.

### ISSUE THREAD

**Issue by Darius0013** [imchillin/Anamnesis#414]
Have this problem for a few hours now, I restarted my computere multiple times, but anamnesis still says that FFXIV isn't running even tho it does.

**Comment by Yuuki-Walsh** [comment]
are you running the dx11 version of ffxiv?

**Comment by Darius0013** [comment]
yep and I already did the trouble shooting, everything worked till around 3pm yesterday

**Comment by Ani-ki** [comment]
If Anamnesis is opening far enough to tell you it can't find the instance, then it's at least at a point where it's generating logs. Can you please throw you latest log file in here @Darius0013?

**Comment by Ani-ki** [comment]
@Darius0013 can you please upload your latest log file, or advise if updating to the newest version has resolved your issue?

**Comment by Ani-ki** [comment]
It has been a week since we last heard from you, so we're going to assume things are working on your end and close this issue. Please reach out to us again if you're still having issues.
