### ISSUE TITLE
Editing character positions while mounted

### ISSUE THREAD

**Issue by SnappyMaru** [imchillin/Anamnesis#415]
Character positions seem to be locked to mounts while mounted, in /gpose we are allowed to select mounts but Anamnesis doesn't seem to have the function yet. CMTool used to have the target mode which worked on mounts.

**Comment by Ani-ki** [comment]
Target mode is not being implemented in Anamnesis due to abuse. Using two actors will achieve the effect you're after.

As a general reminder, Anamnesis =/= CMTool; features in one cannot simply be added to the other.
