### ISSUE TITLE
Feature Request: Save camera settings and Entity Position/Rotation

### ISSUE THREAD

**Issue by Agent-KI7KO** [imchillin/Anamnesis#417]
Thanks for the lovely software!

Would like to request ability to save Camera settings and Entity (Character) Position/Rotation within the current zone. It is a useful feature of CMTools for changing equipment in between gposes. =)

**Comment by Ani-ki** [comment]
You're after Scenes, which is still being worked on. See: #51 
Locking this one since this is already on the project board.
