### ISSUE TITLE
Failed to start application

### ISSUE THREAD

**Issue by Felousia** [imchillin/Anamnesis#418]
same problem as another person had but it seems they didnt respond and the issue was closed. but im having the same issue. i did try deleting and redownloading, checking for compatibility mode, updating .net, updating windows, resetting pc, and none of the above have changed the issue. might be doing something wrong somewhere but as of yet im stumped

[2021-06-21-03-35-38.txt](https://github.com/imchillin/Anamnesis/files/6684923/2021-06-21-03-35-38.txt)

**Comment by Ani-ki** [comment]
According to your log, you're not using the correct version of .NET. 
![image](https://user-images.githubusercontent.com/56663405/122726895-cd4b9f00-d2b9-11eb-8226-b5e07e4bfa30.png)

**Comment by Felousia** [comment]
kinda strange cause i saw that and updated and it didnt seem to change but fortunately, new info i deleted it all again, reloaded .ne once more then redownloaded nemesis and now it indeed works. not sure why not the first time but hey im not complaining i love this tool ^,^  but all is solved

**Comment by Felousia** [comment]
also very big thank you for quick response its was much appreciated <3

**Comment by Ani-ki** [comment]
All good! Yeah, we don't know why, but Microsoft really dropped the ball with their recent update. Hopefully .NET 6 isn't this troublesome, because it's a PITA for everyone to have to reinstall stuff to get it to work :/
