### ISSUE TITLE
Version update required

### ISSUE THREAD

**Issue by Drudicta** [imchillin/Anamnesis#420]
Here is my log file. Thank you.
[2021-06-22-10-52-57.zip](https://github.com/imchillin/Anamnesis/files/6696106/2021-06-22-10-52-57.zip)

**Comment by Roni-Ops6** [comment]
I have the same Problem.

**Comment by Ani-ki** [comment]
The tool will be updated when we have time. The error message tells you as such. Please be patient in future, and refrain from opening superfluous tickets.
