### ISSUE TITLE
Anamnesis Exe File not working

### ISSUE THREAD

**Issue by DavidDallas** [imchillin/Anamnesis#421]
I can't tell if this is due to the update or not, so I'm very sorry if it is. 

Whenever I try to access the program via the exe button, I double click and nothing happens, this is on the latest release. However, when I revert back an update, it works no problem but the program doesn't recognize me as being logged in while within the program.

It randomly flickers between being logged in and not, the weather adjustment tab flickers also.

I thought this might just be due to the last ffxiv update, but my friend is having no trouble on their version so I'm wondering if there is another issue I am not seeing.

Thank you

**Comment by Ani-ki** [comment]
The tool will be updated when we have time. The error message tells you as such. Please wait for an update.
