### ISSUE TITLE
Chinese client support

### ISSUE THREAD

**Issue by assXweXcan** [imchillin/Anamnesis#424]
as logs see how
how can i use it on chinese version
[2021-06-23-18-40-51.txt](https://github.com/imchillin/Anamnesis/files/6701267/2021-06-23-18-40-51.txt)

**Comment by Ani-ki** [comment]
Hi there. Unfortunately, we do not yet have support for the Chinese version ([outlined in the Basic Setup page on our wiki](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#downloading)), as neither of us have access to the Chinese client. We do not have an estimate as to when Chinese client support will be added.

We apologise for this inconvenience.

**Comment by assXweXcan** [comment]
ok thanks
