### ISSUE TITLE
NPC Model Defaults When Used on Ingame Friend in gpose

### ISSUE THREAD

**Issue by xivbwryy** [imchillin/Anamnesis#428]
I was in Anemnesis testing the tool having downloaded it yesterday. I had a friend in party that I was taking gposes with, and would change them into different NPCs. I noticed that when I entered gpose the NPC would revert to a default appearance instead of looking like the intended NPC. This only occurred when the individual was on my friends list or in my party. If they were neither, the NPC would keep their appearance in gpose. No issue occurs when using saved models of my friend's Warrior of Light, regardless if the player was on my friend's list or not. Attached is an image of me, a player on my friend's list, and a player not on my friend's list before and after entering gpose. Unsure if this is an error?

![image](https://user-images.githubusercontent.com/86509914/123504186-be504e00-d625-11eb-816d-dc3a90645cbb.png)
![image](https://user-images.githubusercontent.com/86509914/123504191-c4462f00-d625-11eb-8d61-15599340cecd.png)

**Comment by Ani-ki** [comment]
Hi there. Sorry for the delay getting back to you on this.

This is unfortunately something we've not yet found a workaround for, and as such we suggest users load NPC appearances onto themselves, and their own appearance onto other entities like Carbuncles.

We apologise for this inconvenience. I'll be closing this ticket as this is a known game limitation.
