### ISSUE TITLE
Failed to start application

### ISSUE THREAD

**Issue by qtia** [imchillin/Anamnesis#429]
Ever since I updated Anamnesis, it continues to run into a critical error upon trying to start up the application and it force closes. I have downloaded the latest .NET and I'm not sure what I'm doing wrong. Prior to the update I could open it and it worked no problem.
[2021-06-27-00-27-30.txt](https://github.com/imchillin/Anamnesis/files/6721197/2021-06-27-00-27-30.txt)

**Comment by Ani-ki** [comment]
`2021-06-27 00:27:30.931 -07:00 [INF] Check Working Directory: "C:\Users\Ashtyn\AppData\Local\Temp\Rar$EXa6016.17596"
2021-06-27 00:27:30.931 -07:00 [WRN] Failed to start application
System.Exception: Attempt to run from temporary directory. (Are you running Anamneis from a zip file?)`

Please make sure you extract the archive before running.

**Comment by qtia** [comment]
I've tried to extract it to a few different locations and none of them seem to work for me, saying it cannot find a path. I might just be overlooking something, I'm REALLY not tech savvy so I'm sorry if this is a blindingly obvious fix that I'm just missing

**Comment by qtia** [comment]
I seem to have accidentally fixed it somehow-- sorry for the trouble and thank you for your time!
