### ISSUE TITLE
NPcs with wrong gear and gear color

### ISSUE THREAD

**Issue by unknownuserxv** [imchillin/Anamnesis#431]
Some npcs have different gearsets dyed a certain color, on changing actor the color and gear does not change to the right one, example Francel, only one gear wrong color all models, Keeper of the Entwined Serpents, both Hyur and Elezen, completely different gearset never worn by the npcs however this case repeats on cmt.

**Comment by Ani-ki** [comment]
This seems to happen a lot with Estinien, whose hair turns blue when loaded. Need to look into this more.
