### ISSUE TITLE
Crash due to not being able to set time

### ISSUE THREAD

**Issue by yuyuisyuyu** [imchillin/Anamnesis#432]
Crash due to not being able to set time.

Had time frozen and crashed when I clicked to apply Ocho Green dye to my gloves and ad been clicking every few seconds on one dye or another.

Had previously been in gpose and applying equipment to myself using Anamnesis and also installed several mods with penumbra and refreshed actors with its function.

[2021-06-28-02-41-34.txt](https://github.com/imchillin/Anamnesis/files/6724956/2021-06-28-02-41-34.txt)

**Comment by Ani-ki** [comment]
Sorry for the delay. XIV crashed as well, correct?

**Comment by yuyuisyuyu** [comment]
Yes, FFXIV crashed, I'm trying to remember but I can't recall if Ana also did. I peeked at the log and it doesn't appear so but i'm not sure.
