### ISSUE TITLE
Failed to get file information

### ISSUE THREAD

**Issue by Yasue-Jin** [imchillin/Anamnesis#433]
Just opened the tab for changing appearance to save a character's appearance.  As soon as I clicked on the tab... Error.  Failed to get file information.
[2021-06-29-01-52-49.txt](https://github.com/imchillin/Anamnesis/files/6732034/2021-06-29-01-52-49.txt)

**Comment by Ani-ki** [comment]
> `2021-06-29 01:52:49.279 -07:00 [INF] Framework: .NET 5.0.6`

You appear to be running the incorrect version of .NET. Please update to 5.0.7 using the links provided in the Wiki, or on the main repo page.

**Comment by Yasue-Jin** [comment]
Thanks!  I'll fix it now!

**Comment by Yasue-Jin** [comment]
Fixed!
