### ISSUE TITLE
Unsupported Game Version with latest Ana Update

### ISSUE THREAD

**Issue by Maroonedontuesday** [imchillin/Anamnesis#435]
![image](https://user-images.githubusercontent.com/86805399/124189058-22dc3480-da8e-11eb-914b-f1b39475fd59.png)
![image](https://user-images.githubusercontent.com/86805399/124189194-5dde6800-da8e-11eb-8317-61a7eb985dbd.png) 
![image](https://user-images.githubusercontent.com/86805399/124189410-a8f87b00-da8e-11eb-9144-4efb949e7567.png)
![image](https://user-images.githubusercontent.com/86805399/124189515-d6ddbf80-da8e-11eb-87db-e27ab210bc08.png)

I am encountering the above error every time I launch Ana, which is sometimes stable and sometimes not. I have had to manually download the update as the updater within errors out. I have a feeling it's me not having the most up to date Ana despite downloading manually, but I'm not sure.

**Comment by Ani-ki** [comment]
Can you please upload your latest log file?

**Comment by Maroonedontuesday** [comment]
Just uploaded via the discord! :)

**Comment by Ani-ki** [comment]
Sorry for the delay on this one. Your log says you're running an outdated version of the tool, which is evident by the older updater in your third screenshot. **[Please manually update to the latest version](https://github.com/imchillin/Anamnesis/releases/latest)**.

(Also in future, if you open a ticket here, it's best to upload your log files here as well by dragging them into the text box, as bouncing between different mediums is something we want to avoid.)
