### ISSUE TITLE
Anamnesis Creating duplicate folders when moved and resetting file settings changes

### ISSUE THREAD

**Issue by Allora02** [imchillin/Anamnesis#436]
After moving the default Anamnesis folder inside another folder and launching, the program creates a second Anamnesis folder with the data folder inside onto the old location. 
When moving the default folder, it also causes the program to wipe back to file setting defaults, or back to the data folder inside the default Anamnesis folder, instead of the folders manually selected. 
This happens despite the folders all being on the same drive.

**Comment by Ani-ki** [comment]
I know this was discussed somewhat in Discord, but can you please provide a detailed list of steps to replicate this issue here? I'm not entirely sure what is going on, so I need to know *exactly* what you're doing, from fresh install, to get this issue.

**Comment by Allora02** [comment]
the steps i took were:

- Creating a new folder in the same drive with the base anamnesis folder from github download

- Dragging and dropping base anamnesis folder into new folder

- opening anamnesis while game is running, and manually changing default folder locations to new data path within the new folder (of which the base anamnesis folder is now a subfolder) 

- clicking button to load character data

- seeing that anamnesis has determined the set folder is empty

- checking the folder within the windows file explorer

- noticing that alongside the new folder that has the original inside, a new folder has been created also titled "anamnesis" and has a new "character" folder created inside, which is empty

- checking the file directory settings in anamnesis again, and seeing that the file path was changed to the empty newly created folder

At this point, i have not attempted to delete the new folder it created, because i am concerned it will once again create the folder and try to pull from it. however, resetting the filepath after it created this folder has seemed to solve the issue for now, but it is a concern that the program will continue to re-make the folder and default to it. this was all attempted a few days after an auto-update.

**Comment by Ani-ki** [comment]
Cheers for that. I'll see if I can replicate it after work.

**Comment by Ani-ki** [comment]
Popping this here because I have a hunch about file paths that could be the root of both issues. Uploaded on behalf of Discord user camillee.
[2021-07-30-15-48-38.txt](https://github.com/imchillin/Anamnesis/files/6905960/2021-07-30-15-48-38.txt)
