### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by bocochocolina** [imchillin/Anamnesis#440]
I've got Anamnesis updated and everything, but I'm getting a message upon opening that reads "Critical Error. Anamnesis was unable to recover from this error and must close. Failed to scan memory for text signature." What can I do to fix that?

Thanks!

![image](https://user-images.githubusercontent.com/87144724/124965643-35e38d00-dfd7-11eb-81d8-895c338325c9.png)

**Comment by damphands** [comment]
Can you please upload your latest log file, either to here or the Discord?

**Comment by Ani-ki** [comment]
@bocochocolina can you please upload your latest log file here? Else I will have to close this issue.

You can upload logs directly by dragging them into the text box.

**Comment by bocochocolina** [comment]
[2021-07-14-10-47-32.txt](https://github.com/imchillin/Anamnesis/files/6818042/2021-07-14-10-47-32.txt)

There you go! Sorry, I was out of town. @Ani-ki

**Comment by bocochocolina** [comment]
[2021-07-14-10-47-32.txt](https://github.com/imchillin/Anamnesis/files/6818042/2021-07-14-10-47-32.txt)

There you go! Sorry, I was out of town. @Ani-ki

**Comment by Ani-ki** [comment]
Hi @bocochocolina, can I get you to install the correct version of the NET. Desktop Runtime, as outlined in [the main repo page](https://github.com/imchillin/Anamnesis#prerequisites) and [in the wiki](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#prerequisites)?

**Comment by bocochocolina** [comment]
Works now! Thanks!
