### ISSUE TITLE
Freeze position/rotation

### ISSUE THREAD

**Issue by SnappyMaru** [imchillin/Anamnesis#443]
Unfreeze characters in gpose returns characters to the original position, can we freeze it somehow?

**Comment by Ani-ki** [comment]
Can you please provide more information? Reported issues should be as detailes as possible, [**as per the wiki**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here).

**Comment by SnappyMaru** [comment]
For example, I was taking a screenshot for a spell, then changed my character's location, but some of the particles didn't follow so I decided to resume animation in gpose to redo the spell, but it returned my character to the original spot instead of where I moved him to.

**Comment by Ani-ki** [comment]
Unfortunately, once you disable posing in Anamnesis to resume an animation, any changes you make will be undone, and this is something we are not able to work around at this stage.
