### ISSUE TITLE
Insight on "Item sort" drop down wigout

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#444]
Referring over to my log, (https://discord.com/channels/748454690118828163/834265007066841129/863651168605700116)
Closing out the game and tool did nothing, but on a restart, fixed the issue. What I believe started it all off was earlier in the day, had 2 instances of the game open while messing with Bard Music Player. Perhaps artifacts from that remained even when the processes were closed?

**Comment by Ani-ki** [comment]
While there's nothing in the log to suggest it (time to add more logging!) given Bard Player reads KB/M inputs, that might be interfering. Although you say BMP was closed at the time? I'll do some testing with BMP shortly, see if I can't replicate it.
