### ISSUE TITLE
Minion -> Player, Doesn't work as intended

### ISSUE THREAD

**Issue by SkyAphid** [imchillin/Anamnesis#445]
If you spawn a minion, and then convert it into a player from the menu, when you enter gpose, the newly created character converted back into a minion. To reproduce:

-Spawn Minion
-Select the minion in Anamnesis
-Right click, convert to player
-/gpose in FF14

The character will revert back into a minion, making it unusable. This issues has been in anamnesis since I started using it months ago, so I'm surprised there's no issue for it on here. Perhaps I'm using this function incorrectly? I've tried converting it to a player from within gpose, but of course this doesn't work. Additionally, this usually just crashes the game entirely. So at the moment, it's not possible to pose more than one character with anamnesis, at least for me, without having other players in the zone.

**Comment by damphands** [comment]
As per the Anamnesis Wiki https://github.com/imchillin/Anamnesis/wiki/Using-Other-Entities-as-Extra-Actors

Minions

Minion entities cannot be turned into editable NPCs at this time, and attempts to change them as such may result in unwanted effects including but not limited to Anamnesis not working, or the Final Fantasy XIV process crashing.
