### ISSUE TITLE
Zip File Corrupted?

### ISSUE THREAD

**Issue by Dracornin** [imchillin/Anamnesis#451]
My version of anamnesis will not trigger the update on its own, and for some reason doesn't "log in" when launched - i downloaded the latest release, however, the zip file will NOT unzip. I get the following error: 
![unknown](https://user-images.githubusercontent.com/87621071/126082873-98fc3d83-8953-4f56-8813-8411e39f0547.png)
[2021-07-18-16-29-47.txt](https://github.com/imchillin/Anamnesis/files/6836989/2021-07-18-16-29-47.txt)

**Comment by Dracornin** [comment]
I've tried it with my antivirus completely disabled, i've tried unblocking it... nothing seems to work, the zip file itself refuses to decompress.

**Comment by Ani-ki** [comment]
That issue is a Windows permissions issue. Where are you extracting the file to?

**Comment by Ani-ki** [comment]
@Dracornin It has been 11 days since you opened this ticket. Please advise if you're still having this issue.

**Comment by Ani-ki** [comment]
It's been two weeks since this was opened so we're assuming you solved whatever Windows issue you were having and closing this ticket.
