### ISSUE TITLE
Equipment selector fails to filter items under some circumstances

### ISSUE THREAD

**Issue by LunaScar** [imchillin/Anamnesis#455]
![Capture](https://user-images.githubusercontent.com/87738640/126411882-975e35ff-818e-4e15-b343-f38f7f256d96.JPG)

I click on the chest piece icon to, of course, browse and change equipment models, and this error report comes up in about 4 smaller windows including the main window and freezes the application. FFXIV still runs though, didn't crash the game.

**Comment by Yuuki-Walsh** [comment]
Can you upload a log file for when this happens?

**Comment by Yuuki-Walsh** [comment]
This looks like the error might be a concurrent access issue in lumina's item database.

**Comment by LunaScar** [comment]
I was going to grab a log this morning for you, but it seems like the issue has resolved itself for now. If it happens again with any critical issues I'll be sure to post again and with a log. For now it seems to be working fine though, thank you!
