### ISSUE TITLE
Add option to override system theme for light mode and highlight colors

### ISSUE THREAD

**Issue by AryaFFXIV** [imchillin/Anamnesis#459]
There is no way to change it, but Anamnesis boots up in an inverted color mode, which makes it exceedingly difficult to work with after the most recent update.

**Comment by AryaFFXIV** [comment]
![Plshelp](https://user-images.githubusercontent.com/87787550/126573344-062ccd85-7d69-411e-8788-917af6ba8b9a.PNG)

Here is how it looks to me

**Comment by Ani-ki** [comment]
Hi there. This is due to the latest update that introduces Windows 11 support; this was announced in our Discord server:

> **Windows 11 Support for Anamnesis**
> The latest version now incorporates support for Windows 11. Because of this, a few changes have had to be made to how accent colours are used in the tool, so we've made the decision to default to your Windows theme colour, including light/dark. We will investigate re-adding the ability to change colours specifically in Anamnesis in the near future once we're satisfied that full Windows 11 support has been added. Until then, If you're using a custom colour in Windows 10, you may have issues with visibility (as you would in other apps anyway), so it's recommended you choose a preset Accent colour in your Windows Personalisation settings for maximum compatibility. 

This will be revisited hopefully this weekend, free time permitting. Until then, please adjust your Windows Accent settings accordingly.

**Comment by Yuuki-Walsh** [comment]
an option to override the system theme has been added and will be in the next release: 
![image](https://user-images.githubusercontent.com/379714/126613339-9d2c5c58-9c01-4810-b1a6-a5bf48c0afa2.png)
