### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by u88257** [imchillin/Anamnesis#460]
crash on start up
maybe because i am on china server?
[2021-07-22-20-27-57.txt](https://github.com/imchillin/Anamnesis/files/6862182/2021-07-22-20-27-57.txt)

**Comment by Ani-ki** [comment]
As per the [**Basic Setup page of the wiki**](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#downloading), Anamnesis only works with the International (JP/NA/EU) version of the game. We do not have an estimate as to when Chinese client will be added, as we do not have access to it.

Please be patient; we will announce Chinese and Korean client support when they become available. Until then, you will not be able to use Anamnesis.
