### ISSUE TITLE
Add option to revert to colour mode (or change the posing tab colour palette)

### ISSUE THREAD

**Issue by KataLystTB** [imchillin/Anamnesis#463]
Recently updated to the new version with apparent translucency and windows theme compatibility, however there is no (or at least doesn't appear to be) option to toggle between this mode and the original colour-based themes with much more readable selecters/sliders, notably for the posing mode tab. 
Current settings with a darker windows theme means that much of the UI is the same dark shades of grey, which work fine for windows interfaces as they're contrasted with white text or icons, however much of this UI is almost very difficult to read in the below situation; 
![image](https://user-images.githubusercontent.com/28195734/126778979-5bebe680-e309-40f8-a789-324a13824eac.png)
![image](https://user-images.githubusercontent.com/28195734/126779039-3c38b353-605d-4b09-b83a-33320987ddca.png)

Despite this, the colouring in the other tabs is somewhat more readable and i'm confused why they aren't uniform.
![image](https://user-images.githubusercontent.com/28195734/126779520-90382dc1-8984-4229-829e-34720efa1965.png)

**Comment by Ani-ki** [comment]
This has already been addressed in issue #459. In future, please check closed tickets as well.
