### ISSUE TITLE
Anamnesis will not create folder in My Documents

### ISSUE THREAD

**Issue by SahnUzal** [imchillin/Anamnesis#466]
Anamnesis will launch and run as intended, however since no folders are created in the My Documents folder when attempting to save or load a pose an I receive an error saying no file found.

[2021-07-23-17-55-29.txt](https://github.com/imchillin/Anamnesis/files/6871531/2021-07-23-17-55-29.txt)

**Comment by ajiiisai** [comment]
I tried to recreate the error and couldn't, Anamnesis always creates the folder on launch. Your logs seems fine to me. Did you try launching the application as administrator?

**Comment by SahnUzal** [comment]
**Update:** Ran the older version as a backup. Folder was created as intended. Downloaded and extracted the updated version of Anamnesis. Here is the new log with a critical error.

[2021-07-23-20-06-49.txt](https://github.com/imchillin/Anamnesis/files/6871712/2021-07-23-20-06-49.txt)

This is after running as an administrator.

**Comment by Ani-ki** [comment]
That log also appears to be fine, version difference aside. I'm also unable to recreate this error. Can you please confirm where you're getting the update from? It still says you're running  `2021-06-23`.

**Comment by SahnUzal** [comment]
I download the zip from the github link through discord I'll attach screenshots of the version number as well. Clicking onver the version.tx give me 6-23

![8b74c3480915287bbaccd360035b249e](https://user-images.githubusercontent.com/87881782/126853943-f6ba2bbc-ad1a-4e44-9bce-b84bdac04544.png)

**Comment by Ani-ki** [comment]
Righto, Yuuki's done a fix for the incorrect version being displayed. Still not entirely sure why the folder isn't being created. Could we please grab a few more details, such as your Windows version, and any antivirus software you might have installed?

**Comment by SahnUzal** [comment]
Windows 10 Home. Windows Security is the only antivirus installed on the PC. Just as reminder. The older version words properly. Creates the folder in my documents and able to save poses. Once the newer version is extracted to the same location as the old one it overwrites the older .exe. Then after running the newer version I receive a critical error causing Anamnesis to crash a FFXIV to be bugged. I can screenshot the actually pop up in Anamnesis and post it since the log doesn't seem to show it.

**Comment by Ani-ki** [comment]
The screenshot may be helpful.

**Comment by SahnUzal** [comment]
This is the error received when trying to save a pose.

![image](https://user-images.githubusercontent.com/87881782/126886805-b5d0a376-072e-4971-8a37-1a8241710e05.png)
 
![image](https://user-images.githubusercontent.com/87881782/126886807-ee46a34b-4335-4192-a394-fbcfd2391ae5.png)
