### ISSUE TITLE
Anamnesis.GameData.ViewModels.ItemViewModel

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#467]
Seemingly get this error randomly. Happens when attempting to change gear on an actor.
[2021-07-23-19-36-06.txt](https://github.com/imchillin/Anamnesis/files/6871797/2021-07-23-19-36-06.txt)

**Comment by ajiiisai** [comment]
This was fixed on https://github.com/imchillin/Anamnesis/commit/b8a1319a58a15ab2cb906a75ca3fc849c36b738e, so wait for the next release

**Comment by Ani-ki** [comment]
Reooened as the first instance of this issue; whilst the issue is resolved with the PR linked by ajiisai, people aren't seeing this issue and keep opening tickets. I'll close the other ones and link them here.

**Comment by Yuuki-Walsh** [comment]
this is now fixed in release.
