### ISSUE TITLE
F Au Ra upper lips cannot be moved

### ISSUE THREAD

**Issue by EtaCarinaecer** [imchillin/Anamnesis#470]
F Au Ra upper lips (1) will not display rotational changes ([2] will) if both R and P are enabled during the editing process, although the value changes on anamnesis will display and be saved, and reloading the pose will show said change, but only under the condition that P is disabled. Its position also cannot be changed with P enabled. This issue can be replicated on all 4 Au Ra F faces, did not try with other ones

**Comment by Yuuki-Walsh** [comment]
Hi, this is a limitation of the game, rotation lips with position mode enabled doesn't move the face, we're not sure why.
We think it might have something to do with the procedural speaking animation that characters use.
