### ISSUE TITLE
Critical Error when clicking on "Character" tab 

### ISSUE THREAD

**Issue by Rinforshort** [imchillin/Anamnesis#475]
[2021-07-27-07-16-59.txt](https://github.com/imchillin/Anamnesis/files/6884969/2021-07-27-07-16-59.txt)
Every time I click on the character tab I get this error.

**Comment by Yuuki-Walsh** [comment]
This appears to be an issue with WPF's handling of dynamicly loaded images [when you are running a non-standard windows color profile. ](https://stackoverflow.com/questions/63510630/wpf-bitmapimage-exception-the-image-data-generated-an-overflow-during-processin)

I've added a fix for this in the code for the next release, however you can check the color profile settings in the Color Managment control panel if you want.

**Comment by Rinforshort** [comment]
Yup that was the issue. I set the device profile to default and it's fixed now. Thank you
