### ISSUE TITLE
"Forced Light mode(?)"

### ISSUE THREAD

**Issue by ShiroiTaiga** [imchillin/Anamnesis#476]
![image](https://user-images.githubusercontent.com/88061406/127232111-e97fb221-45ad-4c64-b677-399cc392a67e.png)
So since the Beta, the interface is a little messed up and it's not.. impossible to work with? But still bothers me. 
Can this be fixed somehow? x.x

**Comment by Ani-ki** [comment]
This was fixed in the [**latest update**](https://github.com/imchillin/Anamnesis/releases/tag/v2021-07-26-beta). Please ensure you have updated the tool, then select the Windows theme override in the settings flyout.
