### ISSUE TITLE
.NET 5.0.8, still cant launch program

### ISSUE THREAD

**Issue by LyraRhea** [imchillin/Anamnesis#477]
https://i.imgur.com/aFFRsCv.png

Keeps saying version 5.0.0 was not found.

**Comment by ajiiisai** [comment]
Do you also have [.NET Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/5.0)?
![image](https://user-images.githubusercontent.com/85121274/127753626-054f0073-8e6c-405f-8e2f-e461b6ef50b6.png)

**Comment by LyraRhea** [comment]
I do yes.

Op zo 1 aug. 2021 00:19 schreef Ame ***@***.***>:

**Comment by ajiiisai** [comment]
Could you provide a picture of the installed version just to make sure?
It should show in your intalled applications like this:

![image](https://user-images.githubusercontent.com/85121274/127754087-13a93ab2-fe08-48bb-b6c7-bf8a91f6baa7.png)

**Comment by Ani-ki** [comment]
Hi @LyraRhea, [**please install 5.0.7 specifically**](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.7-windows-x64-installer). There appears to be an issue with. NET that we have not yet found a workaround for but hope to address in the next build.

**Comment by LyraRhea** [comment]
Alright, thank you so much for your quick reply. I'm not behind my pc
anymore, hence not sending the picture. I could provide that tomorrow if
needed.

I'll go and try it with the 5.0.7 version. Again, thanks a lot.

Op zo 1 aug. 2021 00:56 schreef Ani ***@***.***>:

**Comment by Ani-ki** [comment]
Did installing 5.0.7 resolve your issue?

**Comment by Ani-ki** [comment]
@LyraRhea please advise if installing 5.0.7 resolved your issue.

**Comment by Ani-ki** [comment]
Closing as we have not heard from OP in over a week. Please feel free to comment on this if the issue still persists for you.
