### ISSUE TITLE
'Failed to bind skeleton to view' On Lalafell hair 6

### ISSUE THREAD

**Issue by Rayib** [imchillin/Anamnesis#480]
For the last two days I've been unable to pose my character due to the 'Failed to bind skeleton to view'. I checked the log and it has something to do with the Hair_4 bone. If I change the hair it works fine but I'm restricted to only the 3d skeleton view.

Here's the log file.
[2021-08-05-23-19-47.txt](https://github.com/imchillin/Anamnesis/files/6943097/2021-08-05-23-19-47.txt)

**Comment by Ani-ki** [comment]
Hey there @Rayib. It looks like you've generated a custom skeleton for Lalafell:

```2021-08-05 23:29:43.988 -05:00 [INF] Loaded skeleton file: Data/Skeletons/Generated_0_Lalafel_Normal.json```

You can remedy this by going into `Anamnesis/Data/Skeletons` and deleting `Generated_0_Lalafel_Normal.json` before starting the tool again.

Try this out and let me know how you go.

**Comment by Rayib** [comment]
This solution did work, Thank you so much!

**Comment by Ani-ki** [comment]
Glad to see the issue has been resolved!
