### ISSUE TITLE
Issue selecting gear

### ISSUE THREAD

**Issue by gandr-shot** [imchillin/Anamnesis#481]
[2021-08-06-13-36-08.txt](https://github.com/imchillin/Anamnesis/files/6947912/2021-08-06-13-36-08.txt)

**Comment by Ani-ki** [comment]
Per the [Troubleshooting page](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here) of the wiki, we require more information from you before we can do anything:
- a brief description of the bug as the issue title
- any error messages displayed
- the exact steps you took to trigger the issue
- how many times you encountered the issue

Just dropping a log file tells us little.

**Comment by Ani-ki** [comment]
Closed as OP has not provided further input.
