### ISSUE TITLE
error report (anamnesis 2021-7-26 beta)

### ISSUE THREAD

**Issue by Ausar14** [imchillin/Anamnesis#483]
[2021-08-09-23-16-37.txt](https://github.com/imchillin/Anamnesis/files/6955539/2021-08-09-23-16-37.txt)

**Comment by Ani-ki** [comment]
Per the [Troubleshooting page](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here) of the wiki, we require more information from you before we can do anything:
- a brief description of the bug as the issue title
- any error messages displayed
- the exact steps you took to trigger the issue
- how many times you encountered the issue

Just dropping a log file tells us little.

**Comment by Ausar14** [comment]
when I want to run it, A window pops up called 'Critical Error' and 'Anamnesis was unable to recover from this error, and must close'
It said 'GameDataService Error: sheet item column hash mismatch! expected hash: **800968c9**, actual hash:  **a4a9422a**!'

**Comment by Ani-ki** [comment]
Please advise which version of the game you are running.

**Comment by Ausar14** [comment]
5.4

**Comment by Ani-ki** [comment]
Sorry, I was asking for the **locale** version. 5.4 suggests you're using an unsupported version of the game. 

Per the [installation instructions](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#prerequisites):

> ...only the English (International) release is available, with a view to have Chinese and Korean client support added in the future.

**Comment by Ausar14** [comment]
oh, I didn't notice this one, sorry :-(

**Comment by Ani-ki** [comment]
You are encouraged to read the wiki when using Anamnesis.

If you are using the Chinese or Korean client, we must ask that you be patient, as we do not have access to them and therefore cannot work on supporting them at this time.

**Comment by Ausar14** [comment]
yeah, I'm using Chinese client. thanks for answering my question, I'll be patient :-)
