### ISSUE TITLE
Upon entering gpose, NPC faces change when put on another player character besides yourself

### ISSUE THREAD

**Issue by Toki-Snow** [imchillin/Anamnesis#484]
Hello! I am having a strange issue since the last update. When I turn a friend into an NPC then enter gpose, the NPC's face/hair changes. It does not happen if I turn myself or a carbuncle into an NPC, only another player character. Any help would be greatly appreciated. Thank you!

**Comment by Mothism** [comment]
This is a known issue across any tool that temporarily changes character data like CMT, this does not just happen in Anamnesis. Until a fix is found (which is highly unlikely as it's universal), the best thing you can do is change yourself into the NPC and replace your friend's character data with your own.

**Comment by Toki-Snow** [comment]
> This is a known issue across any tool that temporarily changes character data like CMT, this does not just happen in Anamnesis. Until a fix is found (which is highly unlikely as it's universal), the best thing you can do is change yourself into the NPC and replace your friend's character data with your own.

Thanks so much for replying and letting me know! I appreciate it.
