### ISSUE TITLE
Non-named entities doesn't show up in the entity list

### ISSUE THREAD

**Issue by cck0-s** [imchillin/Anamnesis#486]
Anamnesis doesn't pick up any entities that doesn't have any names, for example roaming NPCs in towns, bosses in cutscenes or mounts in gpose.

**Comment by Ani-ki** [comment]
This is a feature of CMTool that cannot be replicated in Anamnesis due to the way the tool handles targeting. As such, this is a known limitation. We apologise for the inconvenience.
