### ISSUE TITLE
Window failing to open

### ISSUE THREAD

**Issue by monochou** [imchillin/Anamnesis#488]
I managed to successfully extract and install anamnesis into a folder of its own within my documents folder, but every time I try to boot it up, it does this thing where it shows the logo and spins around but the window of all the options and such never actually open.

**Comment by Ani-ki** [comment]
Try moving the folder to somewhere outside Documents. Windows likes to be a pain with permissions on this folder on occasion. Temporarily move it to your Downloads folder and try launching it again, and please advise if it persists.

**Comment by monochou** [comment]
Sorry for the late reply, I just tried moving it outside to my downloads folder and the same problem is still persisting.

**Comment by Yuuki-Walsh** [comment]
you may want to check if the window is opening somewhere off screen. 
Try holding Left Shift while the logo is appearing to reset your settings.

**Comment by Ani-ki** [comment]
@monochou is this issue persisting for you?

**Comment by monochou** [comment]
Yes it's still persisting for me.

**Comment by Ani-ki** [comment]
We've done a couple of fixes that should have resolved this- can you please confirm @monochou?

**Comment by monochou** [comment]
Yes, it doesn’t allow me to open it because I don’t think it recognizes me having Windows 10.

**Comment by monochou** [comment]
Computer shows no current updates. Currently this is the version of Windows 10 I have: 
Windows 10 Home Version 21H1

And my System Type: 64-bit operating system, x64-based processor

**Comment by Ani-ki** [comment]
@monochou touching base here, have you read the response above?

**Comment by Ani-ki** [comment]
Almost a month of no response so I'll be closing this. OP can respond if the issue persists.
