### ISSUE TITLE
"Posing" Menu won't show up with Miqo'te

### ISSUE THREAD

**Issue by NevendyND** [imchillin/Anamnesis#489]
A friend of mine has a lil Problem, when she Poses a Miqo'te her Pose menü won't show up correctly.
Only one Posing Option shows up.
![jftj](https://user-images.githubusercontent.com/28860034/129721105-56863788-383c-4a88-a117-f70582dcbddf.png)

on other Races it's this shows up, so she has 3 Posing Options.

![unknown](https://user-images.githubusercontent.com/28860034/129721183-b82dbc97-b782-450c-a93f-2fd354c365e7.png)

Is there a way to enable the second picture for Miqo'te too?
(For me it works perfect only for her this happens)

**Comment by Ani-ki** [comment]
Please ask your friend to check if they've accidentally generated a skeleton by checking their `Anamnesis/Skeletons` folder and looking for a `json` file starting with `Generated_`.

**Comment by NevendyND** [comment]
![skeleton](https://user-images.githubusercontent.com/28860034/130336100-89b276c2-eddc-4d7d-b82a-c6bb6e0f85bf.png)

**Comment by Yuuki-Walsh** [comment]
They'll need to delete that Generated Miqote skeleton to fix the issue.

**Comment by Ani-ki** [comment]
![image](https://user-images.githubusercontent.com/56663405/130344154-a7e8115f-c9ca-4de6-868f-2096205bdc98.png)

**Comment by NevendyND** [comment]
it works now, thank you
