### ISSUE TITLE
Critical Error:index was outside the bounds of the array

### ISSUE THREAD

**Issue by MoonSueAoi** [imchillin/Anamnesis#503]
![Anamnesis_2IM5vPo6a6](https://user-images.githubusercontent.com/89951335/131763887-869df09c-a132-4c58-ba33-d04bd7d62ff9.png)

**Comment by MoonSueAoi** [comment]
why？

**Comment by Yuuki-Walsh** [comment]
This error is seen mostly by player on the CN version of the game. Anamnesis only supports Global version of FFXIV.

**Comment by MoonSueAoi** [comment]
> 此错误主要见于游戏的 CN 版本。阿纳梅尼斯只支持全球版的 FFXIV 。

that make me so saddddd，，，，

**Comment by Ani-ki** [comment]
Hi. In future, [**please read the wiki, as we have outlined the limitations of the tool already several times**](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#prerequisites).
