### ISSUE TITLE
Can't open .NET Error but it is installed.

### ISSUE THREAD

**Issue by Owl8Ball** [imchillin/Anamnesis#504]
![image](https://user-images.githubusercontent.com/61810820/131920789-2abacd5e-f872-4c42-972a-1151b8d70eee.png)

**Comment by Ani-ki** [comment]
Hi there. Can you please doublecheck that you installed the Desktop Runtime?

**Comment by Owl8Ball** [comment]
Yes I did. I think I found the issue. I think it was related somehow to a change I made on regedit when it came to the default path for programs. Both windows specific apps as well as 3rd party software. After reverting that change I kept having the issue but a clean install of windows seemed to do the trick.

Sorry for all the trouble!
