### ISSUE TITLE
Failure to Launch - Wants 5.0.0 .NET, fails to recognize 5.0.9

### ISSUE THREAD

**Issue by FeatherSheen** [imchillin/Anamnesis#505]
Just downloaded Anamnesis and attempted to run. It informed me my .NET was out of date, so I downloaded and updated it.

I now get an error that states "The framework 'Microsoft.WindowsDesktop.App', version '5.0.0' was not found."
Running a cmd prompt confirms the system recognizes 5.0.9 is installed, but Amanesis still declines to launch.

**Comment by Ani-ki** [comment]
Hey there. Just to make sure, you installed the Desktop Runtime?

**Comment by FeatherSheen** [comment]
It looks like the ASP.Net Core Runtime was installed by mistake; installing the Desktop allows the program to launch. Thanks for the clarification!
