### ISSUE TITLE
Scenes

### ISSUE THREAD

**Issue by Yuki-Codes** [imchillin/Anamnesis#51]
Allow for saving world settings and multiple actors together into a single file.
This includes:

- Camera Settings (position, angle, zoom, etc)
- Actor Settings (Position, rotation, scale)
- Map information (what map was the scene saved in? can we safely load absolute positions?)

**Comment by EliCodesThings** [comment]
Can I get this one?

**Comment by MissAniThrope** [comment]
> Can I get this one?

I can't assign until you make a pull request, as discussed on Discord.

**Comment by jpdied** [comment]
Would love to see this feature as well!

**Comment by Yuki-Codes** [comment]
Scenes will be part of [Anamnesis-Studio](https://github.com/XIV-Tools/Anamnesis-Studio), and wont be coming to current Anamnesis due to the necessary UI and structural changes.
