### ISSUE TITLE
Anamnesis not working

### ISSUE THREAD

**Issue by DreamingSol** [imchillin/Anamnesis#511]
Its not working even though i have .NET x86 5.0.9, it keeps telling me to install .NET

**Comment by Ani-ki** [comment]
Sorry, but 'Anamnesis is not working' is not a sufficient error report. [**Please read and follow the Troubleshooting guide, and follow the issue reporting instructions**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here) before opening issues in future.

This ticket will now be closed as the OP was not able to provide enough information.
