### ISSUE TITLE
Having certain dyes favorites removes "None" from the top of the dye selection.

### ISSUE THREAD

**Issue by Featherbrew** [imchillin/Anamnesis#512]
Noticed originally with Wine Red + Midnight Blue favorited -- "None" was in the menu at the location of Midnight Blue
None still appeared with either individually favorited, but not both
Certain other dyes also move None in the options (Shadow Blue) -- Couldn't find "None" anywhere in the scroll, but could search it.

I know the simple solution is to favorite None but whattheheckbroke

![image](https://user-images.githubusercontent.com/82767067/132705452-3c7b9b1c-205d-49df-96e9-ddaf5af70812.png)
![image](https://user-images.githubusercontent.com/82767067/132704950-339ec54b-b8c7-472b-9f02-962c51b73328.png)
![image](https://user-images.githubusercontent.com/82767067/132704972-b5568ad1-0152-441e-983a-4e7df8450aa8.png)
![image](https://user-images.githubusercontent.com/82767067/132704999-e1ee309b-4ceb-4a0c-8b1e-464804d17ee9.png)

**Comment by Ani-ki** [comment]
Lmaooooooo what 

Okay, looks like it's not sorting None before favourites. We can uodate the sorting function this weekend!
