### ISSUE TITLE
Can't run the Anamnesis.exe

### ISSUE THREAD

**Issue by JasonBourne33** [imchillin/Anamnesis#514]
I download and install the .net 5,when I run Anamnesis.exe , this dialog show up
![S36C`AVSV 0P4DMGO Z7~X6](https://user-images.githubusercontent.com/18242586/133115119-f988342f-537e-400c-85dc-98fe726b8676.png)

**Comment by Ani-ki** [comment]
Can you please provide a log file [**per the troubleshooting page of the wiki**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here)?

**Comment by Yuuki-Walsh** [comment]
Cn and ko versions not supported. Global version only for now.
