### ISSUE TITLE
Can't run the Anamnesis

### ISSUE THREAD

**Issue by Tom911117** [imchillin/Anamnesis#515]
Hi! My system is win10 x64, and I installed .Net 5, but an error message appeared after starting Anamnesis. Also I took a screenshot of my log. Could anyone help this, thanks in advance!!
![logFile](https://user-images.githubusercontent.com/70363139/133246193-48e68e95-02f0-4d51-b940-d9049c55c0c6.png)

**Comment by Ani-ki** [comment]
Please do not upload screenshots of the log file. Just upload the actual text file.

**Comment by Tom911117** [comment]
[2021-09-14-18-56-44.txt](https://github.com/imchillin/Anamnesis/files/7161302/2021-09-14-18-56-44.txt)
So sorry about the screenshot, I reupload the log file!

**Comment by Ani-ki** [comment]
Are you using the Korean or Chinese version of the client? If so, these are not yet supported, as documented in the wiki **[multiple](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#basic-troubleshooting)** [**times**](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#prerequisites).

**Comment by Tom911117** [comment]
Yes, I am using the Chinese version of the client, thanks!
