### ISSUE TITLE
CN and KO versions of the game support

### ISSUE THREAD

**Issue by Yuuki-Walsh** [imchillin/Anamnesis#516]
Need to add a handler for this case with a better error message.

**Comment by idlist** [comment]
There is a [fork](https://github.com/Loskh/Anamnesis/releases) that supports CN client specifically.

**Comment by Ani-ki** [comment]
This version is not supported by the developers, and appears to be severely out of date. @Loskh should consider doing a pull request and consolidating it with the main repo.

**Comment by Loskh** [comment]
I think Actor.cs need some changes to determine offsets accrording to the client version  in runtime instead of hardcoded numbers to support CN/KR versions.

**Comment by Yuuki-Walsh** [comment]
Unfortuantely, struct offsets cannot be dynamic. they have to be set at compile time for this to work.

**Comment by Yuuki-Walsh** [comment]
Looks like the offsets in CMTool are now the same for all clients, what values do we need to change?

**Comment by Yuuki-Walsh** [comment]
ok, I've added the ability to swap the models (and their offsets) based on region with the [RegionalMemoryViewModelBase%7BTGlobal,TKo,TCn%7D.cs](https://github.com/imchillin/Anamnesis/blob/master/Anamnesis/Core/Memory/RegionalMemoryViewModelBase%7BTGlobal,TKo,TCn%7D.cs) type.

So if we do have different offsets per region, we can support those now.

**Comment by Yuuki-Walsh** [comment]
as far as I know, this should work now, but I cant test it. so closing this pending any feedback for users in these regions.
