### ISSUE TITLE
My Anamnesis have some problem on china server

### ISSUE THREAD

**Issue by Cherryhy** [imchillin/Anamnesis#519]
[2021-09-21-05-25-30.txt](https://github.com/imchillin/Anamnesis/files/7198253/2021-09-21-05-25-30.txt)
this is my log file
Is it because china server so i can't use Anamnesis?
Thank you!

**Comment by Ani-ki** [comment]
Support for the Chinese client has not been added as yet. This has been stated in the wiki multiple times  ([here](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#prerequisites), [here](https://github.com/imchillin/Anamnesis/wiki/FAQ#why-doesnt-this-work-on-the-chinesekorean-client), and [here](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#basic-troubleshooting). 

In future, [**please read the wiki before opening support tickets**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here).
