### ISSUE TITLE
Odd/Slow mouse movement & GUI flickering

### ISSUE THREAD

**Issue by ashemmi** [imchillin/Anamnesis#523]
The transparency effect and/or the gallery rotation was causing my mouse to be extremely sluggish, then speed up and fly across the screen.  Additionally the GUI for Anamnesis flickered while attempting to show contents behind the window.

Disabling the two options within the config resolved the issue.

``"ShowGallery": false,
  "EnableTranslucency": false,``

Windows 11 and a Ryzen processor may be pertinent to the bug.

**Comment by Yuuki-Walsh** [comment]
this is a bug introduced by the recent windows 11 update. nothing we can do on our side. Hopefuly microsoft fixes it soon.
