### ISSUE TITLE
Failed to get file information System.Text.Json.JsonException: 

### ISSUE THREAD

**Issue by Mrfish074** [imchillin/Anamnesis#530]
not sure what ive done wrong. trying to load cmtool character files
[2021-09-27-21-00-31.txt](https://github.com/imchillin/Anamnesis/files/7235727/2021-09-27-21-00-31.txt)

**Comment by Yuuki-Walsh** [comment]
you may need to send through the file you were loading. it loosk to be somehow malformed.

**Comment by Mrfish074** [comment]
> 
> 
> you'll need to send through the file you were loading. it looks to be somehow malformed.

i havent even loaded the character ive just changed to my local cmtool saves

**Comment by Yuuki-Walsh** [comment]
yea it looks like serveral of the files in that directory dont match the correct CMTool file format. I'd need to see them to determine why.

I'll expand the error to include the names of files in future, so you can tell which files are specifically broken.

**Comment by Yuuki-Walsh** [comment]
specifically the error is stemming from the Hair glow values, which should look like:
`    "HairGlowBlue": {
      "value": 0.6653441
 },`

but is apprantly a string instead of a number in several files.

**Comment by Mrfish074** [comment]
not sure why it would do that i havent tinkered with the raw files

**Comment by Yuuki-Walsh** [comment]
without the files I couldn't tell you whats wrong. 
Might be a formatting issue of some kind, a localle bug (in Ana or CMTool) or some other wierd edge case.

**Comment by Mrfish074** [comment]
probably really old files

**Comment by Ani-ki** [comment]
Please upload one of the files so we can diagnose this issue. Else I will have to close this ticket, as we are not being provided with the data we need.

**Comment by Mrfish074** [comment]
how would i know which file is causing the error?

**Comment by Ani-ki** [comment]
You don't. Feel free to zip them and upload that.

**Comment by Mrfish074** [comment]
theres about 2800 files O_O

**Comment by Ani-ki** [comment]
Then please provide a selection at random. Literally anything.

**Comment by Mrfish074** [comment]
[troubleshoot.zip](https://github.com/imchillin/Anamnesis/files/7235949/troubleshoot.zip)
