### ISSUE TITLE
Does Anamesis need to be Uninstalled before Maintenance?

### ISSUE THREAD

**Issue by IzyshaMizuki** [imchillin/Anamnesis#532]
Just wanting to see if it needs to be uninstalled before maintenance, and if so, how do I do that?

**Comment by Ani-ki** [comment]
No, Anamnesis does not need to be uninstalled prior to maintenance.

In future, this would be a question best asked on the XIV Tools Discord server, as this issue list is for reporting bugs.

**Comment by IzyshaMizuki** [comment]
Roger that, ah got it, I figured since it was an Anamesis thing I needed to post it here, but wasnt sure. thank you for the clarification!

Thank you for the quick response and have a great night!

**Comment by Ani-ki** [comment]
(It's actually just past 10am for me lmao)

I might add something about this to the wiki, as well.

**Comment by IzyshaMizuki** [comment]
ah got it, then have a good day! lol

yeah cause since there isnt an uninstall button, i figured it wouldnt need to be deleted, but still wanted to check.
