### ISSUE TITLE
Can't pin and pose chocobo.

### ISSUE THREAD

**Issue by TheCrimsonVyxen** [imchillin/Anamnesis#539]
Hi! 
Anamnesis is crashing every time I try to pin my chocobo, anyone else having this issue?

**Comment by Ani-ki** [comment]
Per the [Troubleshooting page of the wiki](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here), we require a bare minimum amount of info from you. Please attach log files when opening tickets, as "x doesn't work!" reports give us nothing to work with.

**Comment by TheCrimsonVyxen** [comment]
Sorry, I didn't really know which log it was or how to read them to figure out which it is. After a full reinstall, it works now. Sorry ^^"
