### ISSUE TITLE
Frozen values not updated for actors that are not current actor.

### ISSUE THREAD

**Issue by HungBunZ** [imchillin/Anamnesis#540]
In older versions i was able to set a certain amount of the "wet effect" on characters. Between 0-100 and it would sit there without any problem. This feature doesent work anymore with the current build. When i use the wet effect on my Character and switch to another Character, the wet-effect starts to decrease till it runs out. Would love to see a fix for that because it helped me out a lot with Screenshots

**Comment by Yuuki-Walsh** [comment]
This will be caused by the recent change to memory reads being ticked hierarchly starting with the current actor.

We should change this so any pinned actors get ticked.
