### ISSUE TITLE
NPC data doesn't load

### ISSUE THREAD

**Issue by Tippetyt0p** [imchillin/Anamnesis#541]
I downloaded the latest version, tried on both myself and on the carbuncle but picking any character from the NPC list does nothing

**Comment by Ani-ki** [comment]
Per the [Troubleshooting page of the wiki](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#my-issue-isnt-here), we require a bare minimum amount of info from you. Please attach log files when opening tickets, as "x doesn't work!" reports give us nothing to work with.

**Comment by Tippetyt0p** [comment]
[2021-09-29-19-56-44.txt](https://github.com/imchillin/Anamnesis/files/7256351/2021-09-29-19-56-44.txt)

**Comment by Ani-ki** [comment]
That is still not the bare minimum.

Your log file contains no information. As such, we need you to actually list, step by step, what you're doing to trigger this error.

**Comment by Tippetyt0p** [comment]
I log in, summon a carbuncle, click yes on the "change to NPC" prompt, open the NPC list, click any name, switch to myself, try the NPCs again.
I've recorded a video if that makes it clearer: https://youtu.be/2cwCPfuIHOU
[2021-10-01-06-51-35.txt](https://github.com/imchillin/Anamnesis/files/7264244/2021-10-01-06-51-35.txt)
Plus the log from that session, if that helps

**Comment by Yuuki-Walsh** [comment]
Looks like a recent change made the NPC list behave like the file list, where you need to double-click on items, and clicking outside cancels the load without doing anything.

I've ticketed this up in #552.
