### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by CielLuxor** [imchillin/Anamnesis#542]
![image](https://user-images.githubusercontent.com/91639810/135360736-70ba290a-bb5d-4e8a-bb17-59a88d8a3559.png)

I have no clue why it keep sdoing this I downloaded latest release and I extracted and it keeps giving me this error

**Comment by Ani-ki** [comment]
Please follow the instructions in that error dialogue. Screenshots don't help us.

**Comment by Ani-ki** [comment]
Without a log file, we cannot act on this. Given this does not contain the bare minimum we need to investigate, I'll be closing this ticket.
