### ISSUE TITLE
File browser file name not applying when saving a file

### ISSUE THREAD

**Issue by Maxunit** [imchillin/Anamnesis#543]
This affects the latest release of Anamnesis:

There is a high chance (in my case every time so far), that, even after entering a file name for a Character or Pose upon saving, it reverts to the default name instead of using the entered name.

**Comment by Ani-ki** [comment]
I wasn't able to replicate this last night but I'll try again when I'm back on my pc.

**Comment by Rikardos87** [comment]
Have the same issue, Don't matter what I input as file name , It just saves it as the default name , Overwriting a old file works without issue. Seems to only affect latest release. Friend of mine also have the exact same issue.
