### ISSUE TITLE
Time appears to be offset

### ISSUE THREAD

**Issue by JoeHegarty** [imchillin/Anamnesis#544]
Couldn't see an issue reporting this at first glance, feel free to close if I missed it.

Since updating to 2020-09-29 09:19 in-game Eorzea time and time you set in Anamnesis appears to be offset from one another.
So for example, if I set the time to 690 it appears as 12:30 in Ana, but 18:30 Eorzea Time ingame.

**Comment by Ani-ki** [comment]
Looks like it's off by six hours. We can look into this a little later today.

**Comment by Yuuki-Walsh** [comment]
this doesnt appear to be happening for me, time 690 should be 11:30 in both Ana and Ffxiv. can you confirm?

**Comment by JoeHegarty** [comment]
I can't seem to reliably reproduce it now. It was happening consistently but now it seems to be pretty random if there is an offset or not. 
I'll let you know if I come up with a consistent repro case.

**Comment by Ani-ki** [comment]
All good. We'll keep this one open and see if we can get it on our end as well.

**Comment by Ani-ki** [comment]
Has anyone been able to reliably reproduce this? I've been trying on and off in both the release and development versions and can't see any disparity in the time between the game and the tool.

**Comment by JoeHegarty** [comment]
I think it was unique to `2020-09-29 09:19`, I haven't seen it since that build. Probably makes sense to close this one.

**Comment by Ani-ki** [comment]
Cheers man, much appreciated.
