### ISSUE TITLE
CMP poses won't load

### ISSUE THREAD

**Issue by Madaraki1987** [imchillin/Anamnesis#545]
So, basically, cmp poses don't work anymore. The Anamnesis ones work fine, just the cmp ones don't 

[2021-09-30-03-21-26.txt](https://github.com/imchillin/Anamnesis/files/7256110/2021-09-30-03-21-26.txt)

**Comment by Ani-ki** [comment]
This was already brought up in #535 (which is pinned) and resolved with the latest hotfix. You will need to manually install the latest version.

Please do not open duplicate tickets.
