### ISSUE TITLE
Process Set Privilege failure: Not all privileges or groups referenced are assigned to the caller

### ISSUE THREAD

**Issue by escoaloplop** [imchillin/Anamnesis#547]
[2021-09-30-16-27-49.txt](https://github.com/imchillin/Anamnesis/files/7259608/2021-09-30-16-27-49.txt)

I've turned off my anti-virus, whitelisted the tool, run as admin, moved to different folders, gave full control of program files & folders to admin but to no avail. I kept getting this error message. Is there any way to fix this?

**Comment by Ani-ki** [comment]
Given this appears to be an issue with a personal installation of Windows and not Anamnesis itself, this is not something we can resolve. As such, I will be closing this ticket.
