### ISSUE TITLE
Actor Kind is changed to NPC when entering gpose

### ISSUE THREAD

**Issue by SawedOffMidget** [imchillin/Anamnesis#548]
Every time I adjust the appearance of my model in game, it will no longer identify them as the character 'You' in Gpose. It identifies them as Npc's (enemies). It is an issue with Anamnesis, as it will not do this when I edit appearances with other tools (CM.) I have tried resetting the settings. I have tried a fresh installation, and I'm still having the issue occur.

I've included the last two attempts to edit correctly, as well as what should be some of the corrective actions.

[2021-09-29-06-41-43.txt](https://github.com/imchillin/Anamnesis/files/7259786/2021-09-29-06-41-43.txt)
[2021-09-29-06-41-59.txt](https://github.com/imchillin/Anamnesis/files/7259787/2021-09-29-06-41-59.txt)

**Comment by SawedOffMidget** [comment]
I'm also unable to save new characters or poses.

**Comment by SawedOffMidget** [comment]
Original post edited, not occurring for carbunkle anymore. No idea why

**Comment by Yuuki-Walsh** [comment]
This is probably caused by the code that lets us load NPc faces, since it changes you to NPC as you enter gpose, then changes back once loaded in.

Checking actor Kind in the appearance page might let you set it back to player to restore normal gpose functionality until we fix it.
