### ISSUE TITLE
Can't access BuiltInPoses

### ISSUE THREAD

**Issue by smoochiepooks** [imchillin/Anamnesis#549]
Shortly after updating the Anamnesis tool, I started to come across a Critical Error whenever I tried to load up a pose through BuiltInPoses. (I don't know how anyone else does it, but I can only access/upload poses through the BuiltInPoses folder.) Here's what the error looks like:

![image](https://user-images.githubusercontent.com/91694533/135510983-01430e6f-313d-477d-9e7d-b9ba147cdd15.png)

And here's the log file: 

[2021-09-30-14-26-36.txt](https://github.com/imchillin/Anamnesis/files/7261737/2021-09-30-14-26-36.txt)

**Comment by Ani-ki** [comment]
You should NOT be placing your poses in the built in poses folder at any point. This is stressed multiple times in the wiki.

Poses can be saved anywhere on your pc.

**Comment by smoochiepooks** [comment]
> You should NOT be placing your poses in the built in poses folder at any point. This is stressed multiple times in the wiki.
> 
> Poses can be saved anywhere on your pc.

Ok! It was working for me until I updated Anamnesis, though.

**Comment by Ani-ki** [comment]
Yes. As I said, you SHOULD not. You're technically able to save files in the folder, but that folder is deleted and reinstalled when an update comes out, so anything you put in there will be removed when the update triggers. At which point we are not responsible for any lost data caused by misusing the tool.

**Comment by Yuuki-Walsh** [comment]
this is fixed for a future update.
duplicates #536
