### ISSUE TITLE
Can't save new character appearance without being overwritten.

### ISSUE THREAD

**Issue by residentfire** [imchillin/Anamnesis#550]
Hello!
Every time I try to save a new outfit/appearance; I put in a new name for the file however when I hit save it defaults to "New Anamnesis Character File" even if that is not typed in the box. Then keeps overwriting the same file.
![firefox_Isxichy6tR](https://user-images.githubusercontent.com/91701640/135533243-a991f4ca-ca00-44fd-a696-9f7ff1094581.png)
![Anamnesis_Red3iI5NxF](https://user-images.githubusercontent.com/91701640/135533248-2d3b2b51-69b6-4962-bff6-1a2aff7ef4df.png)

**Comment by Ani-ki** [comment]
This was discussed in #543 and has since been fixed pending an update.

Please do not open duplicate tickets.
