### ISSUE TITLE
Player Character Registering as NPC when in GPose

### ISSUE THREAD

**Issue by spookylune** [imchillin/Anamnesis#554]
When I enter gpose, I am unable to do lip movements, however I can change expressions. When hiding targets, it counts my PC as an NPC. 

I've uninstalled/reinstalled Anam as well as updated it. However, I'm not sure how to fix the issue at this point.

Sorry, I did not provide logs, I wasn't sure how.

**Comment by Ani-ki** [comment]
This report does not follow the layout provided.
