### ISSUE TITLE
Failed to read memory...

### ISSUE THREAD

**Issue by Mistearea** [imchillin/Anamnesis#559]
**Describe the bug**
Anamnesis fails to open and quits before it finishes initializing. Currently running most updated version. Encountered 3 times.

**To Reproduce**
1. Open Anamnesis
2. See error
3. Close Anamnesis

**Expected behaviour**
I expected Anamnesis to open to allow editing of character before going into gpose.

**Log file*
[2021-10-02-00-04-51.txt](https://github.com/imchillin/Anamnesis/files/7270895/2021-10-02-00-04-51.txt)
*

**Comment by Ani-ki** [comment]
Can I get you to roll back to an earlier version and see if the issue happens in that one? [20210915 is considered the most stable at the moment](https://github.com/imchillin/Anamnesis/releases/tag/v2021-09-15-beta).

**Comment by Mistearea** [comment]
No issue with that version. Opens up normally.

**Comment by Ani-ki** [comment]
This may be resolved as part of a larger overhaul we're about to push, but I'll keep this open in case it persists for you after the update.

Per Yuuki: It looks like it's trying to load a nearby actor and failing. We can add better error dialogue for this as well.
