### ISSUE TITLE
Going up a level displays duplicate files

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#560]
Pressing the up arrow in the UI to go back up a folder causes the files in the previous folder to display multiple copies.

**To Reproduce**
Steps to reproduce the behaviour:
Simply click Load to load a pose.
Enter a folder
Go back up a level
Multiple copies of files displayed.

**Expected behaviour**
Obviously shouldn't happen. Thankfully it doesn't make more than 2 copies to display. 

**Log file**
[2021-10-01-23-42-44.txt](https://github.com/imchillin/Anamnesis/files/7271006/2021-10-01-23-42-44.txt)

**Comment by Yuuki-Walsh** [comment]
probably the `UpdateEntries` thread is getting run multiple times by property changes, should thread lock that and check if its already running before starting it.
