### ISSUE TITLE
Saving poses/characters don't add a file type to the file.

### ISSUE THREAD

**Issue by Rikardos87** [imchillin/Anamnesis#562]
**Describe the bug**
Saving Poses or Characters don't add the file type .chara or .pose to the file it just a named "file". Trying to overwrite an old file gives no overwrite prompt and creates a new file with the same name but without the correct file type.

**To Reproduce**
Steps to reproduce the behaviour:
1. Save a pose or character
2. Save to an already excising file

**Expected behaviour**
Expected the program to add either .chara or .pose to the saved file.

**Log file**
[2021-10-02-13-01-44.txt](https://github.com/imchillin/Anamnesis/files/7271353/2021-10-02-13-01-44.txt)

**Comment by Rayna-Grimm** [comment]
same thing here. was about to make my own post, good thing i double checked 
[2021-10-02-06-04-49.txt](https://github.com/imchillin/Anamnesis/files/7271369/2021-10-02-06-04-49.txt)

**Comment by Xullyy** [comment]
Same problem here, it's because Anamnesis doesn't save the files as .chara. But it still saves the file, just navigate to your pose/chara folder in Anamnesis and add .chara at the end of your file name to change them to the correct type until there's a fix :)
