### ISSUE TITLE
Load Character Menu doesn't have CMTool Character Folder as a Default Option

### ISSUE THREAD

**Issue by Cy399** [imchillin/Anamnesis#563]
**Describe the bug**
The load character appearance menu doesn't have the corresponding CMTool folder as a default option which previous versions did, folder still reachable via manual browsing

**To Reproduce**
Steps to reproduce the behaviour:
1. Load character data
2. Folder options on the left-hand side points to CMTool/Matrix Saves rather than CMTool/Saves

**Expected behaviour**
The CMTool/Saves folder being one of the default options would make character loading easier between versions

**Log file**
N/A

**Comment by Ani-ki** [comment]
It also isn't grabbing JSON files, so we can kill two birds with this. Hopefully between this and the file extensions not saving correctly, we don't have any other new file server bugs.
