### ISSUE TITLE
Render Limit Removal

### ISSUE THREAD

**Issue by Kersplosion** [imchillin/Anamnesis#569]
I realize this is sort of a fringe request, but I take a lot of macro shots, and beyond scale 1023 the game will, for the most part, give up on rendering the actor entirely. At some point in CM's lifespan a toggle switch was added to bypass this limit and maintain rendering beyond normal limits. I hope that it would be simple to find/add but software is rarely simple.

**Describe the solution you'd like**
A toggle switch that manages to bypass the game's actor render limit of 1023 scale.

**Comment by Yuuki-Walsh** [comment]
the main reason we've not added this feature is that when tested, we couldn't confirm its functionality, and it would very often crash the game.

Aditionalliy, when investigating its use cases, we were always able to replicate shots without it, so its very low priority.

We'd consider adding this feature if its functionality could be demonstrated clearly, and we could ensure that it wouldn't just crash the game randomly.

Here is a shot I just made with Anamnesis without the 'render limit' removal option: 
![bigLady](https://user-images.githubusercontent.com/379714/135788700-a4d36148-b6c3-4e69-b8e7-1579554de97d.jpg)
as you can see, the game has no issues rendering characters with scale above 1024 without modification.

**Comment by Ani-ki** [comment]
![giant-woman-opal](https://user-images.githubusercontent.com/56663405/135789040-15e2af10-fb96-4056-af62-2fbdc00792d7.gif)

**Comment by Kersplosion** [comment]
That's fair, not much reason to implement a feature if it just adds instability.

I have gotten some >1024 attempts to work, but I haven't been able to really pin a consistent method, is all.

Thanks for the quick response though, and thank you for all the work on the tool!

**Comment by Yuuki-Walsh** [comment]
there may be some game configuration that affects it, like occlusion culling or something. Genrally as long as the character is _close_ to its starting position and that position is still on-screen, the character shouldn't get culled.

I'm not sure what the 'render limit' option actually did, but I _think_ its intended to disable either occlusion culling, frustrum culling, or distance culling. so far nobody has been able to explain it though.
