### ISSUE TITLE
Cannot load poses without glitching hair and facial expression, cannot change expression

### ISSUE THREAD

**Issue by cloverteapot** [imchillin/Anamnesis#580]
Hi, so I have a Miqo'te boy and I'd like to use the poses from other races on him. 

Whenever I load a pose, the face and hair gets distorted and glitched. Whenever I select with the "load expression" option the face glitches out of his head. 

How do I load poses without messing with his expression and hair? And how do I change his expression after a pose is loaded? 

Thank you in advance

**Comment by Ani-ki** [comment]
Not an issue. Also fails to follow the issue reporting format provided.
