### ISSUE TITLE
Changing dye crashes the tool

### ISSUE THREAD

**Issue by PookieChu** [imchillin/Anamnesis#587]
**Describe the bug**

Any time I go to change the colour of a mod in the appearance section the tool suddenly gets a critical error and just crashes and closes.

**To Reproduce**

Steps to reproduce the behaviour:

1. click on character
2.  click on dye button
3.  Crashes 

**Expected behaviour**

I expected to be able to just select the dye colour I want as I have previously been able to do.

**Log file**
[2021-10-21-13-39-35.txt](https://github.com/imchillin/Anamnesis/files/7388641/2021-10-21-13-39-35.txt)

**Comment by Ani-ki** [comment]
You appear to be running an out of date version of the tool. If it has not prompted you to update automatically, you will need to update manually by [downloading the latest release](https://github.com/imchillin/Anamnesis/releases/tag/v2021-10-09-beta).
