### ISSUE TITLE
Skeleton Generation Broken

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#595]
**Describe the bug**
When loading a non-humanoid model and attempting to generate a skeleton in GPose, multiple failings occur. When running the tests of each bone, it fails to use the selected actor's rig, instead using the player's. Once that process concludes, the program returns an error (Failed to bind skeleton to view), detailing how it attempted to access the outdated \Data\Skeletons\ file path from the previous version. The result is you wind up exactly where you started.

**To Reproduce**
Load a monster model, enter GPose, generate skeleton.

**Expected behaviour**
Generating an functional, custom skeleton for use in GPose, like before.

**Log file**
[2021-10-30-13-53-56.txt](https://github.com/imchillin/Anamnesis/files/7447328/2021-10-30-13-53-56.txt)

**Comment by Ani-ki** [comment]
The *one* thing I didn't test gfdi.

Might need to look into adding the Skeletons folder to Documents/Anamnesis alongside the Poses folder.

**Comment by Yuuki-Walsh** [comment]
We're going to remove the 'Generation' step of posing non-humanoids for now.
You'll still be able to pose them, but parenting wont work without hand-making a custom skeleton file.
We'll come back to this when we get the chance, but #24 (improving Pose3D UI) is probably more valuable for now.
