### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Kromilan** [imchillin/Anamnesis#597]
Hello. With the Steam Deck on the horizon and the game already running flawlessly with Wine, I wanted to ask if there are plans to 
also support Linux. I understand that memory gets handled differently on different operating systems and so relying on wine won't be enough. I expect it'll be a lot of extra effort to make this run on Linux, but as said, with the Steam Deck on the horizon and desktop linux getting more usable every month, I'd be really happy if playing ffxiv with this mod became possible.

**Comment by Ani-ki** [comment]
[We have no plans to support Linux](https://github.com/imchillin/Anamnesis/wiki/What-is-Anamnesis%3F#limitations), and at this stage are unlikely to consider supporting Anamnesis on a platform we do not personally use.

**Comment by Ani-ki** [comment]
Ayyy lmao 
![image](https://user-images.githubusercontent.com/56663405/140038381-40cd506f-e7b2-4288-8948-4f3abb430412.png)

**Comment by a-wild-github-user** [comment]
I'll just add that Anamnesis works great in wine.
Run it in the same wine prefix as the game with the same wine version and do not enable dxvk.

Great project :+1:

**Comment by Kromilan** [comment]
> I'll just add that Anamnesis works great in wine. Run it in the same wine prefix as the game with the same wine version and do not enable dxvk.
> 
> Great project +1

I cannot confirm this. Despite Dotnet Runtime 5 being installed on my system as well as the windows version inside the prefix, Anamnesis gives the message that Dotnet needs to be installed. I ran the installer multiple times and can confirm that dotnet is installed.

**Comment by Kromilan** [comment]
After some testing I can now confirm that it does indeed work like a-wild-github-user said. In order to make it work, in my case the a copy of the .dll for Dotnet5 had to be in the same folder as the .exe for Anamnesis.
You can find the .dll after installing dotnet 5 under c/ProgramFiles/dotnet/host/fxr/[your version]/hostfxr.dll. Move that to the same folder as the anamnesis exe and everything works.

**Comment by PapaBones** [comment]
> After some testing I can now confirm that it does indeed work like a-wild-github-user said. In order to make it work, in my case the a copy of the .dll for Dotnet5 had to be in the same folder as the .exe for Anamnesis.
> You can find the .dll after installing dotnet 5 under c/ProgramFiles/dotnet/host/fxr/[your version]/hostfxr.dll. Move that to the same folder as the anamnesis exe and everything works.

Did you get the poses menu to work though? I cannot seem to get it to open up no matter what I do. Everything else has functionality but when I click on the pose menu it freezes and forced me to restart the tool. I use lutris to manage the game and the tool with lutris-ge-6.18.1.

**Comment by Kromilan** [comment]
it is unstable for me but it works occasionally. it's slow and not very responsive, but with enough patience, after each click, it works most of the time for me. I am using lutris-6.10

**Comment by PapaBones** [comment]
Thank you for the very fast reply. I've tried that as well by now, I tried with older version(been using the latest version), with yet different wine versions but I just could not get it to open up the pose menu. I will probably have to try at a later time or if someone can find a solution.

**Comment by a-wild-github-user** [comment]
I'm actually having the same issue, ran into it a few weeks back after running updates. I spent a while trying to track it down but haven't found it yet. 
Tried waiting it out but it doesn't progress after clicking the pose button.
At the moment I'm thinking it might be caused by changes to Lutris which I haven't looked very deep into yet and is the only thing I can think I haven't tried downgrading yet. I'm a little hesitant to as it seems to have changed a bunch of the settings and I don't want to break everything.

I've found the error in the logs but haven't had much luck working out the problem, perhaps someone else can make more sense of it.
This shows up in the log about 30 seconds after clicking on pose and having anamnesis stop responding:
```
2021-12-27 12:08:57.518 +11:00 [FTL] 0x88980406
System.Runtime.InteropServices.COMException (0x88980406): 0x88980406
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

If I enable DXVK then it loads the pose menu fine and it works, the problem is it's black most of the time and only flickers the display for a second here and there. If that can be resolved it *seems* like it otherwise is working with DXVK enabled.

**Comment by Kalidibus** [comment]
> I'll just add that Anamnesis works great in wine. Run it in the same wine prefix as the game with the same wine version and do not enable dxvk.
> 
> Great project +1

I know posing isn't working right now, but do you recall if you had to do anything aside from put Anamnesis in the same wine prefix to get it to see the FFXIV instance? Mine seems to load up fine, but always closes right away after giving a bunch of errors about being unable to find the skeleton data etc in the memory. It seems to notice when FFXIV starts though because it leaves the "Waiting for FFXIV" screen once I open it.

**Comment by a-wild-github-user** [comment]
> > I'll just add that Anamnesis works great in wine. Run it in the same wine prefix as the game with the same wine version and do not enable dxvk.
> > Great project +1
> 
> I know posing isn't working right now, but do you recall if you had to do anything aside from put Anamnesis in the same wine prefix to get it to see the FFXIV instance? Mine seems to load up fine, but always closes right away after giving a bunch of errors about being unable to find the skeleton data etc in the memory. It seems to notice when FFXIV starts though because it leaves the "Waiting for FFXIV" screen once I open it.

I haven't come across that one. I just install dotnet 5.0.13 which the anamnesis installer prompts for.

**Comment by Kromilan** [comment]
> > I'll just add that Anamnesis works great in wine. Run it in the same wine prefix as the game with the same wine version and do not enable dxvk.
> > Great project +1
> 
> I know posing isn't working right now, but do you recall if you had to do anything aside from put Anamnesis in the same wine prefix to get it to see the FFXIV instance? Mine seems to load up fine, but always closes right away after giving a bunch of errors about being unable to find the skeleton data etc in the memory. It seems to notice when FFXIV starts though because it leaves the "Waiting for FFXIV" screen once I open it.

I had to also move/copy the hostfxr.dll from the dotnet folder to the same folder where I saved the Anamnesis exe.

**Comment by manning390** [comment]
Using the quick launcher build from lutris. I installed it using the same wineprefix and copied the hostfxr.dll from the .net 5 installation (installer also required to be ran via prefix). I can get it to launch with DXVK enabled via the lutris configuration. Just use lutris to run an exe within the prefix. Got it to work once I used the GE version of wine. Took awhile to troubleshoot problems but it works fine now with no noticeble problems.

OS: 5.15.7-arch1-1
Lutris: 0.5.9.1
Wine: Lutris-ge-7.0rc3-1-x86_64
Anamesis: 2022-01-06

**Comment by Kalidibus** [comment]
Hmm only difference I can see is I'm using the regular launcher and not the quick launcher build. I've been meaning to switch to that anyways, but everything else seems the same. I found that the hostfxr.dll wasn't relevant for me as it worked the same either way.

I'll keep messing around and hopefully I can get it running. Thanks all

**Comment by rekyuu** [comment]
Really excited too see that I was able to launch both Anamnesis and CMTool on Wine 7 (using the GE 7.0rc3-1 runner). I was able to open both, connect to FFXIV, change out models, pose, etc. 

That being said, both applications suffer from their screens going full black except certain elements that are being interacted with. For example, Anamnesis will launch full black, but if I hover over the settings button, that element will show normally. I suspect this has to do with redraws, but I'm no wine expert.

In any case, this was also an issue for XIVLauncher. What they do is check for an environment variable to specify if the program is being run under Wine on Linux, and it changes to software rendering instead:

https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/src/XIVLauncher/App.xaml.cs#L45 

I believe if this was implemented in Anamnesis, then running under Linux should work normally. There may be other elements to this, but I figured I'd post this while I wait for Visual Studio to install on my Windows laptop to test a build.

CMTool didn't have nearly as many issues for some reason though. Blacked out very few times and the program seemed usable. The above resolution could be the same though.

**Comment by Kalidibus** [comment]
Alright think I may have finally gotten it working. The issue I was having with the memory access was resolved by installing the XIVLauncher version on the Lutris site in a new prefix. Queue is too long to test everything right now, but I'll try it out tomorrow. 

Also disabling DXVK fixes the black boxes, but I don't know if that will cause other issues in posing etc, we'll see.

**Comment by rekyuu** [comment]
I'm actually not able to launch the game if DXVK is disabled so I'm hoping we can get these other things fixed. Not really familiar with DXVK either but I assume it has to do with me using an AMD video card.

**Comment by Kalidibus** [comment]
> I'm actually not able to launch the game if DXVK is disabled so I'm hoping we can get these other things fixed. Not really familiar with DXVK either but I assume it has to do with me using an AMD video card.

You should be able to have DXVK enabled for FF, and disabled for Ana

**Comment by rekyuu** [comment]
How do you manage that? I thought DXVK had overrides for the Wine prefix you were using, so disabling it disabled the entire prefix.

**Comment by Kalidibus** [comment]
> How do you manage that? I thought DXVK had overrides for the Wine prefix you were using, so disabling it disabled the entire prefix.

I'm using Lutris which let's you configure the "games" separately under the same prefix

**Comment by rekyuu** [comment]
Okay, so I went ahead and made an application launcher for Anamnesis in Lutris using the same prefix and can confirm that's how DXVK works. I initially started Anamnesis first and then FFXIV, and it failed to start. 

When I start FFXIV and _then_ Anamnesis it works, but that just means the libraries are replaced while the game is running which I wouldn't say is a very good solution. It'll likely affect my next launch as well. Since I use the ACT scripts to launch the game this means that I would have to launch the game via Lutris first to reset the DXVK libraries to be active. 

This does work as a workaround for now though, if anyone else wants to try this for the time being. Having an option to disable hardware rendering within Anamnesis would be the optimal solution if possible.

**Comment by Kalidibus** [comment]
I talked with one of the devs on discord who was graciously able to create a test build which forces RenderMode.SoftwareOnly like XIV Launcher does. 

It effectively seems to bypass DXVK even if it's on in Lutris, so the application behaves the same way. Rendering is fixed, but the pose menu freezes the program.

[Anaerrorlog - linux build test - DXVK ON - rendering errors.txt](https://github.com/imchillin/Anamnesis/files/7864832/Anaerrorlog.-.linux.build.test.-.DXVK.ON.-.rendering.errors.txt)
[Anaerrorlog - linux build test - DXVK OFF - pose menu freezes.txt](https://github.com/imchillin/Anamnesis/files/7864833/Anaerrorlog.-.linux.build.test.-.DXVK.OFF.-.pose.menu.freezes.txt)

some error logs attached in case anyone is curious.

**Comment by PapaBones** [comment]
> I talked with one of the devs on discord who was graciously able to create a test build which forces RenderMode.SoftwareOnly like XIV Launcher does.
> 
> It effectively seems to bypass DXVK even if it's on in Lutris, so the application behaves the same way. Rendering is fixed, but the pose menu still freezes the program.

Would be great to test, where can one check out the test build?

**Comment by LunNova** [comment]
Running `wine reg add "HKCU\\SOFTWARE\\Microsoft\\Avalon.Graphics" /v DisableHWAcceleration /t REG_DWORD /d 1 /f` (w/ correct `WINEPREFIX=`) will turn off acceleration for all WPF apps, instead of needing the app to handle it.

Should be equivalent to setting `RenderMode.SoftwareOnly`, so this doesn't help with poses.

**Comment by LunNova** [comment]
I was able to get anamnesis posing to work with hardware acceleration still enabled by using these dll overrides: `d3d9,dxgi,dxgi.dll=b` and *not* disabling HW acceleration for WPF.

The posing UI is slow to initialize the first time but eventually works.

![image](https://user-images.githubusercontent.com/782440/149433037-b7803604-d966-4e9f-8f64-b67194edabf7.png)

**Comment by Kalidibus** [comment]
> I was able to get anamnesis posing to work with hardware acceleration still enabled by using these dll overrides: `d3d9,dxgi,dxgi.dll=b` and _not_ disabling HW acceleration for WPF.
> 
> The posing UI is slow to initialize the first time but eventually works.
> 
> ![image](https://user-images.githubusercontent.com/782440/149433037-b7803604-d966-4e9f-8f64-b67194edabf7.png)

That seems to do the trick! I'll try testing a bit as well (once the queue ends...)

Here's the Lutris settings for anyone like me who's never had to do these before and was confused by the syntax

![image](https://user-images.githubusercontent.com/93565603/149445833-2a932dd4-337e-48d4-80bd-8fd80256203f.png)

**Comment by Kromilan** [comment]
> > I was able to get anamnesis posing to work with hardware acceleration still enabled by using these dll overrides: `d3d9,dxgi,dxgi.dll=b` and _not_ disabling HW acceleration for WPF.
> > The posing UI is slow to initialize the first time but eventually works.
> > ![image](https://user-images.githubusercontent.com/782440/149433037-b7803604-d966-4e9f-8f64-b67194edabf7.png)
> 
> That seems to do the trick! Thank you so much! Ran some tests and seems like everything works great. Tested some basic poses, as well as loading some poses from my Windows install. All seemed good. Only issue I could note is that moving a bone with the 3D sphere seems to often turn the body part in the opposite direction you'd expect. There's no setting for this, so it must just be an issue with the WINE translation.
> 
> Here's the Lutris settings for anyone like me who's never had to do these before and was confused by the syntax
> 
> ![image](https://user-images.githubusercontent.com/93565603/149451284-02f64dac-e36e-488d-9330-fc37842327d6.png)

Wow, thank you all for figuring this all out. I can confirm that this indeed does the trick. :D I can confirm that it also works when using the quicklauncher. I cannot say anything about ATC though.

**I'll just summarise everything for everyone who finds this thread later and is overwhelmed.**

We had an issue where we could not open the poses menu. The solution was to:
Have Anamnesis and FFXIV as two games in Lutris, which are installed in the same prefix. 
- To do this, first install Anamnesis normally, then in Lutris add a new game and select the Anamnesis.exe
- After you installed Dotnet5, copy or move the hostfxr.dll from Program Files/dotnet/host/fxr/<version> to the same folder where the Anamnesis.exe is located.
To also have posing work properly, configure the Anamnesis game as shown in Kalidibus picture by adding dll-overrids for d3d9, dxgi and dxgi.dll, each with the value b, under runner options.

**Comment by manning390** [comment]
I'm not sure how you guys are able to install it as a separate game in lutris under the same prefix. When I do this the program immediately closes after launching.

**Comment by Kromilan** [comment]
> I'm not sure how you guys are able to install it as a separate game in lutris under the same prefix. When I do this the program immediately closes after launching.

My methode was that I downloaded it and dotnet5 to some directory inside the wine prefix. So for example I moved it to ~/Games/final-fantasy-xiv-online/drive_c/users/<name>/Downloads.
Then in Lutris I clicked on my game and down at the bottom, next to Play, there is a wineglass symbol with an arrow next to it. When I click on the Arrow, a dropdown menue opens and from that I selected "Run exe inside Wine Prefix". I navigated to that download folder and first ran the exe for dotnet. It ran me through the installation process of dotnet 5.
Then I went to ~/Games/final-fantasy-xiv-online/drive_c/Program Files/dotnet/host/fxr/<version>/ and copied the hostfxr.dll file.
I went back to the downloads folder, where I had the Anamnesis-Download unpacked. There I pasted the hostfxr.dll. So then my Downloads-folder contained a folder called Updater, Anamnesis.exe, Download DotNET Desktop Runtime.URL and hostfxr.dll.

That was step one. Step two was to go to Lutris again and in the top left click on the plus icon (I use Gnome, I don't know if the + icon is somewhere else for you). A window opens that lets me add a new game. The settings there are as follows:
under Game Info, I used Anamnesis as Name and Wine as the Runner.
Under Game options for the Executable, click on Browse and navigate to ~/Games/final-fantasy-xiv-online/drive_c/users/<name>/Downloads and select the Anamnesis.exe.
Also under Game Options for Wine Prefix I selected ~/Games/final-fantasy-xiv-online
Finally under Runner options I have DXVK disabled, VKD3D enabled and under DLL overrides, I added the keys "d3d9", "dxgi" and "dxgi.dll". for all I entered the Value "b". All that without quotationmarks.
Click Save.

Now, in my Games Library on Lutris, I have Final Fantasy XIV, which I can start with a double click, an Anamnesis, which I can also start with a double click. I only start Anamnesis when ffxiv is already running and I am logged in. I don't know if that's a requirement though.

In your particular case, the following things might be different:
~/Games/final-fantasy-xiv-online/ might not be the path to your game folder, depending on where you have Lutris install games. Change the paths I gave you to wherever you installed FFXIV.
You might not want to save the Anamnesis.exe directly in that prefix' download-folder. That's fine, you can save it wherever you want. just make sure that hostfxr.dll and the Updater folder are in the same location as the Anamnesis.exe. Honestly though, it won't matter where you put it because you won't be poking around in that prefix a lot anyways.

I hope this could help you :)

**Comment by Frousties** [comment]
Hello, sorry to bump this, but I have a, um, critical problem when trying to run Anamnesis this way

**Without** putting the overrides, it works fine but the pose menu freezes (as already said earlier), but when I try to run it **with** the overrides it just... crashes my whole desktop??
What are the wine libraries you have installed? I'm probably missing something there

I think this is due to the way the UI is rendered in Anamnesis and CMTool because it only happens when I run these two specific programs (for CMTool it only crashes when I press "Load Appearance" so at least I can use that), but I really don't know why it does that???


OS: Arch 5.16.5
DE: KDE
Lutris: 0.5.9.1
Wine: lutris-6.21-6 (also tested 6.10-7 and ge-7.1-7, same thing)
Anamnesis: 2022-01-31 (tested multiple older versions too)

(I don't know where (or if) Lutris saves the logs before the crash)

**Comment by Sibway** [comment]
> I've gotten past the issue with it constantly asking for the dotnet to be installed by moving the file as peeps in this issue suggested, but now that it boots up, I get an error about requiring Windows 10 or newer. Any ideas?

Change the Windows version to Windows 10 using the wine configuration
![image](https://user-images.githubusercontent.com/12155684/227632243-ea2a2389-6dbf-4dc3-aef6-3c1d6869ad4d.png)![image](https://user-images.githubusercontent.com/12155684/227631990-b6a74789-662e-4cc9-8a61-882d83152aee.png)
