### ISSUE TITLE
Secondary Scene actors' bones reverting to previous or 'T' pose upon bone selection

### ISSUE THREAD

**Issue by ThaddeusCleaver** [imchillin/Anamnesis#600]
When entering gpose to pose more than one actor, i.e. Player + Chocobo/Carbuncle, the actor selected for posing second will, upon selection of a given bone, reset it and it's child bones to their last saved position, which, if the game has been freshly launched at the time of posing, will be a T-pose. Bizarrely, it's the actor that's _selected_ second for posing that will do this. Not the carbuncle/chocobo loaded appearance exclusively. The main player actor can also exhibit this behavior. 

At least one example of this resulted in a previously applied pose being restored, so it isn't exclusively detrimental, but the cause should be rooted out in order to make it an optional feature, rather than a bug with occasional perks. 

The effect stops after a pose is loaded onto the secondary actor, or all bones are reset, so it isn't too much an obstacle, but it is an annoyance.

**Comment by Ani-ki** [comment]
Report does not follow template.
