### ISSUE TITLE
Selecting Second Actor in scenes causes bones to reset

### ISSUE THREAD

**Issue by ThaddeusCleaver** [imchillin/Anamnesis#601]
When posing multiple actors, the actor selected second in a scene's bones will revert to their previous pose--which, when the game has been freshly launched, will be a T-Pose. This is consistent, as far as I can tell, as it's happened every time the described process has been gone through--roughly 5 or more times, as of writing. 

This issue can be bypassed by loading a pose onto the affected actor, at which point bones can be selected without incident, but is a notable annoyance. 

**To Reproduce**
1. Enter Gpose with a second posable actor in range
2. Enable posing
3. Select the second actor in the scene
4. Select a bone
5. Bone and it's child bones will reset to last positions 

**Expected behaviour**
Prior to this update, this was not an issue. Now, however, this can cause issues with resetting player emotes if they're selected second, interfering with posing.

**Log file**
[2021-11-02-23-07-02.txt](https://github.com/imchillin/Anamnesis/files/7465082/2021-11-02-23-07-02.txt)

**Comment by Ani-ki** [comment]
Skeletons do be kinda whack at the moment. Can confirm that this doesn't occur in the development build, although I wasn't actually able to replicate this at all in either the release *or* development builds.
Confused about the T-posing? You may need to record this happening.

**Comment by ThaddeusCleaver** [comment]
> 
> 
> Skeletons do be kinda whack at the moment. Can confirm that this doesn't occur in the development build, although I wasn't actually able to replicate this at all in either the release _or_ development builds. Confused about the T-posing? You may need to record this happening.

https://i.gyazo.com/9cf0e86548f65987d8c9c8e816aa4c8e.mp4

**Comment by ThaddeusCleaver** [comment]
Update: I use quicklauncher/a handful of plugins. Loaded XIV normally (without ql) to see if an interaction there was causing the issue. No dice. Problem still occurred.

**Comment by Ani-ki** [comment]
It does look like an old bug we experienced (and thought we'd resolved?) a while back. It's late here so I'll try to replicate again in the morning.

In the meantime, can you try unpinning and repinning the actor(s) and let me know what happens when you try to pose them?

**Comment by ThaddeusCleaver** [comment]
> 
> 
> It does look like an old bug we experienced (and thought we'd resolved?) a while back. It's late here so I'll try to replicate again in the morning.
> 
> In the meantime, can you try unpinning and repinning the actor(s) and let me know what happens when you try to pose them?

At what point in the process should I be doing the un/re-pinning?

**Comment by Ani-ki** [comment]
Sorry, just woke up.

The fact that it prevented the issue is what we're interested in at the moment, so cheers for confirming that for us.

**Comment by ThaddeusCleaver** [comment]
> 
> 
> Sorry, just woke up.
> 
> The fact that it prevented the issue is what we're interested in at the moment, so cheers for confirming that for us.

I think the most successful method waaasss...

- Enable posing. 
- Unpin and re-pin each actor
- Pose.

**Comment by Ani-ki** [comment]
I had a feeling it would be pretty much that. I'm still not able to replicate it on my end, but this at least gives us more insight into the issue, so I'll tinker for a little while longer and keep you posted.

**Comment by Ani-ki** [comment]
@ThaddeusCleaver this should have been resolved as of the latest update. Can you please confirm if the issue has been resolved on your end?

**Comment by ThaddeusCleaver** [comment]
Doesn't  _seem_ to be an issue any longer. If it ever comes up again I'll open a new ticket.
