### ISSUE TITLE
Crash when selecting NPC with loaded appearance

### ISSUE THREAD

**Issue by Maya067** [imchillin/Anamnesis#602]
**Describe the bug**
When you load appearance on an overworld NPC (for instance, materia medler in Limsa Lominsa), if you click on him in game, the game will crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Limsa Lominsa
2. Use the + button to add the materia melder
3. Load a custom appearance
4. click on the npc

**Expected behaviour**
What's strange is that doing the same step on a housing NPC doesn't crash the game. I tried disabling all mods, the bug is still here.

**Log file**
It's a game crash and Anamnesis doesn't generate a log.

**Comment by Ani-ki** [comment]
Anamnesis starts logging as soon as it's launched, so a log would exist.

**Comment by Ani-ki** [comment]
Throwing mine here for context
[2021-11-03-19-57-02.txt](https://github.com/imchillin/Anamnesis/files/7466390/2021-11-03-19-57-02.txt)
:

**Comment by Ani-ki** [comment]
Can successfully replicate the crash in both current release and development builds. Verbose logging doesn't show anything either- [2021-11-03-20-12-21.txt](https://github.com/imchillin/Anamnesis/files/7466422/2021-11-03-20-12-21.txt)

**Comment by Yuuki-Walsh** [comment]
Looks like NPC's were being changed to Player, which ffxiv really doesn't like.
Is fixed for the next version.
