### ISSUE TITLE
other character models aren't recognised in /gpose

### ISSUE THREAD

**Issue by Renpai03** [imchillin/Anamnesis#605]
**Describe the bug**
I can pin other models (other players, pets, companions, etc.) but they can't be found in /gpose mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'pose tab'
2. Click on 'Plus icon'
3. See error

**Expected behaviour**
models are within the active space, can be found outside of /gpose mode, but cannot be found when in /gpose (aside from my own character).

**Log file**
[2021-11-04-01-24-56.txt](https://github.com/imchillin/Anamnesis/files/7475376/2021-11-04-01-24-56.txt)
[2021-11-04-03-29-42.txt](https://github.com/imchillin/Anamnesis/files/7475377/2021-11-04-03-29-42.txt)
[2021-11-04-03-39-46.txt](https://github.com/imchillin/Anamnesis/files/7475378/2021-11-04-03-39-46.txt)
[2021-11-05-00-10-29.txt](https://github.com/imchillin/Anamnesis/files/7475379/2021-11-05-00-10-29.txt)
[2021-11-05-00-20-27.txt](https://github.com/imchillin/Anamnesis/files/7475380/2021-11-05-00-20-27.txt)
[2021-11-05-00-26-42.txt](https://github.com/imchillin/Anamnesis/files/7475381/2021-11-05-00-26-42.txt)
[2021-11-05-00-40-31.txt](https://github.com/imchillin/Anamnesis/files/7475382/2021-11-05-00-40-31.txt)
[2021-11-05-01-02-32.txt](https://github.com/imchillin/Anamnesis/files/7475383/2021-11-05-01-02-32.txt)

**note**
I also recorded an example since I'm not sure if it's just a me thing.
https://youtu.be/pYUQE1V2pRY

**Comment by Ani-ki** [comment]
Carbuncles should be left as BattleNPCs, or have an appearance loaded onto them directly.

**Comment by Renpai03** [comment]
there weren't any PCs around there when I recorded, so I couldn't show it, but it's the same, I pin them to the model list, then go into /gpose, and they can't be found.

**Comment by Ani-ki** [comment]
I'm referring to when you manually changed their entity type. What happens when you load an appearance onto them directly without fiddling with anything else?

**Comment by Yuuki-Walsh** [comment]
Other players will only enter gpose with you if you are in a party, are firends, or are in an instance together. This is how gpose works, and theres nothing we can do about it.

**Comment by Renpai03** [comment]
It wouldn't reognise my carbuncle at all, it was why I tried messing with vhanging the "battlenpc" tag.

Concerning other players, I had actually been able to pin non party members once before, so I never questioned it until now, when it didn't work.

**Comment by Renpai03** [comment]
have confirmed that everything is in order, the problem that plagued me was that when I pinned my carbuncle, it would automatically change to a female hyur, so I was confused that it wasn't registering as a poseable actor when it all of a sudden didn't do so, confirmed that all I had to do was load a character preset that I saved.

can also confirm that partied characters are found and no-partied aren't. The "Partied" player status also applies to friends, so that's something I discovered was an addition to my confusion as to why things weren't working before, when trying to pose a FC member who wasn't on my friend's list.

Thanks for the help, and apologies for my stupidity.

**Comment by Ani-ki** [comment]
Sorry, just to clarify, are you confirming that loading the appearance onto the entity directly resulted in the desired effect?

**Comment by Renpai03** [comment]
yes, that's what I am confirmed after testing.

**Comment by Ani-ki** [comment]
Fantastic, thanks for the clarification. I'll close this for now, but if it occurs again in the next update, please don't hesitate to poke us in here and we can reopen it.
