### ISSUE TITLE
The failed to tick selected actor issue

### ISSUE THREAD

**Issue by Soysausage** [imchillin/Anamnesis#606]
Saw a post 6 days ago by rensa with no resolution:

"Unfortunately, the update seems to have made the issue even worse, as now I am unable to turn actors in to players at all. Not any NPC or any minion."

Quote from that post, im having same issue, im guessing fix for this is still a WIP?

**Comment by Ani-ki** [comment]
Please do not open duplicate tickets, especially ones that do not follow the issue reporting template.
