### ISSUE TITLE
Saving the exact Face R/P/S Value

### ISSUE THREAD

**Issue by JSharpie** [imchillin/Anamnesis#608]
**Is your feature request related to a problem? Please describe.**
I'm not exactly sure how a .pose file is saved and what it looks for and I completely understand face is a hard thing to work on via the FAQ.
However I do want to propose something if this is not implmented yet or if it's overlooked bug.

I want a specific facial expression from a emote and want to load that expression

I did a test on how values work with the save file and loading the file doesn't load the same value

**Repro Steps**
1. _[ingame]_ /gpose execute emote and freeze character
2. _[Anam]_ Enable editing and Select the entire face nodes 
![image](https://user-images.githubusercontent.com/53364876/140617446-1fa45907-ec0d-49fc-b2f5-3c0ab771d8b9.png)
3. Save as "Selected Bone' (named it HyperHappy for ref) [HyperHappy.zip](https://github.com/imchillin/Anamnesis/files/7490882/HyperHappy.zip)
4. Individually look at each individual bone and look at it's R/P/S values and write it down (provided csv file for the values) [Lalafell Beaming Smile from the Emote 'Toast' - Sheet1.csv](https://github.com/imchillin/Anamnesis/files/7490893/Lalafell.Beaming.Smile.from.the.Emote.Toast.-.Sheet1.csv)
5. Disable editing
6. _[ingame]_ "Disable emote overwriting" so character is in default standing value
7. Toggle Character motion on/off so it freezes again
8. _[Anam]_ Load the _.pose_ file either as normal loading or expression loading
9. Notice the face being deformed as expected in the FAQ
10. Select one of the bones and compare with the original value. Example on one
![image](https://user-images.githubusercontent.com/53364876/140617840-4c61003d-f8f5-44f5-aeb4-070d632e7229.png)

My understanding is that regardless of the Head and Body Position/Rotation the face values won't change. "Tested"

**Describe the solution you'd like**
I would like to see face or expression partitioned as a separate group
Or have it as an **_option_** (Whether it be a toggle or a separate load method) to use the _exact R/P/S values_ instead.

I don't know exactly how the models work in the game as different shapes exists however I think that it is a lot easier to fix deformalities this way (if it exists)
Reason because the value wouldn't be as deformed.

Let me know if you need more information or clarification.

**Comment by Yuuki-Walsh** [comment]
Bone rotations are currently relative to the characters root rotation, so unless all of the bones from the root up through spine and head are also the same, the rotation values of the face bones wont match.

I'm not sure what the actual feature request here is, are facial expressions not loading correctly when using the 'load expression' option?

**Comment by JSharpie** [comment]
> I belive face bone rotations are relative to the head rotation, so if you 0-out the head rotation, the numbers should match?
Here's a video of the facial values _do not_ change when I turn the head.
https://user-images.githubusercontent.com/53364876/140632965-45136cc5-c607-4845-9074-3f44b14c46e0.mp4
The same thing does when you do any rotation to the body that would modify the head.

Which would mean that you should be able to just save the face as a pose/expression and load it as an expression easier.

**Comment by Ani-ki** [comment]
You may need to reupload that video, as it's not loading correctly.

**Comment by JSharpie** [comment]
Here's a Google Drive upload https://drive.google.com/file/d/1W_Ib76pQn-dzVuZXIcjCwZr6n4yNRLpI/view?usp=sharing

**Comment by Yuuki-Walsh** [comment]
oh, yes, the rotation and position values shown in the UI are modified to be parent-relative, however the values used in-memory and in the pose file are the raw character-relative values that ffxiv uses.

(I belive scale is currently not working exactly correctly, and is still character-relative in the UI)

**Comment by JSharpie** [comment]
Yes, which is why I was suggesting if there could be  an _option_ to have it save as exact value.
It could even be a complete different file type.

Extra use cases.
The past few hours. While I was was thinking about poses with specific expressions.
Like eyes from a specific emote and mouth from another emote
So selecting all the eye nodes, then import selected bones
Then select all the mount, then import selected bones would make it so much easier to fix abnormalities if the exact values were imported.

**Comment by Yuuki-Walsh** [comment]
ah yea, I see what you're getting at now, yes thats similar to #286, which has been on our radar for a while.

**Comment by JSharpie** [comment]
Awesome! I really believe this can really cut down on posing workflow by a lot.

**Comment by Ani-ki** [comment]
Given this is a duplicate request, I'll be closing this, and the discussion can continue in #286. It's worth enduring you've checked existing issues before opening new ones.
