### ISSUE TITLE
Pose Flipping no longer working

### ISSUE THREAD

**Issue by Yuki-Walsh** [imchillin/Anamnesis#610]
**Describe the bug**
Flipping a pose is no longer functioning correctly after the recent skeleton upgrade.

**To Reproduce**
Attempt to flip a pose, see that the pose does not flip, but distorts strangely.

**Expected behaviour**
The pose should flip correctly.

**Comment by Yuuki-Walsh** [comment]
I'll be disabling the flip button until we can get this resolved.

**Comment by Yuuki-Walsh** [comment]
@werlej maybe could take a look at this again at some point? the flip/mirror code is beyond me.

**Comment by werlej** [comment]
@Yuki-Walsh yeah I'll have to take a look, if the behavior looks completely random on every bone (i.e. trying to flip a finger looks just a strange as trying the whole pose) my first guess would be a coordinate system and/or rotation transform mismatch (especially if the skeleton rework changed anything with how the transforms are stored) and is flipping the wrong quaternion.
