### ISSUE TITLE
New folder not showing up when created

### ISSUE THREAD

**Issue by cspaen** [imchillin/Anamnesis#612]
**Describe the bug**
When clicking the "Create folder" button while saving a pose, the new folder doesn't actually show up. It does, however, create a new folder on the file system itself, it just doesn't show in Anamnesis.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Pose'.
2. Click on 'Enable' to enable your posing.
3. Click on 'Save'.
4. Click on 'Create folder'.
5. Nothing happens. Check the file system and the new folder is there with an appropriate timestamp of the button being pressed.

**Expected behaviour**
A new folder to save poses in to show up when clicking 'Create folder' button.

**Comment by Ani-ki** [comment]
Resolved. See #596.
