### ISSUE TITLE
When i open gpose, error pop !

### ISSUE THREAD

**Issue by KiyonaEl** [imchillin/Anamnesis#615]
**Describe the bug**
When I type /gpose in game, error appear !

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'type /gpose'

**Expected behaviour**
Mh.. Not to see that error ? Don't know what to say here ! Sorry !

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well
[2021-11-09-04-14-02.txt](https://github.com/imchillin/Anamnesis/files/7501742/2021-11-09-04-14-02.txt)
.

**Comment by Ani-ki** [comment]
Most issues are already resolved in the current dev build, and already being discussed in #599.

Closed as this is a duplicate.
