### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by Kibou-Shitateya** [imchillin/Anamnesis#616]
Well, when I went to resize Anamnesis' window inside for a larger screen so I could see everything, I accidentally hit 2.0 size, and I'm stuck on how to size it back down to it's original, I've deleted it, and redownloaded it several times, I've tried moving it up past the computer screen to find the cogwheel, but it won't let me, and I've ran out of options that I can think of that would help.

**Comment by Yuuki-Walsh** [comment]
try restting your preferences: https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#resetting-the-toolsettings

**Comment by Ani-ki** [comment]
Issue does not use reporting template provided, and is **[already covered in the wiki](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#resetting-the-toolsettings)**.
