### ISSUE TITLE
Wet effect problem

### ISSUE THREAD

**Issue by HungBunZ** [imchillin/Anamnesis#618]
**Describe the bug**
The option to adjust the amount of Wet Effect doesent move. It sits at max and doesent let you adjust the amount.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the Tool
2. Select Wet effect
3. Click the Wet effect symbold that lets you adjust the amount. 
4. Try to move the slider from max to 50% of the whole slider bar. It keeps jumping back to max.

**Expected behaviour**
The Wet effect should sit at the amount i have set up. For example.. i want the Wet effect to only show like 30 or 40% and stay there.

**Comment by Yuuki-Walsh** [comment]
This is fixed for the next release.
