### ISSUE TITLE
Playermodel in Gpose ends up as NPC

### ISSUE THREAD

**Issue by HungBunZ** [imchillin/Anamnesis#619]
**Describe the bug**
Sometimes when i use the Tool and i try to change certain stuff, the tool turns me into an NPC? When i select the option to show myself only, i end up with no character model at all and the tool starts to red mark my set up character inside the tool on the left bar. 
**To Reproduce**
Steps to reproduce the behaviour:
1. I have no clue. it randomly happens. 

**Expected behaviour**
To not change me into an NPC enemy or something

**Comment by Ani-ki** [comment]
Do you have a log for this?

**Comment by Ani-ki** [comment]
Without a log file, this issue is incomplete, and likely was fixed in the latest update.
