### ISSUE TITLE
When selecting a non-PC Anamnesis doesnt give the prompt to change to one.

### ISSUE THREAD

**Issue by Yuzumii** [imchillin/Anamnesis#620]
**Describe the bug**
Usually when you open the tab for , for example the Emerald Carbuncle, the popup for changing the Actor to a Human NPC comes up. This does not occur to me right now regardless of restarting or not.
Since its a non-poseable Model, i also cant change the Model afterwards essentially making the Entity useless.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the program.
2. Click the + to open a new character and select Carbuncle.
3. Popup doesnt come up.

**Expected behaviour**
Popup for Model Change should pop up to transform the mentioned Carbuncle into a poseable Human.

**Log file**
[2021-11-10-23-31-17.txt](https://github.com/imchillin/Anamnesis/files/7516339/2021-11-10-23-31-17.txt)

**Comment by Ani-ki** [comment]
The [**changelog for the latest release**](https://github.com/imchillin/Anamnesis/releases/tag/v2021-10-30-beta) outlines that the function was  removed as it's now redundant, and the wiki was updated to match. We highly recommend reading the changelog when updating the tool in future.
