### ISSUE TITLE
Unable to Undo Actor Type changes

### ISSUE THREAD

**Issue by Kromilan** [imchillin/Anamnesis#622]
**Describe the bug**
When you change the Actor Type of a Character, you can no longer edit them (makes sense, you cannot change the clothing of an aetheryte for example). However, you also cannot edit the actor type back. Once something's actor has been changed, it stays as that actor.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pin any character
2. Change the Actor Type to anything other than Player, Battle NPC or Event NPC
3. Switch to another pinned character
4. Switch back to the pinned character whose actor you changed

**Expected behaviour**
The Actor Type should remain editable.

**Actual behaviour**
The Actor Type can no longer be edited. i.e. you cannot undo these steps.

**Comment by Yuki-Walsh** [comment]
We've fixed for the next release this by not allowing changing actors to types we cant edit in teh first place.
