### ISSUE TITLE
Unable to Select Model

### ISSUE THREAD

**Issue by kairiuq** [imchillin/Anamnesis#623]
Unable to find and select model in Anamnesis, character Dulia-Chai

Step 1: Checked file number in CMtool, obtained file number in CMtool
Step 2: Opened Anamnesis, loaded file number into Anamnesis
Step 3: Observed only files for the Wandering NPC (Disguised Fae) and Wind up Dulia only available in Anamnesis
Step 4: Dulia is selectable in CMtool but otherwise unposable as declared a unique model and unable to be utilized by CMtool standards
Step 5: Checking other permutations of Dulia Chai results in no other results

Result: cannot find any other useable model of Dulia Chai in Anamnesis. Conclusion: Dulia Chai has not been added to the localized search files of Anamnesis by oversight

**Comment by Ani-ki** [comment]
Please provide a recent log file.

**Comment by Yuuki-Walsh** [comment]
Since NPC's are pulled directly from the game, she should appear in the NPC list. Have you changed NPC filters (top)?
![image](https://user-images.githubusercontent.com/379714/141665984-c0bef631-f0a8-4a3c-b1fe-2e390f14c669.png)

**Comment by kairiuq** [comment]
ah I hadn't tried that, thanks for the heads up. thank you!

**Comment by Ani-ki** [comment]
@kairiuq did filtering the NPC list solve this issue for you?

**Comment by kairiuq** [comment]
yeah now it works, thank you!

**Comment by Ani-ki** [comment]
Righto, closing this then.
