### ISSUE TITLE
Tail selector is hidden from view/below the window and you can't scroll to it

### ISSUE THREAD

**Issue by Fyona-chan** [imchillin/Anamnesis#624]
When loading a character with a tail that has multiple variations, you can't see where to select the tail type and you can't scroll down to it. You see just the barest hint of the -/+ buttons at the very bottom of the screen, but there is no way to see what that line actually says. Resizing the window dose not help.

**To Reproduce**
Load any character with a tail.

**Expected behaviour**
Being able to see what tail number I have on my character.

**Log file**
There is no log file as this is not a procedure thing, it is a UI thing. I have attached a picture of the area in question. You can see in the circled area the very tops of the -/+ buttons and that line should be for the tail type. You just can't see what it says because it is below the UI window.

![Screenshot (65)_LI](https://user-images.githubusercontent.com/87735681/141669643-ee8904ba-c254-4ed0-9a59-393ca5625bc5.jpg)

**Comment by Yuuki-Walsh** [comment]
Fixed for the next release
