### ISSUE TITLE
Helm (Met) and Top Extended bones not appearing in Pose Matrix view

### ISSUE THREAD

**Issue by Fyona-chan** [imchillin/Anamnesis#625]
**Is your feature request related to a problem? Please describe.**
I used to be able to adjust the visor portion of helms using the Helm button under the Equipment section. That option is no longer there. I used to use this to fix when the visor would move to the side of the head. I can't do that anymore, so it severely limits the head pieces I can use in poses.

**Describe the solution you'd like**
I would like to see the Helm button returned.

This is from an older version of Anamnesis. You can see the Helm options at the bottom.
![Screenshot_28](https://user-images.githubusercontent.com/87735681/141701109-f6326537-8e04-4570-842f-1266f6044bc0.png)

This is the new version, showing the Helm buttons no longer there.
![Screenshot (67)](https://user-images.githubusercontent.com/87735681/141701209-2d0307d1-7eeb-489e-8880-1dd7350a0988.png)

And this is the issue I use the Helm button to fix. The visor portion of this head piece has moved to the side of the head and I can't move it without the Helm button.

![ffxiv_11142021_140243_369](https://user-images.githubusercontent.com/87735681/141701231-eaf148d5-b294-473f-8817-cf32f231a950.png)

Thank you for your time.

**Comment by Ani-ki** [comment]
Thanks for bringing this up. This may be attributed to the new skeleton system, so we'll have a look into this as soon as we can.

**Comment by Yuuki-Walsh** [comment]
This has been fixed for the next release.
Addiitionally, the visor will now follow the head when loading poses without visor bones.
