### ISSUE TITLE
Critical Error Upon Creating Pose File Folder 

### ISSUE THREAD

**Issue by Falorei** [imchillin/Anamnesis#626]
**Describe the bug**
Anamnesis encountered a critical error after creating a folder before the ability to save ".pose" file within it. This resulted in losing created poses as Anamnesis was forced to close. 
Encountered only once, tried to replicate and instead, Anamnesis creates the new folder but refuses to retain a name and instead becomes "New Folder".

**To Reproduce**
1. Go to Pose Matrix>'Load' Button>'Built in pose' Folder>'Masculine' Folder>'Miqo'te' Folder>'BedDoze SideSleeper'pose>*adjusted pose to customize*'
2. After custom posing Click on 'Save' Button in posing matrix>'Create New Folder' Button>Name New Folder
4. Anamnesis Error displayed "Encountered Critical Error" and forced to close

**Expected behaviour**
Should Create Folder that can be opened to save individual ".pose" files

**Log file**
[2021-11-14-14-18-49.txt](https://github.com/imchillin/Anamnesis/files/7534897/2021-11-14-14-18-49.txt)

**Comment by Ani-ki** [comment]
Can you confirm where you're trying to make this new folder?

**Comment by Falorei** [comment]
That is correct. It occurred after i tried to make the new folder using
anamnesis rather than file explorer.

**Comment by Ani-ki** [comment]
Sorry, I think there's been a misunderstanding. I was asking *where* you were making the new folder, not what system.

**Comment by Falorei** [comment]
I’m sorry, i was trying to make it into a nested set of folders. In this
case anamnesis>“pose files” folder>”sfw” folder>“New folder”

**Comment by Yuuki-Walsh** [comment]
This has been fixed for the next release.
