### ISSUE TITLE
Favourited NPCs don't show up at top of list

### ISSUE THREAD

**Issue by Tippetyt0p** [imchillin/Anamnesis#627]
**Describe the bug**
NPC models marked as favourites aren't sorted at the top of the NPC list. 

**To Reproduce**
1. Open NPC list
2. Click the star next to one of the models

**Expected behaviour**
Model marked as favourite should be sorted at the top of the list.

**Log file**
N/A, is a UI error.

**Comment by Yuuki-Walsh** [comment]
Fixed in 562153d954c60ac0be19869a683ab228d2ccd27b for the next release
