### ISSUE TITLE
In some cases 'Remove all Equipment' removes main hand weapon, but leaves tint and variant behind

### ISSUE THREAD

**Issue by Cy399** [imchillin/Anamnesis#629]
The 'Remove All Equipment' Button sometimes removes the mainhand weapon, but does not remove item variant or tint, which causes a gpose loading error when a model loaded with said 'blank' item is loaded in.

**To Reproduce**
1. Remove All Equipment button is pressed
2. In rare occassions, the mainhand weapon is removed, but the variant, typically 2201, as wel as the tint does not get removed either
3. This error can also sometimes occur when the 'None' item is equipped instead

**Expected behaviour**
In most cases, the button will leave behind the mainhand and offhand still with the character.

**Comment by Yuki-Walsh** [comment]
The remove all equipment button does not remove main or off hands, it does try to hide them though.
