### ISSUE TITLE
Actors Unable to be Detected

### ISSUE THREAD

**Issue by kairiuq** [imchillin/Anamnesis#630]
Step 1: Entered the FC room
Step 2: successfully changed a carbuncle and a Mender to a active actor
Step 3: Entered gpose
Step 4: Anamnesis (current build) did not detect a working skeleton or model for the Mender
Step 5 onward, repeated process with multiple restarts and enter and exits from the room, refreshes of Anamnesis build released this weekend (Nov 14) and currently, the new skeleton system cannot detect a  House Vendor or a Mannequin. Working as intended(?)
Step 6: Went to GC and checked the squadron, all good on this end, nothing changed here just to make sure it worked here.

**Comment by Ani-ki** [comment]
Issue does not follow reporting template.
