### ISSUE TITLE
Option to change iris size

### ISSUE THREAD

**Issue by roy-van-dijk** [imchillin/Anamnesis#636]
**Is your feature request related to a problem? Please describe.**
It seems there is no option to change the iris size in the character tab. I think it is the only option from the character creator that is missing. I couldn't find it in CMTool either, so maybe there is a reason for it.

**Describe the solution you'd like**
Add an option to change the iris size in the character tab.

**Comment by Yuuki-Walsh** [comment]
You can change iros size by changing the eye number, 0-4 are small, and 128-132 are large, I think.
We should add a check box to do this automatically, though.
