### ISSUE TITLE
Default Actor Load Error

### ISSUE THREAD

**Issue by rmaroney** [imchillin/Anamnesis#637]
**Describe the bug**
After going into a private small estate in the Mists (shared from someone else), I had my character on SMN and had a carbuncle out and opened Anamnesis. On opening, my default actor button in the top left started flashing red with the failed to tick actor error, then back to normal and repeating.

Changing any character details on the appearance tab had no effect on the in-game model and going into GPose stopped the error, only to have it appear again when leaving GPose. Restarting Anamnesis and even reinstalling it made no changes.

On leaving the house, the issue fixed and re-entering the house did not cause it to start again.

https://user-images.githubusercontent.com/22939522/142750265-371b250a-3afe-4ef1-bba3-85150fbe714b.mp4

**To Reproduce**
Steps to reproduce the behaviour:
1. Unsure how it happened, occurred randomly when inside a private small Mists house.

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

[2021-11-21-04-34-58.txt](https://github.com/imchillin/Anamnesis/files/7575771/2021-11-21-04-34-58.txt)
[2021-11-21-04-35-40.txt](https://github.com/imchillin/Anamnesis/files/7575772/2021-11-21-04-35-40.txt)
[2021-11-21-04-37-10.txt](https://github.com/imchillin/Anamnesis/files/7575773/2021-11-21-04-37-10.txt)
[2021-11-21-04-43-26.txt](https://github.com/imchillin/Anamnesis/files/7575774/2021-11-21-04-43-26.txt)

**Comment by Ani-ki** [comment]
Extended Appearance strikes again :pepehands:. It's basically in a loop of finding and failing to find the actor. Have you loaded any appearances at all, especially any appearances that take advantage of Extended Appearance?

**Comment by rmaroney** [comment]
Nope, I was on default appearance, nothing on the extended side. I had yet to load anything into Anamnesis at the time, I had just opened it and was about to add the carbuncle to the list of actors when I noticed my actor icon messing up. Even trying to load anything didn't fix anything.

**Comment by Ani-ki** [comment]
@rmaroney we've done some pretty significant rewrites; could you please let us know if this is persisiting for you?

**Comment by zenakrua** [comment]
Issue happened to me, after loading another character's appearance/equipment. Had to zone out to resolve.
