### ISSUE TITLE
A TAsk's exception(s) were not observed either by Waiting on the Task or acessing it (critical error)

### ISSUE THREAD

**Issue by Dndprincess1** [imchillin/Anamnesis#638]
[2021-11-21-12-31-09.txt](https://github.com/imchillin/Anamnesis/files/7576832/2021-11-21-12-31-09.txt)

**Comment by Dndprincess1** [comment]
Happens over and over and over when opening character tab

**Comment by Ani-ki** [comment]
Issue does not follow issue reporting format.
