### ISSUE TITLE
Anamnesis crashes/closes when opening character tab

### ISSUE THREAD

**Issue by moonkeep** [imchillin/Anamnesis#640]
Whenever the character tab is opened, it crashes/Anamnesis encounters an error & closes, usually when there is more than one character, pc, or npc on screen within gpose but can occur with just 1 character on screen as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis in Gpose like normal
2. Click on the "Character" tab

**Expected behaviour**
The character tab to simply open.

**Log file**
[2021-11-22-15-23-44.txt](https://github.com/imchillin/Anamnesis/files/7584132/2021-11-22-15-23-44.txt)

**Comment by Ani-ki** [comment]
This issue should hopefully be resolved with our Lumina integration rewrite. Apologies for the inconvenience between now and the next update! Your patience is appreciated!

**Comment by Yuuki-Walsh** [comment]
Duplicates #635
