### ISSUE TITLE
Dye Selection Crash

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#643]
**Describe the bug**
Opening the dye selection panel crashes the program.

**To Reproduce**
Launch Anamnesis, character tab, open dye selection panel on chest slot, watch program freeze up and close.

**Expected behaviour**
Opening the dye selection panel as normal.

**Log file**
[2021-11-26-04-36-08.txt](https://github.com/imchillin/Anamnesis/files/7607789/2021-11-26-04-36-08.txt)

**Comment by Yuki-Walsh** [comment]
This has been fixed, I'm issuing a hotfix, so you'll need to download the the release from 
https://github.com/imchillin/Anamnesis/releases/tag/v2021-11-26-beta
