### ISSUE TITLE
Clicking Dye box on an empty item slot crashes the tool

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#646]
**Describe the bug**
Anamnesis locks up then crashes instead of erroring out when attempting to select Dyes on an equipment slot that has nothing in it. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove an item from a slot (e.g. hands set to nothing)
2. Click on Dye box
3. Ana freezes, then crashes out

**Expected behaviour**
I would have expected either an empty box or list of dyes, or an error "yo dawg, theres nothing to dye" 

**Log file**
[2021-11-26-22-02-56.txt](https://github.com/imchillin/Anamnesis/files/7611303/2021-11-26-22-02-56.txt)

Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
Resolved w/ latest update.
