### ISSUE TITLE
Can't load cmtool saved gearset files anymore

### ISSUE THREAD

**Issue by cspaen** [imchillin/Anamnesis#647]
**Describe the bug**
Since the release of yesterday (26th November) you cannot load outfit appearances anymore that were previously saved with CMTool (.json files). Anamnesis and CMTool Appearance (.cma) save files work just fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "Character" tab
2. Click on "Load"
3. Locate a CMTool Gearset file (.json)
4. Load it in
5. Character reloads in-game but appearance not matched.

**Expected behaviour**
Outfit to match the outfit from the saved .json file.

**Log file**
[2021-11-27-12-42-43.txt](https://github.com/imchillin/Anamnesis/files/7611648/2021-11-27-12-42-43.txt)

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release
