### ISSUE TITLE
Rotation Position Scale Values save and load (with video)

### ISSUE THREAD

**Issue by JSharpie** [imchillin/Anamnesis#648]
**Describe the bug**
Rotation Position and Scale isn't saving or loading correctly.
It seems like it has gotten better but things could use improvement. I posted in #608 which was merged to #286 about using exact value

I'm not sure if it's considered a bug or a FR I could not reopen the previous tickets.

**To Reproduce**
Steps to reproduce the behaviour:
Here's a updated on my testing out the save and load this time going into more details and only using the mouth since that is the most noticable.
https://drive.google.com/file/d/1vNs3bNGgpwlDsO6jroJG8Mm8ruaFInhF/view?usp=sharing

0:00-1:15
Showing the scale of the mouth

1:17-1:38
Selecting a node changes the structure (this has nothing to do with the current issue, it's something i noticed while making the video)

1:40-
Restting the original emote structure and saving the entire thing

2:05
Resetting pose and pausing it

2:07
Loading expression

2:20
Double checking RPS marking 'x' that has not imported correct value

One thing I noticed that was consistent was that it isn't importing the scale to the value at all it defaults it to 1,1,1.

**Expected behaviour**
Load in the exact value for the face from the .pose file. 

**Log file**
Non needed

**Comment by Yuki-Walsh** [comment]
expressions and poses do not include scale or position values when loading, you need to use the "load full transform" option if you want to include scale.

**Comment by JSharpie** [comment]
I see, then I suppose if this could become a feature request so it will do what I mentioned above.
Even if it's a toggle or a different kind of save/load file. I don't know what would be the best approach.

I think having this would make saving and loading expressions so much easier.

**Comment by Yuki-Walsh** [comment]
well, all saves do include full rotation, scale, and position informtion, the various load options use different parts of the file.
If you want to load an expression with the scales and positions, select the head bones you want, and use "load full transform".

Using scale and positions between races will break pretty badly though, so the default is always only rotations.

**Comment by JSharpie** [comment]
I understand option bloat could be an issue. 
I think it'll create usecases where if people happen to create expressions only. Like, let's say they have a pose already in place and think, maybe I want to try a diffenent expression while holding a pose. Or a just change the eyes and import that only. 

If it's in the save file anyway, I would hope to at least do a test to see if it's useful or not as an option (somehow). Also have a warning about it potentially breaking.

However, if this seems too niche and/or complicated then it's ok to close this. I just thought it'll be useful for ease of use.

**Comment by Ani-ki** [comment]
Given this is incredibly niche and not really something we're prepared to put time into at this stage, I'm going to close this ticket, and we'll look at perhaps reopening it down the track once other matters have been taken care of. We will be adding a 'load full transforms on selection' option in the near future, which may assist with this request.
