### ISSUE TITLE
I've been clicking for days

### ISSUE THREAD

**Issue by Vassagoxiv** [imchillin/Anamnesis#651]
![image](https://user-images.githubusercontent.com/87282182/143951758-fa8c7dfc-71b9-402c-939d-72ca65be510f.png)

I think I had to click more than 300 times for that to go off. Here's whatever that Error message told me to send here.
[2021-11-29-17-07-36.txt](https://github.com/imchillin/Anamnesis/files/7621504/2021-11-29-17-07-36.txt)

**Comment by Ani-ki** [comment]
Issue does not follow reporting template.
