### ISSUE TITLE
Anamnesis does not work with Endwalker

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#652]
**The tool cannot be used with the new expansion.**
_Please don't open duplicate tickets guys I'm begging you._

**No really guys the tool doesn't work yet, please stop opening tickets. We'll tell you when it's working.**

**Game Data:**
- [x] BattleNpc
- [x] BattleNpcName
- [x] CharaMakeCustomize
- [x] CharaMakeType
- [x] Companion
- [x] EquipRaceCategory
- [x] EventNpc
- [x] EventNpcAppearance
- [x] Item
- [x] Mount
- [x] Perform
- [x] Race
- [x] ResidentNpc
- [x] Stain
- [x] Territory
- [x] Tribe
- [x] Weather
- [x] Weather Rate

**Signatures:**
- [x] ActorTable
- [x] GPoseActorTable
- [x] GPoseFilters
- [x] SkeletonFreezeRotation 
- [x] SkeletonFreezeRotation2
- [x] SkeletonFreezeRotation3
- [x] SkeletonFreezeScale
- [x] SkeletonFreezePosition 
- [x] SkeletonFreezeScale2
- [x] SkeletonFreezePosition2
- [x] SkeletonFreezePhysics
- [x] SkeletonFreezePhysics2 
- [x] SkeletonFreezePhysics3
- [x] GposeCheck
- [x] GposeCheck2
- [x] Territory
- [x] GPose
- [x] Weather
- [x] GPose Weather
- [x] Camera
- [x] Time
- [x] TimeStop

**Features:**
- [x] Actor Refresh
- [x] Weather
- [x] Appearance
- [x] Equipment
- [x] Extended Appearance
- [x] Model
- [x] Posing
- [x] Transparency
- [x] Camera
- [ ] #661

**Comment by Ani-ki** [comment]
Missing signatures detailed above in edited OP.

**Comment by Ani-ki** [comment]
Classes that are potentially out of date:
- `ActorMemory.cs`
- `WeaponMemory.cs`
- `ActorEquipmentMemory.cs`
- `ItemMemory.cs`
- `ActorCustomizeMemory.cs`

**Comment by Yuki-Walsh** [comment]
All the offsets seem to be sorted now except for actor transparency.

Still missing signatures, though. Don't get your hopes up everyone.

**Comment by Yuki-Walsh** [comment]
We've gotten signatures for Camera now, and the signatures we have for time are behaving strangely, so might need more investigation there.

Likely to release with time disabled, as its not a critical feature, compared to posing.

**Comment by Yuki-Walsh** [comment]
going to bump time control to its own issue and close this one since the bulk of the work here is done.

**Comment by Ani-ki** [comment]
Reopening this because people are getting the wrong idea.

**Comment by Ani-ki** [comment]
We'll keep the time one open and separate, and close both when we actually push a build.
