### ISSUE TITLE
Distorted hairs and expression when posing disabled

### ISSUE THREAD

**Issue by seirinne** [imchillin/Anamnesis#653]
So, I noticed that there's an FAQ already about this, but after following the steps, I still got an error. 

1st, I already enter the Gpose and disable all motion
2nd, I disabled the poses
3rd, I load the whole transformation and it still got my character's hairs and (sometimes) expression distorted
4th, after I disable the pose, the distortion was gone for a brief second before the char got back to where it was before
5th, sometimes it doesn't work and sometimes it works so it irritates me that it seems like random occurance without knowing where the wrong thing.
6th, the program is very laggy

Can someone please tell me where did I go wrong or how to fix this? I already updated the app yesterday to the latest one.

I attach the video to the google drive here :
This is the 3rd problem's video
https://drive.google.com/file/d/1RauWbWcI5oYhvphpRZqnwvRgpa682_8E/view?usp=sharing

This is after I disabled the pose and a moment before it got back to normal pose, it got better (4th problem)
https://drive.google.com/file/d/1RZY-dtHlONdvyL-w-BknORDFqsVlgAm7/view?usp=sharing

**Comment by Ani-ki** [comment]
Issue does not follow reporting template.
