### ISSUE TITLE
Anamnesis failing to pick up actors as soon as /gpose is enabled.

### ISSUE THREAD

**Issue by CharAznable117** [imchillin/Anamnesis#654]
I recently tried to get anamnesis to work getting group gpose photo's done in Kugane. Upon going into gpose in game, it gives the "this actor cannot be found" error and red's out other players. I even tried doing this with minions and NPC's and the error persists. In addition, this seems to also happen everywhere else with the most recent update to anamnesis, as even going to my own fc room, it reds out even npc's and it does not present the option upon right clicking them, to turn them into players.

**To Reproduce**
Steps to reproduce the behaviour:
1. head to kugane, open anamnesis, 
2. load in any players/npc's/minions as actors
3. switch to /gpose in game

**Expected behaviour**
all actors barring yourself will be red'd out with the "unable to find actor" error.

**Log file**

1st log is kugane

[2021-12-01-17-25-51.txt](https://github.com/imchillin/Anamnesis/files/7636063/2021-12-01-17-25-51.txt)

2nd log is in fc room with npc vendors

[2021-12-01-17-32-13.txt](https://github.com/imchillin/Anamnesis/files/7636068/2021-12-01-17-32-13.txt)

**Comment by Yuki-Walsh** [comment]
many NPC's will not enter gpose with you unless you load an appearance onto them first to change their actor type.
Try loading a saved apeparance, or an NPC appearance before entering gpose.

**Comment by CharAznable117** [comment]
This is about regular player characters, not just npcs.

**Comment by Ani-ki** [comment]
We'll have to leave this on the backburner until after 6.0 support has been added.

**Comment by CharAznable117** [comment]
Update: still occurring on a saved appearance. Issue still occuring with npc's and players, Even manually changing their actor type seperately also results in the same. The pin search for additional actors also comes up blank as soon as it transitions to gpose.

**Comment by Rishea** [comment]
Also having this issue with both players and NPCs. Select actor, in this case a player, and pin them. From here I can load appearances but upon entering gpose I receive the "actor could not be found" error when trying to pose or move them.

Had the player targeted and remained standing next to them while entering gpose. Tried using different players/NPCs/Pets and changing appearance or actor type. Tried in cities and outdoors in housing wards. Issue does not happen inside houses using players or NPCs, only public areas.
Outside of gpose, selected player:
![Anam Actor Error 1](https://user-images.githubusercontent.com/28070655/147787780-c9c96a5d-20c2-4551-bd74-66d0d08bc57b.JPG)

Inside gpose, unable to select pinned actor:
![Anam Actor Error 2](https://user-images.githubusercontent.com/28070655/147787787-dd9ff5cd-3b10-48a8-8f82-102b4122af2e.JPG)
