### ISSUE TITLE
Startup Error 

### ISSUE THREAD

**Issue by Violetgenesis** [imchillin/Anamnesis#658]
getting these two errors 
"Anamnesis has not been validated against this game version: 2021.11.28.000.000."
"GameDataService Error: Failed to initialize Lumina (Are your game files up to date?) 

I have uninstalled and reinstalled the latest files. It has been a while since I've been on FFXIV but now that I'm back id like to start posing again.

**Comment by SherlockHolmesHimself** [comment]
Endwalker caused this. A fix will be here when the developers are ready :)

**Comment by Ani-ki** [comment]
Not sure how you missed the pinned issue that covers this (#652) there, champ.

Also this did not follow the issue reporting template.

Please read before opening tickets in future.
