### ISSUE TITLE
Errors with Anamnesis Launching (included error message via photo for added clarity)

### ISSUE THREAD

**Issue by MyWaifusTrash** [imchillin/Anamnesis#659]
[2021-12-08-16-30-36.txt](https://github.com/imchillin/Anamnesis/files/7679454/2021-12-08-16-30-36.txt)
![ytyry](https://user-images.githubusercontent.com/81496109/145302240-2f0db5f3-696c-4f53-bf7d-4d8068972222.PNG)

**Comment by Ani-ki** [comment]
Not sure how you missed the pinned issue that covers this (#652) there, champ.

Also this did not follow the issue reporting template.

Please read before opening tickets in future.
