### ISSUE TITLE
Male Viera Ear Posing Not Working Correctly

### ISSUE THREAD

**Issue by AsgardXIV** [imchillin/Anamnesis#663]
**Describe the bug**
I'm running master so if you don't want bugs as you are still working, please feel free to close. 

I noticed that the Male Viera ear posing isn't working correctly and I think I know why but my knowledge of WPF binding is pretty limited to submit a fix.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a male Viera with ear type 3.
2. Attempt to pose the ears with the skeleton view (it will fail)
3. Attempt to pose the ears with the matrix view (it will also fail but for a different reason)

**Expected behaviour**
It should work in both scenarios.

Currently ear type 1 will work in the skeleton view, and ear type 4 will work in the matrix view. But ear type 2 and 3 will not work in either.

**Root Cause**
I am pretty sure the reason this happens is because the binding in the Skeleton view checks if the ears are flopped (type 2 for male, using `IsVieraEarsFlop`) and if false then binds to ear 1 (for example `VieraEar01ALeft` which is `j_zera_a_l` but it should be `j_zerc_a_l` for type 3). If true it binds to `VieraEar03`, which is correct for female but incorrect for male (should be ear type 2).

The Matrix view seems to try and have 4 explicit bindings but the corresponding methods (`IsVieraEars01` etc) were removed in an earlier changelist so I assume because type 4 is the last in the layout it is the one displayed though I am not super familiar with WPF rendering behavior. 

I assume the right fix here is to somehow expose the ear type and then bind dynamically, but I have no idea if that's possible in WPF or how to do it. 

Likely also impacts female but in a different way.

**Comment by Ani-ki** [comment]
Cheers for that, we can have a look into this shortly!
