### ISSUE TITLE
Position/Scale mode not working correctly when posing

### ISSUE THREAD

**Issue by Laureena** [imchillin/Anamnesis#669]
**Describe the bug**
Cannot move earings while posing, they always snap back to their original position.

**To Reproduce**
Steps to reproduce the behaviour:
1. enter posing mode
2. select earing A or B (left/right are the same)
3. enable position movement
4. move x/y/z sliders

**Expected behaviour**
The earing should move according to the sliders and stay in place.

**Comment by Yuki-Walsh** [comment]
Rotation and Scale mode are working as expected, but position is flickering.
The position freeze offsets may be wrong.

**Comment by Yuki-Walsh** [comment]
Scaling hair also seems to be having trouble.

**Comment by Yuki-Walsh** [comment]
this appears to be fixed for the next release.
