### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#67]
**Pages to add/edit**

- [x] Home
- [ ] The Character Tab
- [ ] Extended Appearance
- [ ] Model Tweaks
- [x] Loading and Saving Appearances
- [ ] Pose GUI
- [ ] Posing Matrix
- [ ] Pose 3D
- [x] About
- [x] Posing Multiple Actors
- [x] Using Props
- [ ] Combining Poses

**Comment by MissAniThrope** [comment]
Credits and Special Thanks added 20200706
Using Other Entities as Extra Actors added 20200706
Loading and Saving Pose Files added 20200713

**Comment by damphands** [comment]
reporting for duty - here to help with grammar corrections on the wiki!

**Comment by Ani-ki** [comment]
**Pages to add/edit**

- [ ] Home
- [ ] The Character Tab
- [ ] Extended Appearance
- [ ] Model Tweaks
- [ ] Loading and Saving Appearances
- [ ] Pose GUI
- [ ] Posing Matrix
- [ ] Pose 3D
- [ ] About
- [ ] Posing Multiple Actors
- [ ] Using Props
- [ ] Combining Poses

**Comment by Ani-ki** [comment]
Closed because ongoing tasks like these aren't issues.
