### ISSUE TITLE
Meteion face missing

### ISSUE THREAD

**Issue by LimaMathieu** [imchillin/Anamnesis#673]
**Describe the bug**
Meteion's NPC face is missing while loading her appearance

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Character tab
2. Click on NPC
3. Search for "Meteion"
4. Load any of those

**Expected behaviour**
Loading Meteion's NPC model

**Comment by Lionheart237** [comment]
Unhide your helmet.

**Comment by Ani-ki** [comment]
**[User error](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-tried-to-load-monster-but-its-head-is-missing)**.

Issue does not follow reporting template.
