### ISSUE TITLE
Remove Actor Render Limit/Render Cycle

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#68]
From the feedback survey: I'd like to suggest the 'Remove Actor Render Limit' and 'Render Cycle' features be kept for CM3. While most users won't touch these features, they're very important for niche users who use substantially altered actor scales.

**Comment by MissAniThrope** [comment]
We actually can't replicate the use cases for these features and any attempts either of us have made to do so have resulted in crashes. That said, using the example of 'substantially altering actor scales' we've done extensive testing in multiple areas during times of heavy traffic (JP prime time in Limsa Lominsa, Mor Dhona, Eulmore, etc) we have had NO issues altering the sizes of our characters as well as the sizes of NPCs around us, without even touching either of these functions. 

If this feature DOES work for you, we ask that you send us a video of it working in action, as well as a guide of how you use it, so we can try to replicate it. Until then, given we can't get it to work and it outright crashes and is effectively defunct, we won't be adding it to CM3, but with sufficient evidence that it does work and with some reverse engineering, it potentially could be added down the track if need be.

**Comment by Yuuki-Walsh** [comment]
https://cdn.discordapp.com/attachments/701987936312492102/731910909114581053/2020-07-12_12-32-13.mp4

https://cdn.discordapp.com/attachments/701987936312492102/731909367909056592/2020-07-12_12-25-51.mp4

**Comment by Yuuki-Walsh** [comment]
This is still a very niche use case, and the functions in CM2 still crash the game more often than not, so its low priority.

We'll need to figure out how to implement this functionality without having a button that just crashes the game.
