### ISSUE TITLE
Tool reloads skeleton/actor when toggling spotlights in-game.

### ISSUE THREAD

**Issue by Cy399** [imchillin/Anamnesis#683]
Bug: The tool resets/re-reads the actor files whenever a spotlight is toggled in game during g-pose. This can sometimes lead to a tool crash due to an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Gpose with Anamnesis up
2. Click on the Camera Lighting buttons
3. Character/Actor icons will turn red as if the tool is re-reading the character files
4. Can lead to crash

**Expected behaviour**
This behavior has only happened with the newest version, this bug wasn't present in older versions.
[2021-12-13-19-38-14.txt](https://github.com/imchillin/Anamnesis/files/7703981/2021-12-13-19-38-14.txt)

**Comment by Yuki-Walsh** [comment]
Yes, it looks like ana is losing track of the actor over and over again, and the crash seems like a race condition on a secondary thread.

**Comment by Yuki-Walsh** [comment]
I've fixed the crash, and moved the flickering selection to its own issue: #686
