### ISSUE TITLE
Occasionally localized strings do not load/display

### ISSUE THREAD

**Issue by AsgardXIV** [imchillin/Anamnesis#685]
**Describe the bug**
Occasionally localized strings do not load correctly. It is most obvious when you hover over the shortcuts when loading Appearances/Poses, they will randomly have the Label or not.

I believe I have a fix for this linked below.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Go to load appearance and hover over the shortcuts, some will not have a label randomly.

**Expected behaviour**
The labels should appear.

**More Info**
I've submitted a fix to XivToolsWpf which appears to resolve this at https://github.com/XIV-Tools/XivToolsWpf/pull/2 - it seems to be a race condition fetching the locale manager.
Please let me know if you need any more info.

Before:
![Missing](https://user-images.githubusercontent.com/95163444/145884806-b721447b-3f43-4134-a801-16b4fbfbe98b.png)

After:
![Working](https://user-images.githubusercontent.com/95163444/145884833-62a9948f-d983-4def-8c97-7d582a19dee3.png)

**Comment by Yuki-Walsh** [comment]
Fix has been merged and included for next release. Thanks!
