### ISSUE TITLE
Camera offset after model swap, and entering/exiting gpose.

### ISSUE THREAD

**Issue by Rihll** [imchillin/Anamnesis#689]
How to Replicate:
1. Swap player model into something much larger such as Brute Justice
2. Enter Gpose
3. Leave gpose
4. Change player model back to something smaller ie, your character or a beast tribe npc
After doing this the in game camera is locked in a position close to or underneath the map it seems, and no amount of adjustment or model swapping back and forth reverts it.

**Comment by Yuki-Walsh** [comment]
I can confirm this behaviour, but unforunately there's nothing we can do about it. The in-game camera is out of our control.

Unfortunately the only solution is log out and back in to reset the camera.
