### ISSUE TITLE
Intermittent game crash when loading character files

### ISSUE THREAD

**Issue by Vesraff** [imchillin/Anamnesis#691]
Whenever attempting to load a model (A premade model using the character creation settings, no beasts monsters or quest npc's) my game will abruptly crash. Sometimes I will get lucky and am able to change models a few times before the crash. Others it will be the first time. 

Steps to reproduce the behaviour:
1. Select either yourself, or a housing npc
2. load any model on them
3. Attempt loading new models multiple times if the first few tries doesn't crash. 
4. Witness crash

I expected the model to simply load over the designated model. 

[2021-12-15-00-50-56.txt](https://github.com/imchillin/Anamnesis/files/7717890/2021-12-15-00-50-56.txt)

**Comment by StupidBurger** [comment]
Can confirm, had this happen a couple of times. Crashes are random and sometimes it won't crash, but most of the times it crashes for me. Hopefully this gets fixed when possible

**Comment by ivalicea** [comment]
Also confirming. For myself it has been occurring since the ui change.

**Comment by Yuki-Walsh** [comment]
I'm having difficulty replicating this crash.
Can those who are experiencing it confirm that it crashes when loaidng an Anamnesis Character (*.char) file, without XLauncher or dalamud plugins running?

**Comment by Lionheart237** [comment]
Could be Penumbra-related. Launched game w/o Dalamud, and the crash didn't happen, after getting crashed the same way twice, then disabled auto redraws and it seemed to work fine.

**Comment by StupidBurger** [comment]
I do not have XLauncher or Dalamud, and I can confirm that this still happens, although it is not all the time, I'd say most of the time I get an error and it just crashes. I run my game without anything else besides TexTools if that counts, but even then I am only trying to load the appearance, not gear or anything else.

**Comment by ivalicea** [comment]
Can confirm it crashes when loading a .char file without XLauncher or Dalamud plugins. It also seems to be random in its behavior as I've loaded a .char, swapped to npc, reloaded to .char, and it crashes...and other times I'll load a .char once, leave the zone to refresh it, then load it again and it crashes. Older versions of Anamnesis prior to the UI change didn't have this occurring. On my end it's very easily occurring and happens usually on the third or fourth attempt. 
![21](https://user-images.githubusercontent.com/96220924/146565100-758042d6-3497-4655-bea4-4eeaf99bfcfb.png)

**Comment by Virulent** [comment]
Can confirm this occurs when you use the feature while escorting NPCs for the various Endwalker quests, specifically. Hope that helps.

**Comment by RSZealot** [comment]
Can confirm that this still happens. And quite randomly at that. Loading a model will cause it to crash, then I will start the game again, and load the same model without incident. This has happened regardless of it trying to load any modded equipment

**Comment by Yuki-Walsh** [comment]
This appears to be fixed as nobody has reported crashes in a while that aren't penumbra related.
