### ISSUE TITLE
Anamnesis window disappears when tabbing out

### ISSUE THREAD

**Issue by Caelowo** [imchillin/Anamnesis#692]
As the title says the window disappears when I change to a different active window. The program is still running, and I have to use task manager to close it. No idea what's causing it and I haven't found a way to make it not disappear.

**Comment by Yuki-Walsh** [comment]
sounds like you've enabled mini mode, which you can disable with this button in th etitlebar: 
![image](https://user-images.githubusercontent.com/379714/146325280-e0f63c4a-2c17-4817-ac3f-7047f0eeaae2.png)

When in mini mode, anamnesis will close into this icon whenever focus it taken away: 
![image](https://user-images.githubusercontent.com/379714/146325339-2aba2dd3-c88e-4f29-9e38-fcd84317a86e.png)

clicking the icon will open the window next to it.

**Comment by Caelowo** [comment]
You were right, I didn't even realise mini mode was a thing. Thanks!
