### ISSUE TITLE
Window Disappearing

### ISSUE THREAD

**Issue by Kiddameh-F** [imchillin/Anamnesis#694]
**Describe the bug**
I jsut downloaded the most recent update of the software, 14/12/21. I unzipped, ensured I had all the required software installed, and encountered a very strange issue. I can open the program, however as soon as I click into another window, such as ffxiv, the Anamnesis page minimizes, and I cannot reopen it no matter what I do. I am forced to close the software by right clicking on it in my taskbar to close it. I have tried deleting the original install folder, and reinstalling everything, I have white listed the application with my security software (AVG and Malwarebytes). So I have NO idea what to do now. I ensured that the software was being run as an administrator as well. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open software
2. Click anywhere outside software
3. Have software act like it is being minimized but then be unable to be pulled up. 

**Expected behaviour**
I expect the window to not disappear so that I can use it. 

**Log file**
I thought a screen recording of what is happening might help you guys so I created a recording here on loom. 
https://www.loom.com/share/767dd62926e24663bb721fc5847b4c76

**Comment by Yuki-Walsh** [comment]
sounds like you've enabled mini mode, which you can disable with this button in the titlebar: 
![image](https://user-images.githubusercontent.com/379714/146325280-e0f63c4a-2c17-4817-ac3f-7047f0eeaae2.png)

there should be an icon on screen to click to get the window back, but it appears missing for you, so we'll investigate that in this ticket to cach several usability problems with mini mode: #696
