### ISSUE TITLE
Mini mode icon appears off screen and is not obvious.

### ISSUE THREAD

**Issue by Yuki-Walsh** [imchillin/Anamnesis#696]
the mini mode toggle is easy to enable by accident without understanding its functionality.
 ![146325280-e0f63c4a-2c17-4817-ac3f-7047f0eeaae2](https://user-images.githubusercontent.com/379714/146327835-8b239164-b570-4cc5-8721-7ecc26785268.png)

The collapsed icon is easy to miss on a crowded screen:
![146325339-2aba2dd3-c88e-4f29-9e38-fcd84317a86e](https://user-images.githubusercontent.com/379714/146327890-c5fa11f6-b967-4367-87a9-2ccd1ba74fa6.png)

The collapsed icon can be positioned off screen, in effect causing the entire application to just dissapear.

**Comment by Yuki-Walsh** [comment]
I've added some animations to help locate the icon on screen:
![animate](https://user-images.githubusercontent.com/379714/146331636-86360d81-a650-49b9-a499-9ce3abb4d8a6.gif)

**Comment by PremaMarina** [comment]
![anatoggle](https://user-images.githubusercontent.com/75226914/183627253-8864a70e-def5-486e-a6de-c8d6559f6855.png)
Mini mode toggle ended up off screen somehow so I can't use mini mode anymore, cause it's impossible to press it.
Any way to reset its position?
