### ISSUE TITLE
Model List system

### ISSUE THREAD

**Issue by Peebs-miqo** [imchillin/Anamnesis#699]
**Describe the bug**
Fashion Accessories do not show up in the NPC list

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the NPC list
2. The fashion accessories are not there
3. ???
4. Do not profit

**Expected behaviour**
The fashion accessories should be in the NPC list

**Comment by Yuki-Walsh** [comment]
I've added fashion accessories as a new option to load objects from the model list: 
![image](https://user-images.githubusercontent.com/379714/146634556-bc61cd0b-6ff1-4eb8-9240-ffb3f63a7b24.png)

Somebody (@Ani-ki ) will need to populate the list, excluding all the npcs that it used to have though.

**Comment by Ani-ki** [comment]
> Somebody (@Ani-ki ) will need to populate the list, excluding all the npcs that it used to have though.

You got it, babycakes.

**Comment by Ani-ki** [comment]
List populated in 6126884272b8ff60c9c108d6c7ee1d5bb31c64b9!
