### ISSUE TITLE
Renaming Appearances Deletes Them

### ISSUE THREAD

**Issue by BizuZu** [imchillin/Anamnesis#700]
**Describe the bug**
Every preset I rename is destroyed. It happens consistently, regardless of the name chosen.

**To Reproduce**
1. Save an Appearance Preset
2. Rename it
3. Say goodbye to both the preset, and the file (It's not just visual)

**Expected behaviour**
Renaming the appearance preset should just rename it.

**Log file**
The first log is opening the client, and doing the reproduction steps, isolated.
The second log is this happening with normal use.
[2021-12-16-04-39-56.txt](https://github.com/imchillin/Anamnesis/files/7727021/2021-12-16-04-39-56.txt)
[2021-12-16-03-25-22.txt](https://github.com/imchillin/Anamnesis/files/7727022/2021-12-16-03-25-22.txt)

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release.
