### ISSUE TITLE
Renaming local gallery folder causes crash on launch

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#701]
**Describe the bug**
If you have your gallery slideshow set to a local folder, then rename the folder at some point, Anamnesis will crash when it tries to locate that no-longer existent folder name.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set a local gallery folder
2. Close Anamnesis
3. Rename the gallery folder
4. Launch Anamnesis, observe crash

**Expected behaviour**
Dunno if it being able to find the new file name is reasonable but it could handle the error better, like defaulting back to the featured gallery.

**Log file**
[2021-12-16-12-39-40.txt](https://github.com/imchillin/Anamnesis/files/7729384/2021-12-16-12-39-40.txt)

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release.
