### ISSUE TITLE
Demi-Human NPC failed to load equipment that show their body and can't use saved appearance file.

### ISSUE THREAD

**Issue by AevitaImperia** [imchillin/Anamnesis#704]
**Describe the bug**
Seem like all demi human( beast tribe) NPC failed to load their required equipment to be shown in the game.
This only happen if i try to load their appearance onto another NPC (Edit: seem like this only happen with carbuncle).
No mod involve.
But this happen too if modded.

**To Reproduce**
Steps to reproduce the behaviour:
Load demi human model (Ex: Amaljiaa model no. 3) onto another NPC (Edit: seem to be have problem with only carbuncle, it seem fine with human model.)

**Expected behaviour**
No model load, but can be fix by trying to find the exact equipment to equip onto the invisible model.

**Log file**
[2021-12-17-09-42-49.txt](https://github.com/imchillin/Anamnesis/files/7731819/2021-12-17-09-42-49.txt)

**Comment by Ani-ki** [comment]
I wasn't able to replicate this yesterday, but I'll give it another shot later today. I think this may have something to do moreso with Carbuncles themselves than Demihumans.
