### ISSUE TITLE
Actor ID is name only, preventing multiple actors of the same name being pinned.

### ISSUE THREAD

**Issue by AevitaImperia** [imchillin/Anamnesis#705]
**Describe the bug**
Before update 2021/12/14, you can go into trial and check boss model for their ID and pin any number of model inside the trial.

But after update, the program only manage to pick up the 480 invisible model and refuse to pick up any other model with the same name

**To Reproduce**
Just go to any trial boss and pin their model.

**Expected behaviour**
Only pick up ONE model, even if it's the 480 model and refuse to pick up other same named model.

**Log file**
There are no log file since it's not an error.

**Comment by Yuki-Walsh** [comment]
This has been addressed for the next release.
