### ISSUE TITLE
Animation profile selection should carry over to gpose

### ISSUE THREAD

**Issue by HaxtonFale** [imchillin/Anamnesis#706]
I finally got a chance to poke at this tool with Endwalker and overall I'm really happy but find one particular issue that bothers me.

I tried capturing a secondary idle weapon pose (catboy dragoon) that I had selected outside gpose but found that upon entering gpose my animations reverted back to default (catgirl) and poses like this (as well as sitting or standing) cannot be forced to replay in gpose (to the best of my knowledge). I would like for the selection of the animations profile to carry over to gpose, or to be given an option to trigger a restart of the current pose if possible.

**Comment by Yuki-Walsh** [comment]
This is a game engine limitation, there's nothing we can do about it. Your best bet would be to change to masculine, enter gpose and do the animation, save a pose of the frame you want, then change back to feminine and load the pose.

**Comment by HaxtonFale** [comment]
That's the problem, if I change to masc and then enter gpose, the animation set gets reset back to fem, and by the time I can change it to masc again it is too late.
