### ISSUE TITLE
Game crash while loading appearence

### ISSUE THREAD

**Issue by TanakiV** [imchillin/Anamnesis#708]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**When i load an appaerence on me or someone else, it crashes my game sometimes**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '**Character**'
2. Click on **'Load'**
3. Scroll down to **'any character you saved'**
4. See error: **game crashes sometimes in the process of putting it on the character**

**Expected behaviour**

**Just to get the character to what he should look like**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**There is no log file because it just crashes the game, but still stays there.... Due to the amound of traffic on the servers, it got me into 4-7k ques after that**

**Comment by Ani-ki** [comment]
Running Anamnesis will ALWAYS produce a log file. Please provide the latest one.

**Comment by Yuki-Walsh** [comment]
This issue is also being tracked over in #691, please contribute over there.
