### ISSUE TITLE
Anamesis Fail to detect Dot Net Runtime installation

### ISSUE THREAD

**Issue by juan-medina** [imchillin/Anamnesis#709]
**Describe the bug**
Anamesis Fail to detect Dot Net Runtime installation

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the runtime from: https://dotnet.microsoft.com/en-us/download/dotnet/5.0/runtime
2. Install dotnet-runtime-5.0.13-win-x64.exe

Runtime is installed correctly

![image](https://user-images.githubusercontent.com/485083/146641375-353137cc-9eb4-410a-8401-85e1db785a2e.png)

```
wmic product get description | findstr /C:.NET
Microsoft .NET Runtime - 5.0.13 (x64)
Microsoft .NET Host FX Resolver - 5.0.13 (x64)
Microsoft .NET Host - 5.0.13 (x64)
```

3. Open Anamesis 

This error message will show

![image](https://user-images.githubusercontent.com/485083/146641346-88a730e9-99e9-4c5b-bebb-129184c4d4fd.png)

**Expected behaviour**
Application opens correctly

**Log file**
N/A

**Additional Information**
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042

**Comment by Ani-ki** [comment]
Please install the .NET **DESKTOP** Runtime. The link has been provided in multiple places.

**Comment by juan-medina** [comment]
I've installed the link open by the application, shall that not be corrected?

**Comment by Ani-ki** [comment]
![image](https://user-images.githubusercontent.com/56663405/146641741-f73b2662-662d-4928-9505-1645820949ab.png)

In future, please read the documentation.

**Comment by juan-medina** [comment]
I did read it, but when I open the app it opens a link, is a bit confusing if the documentation refers to a link but the application opens another, shall not this be the same? Thanks

**Comment by Ani-ki** [comment]
That's Microsoft's link, not ours. You'll need to take that up with Microsoft. As I stated previously, we have provided direct links, including in the actual release archive.
