### ISSUE TITLE
Time of Day Doesn't stay when entering gpose

### ISSUE THREAD

**Issue by Eph4723** [imchillin/Anamnesis#710]
Every time I enter gpose after setting the weather and the time of day I want, the weather sticks but then the game snaps back to the correct time for the zone i'm in. I made this blank cause idk if its a bug or just something in the coding or writing didn't get set correctly so the tool keeps the same time its locked to when going into gpose

**Comment by Eph4723** [comment]
like if i set it to day sunset but its night time in the zone, when i enter gpose the time snaps back to night time but when i come out of gpose its still locked to the sunset time i have it locked to

**Comment by Ani-ki** [comment]
Issue does not follow reporting template.
