### ISSUE TITLE
Time of Day

### ISSUE THREAD

**Issue by Eph4723** [imchillin/Anamnesis#711]
**Describe the bug**
When setting time of day outside of gpose, tool does not keep same time when entering gpose. Zone is night time, change time to be midday, go into gpose and it snaps back to night time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set time of day outside of gpose.
2. go into gpose and time of day goes back to correct time of day for zone.

**Expected behaviour**
When I set time of day to what i desire, i expect it to be the same time when i go into gpose. Don't like waiting for the lighting or time of day to be what i want them to be.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by AsgardXIV** [comment]
This is normal with the new time control method. You need to uncheck “stop time/weather” in GPose for it to reflect what is set in Anamnesis when I’m GPose.

**Comment by Eph4723** [comment]
oh ok, thanks will give it a try

**Comment by Ani-ki** [comment]
I'll keep this one open for now since there may be changes coming to how time is handled by the tool within the next couple of days.

**Comment by AsgardXIV** [comment]
Improved in #717 and should work how it did before Endwalker.

**Comment by Eph4723** [comment]
well turning off the the weather affect does revert it back to the time of day i wanted, but i don't remember doing that back in ShB but i don't mind clicking the weather affect off to fix this

**Comment by Ani-ki** [comment]
> well turning off the the weather affect does revert it back to the time of day i wanted, but i don't remember doing that back in ShB but i don't mind clicking the weather affect off to fix this

The fix linked above by AsgardXIV was implemented in yesterday's update; can you confirm if this was what you were after, please?

**Comment by Eph4723** [comment]
it is fixed, thank you again!

**Comment by Ani-ki** [comment]
Perfect, glad to hear it's working for you!
