### ISSUE TITLE
Missing Tails?

### ISSUE THREAD

**Issue by Weird-Cat1** [imchillin/Anamnesis#715]
**Describe the bug**
Tails seem to go missing on male miqo'te while loading a pose

**To Reproduce**
Not sure if it's ever pose, but it's happened more than once. Loading a pose causes the tail to vanish.

**Expected behaviour**
Tails to not go missing on male miqo'te when loading a pose

**Comment by Ani-ki** [comment]
Can you confirm if toggling Physics makes any difference here, please?

**Comment by Weird-Cat1** [comment]
> 

Toggling physics does nothing, no. It's only when a pose is loaded, the tail completely disappears. I've noticed a couple of poses do, and then some don't. I'm not entirely sure what the trigger is.
I've loaded a CMT pose, and the tail stayed. Upon loading a .pose, it vanished. Then stayed gone until I reset gpose. I hope that helps!

**Comment by Ani-ki** [comment]
Is the `.pose` the same as the `.cmp`?
