### ISSUE TITLE
Can't switch the actor type to "Mount"

### ISSUE THREAD

**Issue by NailenFlammvor** [imchillin/Anamnesis#722]
**Describe the bug**

When I tried to load Lynx of Divine Light, the model itself loaded but it has a "T pose" and don't play any animations. I wanted to change it's actor type to "mount" to make it work properly but the type isn't available. Mostly the problem with both Lynxes (Divine Light and Eternal Darkness) since other mounts load with their respective animations by default (I checked multiple 6.0 mounts and some old ones).

**To Reproduce**
1. Summon a carbuncle and pin it
2. Go to appearance tab
3. Load mount "Lynx of Divine Light" or "Lynx of Eternal Darkness"
4. Try to change the actor type
5. See that "mount" type isn't available

**Expected behaviour**
Type switch and working animations

![image](https://user-images.githubusercontent.com/96454631/146857527-9163b93a-55b0-42ac-a78c-8b548c160f11.png)
![image](https://user-images.githubusercontent.com/96454631/146857561-a31c2515-9a64-4ad8-84de-0c087f2c661e.png)

**Comment by Ani-ki** [comment]
I believe Yuki already spoke about this in the Discord server, but we will have the option re-enabled for the new build, which we hope to have out in the next couple of days. I'll keep this ticket open for now, and once the new update comes out, I'll get you to confirm that you're able to do what you initially set out to achieve.

**Comment by NailenFlammvor** [comment]
Thank you! Now animations works as they should.
But it still has a problem: I can't target or select carbuncle after I change the model to Lynx. Looks like the carbuncle target fall somewhere under the game terrain and I can't target it even in GPOSe using Tab. Other mounts works fine. No idea what's wrong here and if this should work like that.
Anamnesis can't see the carbuncle after I enter and close GPOSE
![image](https://user-images.githubusercontent.com/96454631/147617241-0a8002a0-d4ed-4e99-8e1d-f2dcd1079b67.png)
![image](https://user-images.githubusercontent.com/96454631/147617269-7dd9bf11-94e1-4c80-8fea-4c10e463d3fb.png)
![image](https://user-images.githubusercontent.com/96454631/147617123-7db18182-beef-4282-8f6b-c81f3db835c1.png)
![image](https://user-images.githubusercontent.com/96454631/147617333-1b7f6143-e9d7-470b-998f-f779e76e34a2.png)
![image](https://user-images.githubusercontent.com/96454631/147617323-1fa6cc94-c54c-46bd-a847-731cce16549c.png)
