### ISSUE TITLE
Inevitable Crash w/ Custom Gallery

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#726]
**Describe the bug**
Anamnesis seems doomed to crash after some period of time if you have it set to use a local gallery folder. The error suggests it's moving to an index that's too high or low, looking for an image in the folder that isn't there, as my best guess. Perusing through the logs shows a few other exceptions that I don't know much about.

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot up Anamnesis
2. Set gallery to a local folder with some images in it
3. Wait
4. Program eventually crashes with an exception

**Expected behaviour**
Program should run indefinitely and loop through images in gallery.

**Log file**
[2021-12-23-03-42-24.txt](https://github.com/imchillin/Anamnesis/files/7771019/2021-12-23-03-42-24.txt)
[2021-12-23-03-35-08.txt](https://github.com/imchillin/Anamnesis/files/7771024/2021-12-23-03-35-08.txt)

**Comment by Ani-ki** [comment]
Good catch! We've confirmed this on our end and will be working on a hotfix in a little bit!

**Comment by Yuki-Walsh** [comment]
this has been fixed for the next release.
