### ISSUE TITLE
Issue with loading up 'Objects' within character screen

### ISSUE THREAD

**Issue by RaphyRaven** [imchillin/Anamnesis#728]
**Describe the bug**
I am having an issues with the 'Object' mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Opened Anamnesis
2. Clicked on 'Object' within the character screen
3. Scrolled down to 'Diabolos wings' model: #3428 and clicked on it
4. Upon clicking on it, my characters body disappeared and the wings sunk down to the floor - static

**Expected behaviour**
That the wings load up as if I was using the fashion item in game with slight motion.

Screenshot of issue:
![image_2021-12-23_230511](https://user-images.githubusercontent.com/96607748/147318750-25b1eec5-f8ca-41fc-85a3-e20a230e327f.png)

**Comment by Yuki-Walsh** [comment]
sorry, this isn't how the object list works. We can change your model into another model, but we cannot attach a model to you.
To get the wings for real, you'll need to get them in-game.

to pose with the wings, its recommended that you load them onto a carbuncle, and move it to line up with ytour characters back.
