### ISSUE TITLE
Random collection of bugs since most recent update

### ISSUE THREAD

**Issue by KirsiKitten** [imchillin/Anamnesis#731]
**Describe the bug**
On the previous versions of Anemnesis (Its been a few months of versions and never gotten better), I encountered an issue of the entire UI going blank, "Actor does not have a model" being flashed for 1 second or less, then the program would go back to normal other than having deselected the limb I was working on at the moment. So I updated to the most recent release today hoping there might be some change there.

NEW ISSUES (v2021-12-23-beta)
-Upon entering Gpose and freezing animation, and beginning posing... "Actor does not have a model" flashed two times within 30 seconds (I think, it happens too fast to read sometimes) like it used to, but then that issue stopped for the rest of the session as two new issues popped up.

-Every few minutes, program would flash a message along the lines of "Actor motion must be disabled" underneath the position area of the UI on the bottom right, while also deselecting the limb I am working on, as well as switching me back to the top character on my pinned list. This happened the entire hour or so I used it.

-Also twice during this posing session, the entire facial structure would bug out and contort the face into a horrific mash of jumbled mess.

-Occasionally while posing, the limb I am trying to rotate will snap to a random position and then snap back to where it was (This is not the issue of using the rotation wheel and having it at an apex of a rotation) It was very strange, kind of like a flicker of it in the wrong position before going back to the right one.

Truthfully, the behaviour is not too far off from if Actor Motion was not disabled...yet I double checked after saving my poses and it was indeed disabled. 

**To Reproduce**
Steps to reproduce the behaviour:
Unfortunately these issues did not have any consistent cause that I could tell. They would just happen randomly while posing, I was not able to reproduce it on purpose despite trying.

**Expected behaviour**

**Log file**
[2021-12-24-23-25-00.txt](https://github.com/imchillin/Anamnesis/files/7775669/2021-12-24-23-25-00.txt)

**Comment by KirsiKitten** [comment]
So, for trial sake, I completely deleted my anemnesis copy and downloaded a fresh version and it still has all the same listed issues with "Disable actor motion" when its already disabled, as well as contorting faces.

Adding new log in case it helps.

[2021-12-25-20-32-46.txt](https://github.com/imchillin/Anamnesis/files/7776580/2021-12-25-20-32-46.txt)

**Comment by Ani-ki** [comment]
Righto, with two builds done since this was reported, can you please advise if these issues have been persisting?

**Comment by KirsiKitten** [comment]
Ironically have not yet had it happen with the most recent update, but every update before this one it was still happening.On Feb 3, 2022 10:30 PM, Ani ***@***.***> wrote:
Righto, with two builds done since this was reported, can you please advise if these issues have been persisting?

**Comment by Ani-ki** [comment]
Just to be on the safe side, I'll get you to do some testing with the next build, and do all the same things your did prior, and if the issues don't occur, then we can consider them resolved and close this. There's currently no ETA for the next build, though.

**Comment by KirsiKitten** [comment]
Alright, sounds good!On Feb 3, 2022 11:45 PM, Ani ***@***.***> wrote:
Just to be on the safe side, I'll get you to do some testing with the next build, and do all the same things your did prior, and if the issues don't occur, then we can consider them resolved and close this. There's currently no ETA for the next build, though.

**Comment by SamaelDark** [comment]
> -Also twice during this posing session, the entire facial structure would bug out and contort the face into a horrific mash of jumbled mess
Unfortunately, this error exists even after the last update. This occurs spontaneously with changes in posture and results in a complete inoperability of Anam.

**Comment by Yuki-Walsh** [comment]
check in at #1006 for posing facial issues.
