### ISSUE TITLE
NPC appearance changes on GPose

### ISSUE THREAD

**Issue by NexusEmberfall** [imchillin/Anamnesis#732]
**Describe the bug**
Selecting and NPC to change any people or companions into will work fine, but the moment you type /gpose it will only change the appearances of anyone changed, but not affect any chocobos or carbuncles or pixies.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select a player
2. Change them to the desired NPC
3. Type /gpose in game
4. See changes

**Expected behaviour**
Normally no changes happen to the target player and you can pose freely.

**Log file**
[2021-12-25-18-53-45.txt](https://github.com/imchillin/Anamnesis/files/7776561/2021-12-25-18-53-45.txt)

**Comment by Ani-ki** [comment]
[**This is known and documented behaviour**](https://github.com/imchillin/Anamnesis/wiki/Loading-Models#types-of-models). This is a game limitation that we are not able to work around.

In future, please read the documentation

**Comment by NexusEmberfall** [comment]
My bad, I read it and just didn't see it at first glance. Thank you for letting me know.
