### ISSUE TITLE
Actors "defaulting" and/or won't register with mannequins

### ISSUE THREAD

**Issue by freezermilk** [imchillin/Anamnesis#736]
**Describe the bug**
Trying to load in NPCs onto mannequins, and one of two things happens:

1) I load them as Player type. Posing works, but their appearance is reverted into player-character appearance data wearing npc clothing
 2) I load them as EventNPC type as makes sense, and they look accurate, but attempting to use posing runs into "Actor motion must be disabled" popup. Disabling action in gpose doesn't register to anamnesis, so I'm stuck.

Attempting to load other types (companion, battlenpc, mount) yields same result, all other options grayed out. 

I am working inside an apartment with no other actors besides 2 mannequins, I have no summoned minions. Have tried all the basic restart, redownload, etc. Posing does not work with default mannequins set to EventNPC either.

**Comment by Ani-ki** [comment]
**[NPCs will only retain their unique appearances if loaded onto yourself or a Carbuncle.](https://github.com/imchillin/Anamnesis/wiki/Loading-Models#types-of-models)** In future, please read the documentation before opening tickets.
