### ISSUE TITLE
Ability to import Eorzea Collection glam sets

### ISSUE THREAD

**Issue by HoloWise** [imchillin/Anamnesis#738]
**Is your feature request related to a problem? Please describe.**
I've been trying to take some screenshots with various different outfits and changing them manually has been a bit of a chore.

**Describe the solution you'd like**
I took a quick look at the code and from what I saw it should be possible to implement a feature that'd accept a link to Eorzea Collection glamour set, extract item names and then apply them to appropriate slots. Identifying slot and item name shouldn't be hard with classes (for example hyperlink element with c-gear-slot-**feet** class and within there's a span element with c-gear-slot-**item-name** class)

It's purely a QoL request and I'm not sure how many people would actually use this, nonetheless I though it's an idea worth sharing.

**Comment by Ani-ki** [comment]
While this wouldn't be difficult to implement, it would wholly rely on their developers providing an API for us to use.

**Comment by HoloWise** [comment]
Yeah, I am not aware of any exposed endpoints that'd allow for fetching of list of items in a glamour set. Looked through the requests while loading a glam set to see if I can find anything there but there's nothing useful that I could find, template gets populated on server side. Guess the only way to achieve that now would be to scrap it from html. 

I dropped a suggestion on Eorzea Collection discord to expose an endpoint for fetching sets in json

**Comment by Ani-ki** [comment]
I'd love it if they could do something, tbh. It's definitely a feature I'd be interested in implementing were the opportunity to arise. We're just a little apprehensive of scraping websites (at least I know I am- bad juju with a different project).

**Comment by Maxunit** [comment]
I am not sure how the CustomXIVLauncher Plugin "Glamaholic" does it, but they might scrap the website, not sure.

https://git.annaclemens.io/ascclemens/Glamaholic

**Comment by HoloWise** [comment]
It does scrap the website - https://git.annaclemens.io/ascclemens/Glamaholic/src/branch/main/Glamaholic/Ui/MainInterface.cs line 203 ImportEorzeaCollection(string url)
