### ISSUE TITLE
App Crashes Then Deletes Itself

### ISSUE THREAD

**Issue by Shaymikyu** [imchillin/Anamnesis#740]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.
I downloaded the latest update, unzipped the file, but it crashes when I open it and then erases the .exe. I've tried this with multiple versions.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download 12/25 update or 12/14 update.
2. Unzip file.
3. Open program up and click anywhere on it.
4. It crashes then deletes the .exe.

**Expected behaviour**

I expected the program to run as intended, my friend who also uses it has never had this issue.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
**[This is covered in the troubleshooting page of the wiki.](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#anamnesisexe-is-deleted-when-the-tool-is-extracted)** In future, please read documentation before opening tickets.
