### ISSUE TITLE
Faster "Abdomen-Bone" selection request

### ISSUE THREAD

**Issue by Nickinsky** [imchillin/Anamnesis#746]
I just found out that poses done by using the "Character - Nothing Selected" won't save, so like rotations and positioning movements, I first thought it would automaticly select the "Abdomen/Root" bone but it wasnt that case, so I thought what about an option that if you press in the GUI View into an empty area it automaticly picks the "Abdomen" instead of "Nothing" or atleast a bone selection between "Lumbar" & "Waist" since there would still be enough space for the "Abdomen" bone, or a something to configure what happens if you click on empty space so it doesn't even remove the last selected bone or picks a certain bone which had been choosen by configuration. Or is it already possible to adjust something like that? If so, someone mind telling me?

Also btw, big thanks for that tool overall I really enjoy it~ :3

**Comment by Yuki-Walsh** [comment]
I've included the actor rotation and scale in the psoe file, so from now on it should behave as described.
We cant edit the root bone, however. game doesn't like that.
