### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Xionicbeats** [imchillin/Anamnesis#747]
A Task's exception(s) were not observed either by waiting on the task or accessing it.

[Exception] a tasks exceptions were not observer either by waiting on the task or accessing its exception property. As a resual the unobserver excepton was rethrown by the finalizer thread (index was out of range must be non-negatice and less than the size of the collection. (Parameter "Index"))

[AggregateException] same as above

[ArgumentOutofRangeException] Index was out of range. Must be non-negative and less than the size of collection

at system.collections.generic.list'1.get_item(int32 Index)
at Anamnesis.View.Gallery.Run

**Comment by Peebs-miqo** [comment]
Issue does not follow reporting template.
