### ISSUE TITLE
Cannot open local gallery image when URI has space in it

### ISSUE THREAD

**Issue by HoloWise** [imchillin/Anamnesis#749]
**Describe the bug**
Opening local images by pressing on preview in Gallery does not account for spaces present in URI causing Windows to throw an error

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings
2. Set Gallery to Local
3. Set directory to a folder with space in it
4. Restart Anamnesis for it to start going through local gallery
5. Press on gallery image
6. Observe issue

**Expected behaviour**
My C# knowledge is limited but a quick check and it seems that it's an issue with ProcessStartInfo constructor call in UrlUtility.cs, the way it is written now makes me assume that argument (image URI) is not in quotes when command is executed and so space is treated as argument separator and cmd is trying to execute

`start W:\GShade`

instead of for example 

`start "W:\GShade screenshots\2020-12-02_01-48-37-049_Witch'sMoonForScreenshots.png"`

Also I think it may be better to use "explorer" rather than "start". Using above command that is corrected with proper quotes and full URI from a local cmd simply opens a 2nd cmd prompt, passing URI to file explorer instead actually opens image in Photos app. 

==Edit to above==
Seems like if first argument when calling start is in quotes it treats it as a title for new console window

Workaround to allow use of start with paths that contain space is to call it with a first argument being an empty quote
`start "" "W:\GShade screenshots\2020-12-02_01-30-01-048_Witch'sMoonForScreenshots.png"`

**Log file**
No log file as it wasn't a crash
Repro on version 2021-12-25 07:45
![image](https://user-images.githubusercontent.com/36460595/147712559-dfff7622-ad21-4360-b22d-c4cb7a7719c7.png)
![image](https://user-images.githubusercontent.com/36460595/147712568-3d56bda0-77c0-44db-91e3-db0602a6f537.png)

**Comment by HoloWise** [comment]
Commit with fix (added quotes to use proposed start command workaround with first empty argument) in PR #752

**Comment by Ani-ki** [comment]
Whew~ will have a looksie when I'm next on my pc! Thanks heaps for the pull request!

**Comment by Yuki-Walsh** [comment]
fixed for next release
