### ISSUE TITLE
umm... when i exit out of gpose everyone is half bodied or missing hair

### ISSUE THREAD

**Issue by xTKATx** [imchillin/Anamnesis#756]
Its really hard to really explain... but when I get out of gpose after using the program, everyone kinda looses half their body or hai
![help](https://user-images.githubusercontent.com/96940567/147848833-6ecb5f1b-a97c-411c-9d58-58e4e1493ab0.png)
![help2](https://user-images.githubusercontent.com/96940567/147848834-fd71cede-265a-4cb9-bedc-53ec1313f145.png)
![help3](https://user-images.githubusercontent.com/96940567/147848835-5d69a346-6b47-4917-9959-4adb6ad5d442.png)
r

**Comment by Ani-ki** [comment]
Issue does not follow reporting format.
