### ISSUE TITLE
Client crashes at launch. Uninstalling and re-installing client does not solve issue.

### ISSUE THREAD

**Issue by silenthunder19** [imchillin/Anamnesis#760]
**Describe the bug**
"Critical Error. Anamnesis was unable to recover from this error and must close. A task's exceptions were not observed either by Waiting on the Task or the Task accessing it. [ArgumentOutOfRangeExcption] Index was out of range. Must be non-negative and less than the size of the colle...at System.Collections.Generic.List1get_Items(Int32.index) at Anamnesis.Views.GAllery.Run()"

This happened after I closed the program first, then logged out of FFXIV, logged back into the game, then tried to load the program. Uninstalling and re-installing the program and re-starting my computer did not solve the issue. Problem has been reproduced 13 times since it occurred (a.k.a. every time I've tried to use it since).

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Final Fantasy XIV
2. Log into Final Fantasy XIV
3. Open Anemnesis as Administrator

**Expected behaviour**
The client gives me an error message, then crashes. I am unable to access any features. I would like the client to not crash and for me to use it.

**Log file**
[2022-01-01-07-00-34.txt](https://github.com/imchillin/Anamnesis/files/7797835/2022-01-01-07-00-34.txt)

**Comment by AsgardXIV** [comment]
I believe this is fixed by #752 so it will be fixed in the next release.

In the meantime, you can try holding down Left Shift when you launch Anamnesis so it will reset your settings to default which should allow you to get around it.

**Comment by silenthunder19** [comment]
This seems to be working for the time being. Thank you :)

**Comment by HoloWise** [comment]
Just to confirm that #752 will address that. Given your description (app worked fine but started crashing after restarting) I assume you must have enabled local gallery but picked a folder with no images in it, is that right?

**Comment by Ani-ki** [comment]
Will keep this ticket open until #752 is merged fully into the main branch and the update is out.

**Comment by silenthunder19** [comment]
"Just to confirm that #752 will address that. Given your description (app worked fine but started crashing after restarting) I assume you must have enabled local gallery but picked a folder with no images in it, is that right?"

This sounds right. It was my first time ever using the program, so I was playing around with features and trying to learn what the wiki does not yet cover. The folder path I had set for content naturally did not have any pictures for this reason.

**Comment by HoloWise** [comment]
That's the issue then 😊 Next release should fix it but for now just make sure you have some images in folder you pick if you want to use custom local gallery.

**Comment by Yuki-Walsh** [comment]
Since this is already fixed, I'll close this in preperation for the upcoming release.
