### ISSUE TITLE
Some Item IDs are visually truncated when Atkinson font is used

### ISSUE THREAD

**Issue by Winter-Stormer** [imchillin/Anamnesis#761]
**Describe the bug**
When the Atkinson font is used, the last digit of some item IDs is partially hidden.

**To Reproduce**
1. Start FFXIV & Anamnesis
2. Log in
3. Enable 'Use Atkinson Hyperlegible font' in Anamnesis settings
4. Select 'Alliance Coat of Healing' and observe that the final 9 is mostly hidden in the main screen

**Expected behaviour**
Text field is large enough for all digits to be visible

**Comment by Winter-Stormer** [comment]
![image](https://user-images.githubusercontent.com/3084312/147883379-f5343c77-ba54-419d-b3b0-1868d60c66ac.png)

**Comment by Yuki-Walsh** [comment]
this has been fixed for the next release!
