### ISSUE TITLE
Color picker is partially hidden

### ISSUE THREAD

**Issue by Winter-Stormer** [imchillin/Anamnesis#762]
**Describe the bug**
When overriding the system theme, the color picker is mostly hidden and can only select very bright colors.

**To Reproduce**
1. In Anamnesis settings, enable 'Override system theme'
2. See below
![image](https://user-images.githubusercontent.com/3084312/147883442-cea57e58-49e1-4686-8d94-b9fffe2ec885.png)

**Expected behaviour**
Entire widget is visible

**Comment by Winter-Stormer** [comment]
I couldn't figure out how to get the settings pane to scroll, if that's possible.  I wound up overriding the colors in the JSON settings.

**Comment by HoloWise** [comment]
Visibility issue was fixed in commit 0f66d1e1a75e1e2fb47de3576a623fab4150d4f7

Discrepancy between UI color and picker color is still most likely a valid issue

**Comment by Yuki-Walsh** [comment]
this has been fixed for the next release.
