### ISSUE TITLE
hands don't follow wrist movement parenting 

### ISSUE THREAD

**Issue by pixe1cat** [imchillin/Anamnesis#763]
Describe the bug
Hands don't move along with the wrist when the radio button is selected and with parenting enabled. Only the forearm rotates with the wrist, 

To Reproduce
Steps to reproduce the behaviour:

1. Go into Group Pose mode 
2. Pause all motion using group pose settings
2. Open Anamnesis 
3. Enable posing using the Anamesis button in the top left 
4. Select wrist radio button 
5. Ensure that the "parenting" check box is selected
6. Rotate the wrist using either the ball or the sliders on the right side of Anamnesis 

Expected Behavior:
The wrist movement acts as a parent movement for the hand and forearm, causing both the hand and forearm to move with it. 

Log file
[2022-01-02-19-10-15.txt](https://github.com/imchillin/Anamnesis/files/7799995/2022-01-02-19-10-15.txt)

**Comment by Yuki-Walsh** [comment]
The hand is not parented to the wrist. This is intentional behaviour by SQEX, we cannot change it.
If you check the Pose GUI page, you can see th eparenting indicated by lines between the bone selectors.
