### ISSUE TITLE
issue loading female NPCs

### ISSUE THREAD

**Issue by hoordar** [imchillin/Anamnesis#768]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue. 

_Silly_ issue found when comparing screenshots from a friend who uses Concept Matrix versus Anamnesis - bust slider on Anamnesis is setting all female NPCS to 0; female created characters (WOLs) are not affected.

**To Reproduce**
Steps to reproduce the behaviour:

Serendipity (goldsmith job quests) has a known bust size 100 (https://garlandtools.org/db/#npc/1004093). 

In Anamnesis, she is loaded in with size 0. In Concept Matrix, she is loaded in correctly with size 100. (Pictures attached).

[female npc issue.zip](https://github.com/imchillin/Anamnesis/files/7818568/female.npc.issue.zip) 

Tested this with multiple NPCS, female NPCs are being loaded with 0 bust slider.

**Expected behaviour**
Sliding bust slider.

**Log file** NONE.
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Yuki-Walsh** [comment]
this has been fixed for the next release.
thanks for reporting!
