### ISSUE TITLE
Anamnesis not being able to reopen once tabbed out

### ISSUE THREAD

**Issue by SayomiiNeko** [imchillin/Anamnesis#776]
Every time I launch Anamnesis the program will load up completely fine without error but the moment I am tabbed out of it even though it’s set to always pin on top that instance of the program disappears and I cannot reopen it. 

I have to completely close it out of background programs and relaunch it only to encounter the same issues again. This happens every time I try to use Anamnesis. 

I’ve tried reinstalling and such but it is currently not usable at all for me. If someone may have any suggestions on how to fix this? Because I really do prefer using Anamnesis for posing.

**Comment by Yuki-Walsh** [comment]
sounds like you've enabled minimode in settings, there should be an icon on screen somewhere that you can click to reopen the window. However there is a known bug with the icon dissapearing off the edges of some monitor setups.

next time you open it, try checking under settings and disabling mini mode.

**Comment by SayomiiNeko** [comment]
Thank you so much, this immediately fixed my issue.
