### ISSUE TITLE
Child Actor Forearm Bugging out

### ISSUE THREAD

**Issue by ThatOneAdonis** [imchillin/Anamnesis#785]
So I was trying to do a pose for my character and his daughter and when I tried to move her forearms or hands, the arm begins contorting from the elbow down to the hand and continues doing that even when I don't touch it until I target a different bone. I have tried reloading actor and restarting the program to the same result. 

**To Reproduce**
1. Go to Forearm of child Miqo'te.
2. Adjust the forearm on the x y or z axis
3. See error

**Expected behaviour**
I expected it to work like any other actor's bones. Smooth movement with no change besides what I make.

**Comment by Yuki-Walsh** [comment]
pretty sure this was fixed with the changes to posing from a few versions ago.
