### ISSUE TITLE
Attempting to type-change invisible EventNPCs causes FFXIV to crash

### ISSUE THREAD

**Issue by Vievin** [imchillin/Anamnesis#787]
**Describe the bug**
When trying to change an EventNPC who isn't visible anymore because they're no longer relevant, into a BattleNPC or Player, the game crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Fortemps Manor with progress past 3.3 MSQ
2. Click on the new actor button
3. Select one of the Haurchefant or Alphinaud NPCs
4. Attempt to change type from EventNPC to BattleNPC or Player
5. Witness crash

**Expected behaviour**
I can steal an actor out of pretty much nowhere, **or** Anamnesis prevents me from pinning "past" EventNPCs, **or** Anamnesis prevents me from trying to type-change "past" EventNPCs

**Log file**
[2022-01-09-16-53-32.txt](https://github.com/imchillin/Anamnesis/files/7835973/2022-01-09-16-53-32.txt)
[2022-01-09-22-26-28.txt](https://github.com/imchillin/Anamnesis/files/7836005/2022-01-09-22-26-28.txt)

**Comment by Vievin** [comment]
Additional Comment: Attempting to change visible EventNPCs causes a crash too.
[2022-01-09-22-44-06.txt](https://github.com/imchillin/Anamnesis/files/7836077/2022-01-09-22-44-06.txt)

Reproduction:
1. Go to Fortemps Manor with progress past 3.3 MSQ
2. Click on the new actor button
3. Select House Fortemps Steward 4y from the entrance
4. Change his clothes to confirm he is the visible actor
5. Attempt to change type from EventNPC to BattleNPC or Player
6. Witness crash

**Comment by Ani-ki** [comment]
This issue should be resolved in the next build- when this comes out, please let us know if the issue persists for you.

**Comment by Vievin** [comment]
"Past" EventNPCs cannot be found by the actor pinner anymore, so I guess solved?
