### ISSUE TITLE
Anamnesis in gpose cannot find actors (With Logs)

### ISSUE THREAD

**Issue by ABagofSunshine** [imchillin/Anamnesis#792]
**Describe the bug**
Making sure to select the person, pinning them in Anamnesis, and then going into GPose, Anamnesis cannot find the actors for anyone (Player or NPC) while inside GPose. No matter who it is or what location I am in, I am still able to click people in game and they are set to players in Anamnesis.

**To Reproduce**
Steps to reproduce the behaviour:
1. Pin someone in Anamnesis
2. Go into Gpose
3. Pinned actor cannot be found in Anamnesis

**Expected behaviour**
Once going into Gpose should be able to click on a pinned person in Anamnesis.

**Log file**
[2022-01-10-06-53-44.txt](https://github.com/imchillin/Anamnesis/files/7839317/2022-01-10-06-53-44.txt)
[2022-01-10-06-50-53.txt](https://github.com/imchillin/Anamnesis/files/7839318/2022-01-10-06-50-53.txt)
[2022-01-09-09-32-14.txt](https://github.com/imchillin/Anamnesis/files/7839319/2022-01-09-09-32-14.txt)
![AnamnesisApplicationGposeScreenshot](https://user-images.githubusercontent.com/46640676/148778174-98e5a9e3-071b-418a-9ba8-897c5eb008b4.png)

**Comment by Vievin** [comment]
I can confirm this happens with some EventNPCs too. Specifically inside Fortemps Manor (haven't tried elsewhere), all visible EventNPCs but Count de Fortemps display this behaviour, and the Count displays it if he's too far when I enter gpose.

Reproduction steps:
1. Head into Fortemps Manor.
2. Pin every visible EventNPC (the Manservant, the Steward, Saluette and the Count
3. Get close to the Count
4. Open Gpose
5. (everyone but the Count will turn red, meaning the actors were lost)
6. Close Gpose
7. Head half a room away from the Count
8. Open Gpose
9. (everyone, including the Count, will turn red)

Log
[2022-01-10-15-13-41.txt](https://github.com/imchillin/Anamnesis/files/7839445/2022-01-10-15-13-41.txt):

**Comment by HanaUzaki** [comment]
I had a same problem finding a maid servant, I could change it to what ever I wanted but would loose it when I went into gpose and find it again when I left it

**Comment by Ani-ki** [comment]
We will be pushing a build in the next few hours (static raid and dinner notwithstanding), so once this build is out, I'll get you to try out the exact same steps you took previously and update us on whether or not the issue persists for you.
