### ISSUE TITLE
Multiple NPC heterochromia mirrored

### ISSUE THREAD

**Issue by Allora02** [imchillin/Anamnesis#793]
When Loading the Appearance of G'raha Tia from ARR (pre- world of darkness) His eye colors are swapped. The NPC in game, and the minion both show the teal/green eye as his left. (the one not covered by his bangs) and his red eye as his right (the one covered by bangs). however, when loading g'raha's appearance via the NPC tab, his eye colors are swapped. everything else about the actor is correct, except this detail. 
I'm unsure what is causing the issue, as his eyes have been swapped for months, and as I recall, the previous tool, CMTool had the same issue with his eyes, which is what caused me to not log this before now. this happens on all versions of g'raha with Odd Eyes (or two different colored eyes).  I am attaching a log file now, and will provide more screenshots as I gather them (as the only way to encounter this NPC for me is via NG+ to get to the correct point of the Crystal Tower storyline
[2022-01-10-09-07-32.txt](https://github.com/imchillin/Anamnesis/files/7839463/2022-01-10-09-07-32.txt)

**Comment by Allora02** [comment]
Ok, Update with screenshot comparisons, and another log file. hope this helps. I also noticed from looking at the values in Ana, the NPC version has a tail at 100, whereas the version loaded via the NPC apperance selector has a tail at 0, but the tail (and bust) being different may be because I started as a Fem Elezen, which has no tail and a bust value. 
[2022-01-10-09-53-29.txt](https://github.com/imchillin/Anamnesis/files/7839751/2022-01-10-09-53-29.txt
<img width="866" alt="comparison1" src="https://user-images.githubusercontent.com/86975714/148788536-fb469690-9633-47bc-a5d0-8b686822581c.PNG">
<img width="869" alt="comparison2" src="https://user-images.githubusercontent.com/86975714/148788561-fa3bc214-28ab-4adf-b41c-2c1193137597.PNG">
<img width="787" alt="comparison 3" src="https://user-images.githubusercontent.com/86975714/148788582-35511b16-ed5f-4307-b759-ac6600ed4e92.png">
)

**Comment by Sparrows413** [comment]
Issue also appears to affect Thancred's Heavensward models. I strongly suspect this would affect _anyone_ with odd eyes, but I can't for the life of me remember who else has 'em.

Issue happens _only_ when loaded from NPC list - loading saved appearances with odd eyes keeps them the right way round.

[Loaded via NPC list](https://user-images.githubusercontent.com/1424138/148866513-46f3603d-eac3-4ee0-b1a1-2b06dd731d3f.png) vs [loaded from saved appearance.](https://user-images.githubusercontent.com/1424138/148866520-8cfd5acd-09a7-4408-9a04-5c9f7da27677.png) (Blindfold removed to more clearly illustrate point.)

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release.
looks like we just had the eye colors flipped for all event npc's.
