### ISSUE TITLE
Preserve character scaling

### ISSUE THREAD

**Issue by InternIsla** [imchillin/Anamnesis#797]
This is a bit outside the intended scope of Anamnesis, but I figure it's worth asking about anyway. Would it be possible to include an option in the character tab to preserve scaling through loading screens, or automatically re-apply it after loading screens?

It's a very niche feature, admittedly, but as someone who role-plays a character outside the height range allowed in character creation, and enjoys playing with my character scaled to match their 'canon', it's extremely irritating to have to manually reset scaling after every single loading screen.

**Comment by Ani-ki** [comment]
This will be achieved through a separate tool, as the way Anamnesis is built will purposely not allow for such a feature.

[**Please follow Customize+ instead**](https://github.com/XIV-Tools/CustomizePlus).
