### ISSUE TITLE
Face bones randomly changing positions

### ISSUE THREAD

**Issue by EliCodesThings** [imchillin/Anamnesis#800]
Every now and then, the the actor faces get twisted due to the face bones randomly rearranging, as seen on this picture.

![2022-01-15_03-18-45-011_Talim - Golden Leaf](https://user-images.githubusercontent.com/67561268/149605821-69cae209-ec69-48fa-a0cc-0e5b25b1b584.png)

I am not sure what causes this, since the issue appears to happen randomly.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
