### ISSUE TITLE
Modern Aesthetics - Great Lengths keeps breaking faces when I do custom poses

### ISSUE THREAD

**Issue by Clawstrophobic** [imchillin/Anamnesis#804]
Every time I try to pose my friend's character, she loves using the Great Lengths hairstyle (attached file)

![Screenshot_1](https://user-images.githubusercontent.com/97812499/149641043-f8ea8739-1f3b-4a0b-907f-37675c6706d7.png)

But any time I try to pose her character with that hairstyle, her face breaks. 
This has happened on both her Hyur, and Roegadyn characters. 
See attached files.

![Screenshot_2](https://user-images.githubusercontent.com/97812499/149641139-772969b2-44be-4625-9a74-78f6b6a86918.png)
![Screenshot_3](https://user-images.githubusercontent.com/97812499/149641141-6d327bca-48ce-4ff8-8d89-992f7a33c161.png)
![Screenshot_4](https://user-images.githubusercontent.com/97812499/149641144-5b9b933e-1510-4518-bac9-111223846a7a.png)
![Screenshot_5](https://user-images.githubusercontent.com/97812499/149641235-a197697d-b146-41b2-8a7c-3d05d6cae316.png)
![Screenshot_6](https://user-images.githubusercontent.com/97812499/149641239-22c1d0b2-787f-4f89-8103-8fe77436aa01.png)

We would both greatly appreciate this bug fixed as soon as possible.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
