### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by isythur** [imchillin/Anamnesis#808]
**Describe the bug**
A lot of errors with a crash on startup.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download latest from repository
2. Install linked .NET from the prerequisites portion of the github
3. Set to 'Run as Admin'
4. Run program
5. Multiple errors pop up before a final one leaving no other choice but to terminate.

**Expected behaviour**
The Program launches

**Log file**
[2022-01-19-22-50-34.txt](https://github.com/imchillin/Anamnesis/files/7902251/2022-01-19-22-50-34.txt)

**Comment by Ani-ki** [comment]
Just to clarify- you're running the game and then running the tool, correct? Your log suggests it's not finding the game memory.

**Comment by isythur** [comment]
Yes I have the game running when I start up the tool.

**Comment by Ani-ki** [comment]
And are you on actual Windows or are you running emulated Windows on Linux?

**Comment by isythur** [comment]
Actual Windows 10

**Comment by Ani-ki** [comment]
What other third party tools are you running?

**Comment by isythur** [comment]
For final fantasy just FFXIV TexTools and GShade.

**Comment by isythur** [comment]
Hey just a quick update, I'm thinking its something on my end with my pc in general. No Third party tool is detecting the game when its running now. Even tried BMP just too see which did work before doesn't seem to be detecting the game now. I don't believe it's an issue with Anamnesis itself at this point so I may try reinstalling the game. But if you have any ideas as to why this may be happening please let me know. I'll be closing this with this last reply so if you have any ideas I'm on the discord server as Isyther. Thankyou for you time Ani-ki :)
