### ISSUE TITLE
anamesis character issues

### ISSUE THREAD

**Issue by kanoey** [imchillin/Anamnesis#812]
[2022-01-21-15-59-25.txt](https://github.com/imchillin/Anamnesis/files/7916564/2022-01-21-15-59-25.txt)
i keep having issues with anamesis where my character does not move properly and the character's body becomes completely twisted otherwise

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
