### ISSUE TITLE
Filter Animation by Race/Gender

### ISSUE THREAD

**Issue by JSharpie** [imchillin/Anamnesis#816]
**Is your feature request related to a problem? Please describe.**
Some animations only with with certain race and/or gender.
Some animations are only for monsters.

**Describe the solution you'd like**
Hide animation that doesn't work with the the selected character's race/gender.
This can greatly help cutdown the list without having to go through them one at a time to see what they are or guessing to see it if works.

If animations doesn't contain metadata that allows this, then you can close this ticket.

**Comment by AsgardXIV** [comment]
Not possible unfortunately. 

The ActionTimeline itself doesn't contain any information about what it is playable on. Instead the engine goes through a bunch of logic to determine which animations it should load and play (which is how different races/genders and weapons have a different animation for the same action) based the action initiated, and sometimes it's nothing. 

We do have some improvements planned or already implemented for the next version to improve the animation search though! Yuki already implemented searching by Emote Name as well as Action Timeline and in future we may be able to do things like search by combat action name.
