### ISSUE TITLE
Typo in the FAQ

### ISSUE THREAD

**Issue by Vievin** [imchillin/Anamnesis#824]
**Describe the bug**
The "What does 'Unable to Find Actor' mean?" section in the wiki FAQ has a typo in it: instead of "highly populated areas" it writes "highly populated errors".

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the wiki
2. Click on Help -> FAQ
3. Scroll down to "What does 'Unable to Find Actor' mean?" 
4. Witness typo

**Expected behaviour**
"This is not considered a bug, as it is up to the game what is allowed into GPose, especially in highly populated areas."

**Comment by Ani-ki** [comment]
Fixed.

The issues tab is for issues with the tool itself. In future, please report typos on the XIV Tools Discord.
