### ISSUE TITLE
Anamnesis reverts to light mode under undetermined conditions (w/workarounds)

### ISSUE THREAD

**Issue by ProtoDVD** [imchillin/Anamnesis#825]
In both the Character menu and the Pose menu, Anamnesis sometimes spontaneously reverts to light mode, though the Light Mode checkbox remains empty. This occurs even with the "Override system theme" toggle enabled. However, workarounds are available; the workaround available from the equipment menu cannot be accessed while posing mode is enabled, but a different means of fixing the problem is available in this case.

**To Reproduce**
Steps to reproduce the behaviour:
Not clear. Behaviour periodically experienced on Windows 10 with **Mini mode disabled** and **Always on top enabled**.

**Expected behaviour**
State of program corresponds 1:1 with state of Light Mode checkbox.

**Workarounds**
In the Character menu, enabling and then disabling the Light Mode checkbox will return the program to dark mode.
In the Pose menu, toggling the Flip Sides checkbox will return the program to dark mode.

**Comment by Yuki-Walsh** [comment]
Is this possibly #573 ?

**Comment by ProtoDVD** [comment]
@Yuki-Walsh The theme colour never changes; the behaviour is exclusively a swap to light mode, always with the same theme colours as what had been established previously for the program in dark/light mode. Maxunit's reply implies that the same workaround (anything that effectively forces a reload of the UI) may work in that case as well. I haven't been using the program in the past few days (was moving apartments) and as such haven't replicated it since; going by my rough recollection, I am not sure if it was triggered by other programs opening. That being said, I'll look to see if I can pull a log (not to mention, figure out how to pull a log) next time it happens, and I'll pay attention if opening other programs.

**Comment by ProtoDVD** [comment]
Update: issue appears to have some overlap with issue #573, in the sense that some external programs (CMTool, most notably) do indeed seem to set it off.

However, I wasn't able to articulate why this didn't feel complete, because I didn't feel like every instance of the error was a result of a program being opened. I just managed to isolate **another trigger** for this behaviour: moving the Start bar from one monitor to another.

**Comment by ArpoXIV** [comment]
Opening Textools while Anamnesis is running will reliably switch to light mode for me.

**Comment by Yuki-Walsh** [comment]
going to track this as part of #573.
