### ISSUE TITLE
Problem with breasts

### ISSUE THREAD

**Issue by iinatsuwolfie** [imchillin/Anamnesis#826]
So I am trying to do a gpose and every time I unfreeze the character and pick a pose, her breasts glitches, twists and turns to where it shrinks her breasts and I don't know what to do but to reset and refreeze my character a lot.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
