### ISSUE TITLE
Embedding image preview in .pose files or preview within Anamnesis

### ISSUE THREAD

**Issue by ivalith** [imchillin/Anamnesis#828]
**Is your feature request related to a problem? Please describe.**
My problem is that often when loading or organizing poses it can be an arduous process needing to test them all individually to tell what the pose is or download preview images with them and keep them together in a separate folder that can't be checked while using Anamnesis because it's naturally not looking for image files. 

**Describe the solution you'd like**
If it would be possible I think it would be really convenient if the .pose file type allowed for attaching an image to the file as well as the pose information itself so that .pose files could be previewed in something like windows explorer or an image viewer to see what the pose is without needing multiple files, or alternatively for Anamnesis to be able to preview the image attached to a .pose file so that when I'm picking a .pose file in Anamnesis when I click on it I can see what the pose itself is if the pose maker attached a preview sample image to it as pose-makers frequently provide. If that isn't a possible change with the .pose file type, allowing Anamnesis to preview image files included in the folders that .pose files are in would also be convenient.

**Comment by Yuki-Walsh** [comment]
This has been implemented for the next release as the tool tip for files
![image](https://user-images.githubusercontent.com/379714/156371470-91011025-4d73-4e4f-9a01-f9897836f147.png)

The metadata can be edited:
![image](https://user-images.githubusercontent.com/379714/156371507-00419949-5304-458e-b404-dd3349fa3506.png)

Embedded images can be loaded from a file, or pasted directly from the system clipboard (useful for screen snip users!)
![image](https://user-images.githubusercontent.com/379714/156371536-83b9bacf-3616-47d5-8a96-020ec9479a5a.png)

This metadata can be added to any file format Anamensis can save (Poses and Character files currently)
