### ISSUE TITLE
Validation Error & Windows Version Error

### ISSUE THREAD

**Issue by cygnus-rex** [imchillin/Anamnesis#829]
**Describe the bug**
When in FFXIV on a character and trying to load Anamnesis, I get two errors: 
![errors20220130](https://user-images.githubusercontent.com/98709469/151713602-1881b370-bfdd-40b6-bc8e-d65df2a900b2.JPG)
- The first error that pops up: "Anamnesis has not been validated against this game version: 2022.01.25.0000.0000. This may cause problems."
- The second error that pops (right after the first one): "Only Windows 10 or newer is supported."

The program does not start after I get these two errors.

This is my first time ever using Anamnesis.
- I have made sure to download the newest version of Anamnesis.
- I have made sure to install DotNET Desktop Runtime.
- I am also running Windows 10, so I am unsure why I am getting the Windows version error. 
![windows10](https://user-images.githubusercontent.com/98709469/151713792-af7d8e1a-d983-40a0-a933-2b270a0c37dc.JPG)
Edition	Windows 10 Home
Version	21H1
Installed on	‎11/‎22/‎2020
OS build	19043.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Log into a character in FFXIV
2. Run Anamnesis.exe

**Expected behaviour**
Anamnesis.exe starts up.

**Log file**
[2022-01-30-13-34-47.txt](https://github.com/imchillin/Anamnesis/files/7966715/2022-01-30-13-34-47.txt)

**Comment by Yuki-Walsh** [comment]
have you set any compatibility mode options for the Anamensis executable?
![image](https://user-images.githubusercontent.com/379714/151723443-ffc2eb45-f279-4d26-8403-836a09626942.png)

**Comment by Ani-ki** [comment]
Additionally, the first 'error' is not really an error, and just needs a verbiage update. The warning exists as a sort of "hey, the game's updated, you can still use the tool but it may not work' heads-up. We'll be updating this window to better reflect this in the next update.

**Comment by cygnus-rex** [comment]
The compatibility mode options were the cause of it--unchecking the box worked like a charm! Thank you so much for the help!
