### ISSUE TITLE
Can't load poses on myself after the update

### ISSUE THREAD

**Issue by V3semir** [imchillin/Anamnesis#832]
**Describe the bug**
After today's update, I can't load poses on myself anymore. I can load poses on carbuncle but not on myself, nothing happens when I try to do so. To reproduce, just try to load any pose on yourself.

**Log file**
[2022-01-31-13-38-05.txt](https://github.com/imchillin/Anamnesis/files/7970721/2022-01-31-13-38-05.txt)

Edit:
I found the workaround for now.
1. Go to scene tab.
2. Unpin your character bubble.
3. Pin your character.
4. Click on your character bubble.
5. Go to pose and it should work now.

**Comment by Yuki-Walsh** [comment]
This has been fixed with the [v2022-01-31-beta (Hotfix) ](https://github.com/imchillin/Anamnesis/releases/tag/v2022-01-31-beta) release.
