### ISSUE TITLE
Schrodinger's GPose if Posing Mode enabled on exit

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#834]
**Describe the bug**
If "Posing Mode" is left enabled when leaving GPose, the Appearance and Equipment tab will display as though you are still in GPose, while the Posing tab recognises that you are no longer in GPose. To clear the issue, re-enter Gpose and exit it again (whether or not you turn on Posing Mode is irrelevant).

On attempting to reproduce, it may be required to make adjustments to the skeleton within Posing Mode. Unclear; can experiment further.

**To Reproduce**
1. Enter GPose in game.
2. Enable Posing mode.
3. Exit GPose ingame without turning off Posing mode.
4. Go to the Appearance and Equipment tab. It will be locked and unusable until GPose is re-entered and exited properly.

**Expected behaviour**
To be able to change appearance/equipment as normal while out of GPose.

**Log file**
(Please note: log file has been edited to remove deadname. No other changes were made.)
[2022-01-31-15-19-31.txt](https://github.com/imchillin/Anamnesis/files/7971912/2022-01-31-15-19-31.txt)

**Comment by Yuki-Walsh** [comment]
Sounds like it might be the opposite side of the #832 problem, the gpose actor remaining targeted after exiting gpose?

**Comment by Yuki-Walsh** [comment]
fixed it. dye will clear whenever the user equips none or emperor's new fists.
