### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by Kyla772** [imchillin/Anamnesis#840]
So Anamnesis won't load up whenever I click the icon to boot it up.

I've literally tried everything I can think of. I've restarted my system, I deleted the older Anamnesis and installed the update from today, ran as administrator, tried the different compatibility modes, literally everything I can think of. 

Idk where to find a log file for this.

Please help!

**Comment by BlackWyvern** [comment]
https://github.com/imchillin/Anamnesis/wiki/Troubleshooting
Covers everything you're asking.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
