### ISSUE TITLE
Gallery Does Not Cache Images

### ISSUE THREAD

**Issue by AsgardXIV** [imchillin/Anamnesis#843]
**Describe the bug**
The gallery appears to not cache images and downloads the full image every time it rotates them. This uses large amounts of bandwidth/data transfer (10s to 100s of GB a month depending on how long Ana is running).

**Expected behaviour**
Should cache the images locally so they are only downloaded once.

**Comment by HoloWise** [comment]
This should be fixed by #857 - local long term caching of smaller thumbnails.
