### ISSUE TITLE
Minions not retaining their actor type while in Gpose

### ISSUE THREAD

**Issue by BowlOfCactusJuice** [imchillin/Anamnesis#846]
**Describe the bug:**
I have 4 actors under my control, From left to right I have a Carbunkle, a Chocobo, Myself, and a Minion. I am trying to make screenshots in Gpose, but when I load into Gpose the Minion reverts to his froggy self.

Weirdly it's only in Gpose, if I load back out of Gpose he remembers he is an Elexzan.

_In Game Appearance:_
![unknown](https://user-images.githubusercontent.com/97313360/152052974-763e06e1-e4c6-4417-8198-dd505c568d62.png)

_Gpose Appearance:_
![unknown (1)](https://user-images.githubusercontent.com/97313360/152052992-994bbc49-97c8-4455-86fd-ba7db1df9209.png)

**To Reproduce:**
>Go to the Azim Steppe
>Load a Minion as an Actor (Possibly with also a Carbunkle and Chocobo as company)

**Expected behavior:*
I would expect the Minion to retain his Elezan-ness.

**Closing thoughts:**
Thank you for your time~! I hope everyone on the Anamnesis team is doing well ♥

**Comment by AsgardXIV** [comment]
This is intended, as noted in the release notes:
```
* Loading appearances onto Mounts, Minions, and Fashion Accessories no longer crashes the game.
     * Please note that changes to appearances will not be copied to GPose for these actor types.
```

**Comment by BowlOfCactusJuice** [comment]
Awww man, that makes me a lil sad. But I can see why it would be imporant, better to disable it as a feature than letting it crash the game. Still... one day I hope a fix can be found, having four characters under my control (without pestering my friends to get on and stand next to me XD) would be so helpful.

**Comment by Ani-ki** [comment]
Given this is not something we are able to work around due to game limitations, I'll close this for now, and should the opportunity arise to change this in future, we can reopen this.
