### ISSUE TITLE
Closing FFXIV, then reopening it, while Anam is kept running, will cause the sky and music to glitch if the time was frozen in Anam

### ISSUE THREAD

**Issue by Vievin** [imchillin/Anamnesis#847]
**Describe the bug**
If you freeze time, then exit FFXIV without exiting Anam, then reopen FFXIV, the sky and the music will glitch back and forth between Anam time and game time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis and freeze time. Set it to 12 hours away from current eorzea time for a more profound effect.
2. Close the game, do not close Anamnesis, just let it error away in the background.
3. Open FFXIV back up
4. Observe glitching of the skybox and the music (between day/night music)
5. Close and reopen Anam
6. Observe the settings being wiped, stopping the glitching

**Expected behaviour**
Closing the game wipes Anam of all applied settings, **or** the time and weather settings are immediately applied correctly upon the game being reopened

**Log file**
[2022-02-01-17-40-51.txt](https://github.com/imchillin/Anamnesis/files/7982296/2022-02-01-17-40-51.txt)
https://ibb.co/2PgGVwS (Note: contains spoilers to zone 5 of EW)

**Comment by AsgardXIV** [comment]
Fixed in #848. Should be in the next release.
