### ISSUE TITLE
Pose folders coming up empty

### ISSUE THREAD

**Issue by Klarisox** [imchillin/Anamnesis#849]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue. 

I have read that all poses from cmt are compatible with this new tool. At first it worked perfectly but now when I click to load a file with downloaded poses - the folder comes up empty. Though switching back to the cmt they're all there. Is there a reason why they aren't showing up in the Ana tool? I can't just use the cmt again because I play male viera and the mouth/ears are screwed up - unable to really fix myself.  I have uninstalled the tool and redownloaded it and it hasn't changed anything. I am still pretty new when it comes to using these tools (and a windows computer), in general, therefor my confusion is quite high.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
Have you perhaps set CMTool to use a folder that isn't the default? Anamnesis checks for `Documents/CMTool/MatrixSaves` so if there's nothing there, they won't show up, but can still be navigated to via the Browse button.
