### ISSUE TITLE
Anamnesis crashes game randomly

### ISSUE THREAD

**Issue by LashStarza** [imchillin/Anamnesis#850]
**Describe the bug**
When changing to custom poses or loading character loadouts, Ana seems to stall then crash Final Fantasy.
I tried to figure out whether or not this was happening at a particular time or whatnot but have been unable to ascertain exact process.
I have reinstalled both Final Fantasy (fresh download, install) and Ana. Still occurs.

**To Reproduce**
Steps to reproduce the behaviour:
See description.

**Expected behaviour**
Expected behaviour is the loading of character loadout or custom pose but instead will sometimes (often) stall and then crash final fantasy.

**Log file**
No log file as the issue doesn't seem to affect Ana. Ana remains open.

**Comment by LashStarza** [comment]
I have a bit more info. It would appear that some of the character loadout files are corrupted because I can make it crash constantly on some of the files while others are fine. Did you want me to upload a copy of one of these files?

**Comment by Rubylium** [comment]
Not sure if it's the same, but i have a crash when trying to change an NPC as a player

**Comment by Ani-ki** [comment]
Please provide the log file.

**Comment by Ani-ki** [comment]
Without a log file, we are unable to investigate this issue. It will now be closed.
