### ISSUE TITLE
Shadowhunter is missing his forearms

### ISSUE THREAD

**Issue by jlybelly** [imchillin/Anamnesis#853]
**Describe the bug**
All versions of Shadowhunter's model from Stormblood are missing their forearms. It appears to be an issue with the bandages that would be included in his chestpiece, as changing the chestpiece gives him back his forearms but changing the gloves (even to gloves that would cover the forearms) does not. I experience this bug without other mods active, and began experiencing this bug before installing any other mods outside of anamnesis and gshade.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the actor you would like to replace w/ Gaius.
2. Click on 'Character' then 'NPC' to edit the actor to replace them with Gaius.
3. Search for 'Gaius' and select any of the actors that would have his Shadowhunter/Stormblood/Shadowbringers appearance.

**Expected behaviour**
I would like Shadowhunter to have his forearms in this outfit.

**Log file**
[2022-02-04-14-23-47.txt](https://github.com/imchillin/Anamnesis/files/8006601/2022-02-04-14-23-47.txt)

Further examples of error:
https://pbs.twimg.com/media/FKtwfwkUUAIYVNi?format=jpg&name=medium (completely base/vanilla Shadowhunter, no mods, no adjustments to his equipment)
https://pbs.twimg.com/media/FKtxRM0VEAQ66dP?format=png&name=900x900 (completely vanilla Shadowhunter, no mods, adjustment to gloves that would cover his forearms, to show the issue appears to be with his chestpiece)

**Comment by jlybelly** [comment]
This is listed as closed, but I'm confused. The linked changes affect EventNPCs' hands, while Gaius is not listed under EventNPCs, and as shown in my screencaps, the hand model didn't appear to be the problem.

**Comment by Ani-ki** [comment]
It's closed as it's fixed in the next build.
