### ISSUE TITLE
Anamnesis should not allow user to apply 0 model height

### ISSUE THREAD

**Issue by HoloWise** [imchillin/Anamnesis#862]
**Describe the bug**
If user inserts 0 into model height text field it has a potential to cause some issues such as making body parts disappear, hair freak out and camera detach from actor (I think camera issue happens if user attempts to move with height set to 0)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open FF
2. Open Anamnesis
3. in Character view go to Model section
4. insert height 0 and then 1
5. Observe issues

**Expected behaviour**
Anamnesis should never allow for 0 to be entered there in any form, it can default to 0.001 when it detects 0 since that'll make model invisible and so is functionally identical to 0.

**Log file**
No log files here but a video 😉 

https://user-images.githubusercontent.com/36460595/153308432-a892bb0c-4127-4d93-b046-0e80b348b344.mp4

**Comment by HoloWise** [comment]
This should most likely be tested on other fields (especially ones related to model scaling) and fixed if applicable as well.

I suspect the core issue is that setting things like height or scale to 0 will force the game to unload some character elements

**Comment by Yuki-Walsh** [comment]
This has been fixed with 0625af62703c25eaefd3362a2e6695c21f2d0865

**Comment by Yuki-Walsh** [comment]
Broke this again with de654f5c71d7744d06556fa88c499cb5d97db93e

**Comment by Yuki-Codes** [comment]
Fixed for the next release (again)
