### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by bocochocolina** [imchillin/Anamnesis#866]
[2022-02-15-09-22-22.txt](https://github.com/imchillin/Anamnesis/files/8073225/2022-02-15-09-22-22.txt)

No other copy of Anam exists on my computer, and this shows up when I try to open it to use it.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
