### ISSUE TITLE
MemoryService Error: Process module is invalid.

### ISSUE THREAD

**Issue by PaullyHolmes** [imchillin/Anamnesis#867]
![Screenshot 2022-02-16 161103](https://user-images.githubusercontent.com/99789913/154214190-19d904e4-db60-4402-9ce7-cf5630eccce7.png)

I've tried several fixes like booting the game, re downloading anamnesis, excluding the app from my antivirus scans but still not working. My disk storage is not full either.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
