### ISSUE TITLE
Disabling Pose Mode deactivates "Freeze Actor/Camera World Position"

### ISSUE THREAD

**Issue by 6DK6DK** [imchillin/Anamnesis#868]
**Describe the bug**
"Freeze Actor/Camera..." can be toggled on or off independently of Posing Mode, and Posing Mode can be activated without affecting "Freeze Actor...", but deactivating Posing Mode will forcibly disable "Freeze Actor..." without warning, possibly leading to unintended loss of progress.

**To Reproduce**
Steps to reproduce the behaviour:
1. In gpose
2. Start an animation in Anamnesis
3. Activate "Freeze Actor/Camera World Position" and move the actor
4. Turn on Posing Mode
5. Turn off Posing Mode

**Expected behaviour**
I expect my actor to stay where I moved them but resume animating as normal

**Comment by AsgardXIV** [comment]
Fix submitted for this in #885
