### ISSUE TITLE
Neck/hair bones moving on their own while selected in gpose

### ISSUE THREAD

**Issue by 0rdinaryMage** [imchillin/Anamnesis#870]
Selected neck or hair bone in gpose will jump into another position multiple times until de-selected.

Steps to reproduce the behaviour:
1. Enter gpose 
2. enable posing
3. Select neck or hair R/L
4. Wait 
5. Within 1-30 seconds bone will jump to another location on screen and then return to original position (might be rotating). If selected bone was neck, the movement will not revert and parenting will fail to account for it. 

**Expected behaviour**
Bone doesn't move until its position/rotation is interacted with

**Comment by Ani-ki** [comment]
Per discussion on Discord, nil log req.
