### ISSUE TITLE
GPose crashing with BattleNPC type selected versus Player for Carbuncle

### ISSUE THREAD

**Issue by ahhardesty** [imchillin/Anamnesis#871]
Noticed this issue this morning when I was fussing with trying to get a couple RP poses done using my carbuncle. Gpose was crashing with the entity type of my second pinned person as Battle NPC. However, it was also having some issues with a second pinned person that was a player as well this morning too, so I'm not sure if it's something with multiple pins or with the entity type. Need to look into that a little more.

**Comment by ahhardesty** [comment]
On further investigation, it appears to be an issue with the carbuncle with a different model loaded onto it. I have been able to successfully pause motion and such without anything loaded in its place and with the type set to BattleNPC, however if I load a different model over the carby and do not swap it to Player, gpose will fail to load and I have to Task Manager close the game. Additionally, I am not able to disable motion on the carby either (it acts as though it's disabled, and pose mode works just fine, but it still does the weird small float as though it's moving around in idle still).

**Comment by Yuki-Walsh** [comment]
Can you confirm that all actors have weapons equipped when entering GPose? Having no weapon equipped can cause GPose to hang while loading as it breaks the games animation system.
![image](https://user-images.githubusercontent.com/379714/156316436-1d7354bd-40aa-4ce4-8477-0728eadad46d.png)

**Comment by Yuki-Walsh** [comment]
should be fixed since we've taken away the ability to change actor kind manually, and forced the emperor's fists as a main hand when clearing it.
