### ISSUE TITLE
"Critical Error"

### ISSUE THREAD

**Issue by PaullyHolmes** [imchillin/Anamnesis#872]
*Describe the bug*
-When I start Anamnesis, it always crashes, and warning me (Critical Error): Anamnesis was unable to recover from this error, and must close. (Attached is the screenshot of error.)
![image](https://user-images.githubusercontent.com/99789913/154845291-351f1779-4cfd-4007-97bc-364a6430d1e3.png)

*To Reproduce*
Steps to reproduce the behaviour :
1. Start Anamnesis (I have launched Final Fantasy XIV and logged into a character）
2. Warning
3. See error:
[2022-02-20-22-16-38.txt](https://github.com/imchillin/Anamnesis/files/8104068/2022-02-20-22-16-38.txt)
[2022-02-20-22-29-24.txt](https://github.com/imchillin/Anamnesis/files/8104067/2022-02-20-22-29-24.txt)
[2022-02-20-22-31-21.txt](https://github.com/imchillin/Anamnesis/files/8104064/2022-02-20-22-31-21.txt)

*Expected behaviour*
-I want to know what happened and how to repair it.

**Comment by PaullyHolmes** [comment]
Additional, troubleshoots I did but still get the same error:
-Reinstalling FFXIV.
-Reinstalling Anamnesis, and running the latest ver. of the tool.
-Made an exception for Anamnesis executable in my Antivirus program and Windows Firewall.
-Installed .NET Desktop Runtime 5.0.9 x64.
-Reset the tool by holding down SHIFT button.
-Checked task manager if there were multiple copy of the app running.

**Comment by Yuki-Walsh** [comment]
That's an odd error, usually caused by antivirus preventing Anamnesis from hooking into ffxiv's memory, or by attempting to hook Anamnesis onto something that is not ffxiv. (ACT sometimes impersonates ffxiv and that can confuse Anamnesis)

There might be more settings in your antivirus that need changing.

**Comment by Ani-ki** [comment]
@PaullyHolmes can you try installing 5.0.13 for me, please? I'd like to test a theory.

**Comment by PaullyHolmes** [comment]
> That's an odd error, usually caused by antivirus preventing Anamnesis from hooking into ffxiv's memory, or by attempting to hook Anamnesis onto something that is not ffxiv. (ACT sometimes impersonates ffxiv and that can confuse Anamnesis)
> 
> There might be more settings in your antivirus that need changing.

Hello! I did everything with my antivirus and uninstalled my ACT still nothing works. I also find this error odd. Been using anam for several months now and this never happened before. (Sorry on the late reply. I got really busy with irl stuff. Couldn't find the time to check here.)

**Comment by PaullyHolmes** [comment]
> @PaullyHolmes can you try installing 5.0.13 for me, please? I'd like to test a theory.

Hello! I get this error with 5.0.13 ver. 
![image](https://user-images.githubusercontent.com/99789913/156938913-716e39ad-8dd6-4483-a4e4-2496360864e8.png)
