### ISSUE TITLE
Entering Pose Mode Crashes Anamnesis

### ISSUE THREAD

**Issue by Lexden12** [imchillin/Anamnesis#873]
**Describe the bug**
Anamnesis crashes whenever I try to enter pose mode. Occurs every time.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open GPose
2. Open Anamnesis
3. Click on the Pose button
4. Anamnesis hangs for several seconds before silently crashing

**Expected behaviour**
Expected Anamnesis to open the pose menu successfully.

**Log file**
This is what I have seen every time in the logs:
[2022-02-27-02-11-57.txt](https://github.com/imchillin/Anamnesis/files/8148468/2022-02-27-02-11-57.txt)
One time it generated this long list of exceptions though:
[2022-02-27-02-03-13.txt](https://github.com/imchillin/Anamnesis/files/8148470/2022-02-27-02-03-13.txt)

**Comment by Lexden12** [comment]
I see now that the issue crops up when I drag Anamnesis to my secondary display which is running on my integrated graphics while my primary display is running on my dedicated graphics. Entering Pose mode while Anamnesis is on my primary display allows it to continue functioning, but moving it to my secondary display immediately crashes it.

**Comment by Yuki-Walsh** [comment]
ah, is this possibly #888 ?
