### ISSUE TITLE
Facepaint colour picker lacking colours / unable to pick colours

### ISSUE THREAD

**Issue by LexiKatta** [imchillin/Anamnesis#874]
**Describe the bug**
When going into the colour picker for facepaints I am unable to pick below purple on the light shades section due to 4 blocks of white taking up the middle section of the picker
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Character'
2. Click on 'Facepaint Colour'
3. See error

**Expected behaviour**
Being able to pick light shades of blues and greens for facepaints.

**Log file**
I know it says to post a log file but since this isn't a crash / log error I can only post a screenshot / screensnip of what I see on the menu
![image](https://user-images.githubusercontent.com/100780784/156377566-e32a74b0-f099-4c3b-b3f7-47b4a4adb607.png)

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release.
