### ISSUE TITLE
Legacy Pose File has no specified race

### ISSUE THREAD

**Issue by c0smicreplay** [imchillin/Anamnesis#875]
Hello, im trying to load up a pose file and when i try to apply it it pops up this message. im not sure what it means, or how to fix it, and hope someone can help.

**Comment by Yuki-Walsh** [comment]
hi, can you please attach the pose file?

**Comment by c0smicreplay** [comment]
for some reason i am unable to attach a cmp file, i can give a link to the original download site, if that works?

**Comment by Yuki-Walsh** [comment]
sure, a download link should work fine.

**Comment by c0smicreplay** [comment]
https://www.xivmodarchive.com/private/3168574e-30ec-4433-96f9-9b158da63681/files/Oooh!%20He%20FLEW!!.CMP

i hope this works. i do apologize if it doesnt, but if it doesnt work heres the original xivmodarchive page with it: https://www.xivmodarchive.com/modid/40149#files

**Comment by c0smicreplay** [comment]
one thing i did notice, is that the file doesnt show up unless you change the CMP at the end of the file to lowercase cmp. not sure whats going on, this files kind of a nightmare.

**Comment by c0smicreplay** [comment]
is there any updates or information regarding this? its been two days and id like to get this pose to work. thank you.

**Comment by Yuki-Walsh** [comment]
oh, I see the problem, that's not a *.cmp file, its a *.pose that's had its extension changed. Not sure why or how that happend, but changing the extansion back to *.pose should fix it.

**Comment by Ani-ki** [comment]
> is there any updates or information regarding this? its been two days and id like to get this pose to work. thank you.

Please bear in mind that we don't get paid for this, and we do this in our spare time. A two day wait is more than reasonable for a free tool. Cheers :)
