### ISSUE TITLE
Exiting gpose in game doesn't carry over to the equipment tab.

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#876]
**Describe the bug**
When exiting gpose, the equipment tab will remain greyed out with the warning "cannot be changed while in gpose." Re-entering and exiting gpose once more seems to fix the problem. 

**To Reproduce**
Steps to reproduce the behaviour:
Unsure, as it seems to happen randomly when exiting from gpose in game. 

**Expected behaviour**
Equipment tab to become useable again on the first go.

**Log file**
[2022-03-05-19-38-19.txt](https://github.com/imchillin/Anamnesis/files/8191921/2022-03-05-19-38-19.txt)

**Comment by Yuki-Walsh** [comment]
This might be caused by recent changes to the external refresh system not firing propertychanged events for the 'CanRefresh' property.
