### ISSUE TITLE
anamesis window dont work

### ISSUE THREAD

**Issue by lealin92** [imchillin/Anamnesis#877]
**Describe the bug**
Hello, i have problem with Anamesis even tryin back to previous version without animations. When Anamesis lauch propery and see window i can chage weather and everything. But when i clik anyware (Game window, browser) anamesis window just dissapear. Stil icon is on taks menager, still working in bacground but nothing heaped. I need to use task menager to shut it down.

**To Reproduce**
Steps to reproduce the behaviour:
1.Anamesis 2022-01-31 and later 2021-12-25
2. lauch
3. Talking about not supporting version (on 2021-12-25)
4. See anamesis window
5. click on game widow
6. anamesis windo disaeper
7. still on task bar and in proces on task menager
8. Forced to shut down via task menager

**Expected behaviour**
Sill window on sight with "always on top" feateure

**Comment by Ani-ki** [comment]
Hi there. Can you please confirm if you're running the game in Windowed mode?

**Comment by lealin92** [comment]
> Hi there. Can you please confirm if you're running the game in Windowed mode?

Yep always on windowed without border for easy switch between windows

**Comment by lealin92** [comment]
> Hi there. Can you please confirm if you're running the game in Windowed mode?

And is not there on bacground elier just window just somehow shut down and cant do anythin. I add the last log from ana i got
[2022-03-06-23-11-39.txt](https://github.com/imchillin/Anamnesis/files/8193648/2022-03-06-23-11-39.txt)
g

**Comment by Ani-ki** [comment]
You appear to be on a VERY old version of the .NET Desktop Runtime:

`2022-03-06 23:11:39.764 +01:00 [INF] Framework: .NET 5.0.5`

**[Please make sure you're using the most recent version of the Desktop Runtime (currently 5.0.14).](**url**)**

**Comment by lealin92** [comment]
> You appear to be on a VERY old version of the .NET Desktop Runtime:
> 
> `2022-03-06 23:11:39.764 +01:00 [INF] Framework: .NET 5.0.5`
> 
> **[Please make sure you're using the most recent version of the Desktop Runtime (currently 5.0.14).](**url**)**

Ok im gonna try toomorow (close to midnight for me) and im gonna see. Thanks for info!

**Comment by Yuki-Walsh** [comment]
You might have enabled Mini Mode in settings, try checking for and disabling it.

**Comment by lealin92** [comment]
> You might have enabled Mini Mode in settings, try checking for and disabling it.

Oh my this helped! but still im sad that mini mode dont work i remember this litle cin it was helpfull for my posing
