### ISSUE TITLE
Children "Grow Up" When in Gpose

### ISSUE THREAD

**Issue by XereniaAsgeir** [imchillin/Anamnesis#878]
**Describe the bug**
If a Child is created in Amnesis, they will look and pose as children when placed on another person, as soon as /gpose is typed and started, child actors will suddenly "grow up" into adults.. this will not happen to carbunkles, or yourself, but placing a child appearance or .chara file on them will cause it to happen, even if the child was originally created in Amnesis or by altering Child data from an existing child model. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'load'
3. Scroll down to 'open
4. load in Child Au Ra .chara file.
5. enter /gpose 
6. See error

**Expected behaviour**
The model for another person is supposed to be overlayed by the .chara file but it is not.. at least for Au Ra children. When entering gpose, they will suddenly hit 35 years old. No altering options are available because you cannot be in character edit if also in gpose. I have provided examples with a maidservant, but it does this exact thing when applied to a friend or other player character as well. 

**Log file**
![unknown (1)](https://user-images.githubusercontent.com/101072603/156948253-c3c983a9-7d59-419a-a405-454611266a97.png)
![unknown](https://user-images.githubusercontent.com/101072603/156948255-224afae8-d4e5-4faa-a709-1382c6a847e9.png)

**Comment by Ani-ki** [comment]
This is a known issue. Please load appearances onto Carbuncles as opposed to any actor that is generated using regular player assets.
