### ISSUE TITLE
Idle Character while doing a persistant emote locks the persistant emote serverside

### ISSUE THREAD

**Issue by FatalitySonicX** [imchillin/Anamnesis#879]
**Describe the bug**
While the idle stance has been applied to your character, on other players' end, if you did a persistant emote, you will move while doing that said emote. It can be "dangerous" as it is applied serverside.

**To Reproduce**
1. On Anamnesis, go to the Pose tab.
2. In the game, execute a persistant emote (Bee's Knees, Moogle Dance, etc.).
3. Back to Anamnesis, click the "Idle Character" button.
4. On your screen, you should be back to your idle pose. But while you're moving, you will "slide".
----On the other players' screen however, you will move while doing the persistant emote.
5. To stop the glitch, in Anamnesis, click the "Reset Animation" button. Your character should resume doing the persistant emote you have executed previously and move correctly.

**Expected behaviour**
If possible, your character should be going back to the idle animation not just clientside but also serverside.

**Log file**
[2022-03-07-20-50-58.txt](https://github.com/imchillin/Anamnesis/files/8200512/2022-03-07-20-50-58.txt)

**Comment by Ani-ki** [comment]
Do you by any chance have a video showing this happening serverside on someone else's machine?

**Comment by FatalitySonicX** [comment]
I asked someone to get a video of it for me, I'll post it in a few once they done it.

**Comment by FatalitySonicX** [comment]
Alright, they got it.
https://drive.google.com/file/d/1OJSAFk7NP0jrBykVk7YnPiTBz-FDcegh/view?usp=sharing

**Comment by Ani-ki** [comment]
ASDFGHJKL that should not amuse me as much as it does.

@AsgardXIV would you have any thoughts on this one?

**Comment by Ani-ki** [comment]
I think we're just gonna have to really stick to the whole 'GPose-only' thing. The only overwork changes we should really be allowing are appearance changes. People will continue to ask and I've no qualms telling them no to avoid situations like this.

**Comment by AsgardXIV** [comment]
I think the only risk in this case is for you own character, so we could just disable in that specific case. 
I'll have a think if there is something we can do to avoid it.

**Comment by FatalitySonicX** [comment]
> 

I could always delete the link just to be extra safe but thanks for the responses.

**Comment by AsgardXIV** [comment]
There is definitely a risk this could be detected so we should definitely try and clean it up.
We do want to allow changing animations on overworld characters, but the real risk is when you do it on your own local player character.

I see 2 options:
1. We disable animation control for the local player character in the overworld.
2. We only allow animation control for the local player character in the overworld if the character state is already neutral.

Option 2 is my preference but probably requires a bit more dev work. 

We can leave this one open and I will take it up once I have a working dev env again.

**Comment by Yuki-Walsh** [comment]
I agree that we should disable animation control in the overworld if its going to lead to the server getting weird state updates like that. 

Animating in the overworld isn't super useful for taking screenshots, especially since we can freeze characters in place while they animate now.

**Comment by AsgardXIV** [comment]
The most common use case I've seen for it is around lining up animations (dances or abilities) more easily. 

However, even if we're ok with just not supporting that use case, disabling animation in the overworld likely won't be enough as you could pin the overworld version of yourself in GPose, apply an animation and exit GPose. 

I think the right fix is to stop the animation system from changing the character state of your own character when such a change could in theory be dangerous.

The more I think about it the easier it seems. It really is just a couple of logic checks. 

As soon as I have a working windows machine again I'll take a look at implementing it.

**Comment by Yuki-Walsh** [comment]
This should be fixed now, if someone wants to verify, we'll close this issue.

**Comment by FatalitySonicX** [comment]
> This should be fixed now, if someone wants to verify, we'll close this issue.

Will check in a few. o/

**Comment by FatalitySonicX** [comment]
Alright, after checking with a friend, it seems like the animation controls are disabled when I'm not in GPose. They enable as expected while going in GPose and disables again when exiting it. Seems fixed to me.
