### ISSUE TITLE
Option to convert NPCs into Minions (Pets)

### ISSUE THREAD

**Issue by teutelquessir** [imchillin/Anamnesis#880]
There doesn't seem to be an option to convert NPCs (or anything) into minons (read: pets).  Unless that is the Companion option?  If so, is there a list of the Companion numbers somewhere which lists all the Companion types without having to scroll through the entire huge compendium of Companion numbers to find a specific minion (pet) that one is looking for to use for a model?

Thank you! ^_^

**Comment by Yuki-Walsh** [comment]
You can load the minion appearance under the 'NPC' button:
![image](https://user-images.githubusercontent.com/379714/159147182-91ef12e5-504c-46fa-b5f0-06defa3ee2ed.png)
and you can filter the npc list to only show minions here:
![image](https://user-images.githubusercontent.com/379714/159147171-6357f34a-6497-44bb-8f9c-c45b75e5efec.png)
