### ISSUE TITLE
Facepaint Changes Being Retained when Going to Aesthetician and Redraws

### ISSUE THREAD

**Issue by Darksoul9669** [imchillin/Anamnesis#882]
It seems that on occasion I'm seeing facepaint changes get saved and show up as such when entering the aesthetician, as if I have that option selected and saved on my character. I started trying out Penumbra so maybe it's that as they seem to be finnicky with their redraws together, but to be safe I figured I'd put it out there. I also wasn't running anything on Penumbra other than a body mod that didn't change the facepaints so I'm not sure if that should really be impacting this situation (or if it should regardless of mods).

If this is something that just happens with Penumbra and Anamnesis, my bad; but it may be worth having some warnings around unless I missed them.

**Comment by teutelquessir** [comment]
Are you exiting out of Anamnesis completely, teleporting to a new zone, then exiting out of the game completely to reset your character data?  That should fix the problem.  I'm not a developer or anything, but I know that's what I do any time I use the program to reset all my character data so there's no errors with my game after I use Anamnesis.
