### ISSUE TITLE
Model #2710 is misnamed

### ISSUE THREAD

**Issue by Vievin** [imchillin/Anamnesis#883]
**Describe the bug**
Model #2710 is called "Emet-Selch" in the model list, when it is in fact Storge (the final boss of the dungeon Ahm Araeng).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open "Load NPC"
2. Search "Emet-Selch"
3. Find the one who's got "Model #2710" written under it and load
4. Witness Storge

**Expected behaviour**
The model labeled "Emet-Selch" is Emet-Selch. (If Emet ever transformed into Storge or anything and that's why the model pops up, perhaps it could be manually edited to avoid confusion?)

Edit: Model #2710 also shows up under Storge with a different ID, perhaps the title was poorly worded. It is "resident NPC #1028666" who is misnamed. (There is an event NPC with "Event NPC #1028666". which is correctly labeled as Storge.)

**Comment by Yuki-Walsh** [comment]
unfortunately, the names of Resident NPCs are pulled directly from the game files, meaning that mistake is on SQEX's side, we cant fix it.
