### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by SCowart** [imchillin/Anamnesis#884]
[2022-03-12-18-27-17.txt](https://github.com/imchillin/Anamnesis/files/8238686/2022-03-12-18-27-17.txt)

**Comment by SCowart** [comment]
No quite sure but it says anamnesis was unable to recover from this error and must be closed. I have closed it. Tried to reopen it, says multiple anamenesis process found. Please close all other instances, but I don't have any others open.

**Comment by Ani-ki** [comment]
[**FAQ**](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)
