### ISSUE TITLE
NPC appearances do not load when entering GPose

### ISSUE THREAD

**Issue by sirenhavok** [imchillin/Anamnesis#890]
When I upload an NPC, they show up fine when not in Gpose, but once I get into gpose, they don't appear, it's just a random model. 
For example, if I upload Emet - Selch into the gpose, he doesn't show up, a random elezen does. 

**To Reproduce**
1. Load an NPC appearance onto the players actor
2. enter gpose
3. observe that the face and hair reset to normal player options

**Workaround**
> Load NPC appearances on carbuncles or chocobos, as they are already a type of NPC, the game allows them to load the NPC appearance options without the (currently not working) NPC face hack.

**Comment by nealinor** [comment]
I'm having this problem with G'raha Tia. He's fine when not in gpose, but once in Gpose, his face changes.

**Comment by Yuki-Walsh** [comment]
A work around to this is to load NPC appearances on carbuncles or chocobos, as they are already a type of NPC, the game allows them to load the NPC appearance options without the (currently not working) NPC face hack.

**Comment by lhWeiss** [comment]
I'm having this issue as well. If you load the appearance to minions, they also reset

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release
