### ISSUE TITLE
Actor refresh results in Error

### ISSUE THREAD

**Issue by KGruson** [imchillin/Anamnesis#892]
**Describe the bug**
Whenever i try to change something on any PC or NPC, Anamnesis gives out an error that it "Failed to refresh actor".
When i go into gpose the changes are applied tho.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Game
2. Open Anamnesis
3. Try to change anything

[2022-03-24-23-36-21.txt](https://github.com/imchillin/Anamnesis/files/8346185/2022-03-24-23-36-21.txt)

**Comment by Yuki-Walsh** [comment]
looks like you enabled Penumbra redraw feature in Anamensis without enabling the HTTP API in penumbra
