### ISSUE TITLE
Allow entering of any value to Actor Scale numberbox

### ISSUE THREAD

**Issue by BigMunsBuns** [imchillin/Anamnesis#893]
The recent update added a cap to the maximum actor scale/height available to users, both in and out of gpose. This can be extremely limiting to specific content creators and general creativity.

I request the hard limits on actor scale be removed. Ideally, a player would be able to manually value above the slider's cap like they could in versions past. If a happy medium needs to be reached, perhaps "a use-at-your-own-risk" delimit checkbox would serve well for those wanting to work outside of the would-be soft caps?

**Comment by Yuki-Walsh** [comment]
We should implement exponential slider values and increase the max scale value to 1024 to cover this case.

**Comment by BigMunsBuns** [comment]
Would restoring uncapped, manual entry be viable? It would cover the broadest range of use. 

I'm told 1024 is the maximum value before one needs to modify camera FoV and distance to see an actor. If there *needs* to be a cap I would advocate for one much higher than 1024.

For the slider values, I think whatever fits the most general users or use cases would suffice — ten is fine, honestly. Those who work with bigger scales have used and may prefer the granular to-the-hundredth/thousandth control of manual entry.

**Comment by AIIiz** [comment]
Personally, I'd love to have this limit uncapped back.

Having the slider capped at 2 limited a personal project I was in the middle of (project I spent some money in already). I don't necessarily use or expect the 100% of the uncap back (most definitely couldn't use above a certain number, 15 being the max) but could definitely use a bigger cap than barely 2.

**Comment by AliceApplez** [comment]
Having it uncapped on manual entry again would be perfect... This change is really limiting :(

**Comment by UndefinedUndefined** [comment]
> Having it uncapped on manual entry again would be perfect... This change is really limiting :(

This would be nice, I like the sliders and the min/max is fine. 
But on the off chance I'd like 200 boob size then this would be amazing!

**Comment by Yuki-Walsh** [comment]
Sounds like general consensus is just to allow exceeding of the max value for scale when entering values via text.

Shouldn't be too hard to add a `CapValueEntry` property to the `NumberBox` control and set it to false just for the `TransformEditor` scale.

**Comment by Ani-ki** [comment]
Just a heads-up to let you know that we'll be pushing an update to address this and other issues on Sunday (03/04/21 Australian time).

**Comment by Ani-ki** [comment]
Quiet bump for edited comment about the next update
