### ISSUE TITLE
Locking World Position/ Camera while animating and then closing the tool causes overworld issues.

### ISSUE THREAD

**Issue by CapnKett** [imchillin/Anamnesis#897]
**Describe the bug**
If you hit the lock world position/ camera button and do some animations, then close the tool without unlocking and exit gpose, the Actor's position and camera remain locked. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter gpose
2. In the posing tab, Lock world positions/ camera
3. Close the tool
4. Exit gpose
5. All affected Actors now stuck
6. Solution: restarting the game and tool completely. 

**Expected behaviour**
Expected to simply resume overworld functionality.  

**Log file**
I have added my last 4 as they showcase attempts and trying to fix the issue by restarting the tool initially

[2022-03-24-21-00-46.txt](https://github.com/imchillin/Anamnesis/files/8347331/2022-03-24-21-00-46.txt)
[2022-03-24-20-57-48.txt](https://github.com/imchillin/Anamnesis/files/8347332/2022-03-24-20-57-48.txt)
[2022-03-24-20-56-48.txt](https://github.com/imchillin/Anamnesis/files/8347333/2022-03-24-20-56-48.txt)
[2022-03-24-20-51-05.txt](https://github.com/imchillin/Anamnesis/files/8347334/2022-03-24-20-51-05.txt)

Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by AsgardXIV** [comment]
Oh. I don't think we have anything which will undo it when Ana closes. I'll fix.
