### ISSUE TITLE
Toggle Weapon Visibility not working

### ISSUE THREAD

**Issue by nyanyaxiv** [imchillin/Anamnesis#899]
**Describe the bug**
Toggle Weapon Visibility not working

**To Reproduce**
Steps to reproduce the behaviour:
1. Add weapon to main/off-hand slot
2. Enter Gpose (or stay outside)
3. Click "Toggle Weapon Visibility"

**Expected behaviour**
Before the latest update the toggle would work in and outside of Gpose. Albeit the weapon would reappear if you hid it before entering Gpose (and then entered).

Apologies if this was already reported or if I'm just doing it wrong. Couldn't find anything on the topic.

**Comment by AsgardXIV** [comment]
Is the weapon drawn when you are doing this? You need to set the scale to 0.

In the previous version of Ana, the toggle would just set the scale to 0, in the new version it follows the same rules as if you toggle it in the character menu (Same with the new Visor and Hat toggles). 

![image](https://user-images.githubusercontent.com/95163444/160254275-42177f84-9c44-4a62-b128-2e3b30cc99ce.png)

**Comment by nyanyaxiv** [comment]
> Is the weapon drawn when you are doing this? You need to set the scale to 0.
> 
> In the previous version of Ana, the toggle would just set the scale to 0, in the new version it follows the same rules as if you toggle it in the character menu, so it will be invisible when sheathed and visible when drawn.
> 
> If you want to hide a drawn weapon, set the scale to 0 as shown below.
> 
> ![image](https://user-images.githubusercontent.com/95163444/160254275-42177f84-9c44-4a62-b128-2e3b30cc99ce.png)

Previously when the weapon was drawn and the toggle was clicked it would hide it. Now it doesn't do anything. I know scaling works so it's definitely not a big deal if the toggle itself doesn't work. It's just that the toggle is kind of obsolete haha. At least, if I'm understanding this all correctly.

**Comment by nyanyaxiv** [comment]
> Is the weapon drawn when you are doing this? You need to set the scale to 0.
> 
> In the previous version of Ana, the toggle would just set the scale to 0, in the new version it follows the same rules as if you toggle it in the character menu, so it will be invisible when sheathed and visible when drawn.
> 
> If you want to hide a drawn weapon, set the scale to 0 as shown below.
> 
> ![image](https://user-images.githubusercontent.com/95163444/160254275-42177f84-9c44-4a62-b128-2e3b30cc99ce.png)

Oh I know I know, scaling still works fine. It's not a major issue, it just makes the toggle obsolete since it just doesn't do anything at all.

But to clarify what I'm doing, here's a [video](https://cdn.discordapp.com/attachments/907597350413934602/957406935118909500/2022-03-26_23-28-18.mp4). Before this would hide the weapon the same as scaling it to 0 would. Now it's just... nothing?

**Comment by AsgardXIV** [comment]
It's because you have the weapon actually drawn. If it was sheathed at your side it would hide/show it, just like the toggle in game (So if you had it hidden in game, it would show it).

**Comment by nyanyaxiv** [comment]
> It's because you have the weapon actually drawn. If it was sheathed at your side it would hide/show it, just like the toggle in game (So if you had it hidden in game, it would show it. which scale can't do).

Aahhh fair enough

**Comment by AsgardXIV** [comment]
Not sure if Yuki or Ani maybe has an idea about how to improve the UI around it (Have 2 toggles or similar).

**Comment by Yuki-Walsh** [comment]
can we detect if the weapon is drawn? we could swap out the toggle functionality for scale at the time? Trying to avoid having 2 toggle buttons on the UI for the same task again.

**Comment by Yuki-Walsh** [comment]
(github auto closed this, but its not fixed yet)

Now that we have the IsSheathed, I can update the UI to have the toggle swap out for the old scale one when the weapon is drawn.
