### ISSUE TITLE
Paladin Offhand Shield

### ISSUE THREAD

**Issue by Arnasja** [imchillin/Anamnesis#901]
**Describe the bug**
I have a Paladin and I cannot select a shield to equip in the offhand slot because there is no listing for them in the equipment data base for Anamnesis. 

**Expected behaviour**
To be able to select an offhand shield.

![No Shield](https://user-images.githubusercontent.com/102417617/160239951-02ad5490-fc3c-46f1-b4d9-0985bfb50112.png)

**Comment by Arnasja** [comment]
Found a work around...
looks like Anamnesis thinks the shields are main hand models, so ticking that "force main hand model" should show them up for now

**Comment by Yuki-Walsh** [comment]
This has been fixed for the next release
