### ISSUE TITLE
Paladin Offhand Shield

### ISSUE THREAD

**Issue by Arnasja** [imchillin/Anamnesis#902]
**Is your feature request related to a problem? Please describe.**
 Yes it is related to a problem.

I have a Paladin and I cannot select a shield to equip in the offhand slot because there is no listing for them in the equipment data base for Anamnesis. 

**Describe the solution you'd like**
To be able to select an offhand shield.
![No Shield](https://user-images.githubusercontent.com/102417617/160240072-39a8a328-1e14-4e6c-9e1c-5ffd73ff6f9c.png)

**Comment by Ani-ki** [comment]
Please do not open feature request tickets for bug reports. Ensure you have followed the bug reporting instructions properly in future.
