### ISSUE TITLE
Model+Extended Appearance Panels Vanishing on NPC Load

### ISSUE THREAD

**Issue by Lionheart237** [imchillin/Anamnesis#904]
**Describe the bug**
When loading non-player rigs, Model and Extended Appearance panels on the right side of the window disappear, removing functionality from the tool, such as Height/Scaling and the Wet slider.

**To Reproduce**
Steps to reproduce the behaviour:
- Boot Anamnesis
- Appearance tab
- Load NPC -> any non-player base (such as a minion)
- Watch panels disappear

**Expected behaviour**
Rather than removing entire panels with functions that still might work, simply deactivate ones that aren't compatible with a given model.

**Log file**
I don't believe the log helps much in this case, but here it is.
[2022-03-28-04-51-55.txt](https://github.com/imchillin/Anamnesis/files/8361186/2022-03-28-04-51-55.txt)

**Comment by Yuki-Walsh** [comment]
oh, looks like that got broken a while ago, its been fixed for the next release in 1e7149b556688ba7498464ce14fd46bf453d6c7e
