### ISSUE TITLE
Cant zoom out of appilcation

### ISSUE THREAD

**Issue by PlushieWarlock** [imchillin/Anamnesis#906]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
i wanted to zoom in on the skeleton to be able to pose an amajiaa better but now im unable to zoom out, unable to scroll down or left to right, tried to uninstall and redownload but the app stay the same all zoomed in 
![image](https://user-images.githubusercontent.com/102613502/160661423-ec525193-c87d-4c3b-a9a6-0381f9a14c75.png)
i put a screenshot of what i can see, everything else im unable to access no matter what i do, even trying to zoom out  with the ctrl key doesn't work

**Comment by Ani-ki** [comment]
A reset of the tool's settings will resolve this. 

**In future, please follow the [Troubleshooting section of the wiki](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting) prior to reporting issues.**
