### ISSUE TITLE
"Failed to refresh actor" bug?

### ISSUE THREAD

**Issue by OrielShepherd** [imchillin/Anamnesis#909]
[2022-04-01-17-40-37.txt](https://github.com/imchillin/Anamnesis/files/8395426/2022-04-01-17-40-37.txt)
 
Hi, I've been having an issue for the past few days, where once i try to load a Player i have already saved, it will give an error that says "Failed to refresh actor". It was working fine and then broke suddenly once i left gpose and attempted to change my Player model.
Everything will stay the same with the model, bar the height and colouring. 
I've uninstalled and redownloaded both the game itself and Anamnesis but the issue persists, am i just stupid and missing something or is this a bug?
Thanks.

**Comment by Peebs-miqo** [comment]
It looks like you're using the 'Use Penumbra Redraw' option without having enabled the HTTP API within Penumbra itself. Please either enable the HTTP API in Penumbra or disable the 'Use Penumbra Redraw' option in Anamnesis.

**Comment by OrielShepherd** [comment]
Oh okay, that's a simple fix.
Thank you so much!
