### ISSUE TITLE
NPC applied on PC changes to vanilla face appearance when triggering GPOSE in game

### ISSUE THREAD

**Issue by HuldraK** [imchillin/Anamnesis#910]
**Describe the bug**
When loading NPC onto Character (eg. Emet-Selch in this case, but have tried with Hythlodaeus, Themis, Erichtonios, and Thancred with same result), the load works in gameplay but will change to vanilla Elezen (or corresponding race) face setting. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Choose Player Character
2. Go to 'Character'
3. Click on 'NPC'
4. Click on 'Emet-Selch Model: #2941' 
5. Return to FFXIV game window
6. Enter gpose: /gpose on chat
7. Sees error

**Expected behaviour**
Gpose should simply show both the NPC face and body in place of player character. 

**Log file**
[2022-04-02-15-13-29.txt](https://github.com/imchillin/Anamnesis/files/8402718/2022-04-02-15-13-29.txt)

I wanted to upload appearance file as well, but when saved it just shows NPC as they should look like.

**Comment by Ani-ki** [comment]
**Please do not open duplicate tickets.**
