### ISSUE TITLE
Failed to refresh actor error, happens whenever trying to load saved appearance data/change gear

### ISSUE THREAD

**Issue by ForevermoreOwO** [imchillin/Anamnesis#911]
[2022-04-02-18-59-40.txt](https://github.com/imchillin/Anamnesis/files/8403669/2022-04-02-18-59-40.txt)

**Comment by Peebs-miqo** [comment]
You have the 'use penumbra refresh' option selected. Either turn it off or enable the HTTP API in your Penumbra settings.
