### ISSUE TITLE
Unlinked scale behaving strangely with weapons

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#918]
**Describe the bug**
The scale slider/boxes on the Equipment screen work fine whether linked or unlinked.
In Posing mode, the weapon/sheath/scabbard bones behave as expected when the linked scale slider is used on them.
However, if the scale slider is unlinked, the X slider continues to scale all three axes, while the Y and Z sliders have no effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter GPose and switch to Posing mode with scale enabled
2. Click the weapon, scabbard, or sheath bones (as relevant to current character state)
3. Unlink scale
4. Attempt to scale the bone on any slider and it will either affect all three or not affect anything

**Expected behaviour**
For the unlinked scale slider in Posing mode to behave like the one on the Equipment screen and scale individual axes.

**Comment by Yuki-Codes** [comment]
This is a limitation of the game engine unfortunately. You can still scale the weapon on each axis by using the Main Hand weapon bone (On the matrix or 3d views) or by using the weapon scale in the character tab while posing.

Additionally, in future versions the ability to unlink the scale slider will be removed for the bones where independent axis scaling is not available:
