### ISSUE TITLE
Scale value does not update if you click in the box beforehand

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#919]
**Describe the bug**
If you're trying to use the scrollwheel to adjust scale up/down, it will still work, but the number itself will not change if you clicked in the box beforehand. Clicking outside of the box causes the value to update. If you scrollwheel without clicking into the box, the value updates as normal.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter GPose, switch to posing mode with scale enabled
2. Click inside the box with '1.0' inside it with any bone selected
3. Use the scrollwheel to adjust the scale
4. Number does not update, but the scale still changes ingame

**Expected behaviour**
For the number to represent the current scale value of the bone.

**Comment by Sparrows413** [comment]
Update: Issue appears to happen with _any_ numerical value, not just scale.

**Comment by Yuki-Walsh** [comment]
actually, we need to check if this was affected by https://github.com/XIV-Tools/XivToolsWpf/commit/2116d85925ad68c13a312cbf14118628389dfe04

**Comment by Yuki-Codes** [comment]
This has been fixed for the next release
