### ISSUE TITLE
Restore earlier states

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#92]
Using this as a central point for the following issues: #93 and #305 

A system for restoring the earlier states of values, panels, pages, or the entire program at once.

CMTool has Save states for camera:
![image](https://user-images.githubusercontent.com/109395/115673110-8cccb500-a34c-11eb-9e32-25ddb3e922a2.png)

And save states for gear/appearance:
![unknown](https://user-images.githubusercontent.com/379714/115710306-89214880-a3b5-11eb-983f-b287312b9db7.png)

A Unified system for recording and restoring values that covered these use cases and possibly an undo stack is desirable.

**Comment by MissAniThrope** [comment]
This is actually a lot more complex than people think it is to implement, and while it’s not entirely impossible, it would take a LOT of time to do that at this stage could be better spent elsewhere. I’m not ruling it out but due to the nature of the function it would be incredibly low priority.

**Comment by Yuuki-Walsh** [comment]
I think adding a save/restore state option generically to each numberbox and panel might cover many use cases?
![undo](https://user-images.githubusercontent.com/379714/115711163-8ecb5e00-a3b6-11eb-86e5-bcbc172d8e41.jpg)

Additionally the typical program-wide [ctrl][z} and [ctrl][y] would help a lot, but might be difficult with memory updating the UI not entering into the undo stack?

**Comment by Yuki-Walsh** [comment]
Since we've implemented undo/redo, and camera saves, I think scenes will cover what left here.
