### ISSUE TITLE
NPCs wielding offhand items are using the mainhand models

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#920]
**Describe the bug**
This bug only appears to affect loading NPCs who use a mainhand weapon with some offhand 'aesthetic' (so far I have tested and confirmed this happens with bows/quivers, starglobes/card decks, and katanas/sheathes). It does not affect NPCs wielding sword-and-shield or twin daggers.

Loading in any NPC using one of the affected weapons will have them wield their regular mainhand, but their offhand weapon will appear with whatever the equivalent mainhand model would have been. This leads to oddities such as [G'raha duel-wielding bows](https://i.imgur.com/nn9kXxS.png), [Urianger dual-wielding starglobes](https://i.imgur.com/1pAm1Cs.png), and [Makoto duel-wielding katanas](https://i.imgur.com/2d7ag5l.png).

*However*, as I found out while attempting to pick specific NPCs you can use to test this out, I found that [both Hien and Gosetsu load their weapons in normally with a katana and sheath as expected](https://i.imgur.com/5y8Lgqn.png). I noticed that they use 'Unknown' (NPC-only) weapons, whereas the other NPCs I tested out were all using player-accessible weapons. Maybe it doesn't happen for the NPC-exclusive ones?

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Load appearance of an NPC using one of the affected weapon types in hainhand and offhand
3. Observe their mighty dual-wielding prowess

**Expected behaviour**
I would expect the NPCs to load in with their regular mainhand and offhand appearances instead of dualwielding mainhand appearances.

**Comment by Yuki-Codes** [comment]
This has been fixed for the next release.
