### ISSUE TITLE
Will not launch, gives Critical Error

### ISSUE THREAD

**Issue by Winged-Monotone** [imchillin/Anamnesis#921]
**Describe the bug**
My computer recently BOSD'd and I had to reinstall its system files, all of my other programs seem to be working fine, but when I try to activate Asam it I get the message and error in the screenshot, which I am sorry but the file of the log won't save and seems to be having issues and it won't save any logs as of this incident, I'll try to capture the entire incident code.

**Log file**
![image](https://user-images.githubusercont
![image](https://user-images.githubusercontent.com/12200839/161631264-3e8f151f-3dd0-4aa1-aac2-1d6206474172.png)
ent.com/12200839/161631211-6604aeec-82e5-49e2-85ef-79d9cd987f75.png)
![image](https://user-images.githubusercontent.com/12200839/161631316-fe25def3-b90d-4613-8df9-fadcab6de35c.png)
![image](https://user-images.githubusercontent.com/12200839/161631339-5487933a-2c5e-49bf-9a34-bb98ba12c96b.png)

**Comment by Ani-ki** [comment]
Given it's generated those error messages, a log should exist.

Additionally, in future please ensure you follow the template provided.

**Comment by Yuki-Walsh** [comment]
Reinstalling the .net desktop runtime might fix it, if not, I'm not sure.

**Comment by Ani-ki** [comment]
No further information was provided by the user so this ticket will assume their issue is resolved and be closed.
