### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by greenfox50** [imchillin/Anamnesis#924]
Failed to initialize Lumina
![anamnesis issue](https://user-images.githubusercontent.com/103156023/162098113-a647de32-e002-499b-8fc3-de38417310c4.PNG)

A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Ani-ki** [comment]
**[FAQ.](https://github.com/imchillin/Anamnesis/wiki/FAQ#i-opened-an-issue-or-feature-request-but-it-was-closed-what-happened)**
