### ISSUE TITLE
Anamnesis opens up then disappears once  I click away

### ISSUE THREAD

**Issue by greenfox50** [imchillin/Anamnesis#925]
**Describe the bug**
The app usually loads and i can use it until i click out of the window. The blue icon to pop it up in game does not show up. Anamnesis still shows as running in windows but is nowhere in game

**To Reproduce**
Steps to reproduce the behaviour:
1. Run anamnesis as an administrator
2. Click away from the anamnesis app in game
3. Anamnesis disappears 

**Expected behaviour**
Anamnesis loads the smaller icon, then i can go in and out of it in game

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by Yuki-Walsh** [comment]
hmm, we've had problems with the mini mode icon disappearing off peoples monitors. holding shift when you launch Ana should reset the settings to default and restore the default functionality.
