### ISSUE TITLE
Unique faces reverting to unselected base faces 

### ISSUE THREAD

**Issue by BurningBloom** [imchillin/Anamnesis#926]
**Describe the bug**
Some special faces, such as the elderly Elezen faces or even the unique faces of say the Garleans like Gaius or Nero revert to their base game elezen base equivalents whenever entering gpose.  

**To Reproduce**
Steps to reproduce the behavior :
1. Go to the race section in the character customization screen in anamnesis
2. Click on the age
3. Scroll down to select "old"
4. Once done, then enter /gpose into chat

**Expected behaviour**
This should show the chaning of the facial model from "old" to "normal" while in gpose and not the selected face in the model editor. 

**Log file**
[2022-04-06-21-52-22.txt](https://github.com/imchillin/Anamnesis/files/8439255/2022-04-06-21-52-22.txt)

**Comment by Ani-ki** [comment]
**[Please do not open duplicate tickets.](https://github.com/imchillin/Anamnesis/issues/890)**
