### ISSUE TITLE
Added an option to synchronize the game time with the real time

### ISSUE THREAD

**Issue by Luna664** [imchillin/Anamnesis#928]
Hi, I would like to propose the addition of an option to synchronize the time in games with that of the PC in the world module of Anamnesis, it would be particularly interesting for roleplay players

**Comment by Ani-ki** [comment]
This won't really be possible as Anamnesis was not designed or built to be left open for extended periods, as this could potentially have negative impacts over performance both in the tool and in the game. A feature like this would be better suited to a Dalamud plugin, which would be active throughout runtime.
