### ISSUE TITLE
Save states

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#93]
From the Feedback Survey: i'm unsure where the save states are? and if that's it in the bottom right, does that mean we only get one save state per bone? personally, i would like two as in CM2.

**Comment by Yuuki-Walsh** [comment]
Could probably leverage the scene system. This could possibly also be used for a undo/redo stack.

**Comment by Yuuki-Walsh** [comment]
pushing this discussion to #92 to consolidate.
