### ISSUE TITLE
Failed to Extract Pose Library

### ISSUE THREAD

**Issue by DiscardedData** [imchillin/Anamnesis#930]
Hi there,

Whenever I launch Anamnesis (admin or not), I get the error "Failed to extract pose library." This error goes away if I delete everything in the AppData folder, but comes back on subsequent launches.

I have a pose folder at My Docs/Anamnesis/Poses, but nothing is in there. 

[2022-04-08-13-07-16.txt](https://github.com/imchillin/Anamnesis/files/8454949/2022-04-08-13-07-16.txt)

**Comment by Ani-ki** [comment]
**[Please do not open duplicate tickets.](https://github.com/imchillin/Anamnesis/issues/891)**
