### ISSUE TITLE
Failed to scan memory for text signature: AnimationSpeedPatch

### ISSUE THREAD

**Issue by mikustarbloom** [imchillin/Anamnesis#933]
**Describe the bug**
I click the Poses mode and then the program will freeze and close, then the error pops up.

**To Reproduce**
1. Go to 'Anamnesis'
2. Click on 'Poses'

**Log file**

[2022-04-09-01-39-25.txt](https://github.com/imchillin/Anamnesis/files/8456400/2022-04-09-01-39-25.txt)

**Comment by AsgardXIV** [comment]
This error is caused when Anamnesis fails to close properly (which it sounds like it does the first time you go to poses).

It could be #888 which is causing the initial crash. Do you have 12th gen intel graphics?
