### ISSUE TITLE
Lumina critical error (patch 6.1)

### ISSUE THREAD

**Issue by Zikose1** [imchillin/Anamnesis#956]
**Describe the bug**
Anamnesis encounters an error

**To Reproduce**
Steps to reproduce the behaviour:

1. Start the game
2. launch Anamnesis 
3. Lumina critical error 

**Expected behaviour**
software operation

**Log file**

[2022-04-14-22-07-53.txt](https://github.com/imchillin/Anamnesis/files/8491994/2022-04-14-22-07-53.txt)

**Comment by RageShoTT** [comment]
Wait for an update, see issue #937
