### ISSUE TITLE
Critical Error after 6.1 patch

### ISSUE THREAD

**Issue by Gk247** [imchillin/Anamnesis#960]
Hello,
I've tried starting Anamnesis after 6.1 like always but this Error Message always pops up. Could you please help me indentify the error and help me resolve it?

[2022-04-15-03-41-55.txt](https://github.com/imchillin/Anamnesis/files/8493316/2022-04-15-03-41-55.txt)

**Comment by Ani-ki** [comment]
Duplicate of #937
