### ISSUE TITLE
Remove dye when selecting Clear Slot

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#963]
**Is your feature request related to a problem? Please describe.**
Using the Clear Slot function only removes the item, leaving the dye behind.

**Describe the solution you'd like**
Clear the dye at the same time.

**Comment by 92RED** [comment]
Hello, I suspect the issue refers to when the clear option is used and the weapon dyes are left behind, or is there a different piece of equipment that is affected by this issue as well?

**Comment by Ani-ki** [comment]
Oh, you beat me to it!
It was all gear.

**Comment by Ani-ki** [comment]
That was only main and off BTW Yuki.

**Comment by 92RED** [comment]
I see, for all other equipment it was working as soon I forked from the master branch, except the main/off hand slots.

**Comment by Yuki-Walsh** [comment]
yep, I got it. its the other clear button. Am fixing now.

**Comment by Yuki-Walsh** [comment]
fixed it. dye will clear whenever the user equips none or emperor's new fists.
