### ISSUE TITLE
lumina issue? sorry for the trouble :)

### ISSUE THREAD

**Issue by feaqu** [imchillin/Anamnesis#975]
[2022-04-17-20-27-04.txt](https://github.com/imchillin/Anamnesis/files/8502106/2022-04-17-20-27-04.txt)

**Comment by MasterZen369** [comment]
Can we get an update soon. Love the program, miss taking amazing pictures, Or could you possibly let us know if your working on it or not?

**Comment by Maxunit** [comment]
Anamnesis for 6.1 is being worked on.

**Comment by nadfor404** [comment]
Thank you for your hard work!! looking forward to the new update.

**Comment by Peebs-miqo** [comment]
Duplicate of #937
