### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by zeautumn** [imchillin/Anamnesis#976]
![Capture d’écran 2022-04-17 144022](https://user-images.githubusercontent.com/94714182/163728018-beda8004-ec5e-43e4-a295-32cf9b55e919.png)

**Comment by Sparrows413** [comment]
The tool needs to be updated for 6.1. Have some patience.

**Comment by zeautumn** [comment]
> The tool needs to be updated for 6.1. Have some patience.

Ah, perfect. I thought the error was something else. Thank you.

**Comment by Peebs-miqo** [comment]
Duplicate of #937
