### ISSUE TITLE
[Feature Request] Organise items per level or ilevel

### ISSUE THREAD

**Issue by lhWeiss** [imchillin/Anamnesis#979]
It's a little confusing scrolling through the items and having level 30 things mixed with level 87. If possible, could we organise by ilevel or level?

A solution would be adding a level filter, although I'm not sure this is possible.

Thank you!

**Comment by Ani-ki** [comment]
We're already pulling class/Job data so this shouldn't be too much of a stretch for a future build. We'll see what we can do!

**Comment by Yuki-Codes** [comment]
This has been added for the next release.
