### ISSUE TITLE
My Anamnesis is being buggy

### ISSUE THREAD

**Issue by Derasdt** [imchillin/Anamnesis#982]
Critical Error Anamnesis was unable to recover from this error, and must close
GameDataService Error: Failed to initialize Lumina (are your game files up to date?)

[2022-04-18-10-02-34.txt](https://github.com/imchillin/Anamnesis/files/8506100/2022-04-18-10-02-34.txt)

**Comment by Ani-ki** [comment]
Duplicate of #937

**Comment by Derasdt** [comment]
Yea that makes no sense to me

**Comment by EstoyMejor** [comment]
Your Anamnesis version is horribly outdated. Or was. 
Update your anamnesis if the issue persists.
