### ISSUE TITLE
Freezing appearance/equipment

### ISSUE THREAD

**Issue by cspaen** [imchillin/Anamnesis#984]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature I'm missing and would *love* to see. 

**Describe the solution you'd like**
A way to freeze/unfreeze certain character appearance and equipment slots to make them persistent through loading screens/zone changes. An example of this would be CMTool's tickboxes. 

![image](https://user-images.githubusercontent.com/41430380/163826524-43982701-5319-4db8-a032-78822b0761e7.png)

**Comment by Ani-ki** [comment]
We will not be implementing this. See: **[Gear Being Carried Across Loading Screens](https://github.com/imchillin/Anamnesis/wiki/Before-Making-a-Suggestion#gear-being-carried-across-loading-screens)**.
