### ISSUE TITLE
Failed to read game color data

### ISSUE THREAD

**Issue by LadyLizellea** [imchillin/Anamnesis#986]
### Solution:
This issue is caused by corrupted game files from Tex Tools.
Perform an Index clean:
 1. Select: Help -> Download Index Backups
 2. Select: Help -> Start Over
 
Do **NOT** apply any backup modpacks, as these will re-corrupt the file.
![image](https://user-images.githubusercontent.com/379714/163905909-9838094c-e95f-4d9e-bc22-d863f763be25.png)

----------------------------------------------------------

### Original Issue
First I had to download the new one due to me not getting an automatic update what so ever. Even though I can use the tool now, I get an error opening it before it goes to the actual tool. I don't know how to reproduce anything as it happens when I open up the tool at the start. I also don't know how to get the log file but the error itself is pretty simple. It says: 

Error
Failed to read game color data
File type 42951980 is not implemented

**Comment by nannoxxx** [comment]
I also have this same issue! 
Failed to read game color data. File Type 3667400659 is not implemented
(not showing the colors for hair etc etc)

**Comment by Yulu7766** [comment]
Same
![Dialog 4_19_2022 2_30_11 AM](https://user-images.githubusercontent.com/103951241/163852490-4efed79f-8782-41f3-b9d6-a546d4755cbe.png)

**Comment by nannoxxx** [comment]
![anem error](https://user-images.githubusercontent.com/103955809/163852731-1b7590a6-1482-4a20-bbd2-b3827edf85a4.png)

**Comment by Groot0075** [comment]
Welp finally had a breakthrough in where it's not the effect mods i have installed but still something with the backup mod pack that i made though i do not know which one it is though i have learned something new at least though now i also knows that it might be one of non-effect mods like possibly a mod that affects the mounts as it can't be the body or outfits mods i have installed
I hope this helps explain something at least though it might be different for other people but still hope this help in figuring out what might be causing t he issue

**Comment by LadyLizellea** [comment]
I am new to the modding and such with textools. So can you explain to me how to do that please and I can try it.

**Comment by Yuki-Walsh** [comment]
You can get them here in the Tex Tools window:
This will reset all your mods.
![image](https://user-images.githubusercontent.com/379714/163901753-e08bb2fc-26b4-461e-8abb-09099636fcee.png)

**Comment by LadyLizellea** [comment]
Thank you I will try that now

**Comment by LadyLizellea** [comment]
Nope I now have another error. This is what it says now after doing that. [https://i.gyazo.com/d8e1686cb32d9cc61689be4b00313bc7.png](url)

**Comment by Yuki-Walsh** [comment]
Did you also run the 'Start Over' option after the 'Download Index Backups' to apply them?

**Comment by LadyLizellea** [comment]
Yes I did as it said to do so.

**Comment by S1lentSymphony** [comment]
> Did you also run the 'Start Over' option after the 'Download Index Backups' to apply them?

Yes. I created a backup mod pack because I knew I would have to start over. After starting over, imported my backup modpack and removed a few mods. Same issue occurred.

**Comment by Yuki-Walsh** [comment]
ah, backup mod packs appear to be the cause of the bug, try it without applying your backup.

**Comment by LadyLizellea** [comment]
That means I have to download the mods again one by one. I also didn't do my mod backup when the game updated. texttools auto reapplied my mods so I didn't have to. My issue accused before this start over and back up mod pack applying

**Comment by Yuki-Walsh** [comment]
Yes, it looks like a previous version of Tex Tools has corrupted the file during a mod installation, using a modpack backup carries the corruption into the current version.

We can't fix this, as its an issue with Tex Tools.

**Comment by Yuki-Walsh** [comment]
I've opened an issue with Tex Tools: https://github.com/TexTools/FFXIV_TexTools_UI/issues/171, they'll need to fix it.

**Comment by LadyLizellea** [comment]
Thank you very much for the help. Do we need to reinstall our mods or just wait?

**Comment by Yuki-Walsh** [comment]
I'm not sure. to get it working right away, download your mods again one by one.
You may want to keep an eye on the tex tools issue list and see if they comment on it.

**Comment by nannoxxx** [comment]
I started over, added mods 1 by 1, seemed to be a clothing mod out of everything! Still cant figure out which particular one it is! Will update if I figure it out

**Comment by Yulu7766** [comment]
I've got over 200 mods😭😭😭
But I'll try to do the same with reinstalling one by one to figure out which one it is🥴🥴

**Comment by dekz0rs** [comment]
> I've got over 200 mods😭😭😭 But I'll try to do the same with reinstalling one by one to figure out which one it is🥴🥴

Good news is TT mods have replicated the issue and are working on a fix.

You can see the thread here, its def an issue that was released with 6.11's update to TT

https://github.com/TexTools/FFXIV_TexTools_UI/issues/171

**Comment by chirpcodes** [comment]
A fix has been found for this, should make its way to release soon!

**Comment by Yuki-Codes** [comment]
This has been fixed by a Lumina update for the next release.
