### ISSUE TITLE
Facial features deselecting when selecting character in Anamnesis.

### ISSUE THREAD

**Issue by Maigistr** [imchillin/Anamnesis#987]
**Describe the bug**
When I go to select my character in Anamnesis in the customize tab, it refreshes them and seems to disable the limbal rings on Au Ra, ear cuffs on Elezen, tattoos on Hyur, Lalafell, Miqo'te, Roegadyn, Viera & Hrothgar, or whatever two facial features are next to the legacy mark in the customize tab. Other features are unaffected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Click on the customize tab.
3. Character refreshes (or "redraws").
4. Facial features deselect.

**Expected behaviour**
Opening Anamnesis and selecting the customize tab shouldn't deselect character features unless I myself choose to deselect them.

**Comment by justauser95** [comment]
This is happening to me consistently as well. I'll provide a log, and note it seems to only happen when launching anam and selecting the character tab for the first time. Re-selecting the features and moving out of the tab and back in doesn't disable them a second time. My character is female Au Ra and has all the extra scales, upper eyeliner, rings on horns, and both limbal rings, and it disables all of them.
[2022-04-18-13-55-22.txt](https://github.com/imchillin/Anamnesis/files/8507241/2022-04-18-13-55-22.txt)

**Comment by Maigistr** [comment]
[2022-04-18-12-26-59.txt](https://github.com/imchillin/Anamnesis/files/8507371/2022-04-18-12-26-59.txt)
I realize I neglected to provide a log, so here's that as well. I just opened Anamnesis, selected the customize tab and let it redraw, disabling my Elezen's ear cuffs.

**Comment by ararebeast** [comment]
[2022-04-18-18-10-54.txt](https://github.com/imchillin/Anamnesis/files/8508647/2022-04-18-18-10-54.txt)
I can confirm it occurs when I click on the tab to customize my gear and not before.

**Comment by AsgardXIV** [comment]
Thanks for the reports. I have managed to reproduce and I believe fix this. 
Fix should be in the next release and will hopefully resolve it.
