### ISSUE TITLE
Cant Start Anamnesis

### ISSUE THREAD

**Issue by sprocketaudio** [imchillin/Anamnesis#989]
I can't load the program at all - Log included

Steps to reproduce the behaviour:
1. Log into FXIV
3. Run Anamnesis  [2022-04-18 (Beta)]
4. Loading animation starts, then dissapears.

**Expected behaviour** 
Program should open

**Log file**
[2022-04-18-20-53-18.txt](https://github.com/imchillin/Anamnesis/files/8507839/2022-04-18-20-53-18.txt)

**Steps taken so far**
Unistalled .net Desktop Runtime 5.13 (x64) and installed 5.14 (x64)
Restarted computer

**Extra Notes**
Reinstalled windows not to long ago (Windows 10) and am fully updated
Do not have discrete gfx - I am on desktop with GTX970 and 2 monitors.
Exclusions set in Windowsw Security
![image](https://user-images.githubusercontent.com/13222732/163871163-f8811210-6372-46ee-88f0-d6a10cade6dd.png)
Program set to run as admin
![image](https://user-images.githubusercontent.com/13222732/163871389-84ba325c-e2b0-4637-9d40-9ce8b1c65236.png)

**Comment by Yuki-Walsh** [comment]
Can you take a look in the windows event viewer, under Windows Logs -> Application, and see if there are any critical errors reported there for Anamnesis?

**Comment by sprocketaudio** [comment]
Hi, thanks for responding - I have looked fo you and can see this - I do not know if they all related but they seem to have generated all at the same time.

![image](https://user-images.githubusercontent.com/13222732/164000336-51d83b19-2953-4619-b875-74666b6e7f61.png)
![image](https://user-images.githubusercontent.com/13222732/164000350-bb157fdc-3144-47b3-be44-686c48010be6.png)
![image](https://user-images.githubusercontent.com/13222732/164000433-e142253d-3e9d-4453-b972-246f52efd69c.png)
![image](https://user-images.githubusercontent.com/13222732/164000532-0447ffab-4cad-4fd7-8d54-3c1406b90ad8.png)
![image](https://user-images.githubusercontent.com/13222732/164000642-4d9d6f37-5433-4762-95b4-e2eccad91a77.png)
![image](https://user-images.githubusercontent.com/13222732/164000697-ed074ef2-e181-43c4-a3c8-188e03d8d4c3.png)
![image](https://user-images.githubusercontent.com/13222732/164000774-cbffde3a-31db-4258-8221-6fb01d85f7ee.png)
![image](https://user-images.githubusercontent.com/13222732/164000788-3b0eff3a-bab3-4d53-bfb2-5a3b82c6a99f.png)
![image](https://user-images.githubusercontent.com/13222732/164000815-a25db16a-ba92-4c3a-94b6-bb800282bc83.png)

**Comment by Yuki-Walsh** [comment]
You may need to reinstall .net, looks like something is going wrong in there.

**Comment by sprocketaudio** [comment]
I cant install .net framework as im on latest version and its built into windows 10. I reinstalled .net 5.14 but stil get the same error. 

I had a look around online and found some people saying this happens with their apps but only on some users machines. Someone even suggested to create a installer for the app to make it more stable across all users machines:

"I used the setup extension on vs 2019 to build an installer for the application. It gets installed on the specified OS versions without crashing" 

- Is this a possibilty?

**Comment by Ani-ki** [comment]
> "I cant install .net framework "
The prerequisite required is the **.NET Desktop Runtime** which is now on version 5.0.16. Can you please ensure you have this installed?

> I used the setup extension on VS to build an installer for the application.
Was this done *specifically* for Anamnesis, or was this found on a website for a different project?

Additionally, the wording provided implies that it's not a good overall, universal solution to this issue.

**Comment by sprocketaudio** [comment]
Just reporting back after a lot of testing - This turned out to be a faulty CPU issue. I found a post suggesting this could be the cause and used the bios to disable all but 1 core, one at a time, then tested. I found some cores were causing these crashes, and have now left them disabled. All is working :)
