### ISSUE TITLE
Tab and Printscreen key inputs passed to game while Anamnesis has focus

### ISSUE THREAD

**Issue by Sparrows413** [imchillin/Anamnesis#991]
**Describe the bug**
If Anamnesis currently has focus, even with hotkey mode disabled, pressing the Tab or Printscreen keys (for example to alt-tab away or to take note of something in the Ana window) will pass these inputs to the game with the expected result.

(Note: Maybe other inputs too? But these are the two I've noticed.)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game, then Anamnesis
2. Have Anamnesis focused with FFXIV in the background
3. Press Tab
4. Whatever action you have bound to Tab will happen in FFXIV.
5. Press Printscreen
6. Whatever action you have bound to Printscreen will happen in FFXIV.

**Expected behaviour**
For the inputs not to be passed to the game as it is not the currently-focused window.

**Comment by Maxunit** [comment]
This is a known bug and has been reported internally.

**Comment by yesokcool** [comment]
This appears to be occurring for all inputs on the keyboard. This is causing commonly used keyboard shortcuts to produce possibly undesired effects, such as switching actors when using Alt+Tab, and panning down when screenshotting on Windows (Windows+Shift+S).

**Comment by thrdplanet** [comment]
I have this same issue trying to use the arrow keys to "scroll down" and load different gear pieces - the keys work in ana, but also bypass ana and affect my game (for me, moving my camera around).

**Comment by Yuki-Codes** [comment]
We've added an option to disable the key forwarding behavior in the next version.
