### ISSUE TITLE
Fail to Read Game Color Data (Arithmetic operation overflow)

### ISSUE THREAD

**Issue by Nirithaa** [imchillin/Anamnesis#992]
Describe the bug
Upon opening Anamnesis, gives a error that colorset data cannot be read due to an overflow.
Reproduced on any character.

To Reproduce
Steps to reproduce the behaviour:
Open the game, the error immediately comes up.
![image](https://user-images.githubusercontent.com/50635218/163880736-0ef80a52-248d-453d-b7f4-8b3b6b8bd907.png)
Hit okay.
Anamnesis opens properly. Go to character tab. Colors are blacked out.
![image](https://user-images.githubusercontent.com/50635218/163880830-116c3e05-3d58-4ccb-9271-a62918586dee.png)
![image](https://user-images.githubusercontent.com/50635218/163880860-dcbd2255-d6d5-4503-b2db-0396b7e1f554.png)

Expected behaviour
For colorset data to load properly and to have changeable color palates.

**Comment by Groot0075** [comment]
huh so it related to the color set data
that would explain why effect mods are not the root cause of the color data error and why it might have to do something with the color set rows in tex tools
that's my theory on the subject matter anyways

**Comment by Yuki-Walsh** [comment]
This might be an issue with Tex Tools, does getting clean indexes solve it?
It's likely not something we can fix from our side.

**Comment by S1lentSymphony** [comment]
> This might be an issue with Tex Tools, does getting clean indexes solve it? It's likely not something we can fix from our side.
> 
> ![image](https://user-images.githubusercontent.com/379714/163901896-06daa5c0-8e56-4d84-be11-0bcf38b09539.png)

Will check in a few minutes and report back

**Comment by S1lentSymphony** [comment]
So I started over, downloaded and implemented index backups. Error has changed from overflow to "File Type Not Implemented". Log in Discord.

**Comment by Yuki-Walsh** [comment]
ah, so now you are #986 also.

**Comment by Yuki-Walsh** [comment]
looks like this is the same issue, so moving discussion to #986.
