### ISSUE TITLE
Loading some poses resets rotation of actor

### ISSUE THREAD

**Issue by yuyuisyuyu** [imchillin/Anamnesis#994]
**Describe the bug**
Upon loading some poses that I have saved or downloaded, the actor will snap rotation to a particular angle instead of remaining fixed in place.

[Streamable](https://streamable.com/f8691k) - Video example of the built-in poses loading normally and the rotation snapping occurring when loading an example pose.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter GPose
2. Enable posing mode and rotate actor
3. Load example pose
4. Actor will rotate to a particular direction upon loading

**Expected behaviour**
Pose loads without moving actor out of their current rotations, like the pre-packaged default poses do.

**Log file**
[2022-04-18-16-42-31.txt](https://github.com/imchillin/Anamnesis/files/8508357/2022-04-18-16-42-31.txt)

Pose used in example: [cat_smirk.zip](https://github.com/imchillin/Anamnesis/files/8508362/cat_smirk.zip)

**Comment by Yuki-Walsh** [comment]
The actor rotation was added to poses a few versions ago. (#71, #222, and #774 I think).
Perhaps we need the actor rotation/scale loading as an option instead of always on?

**Comment by yuyuisyuyu** [comment]
I'd be in favor of that, there's times I could see myself using it sometimes for sure but at the moment if I find myself reusing a sequence of poses I've done previously, I will likely have to adjust after loading each set of poses.
