### ISSUE TITLE
Anamnesis Crashing PC when updating to latest version

### ISSUE THREAD

**Issue by Dragonessa** [imchillin/Anamnesis#998]
I updated Anamnesis to the latest version and my PC crashed and rebooted itself. I’ve actually experienced a crash and reboot issue previously when using Anamnesis a couple of times as well, not sure if it’s my PC or the program itself.

**Comment by Squall-Leonhart** [comment]
User mode software cannot reboot your pc, check for driver updates, the thermals of your pc and power supply outputs.

**Comment by Dragonessa** [comment]
All drivers on my PC are up to date, drivers are updated and thermals are within normal limits. My power supply was also recently replaced a couple months ago so I'm fairly certain its not an issue with that either. The crash and reboots only happened when attempting to use Anamnesis without the .net framework being updated properly. Once I updated the ,NET framework, Anamnesis worked as intended.
